### ISSUE TITLE
Run Functional Tests Hangs on 'InProgress' state

### ISSUE THREAD

**Issue by structre40** [Microsoft/vsts-tasks#4684] opened 2017-06-29 22:56 UTC
[TestAgentConfig.log.txt](https://github.com/Microsoft/vsts-tasks/files/1113741/TestAgentConfig.log.txt)
We are running across 4 different environments and sometimes the "Run Functional Tests" task works and sometimes it hangs with the message: 
2017-06-29T22:22:45.6329831Z DistributedTests: Test run '52931' is in 'InProgress' state.

It eventually times out, failing the VSTS release. The DTA log shows:

> DTAExecutionHost.exe Warning: 0 : Main.InitializeAndStartExecutionHost. Failed to load assembly: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\TestAgent2017\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll' or one of its dependencies. Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
> File name: 'file:///C:\TestAgent2017\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Microsoft.VisualStudio.TestPlatform.ObjectModel.dll' ---> System.Runtime.InteropServices.COMException (0x8000FFFF): Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
>    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
>    at Microsoft.VisualStudio.TestService.Utility.TestPlatformAssemblyLoader.AssemblyResolve_LoadFrom(String probingPath, String name, Boolean recurse) in E:\v2.0\A5\_work\1\s\Ta\Agent\VS.TestService.Utility\TestPlatformAssemblyLoader.cs:line 86

I have attached the DTAExecutionHost.exe.txt file for review.

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/1113733/DTAExecutionHost.exe.txt)

**Comment by structre40** [comment] 2017-06-29 23:06
TestAgentConfig file is attached to this message.
[TestAgentConfig.log.txt](https://github.com/Microsoft/vsts-tasks/files/1113745/TestAgentConfig.log.txt)

**Comment by ChrisLGardner** [comment] 2017-07-04 13:32
I have noticed this as well. Rerunning the deploy test agent and run functional test task causes it to work so I suspect something in the initial install is failing silently, I'm deploying to a fresh VM the first time I run the tasks.

**Comment by nigurr** [comment] 2017-07-05 09:00
@ChrisLGardner @structre40 
Is "Update Test agent" is enabled in build/release definition?

If yes, can you please disable it and see if you are still hitting this issue.
Can you attach Event Viewer logs and %temp% logs from the test agent machine whenever this error happens.

Sorry for the trouble, we are trying to investigate and collect some data.

**Comment by ChrisLGardner** [comment] 2017-07-05 13:38
I've tried swapping to the VS 2015 agent and hit the same errors. I've also had a few test runs (both first attempt and second attempt) that have moved straight from InProgress to Abandoned within a few seconds of starting.

I've attached the logs from the install and the DTA logs as well just in case. The VM I'm using is Server 2012R2 with SQL 2014 (with pre-reqs) and nothing else installed.

[dd_vstf_testagent_20170705095321.txt](https://github.com/Microsoft/vsts-tasks/files/1124799/dd_vstf_testagent_20170705095321.txt)
[DTAExecutionHost.exe-FirstRun.txt](https://github.com/Microsoft/vsts-tasks/files/1124800/DTAExecutionHost.exe-FirstRun.txt)
[DTAExecutionHost.exe-SecondRun.txt](https://github.com/Microsoft/vsts-tasks/files/1124798/DTAExecutionHost.exe-SecondRun.txt)

**Comment by abhishekkumawat23** [comment] 2017-07-10 11:56
@ChrisLGardner @structre40 : Is it possible for us to have access to any repro machine so that we can debug into this issue further?

**Comment by ChrisLGardner** [comment] 2017-07-10 13:07
I can probably arrange access via a skype call or something similar to use desktop sharing.

**Comment by structre40** [comment] 2017-07-11 16:10
@abhishekkumawat23 I would also be able get on a call to review this with the team.

**Comment by structre40** [comment] 2017-07-12 14:29
@nigurr I have tried running releases with and without the "Update test agent" checkbox checked and get the same result.
I have noticed that if I am remoted in to the test machine using Remote DeskTop, the release runs fine. I have already tried enabling auto login for the VM but that does not resolve this issue after I reboot and try the tests again.

**Comment by abhishekkumawat23** [comment] 2017-07-13 04:37
@structre40 Yes, we noticed with other customers also that scenario is working with RDP session on.

@structre40 @ChrisLGardner  Can you try following scenario?:
While setting up machine environment, does DTA binaries and Test agent binaries are already present before running the tests? Typically DTA binaries are installed at C:\TestAgent and Test agent 2017 binaries are installed at C:\TestAgent2017 or C:\Program Files (x86)\Microsoft Visual Studio
If yes, then can you please create machine without both of above and try running tests again?

**Comment by structre40** [comment] 2017-07-13 15:36
@abhishekkumawat23 I uninstalled Visual Studio 2017 on the box but also had to stop the services Visual Studio Lab Agent Service and Lab Network Agent Service to be able to clean the folders up. 
I rebooted and then re-ran the release. It worked and ran the tests as expected. The downside is it takes over 4 minutes for the "Deploy TestAgent on Machine" task to complete. 
This is why we had the agent installed already to avoid this delay. We currently have 12 teams working on a project and a 4 minute delay from test hosts per environment is blocking many builds and releases.

**Comment by ChrisLGardner** [comment] 2017-07-13 17:28
@abhishekkumawat23 the binaries aren't there on my machines as I'm spinning up completely new ones from a sysprepped VHD (with nothing but SQL installed). My release pipeline is pretty much:

1) Deploy VM
2) deploy code
3) deploy agent
4) run tests
5) delete VM

I can remove the deploy agent step but I've always assumed it's required for the run tests step to work.

**Comment by nigurr** [comment] 2017-07-14 03:27
@structre40 we are willing to unblock you and make it simple. Currently we are investigating what's causing the store and restore of VM with test agent, failed to load basic assembly loading functionality.
@ChrisLGardner This issues seems to occur (from other customers), when using VHDs from [VmWare/SysPrepped], we are looking into this issue. Kindly bear with us.

**Comment by abhishekkumawat23** [comment] 2017-07-20 12:14
@ChrisLGardner @structre40  We are trying to repro on our end. Can you please share OS version and processor info (32 bit or 64 bit) on which this issue can be reproduced.

In addition, can you try following?
Create a new VM (without cloning from any base image). Install Test agent manually from Microsoft website. Clone this machine (without running tests on it). Try running tests on this cloned machine.

**Comment by abhishekkumawat23** [comment] 2017-07-28 10:08
@ChrisLGardner @structre40 Any update on the above info?

**Comment by ChrisLGardner** [comment] 2017-07-28 10:32
I'm using Server 2012R2 64bit.

I'm just working on the other request, spinning up a VM from ISO, installing the agent then cloning the VM. Should hopefully have some more info on that later today.

**Comment by cltshivash** [comment] 2017-08-10 02:07
@ChrisLGardner Could you please share info on the trial you had done ?

**Comment by abhishekkumawat23** [comment] 2017-08-21 07:17
@structre40 @ChrisLGardner : We tried to repro this issue on our end with various scenarios but we were unable to repro the issue.
Following are the ways to unblock from the issue:

Way 1: Base snapshot shouldn’t have any TestAgent installed and there shouldn’t be any RFT/DTA tests ran on this base snap. Now, take a clone of this machine and run the tests. This way is little time consuming for 1st test run (as test agent will be installed in first run.)

Way 2: Base snapshot should have Test Agent installed from https://www.visualstudio.com/downloads/. No RFT/DTA tests should be ran on this base snapshot. Now take a clone of this machine and run tests with Update Test Agent checked.

**Closed** 2017-08-21 09:14 UTC
Labels: Area: Test

**Comment by kalin-toshev** [comment] 2017-09-02 04:13
I hit the same issue (System.IO.FileLoadException/E_UNEXPECTED) while trying to hook up Functional Tests task, preceded by Deploy TestAgent in my VSTS release definition. I also spent some time to investigate the root cause and I think I found the problem. 

Basically, during startup, DTAExecutionHost.exe (via [Microsoft_VisualStudio_TestService_Utility]) installs an AssemblyResolver handler, which is supposed to resolve references to various assemblies, residing in different directories (under TestAgent2017 or Program Files (x86)) from the 'main' location (TestAgent). When the process goes through its initialization [Microsoft_VisualStudio_TestService_VstestAdapter!Microsoft.VisualStudio.TestService.VstestAdapter.SessionDetailStore..ctor] 'triggers' loading of Microsoft.VisualStudio.TestPlatform.ObjectModel.dll (which is under Program Files (x86)\...\TestWindow or under TestAgent2017), because of a referenced type (TestResult). This eventually hits the following stack - 

...
**0053b6f8 71220fc5 clr!AssemblyNative::Load+0x330**
0053b71c 712c9439 mscorlib_ni!System.Reflection.RuntimeAssembly.nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)+0x25
0053b758 71257593 mscorlib_ni!System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)+0x99
0053b780 7126d5bf mscorlib_ni!System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)+0x67
0053b7a0 0560fb33 mscorlib_ni!System.Reflection.Assembly.LoadFrom(System.String)+0x23
0053b7c8 0560f62f Microsoft_VisualStudio_TestService_Utility!Microsoft.VisualStudio.TestService.Utility.TestPlatformAssemblyLoader.AssemblyResolve_LoadFrom(System.String, System.String, Boolean)+0xd3
0053b800 71223395 Microsoft_VisualStudio_TestService_Utility!Microsoft.VisualStudio.TestService.Utility.TestPlatformAssemblyLoader.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)+0x1b7
0053b824 7254eaf6 mscorlib_ni!System.AppDomain.OnAssemblyResolveEvent(System.Reflection.RuntimeAssembly, System.String)+0x95
...

Eventually (continuing 'stepping' the stack above), we will go through urlmon!CSecurityManager::MapUrlToZone (urlmon.dll is loaded) and from there, we land in urlmon!InternetCreateZoneManager. This is the function that **sometimes** fails with E_UNEXPECTED when the CUrlZoneManager fails to initialize (this propagates up the stack as the exception, seen above). The reason why it fails sometimes, is that **HKCU hive may not be loaded** at the time, when the call is made (and it's needed there!). Sometimes, when we are lucky, we may get the hive (profile) loaded via other tasks (or RDP session or another WinRm connection with the same account) at the time DTAExecutionHost.exe needs it (because of the Assembly.LoadFrom business above). But then in other times, the HKCU is not loaded and then we hit the error above. 
Because of the tricky conditions when this happens, I had to hook a remote debugger (IFEO/DTAExecutionHost.exe) using something like this - **c:\debuggers\cdb.exe -server tcp:port=4445 -noio** on the node (opened the port, etc.), running the tests; then make sure I am logged off (and all WinRm sessions using this account are closed). Then, when VSTS release workflow activates the DTAExecutionHost.exe, I connect from another box (cdb -remote tcp:server=<node ip>,port=4445) and wait for ~1 min (again to make sure that no WMI workers (wsmprovhost.exe - from previous WinRm connections) are around (keeping the hive loaded)). Then, **sxe ld:urlmon.dll; g** in the debugger. Once we stop in ntdll.dll, **bp urlmon!InternetCreateZoneManager** and **g** and then (when we stop), gu and check *eax* (register) -> E_UNEXPECTED (0x8000FFFF). 

Note that this can happen in any other 'context' where the HCKU hive is needed and we have a similar 'setup'. 

Currently, I patched things up by throwing in a 'wrapper' pair of tasks (basically a PS script over WinRm) - 'lock/unlock', During 'lock', I leave the (remote) session is 'disconnected' state (Disconnect-PSSession), which would keep the wsmprovhost.exe and the (hive) state on the node loaded. Once we are done, the 'unlock' step tries to reconnect to the (existing) session (Get-PSSession -> Connect-PSSession) and eventually removes it (cleanup). Note that unlock is set to always run in the release definition. After that ('patch'), I have not seen the issue anymore, but it would be nice if we have a real fix in the VSTS task(s) :-)
