### ISSUE TITLE
DownloadSecureFile YML Support

### ISSUE THREAD

**Issue by smokedlinq** [Microsoft/vsts-tasks#6250] opened 2018-01-18 15:04 UTC
Environment:
   VSTS (msg me for tenant)
   Hosted VS2017 Agent

Using the YML build definition with the DownloadSecureFile task the following error occurs when trying to queue the build. Tried using system.debug = true but the build is never kicked off as queuing it fails.

```
Phase Build: Step input secureFile references secure file a7ca8c7d-d493-480a-854b-17dfeaa105d5 which could not be found. The secure file does not exist or has not been authorized for use. 
```

**Comment by ericsciple** [comment] 2018-01-22 21:48
check this doc https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-authz.md

if that resolves it, it sounds like we should add an fwlink to the error message.

**Comment by ericsciple** [comment] 2018-01-22 22:14
Closing the issue. This isn't really an issue with any task in this repo. Email me ersciple if that doesn't resolve the issue (at microsoft com)

**Closed by ericsciple** 2018-01-22 22:14 UTC

**Comment by smokedlinq** [comment] 2018-01-23 13:39
Thanks, that seems to have resolved it: granted Project Collection Build Service (accountname) access to the secure file.

**Comment by ericsciple** [comment] 2018-01-23 13:52
Explicitly granting the service account should not be required. Once it is enabled for use on the definition, it should be usable from any branch.

Are you using a vsts git repo, or a GitHub repo?

**Comment by smokedlinq** [comment] 2018-01-23 19:42
I am using a VSTS GIT repo, the yml file I am updating is not in the master (default) branch. From reading the link you sent it looks like it needs to be there to be authorized. I'm trying to prove this out on a fork, I thought it had worked earlier but my CI build kicked off on the new branch and not my update.

**Comment by smokedlinq** [comment] 2018-01-23 19:50
So I did verify, my yml build does work with the DownloadSecureFile when in the master branch. Also once it is in the master branch the other branches can access the file successfully. My problem was I was trying to use it from a non-default (feature) branch and PR it into master but couldn't get the build to succeed and satisfy the PR policy. For now I'll disable the PR policy, merge it, then re-enable the PR build policy.

**Comment by ericsciple** [comment] 2018-01-24 18:58
Thanks for confirmation. Yes that is a painpoint today. We are working on changes that will enable resource-authorization on-push to any branch (vsts git repo only). Another longer term solution to the problem is a resource authorization experience in the web.

**Comment by in4margaret** [comment] 2018-10-11 19:06
@ericsciple does it actually work?
