### ISSUE TITLE
Help link on Deployment Script Type is a 404

### ISSUE THREAD

**Issue by DarqueWarrior** [Microsoft/vsts-tasks#7256] opened 2018-05-19 17:20 UTC
## Environment

- Server - VSTS
   - AzureRMWebAppDeploymentV4 task

- Agent - Hosted or Private: 
   - N/A

## Issue Description

The help link in the tooltip for the Deployment Script Type is a 404

### Error logs

N/A

**Comment by bryanmacfarlane** [comment] 2018-05-19 17:49
release needs to update the fwlink

**Comment by rokmicrosoft** [comment] 2018-05-21 05:52
Duplicate of same [issue](https://github.com/Microsoft/vsts-tasks/issues/7220)

**Closed by rokmicrosoft** 2018-05-21 05:52 UTC
Labels: Area: Release
