### ISSUE TITLE
Using a template containing a task group: One or more of the steps defined in the build does not have an associated task definition

### ISSUE THREAD

**Issue by pabrams** [Microsoft/vsts-tasks#7609] opened 2018-06-29 16:52 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
**TFS  2017, Update 3**
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

**Agent version: 2.122.1 or 2.112.0 (happens on both)
OS: Windows 7**

## Issue Description

**1. Create a template containing a Task group (which contains a single command line task)
2. Create a build definition from that template 
3. Try to queue a build
4. Queue fails:  "One or more of the steps defined in the build does not have an associated task definition. Check if the task was uninstalled or has failed a licensing check."**

**Can work around by removing and re-adding the task group, but that defeats the purpose of using a template.**

### Error logs

**The build doesn't actually execute at all, this is a validation error in the Queue Build dialog.  I don't see anything interesting in event viewer on the TFS server.**

**Comment by bryanmacfarlane** [comment] 2018-07-05 01:42
Release since the steps are contained to templates and a task group.

**Comment by ArieHein** [comment] 2018-07-08 08:49
Cant reproduce.
On your Agent server, go to the tasks subfolder of you agent ( if you have multiple agents on the server, do so for all) and delete the content of it. 
As the agent downloads all tasks from server if that folder is empty or task definition has new tasks or new versions of a task, it is safe to delete the content.
Perhaps something is stuck with the versions of the tasks.

Other option if you have multiple agents on the same server is to try to force the build to run on each agent to see if there are differences

**Comment by DanielTheCoder** [comment] 2018-07-10 06:48
We have the same problem with TFS 2017 Update 3.
Workaround "Can work around by removing and re-adding the task group, but that defeats the purpose of using a template." was working for us.

**Comment by pabrams** [comment] 2018-07-10 17:31
I tried the following one of @ArieHein 's suggestions: 
1. delete all tasks from tasks folder on all agents (/agent#/_work/_tasks/) on build machine 
1. reboot build machine 
1. repeat original steps

I still get the same result.  Getting it in an alert now because I'm queuing from a different spot I guess:
---------------------------
Message from webpage
---------------------------
There are issues with the request or definition that will prevent the build from running:

One or more of the steps defined in the build does not have an associated task definition. Check if the task was uninstalled or has failed a licensing check.
---------------------------
OK   
---------------------------

The task group in my template just contains a command line task that runs `dir`.

**Comment by bansalaseem** [comment] 2018-07-13 11:07
I tried to reproduce it on my VSTS account but was not able to. @pabrams, @DanielTheCoder Does this error come only with TFS 2017.Update 3?

**Comment by pabrams** [comment] 2018-07-15 11:09
@bansalaseem I don't have another installation to try it on.  Our TFS server has been upgraded from an older version though, so if this can't be reproduced on a clean install, maybe that could be the reason?

**Comment by bansalaseem** [comment] 2018-07-16 12:05
Thanks Pabrams. We have identified the issue, have observed that the issue is fixed in TFS 2018 RTM and are preparing a patch change on top of TFS 2017.Update 3 so that you can try it out in your installation.

**Comment by nishubansal** [comment] 2018-08-16 04:34
**Steps to fix Build template issue with TaskGroups**
1.	Copy Zip file, backup script and rollback script (files given after steps) to TFS installation location. Default Location will be like C:\Program Files\Microsoft Team Foundation Server 15.0
2.	Take backup using the backup script provided. 
a.	Open command prompt in Administrator mode. 
b.	Go to TFS installation location. 
c.	Run the script.
d.	Once backup is successfully done. Move to next step.
3.	Unzip the zipped file. You will get prompt for “Replace or Skip Files”. Click on “Replace the files in destination”.
4.	You will get another prompt saying “Provide administrator permission to copy to this folder”. Click on “continue”.
5.	Go to VSTS web page. Press Ctrl + F5.
6.	If after the fix if you face any issue. Run Rollback script to revert the change.
a.	Open command prompt in Administrator mode. 
b.	Go to TFS installation location. 
c.	Run the rollback script. 

[Application Tier.zip](https://github.com/Microsoft/vsts-tasks/files/2292404/Application.Tier.zip)

**Backup script:**  (Save the below mentioned script as .bat file)

@echo off
 if not exist backup\nul mkdir backup
cd backup
if not exist min\nul mkdir min
if not exist debug\nul mkdir debug
cd ..
set "errorcount=0"
copy /Y "Application Tier\Web Services\_static\tfs\Dev15.M125.1\_scripts\TFS\debug\CIWorkflow\Scripts\Scenarios\Definition\Sources\BuildDefinitionSource.js"  "backup\debug" >nul 2>&1
if %errorlevel% neq 0 set /a errorcount+=1

copy  /Y "Application Tier\Web Services\_static\tfs\Dev15.M125.1\_scripts\TFS\debug\CIWorkflow\Scripts\Scenarios\Definition\Sources\BuildDefinitionSource.min.js"  "backup\debug" >nul 2>&1

copy  /Y "Application Tier\Web Services\_static\tfs\Dev15.M125.1\_scripts\TFS\min\CIWorkflow\Scripts\Scenarios\Definition\Sources\BuildDefinitionSource.js"  "backup\min" >nul 2>&1
if %errorlevel% neq 0 set /a errorcount+=1

if %errorcount% equ 0 (
  echo Backup completed successfully.
) else (
  echo Backup failed. Error copying 1 or more files.
   rmdir /S /Q backup
)

**Rollback script:** (Save the below mentioned script as .bat file)

@echo off
set "errorcount=0"
copy /Y "backup\debug\BuildDefinitionSource.js" "Application Tier\Web Services\_static\tfs\Dev15.M125.1\_scripts\TFS\debug\CIWorkflow\Scripts\Scenarios\Definition\Sources"  >nul 2>&1
if %errorlevel% neq 0 set /a errorcount+=1

copy  /Y  backup\debug\BuildDefinitionSource.min.js" "Application Tier\Web Services\_static\tfs\Dev15.M125.1\_scripts\TFS\debug\CIWorkflow\Scripts\Scenarios\Definition\Sources"  ">nul 2>&1

copy  /Y "backup\min\BuildDefinitionSource.js" "Application Tier\Web Services\_static\tfs\Dev15.M125.1\_scripts\TFS\min\CIWorkflow\Scripts\Scenarios\Definition\Sources"  >nul 2>&1
if %errorlevel% neq 0 set /a errorcount+=1

if %errorcount% equ 0 (
  echo Rollback completed successfully.
     rmdir /S /Q backup
) else (
  echo Rollback failed. Error copying 1 or more files.
)

**Comment by pabrams** [comment] 2018-08-17 17:59
Thanks @nishubansal, I'll try this when I get a chance.

**Comment by pabrams** [comment] 2018-08-17 18:17
Actually, my client has a workaround, so we don't need to mess with the server, so I probably won't try this, and will just wait until we upgrade instead.

**Comment by bansalaseem** [comment] 2018-09-18 11:35
I am closing this issue as Nishu has posted a workaround and we have fixed it in latest code.

**Closed by bansalaseem** 2018-09-18 11:35 UTC
Labels: Area: Release
