### ISSUE TITLE
AzureRmWebAppDeployment ignores unchecked "Publish using Web Deploy"

### ISSUE THREAD

**Issue by MattPitlyk** [Microsoft/vsts-tasks#3793] opened 2017-03-15 20:29 UTC
I am trying to deploy Python code to a Webapp using VSTS. I have a custom deploy.cmd file that helps deploy the code when I use a local git repo and Kudu. (That is, I can successfully git push my python code to my Webapp, and Kudu recognizes the changes and runs my deploy.cmd script which deploys the webapp correctly). 
I now have my code in a VSTS repository and am creating a build definition to deploy the code to the Webapp. In the build definition, I add the AzureRmWebAppDeployment task: 

![image](https://cloud.githubusercontent.com/assets/7517280/23968889/97c45498-0992-11e7-9a24-1fafb7e12b21.png)

I then uncheck the box next to "Publish using Web Deploy”: 

![image](https://cloud.githubusercontent.com/assets/7517280/23968917/ace5fb7e-0992-11e7-8fbd-9df6832e4207.png)

But when I queue up and run the build definition, I can see that Web Deploy is still being used, which copies my files to /wwwroot (instead of /respository) and does not run my deploy.cmd:

![image](https://cloud.githubusercontent.com/assets/7517280/23969272/d865e754-0993-11e7-83cb-7c5f2c958bd9.png)

Near the bottom of this [page](https://github.com/projectkudu/kudu/wiki/VSTS-vs-Kudu-deployments) are instructions on how to set up Kudu to deploy from VSTS manually in the portal, however I need to set this behavior up programmatically, on a fresh webapp, from a VSTS build definition. How can I either:
- Add properties to my webapp ARM template or the VSTS build definition in order to programmatically execute the manual steps on that webpage?
- Get the AzureRmWebAppDeployment task to copy my code to /repository and run my deploy.cmd file?
- Write a custom powershell script (which I can run from my VSTS build definition) that does the copy and runs deploy.cmd?

**Comment by vincentdass** [comment] 2017-03-16 05:21
@MattPitlyk , thanks for reporting the issue.
As you know, Azure App Service Deploy task uses MSdeploy (for Windows platform) and Kudu Rest call (for other platforms).

- MSdeploy option is used when "publish using web deploy" is selected or the agent is in windows.
- Kudu rest call copies the web package to site/wwwroot (or other location provided in Application settings of App Service).

Recently, we launched deployment script execution feature that takes custom script (.cmd or .bat) and runs it on Azure App Service. This feaute will be available in all the regions in a week or two.

![image](https://cloud.githubusercontent.com/assets/20121508/23982763/92d7769c-0a35-11e7-9186-f75a0363ef08.png)

In this way, you can deploy to the root folder and run your script post deployment.
Inline script is limited to **500** characters.
You can also provide a script file as input (File Path option).

We planned to launch a template for deploying python app and will notify you once it is done. :)

**Comment by MattPitlyk** [comment] 2017-03-16 18:20
This is great news! I can use the script I am already including in my repo, as soon as that option shows up in my v3 template (currently mine looks different than your screenshots).

Looking forward to the python template as well, so please do keep me posted!

**Comment by vincentdass** [comment] 2017-03-27 07:03
@MattPitlyk , Post Deployment script feature is available in all the regions now. 
Please do give a try an provide your feedback. :)
Closing this thread as there is no action item.

**Comment by MattPitlyk** [comment] 2017-04-18 04:55
@vincentdass Finally got to try out the post deployment script feature and it works great when my script does not throw an error, but if my script errors out, control is never returned to the build agent. Is there anyway to redirect the stdout and errout from the script back to VSTS while the script is running?

**Comment by vincentdass** [comment] 2017-04-18 13:03
Live logs are not supported currently.
Kudu team have this feature for live logs in their backlog.
Can you please provide us some more details when the script throws error ?
Is the stderr not shown in the logs after script execution or the release throws timed out error ?

**Comment by MattPitlyk** [comment] 2017-04-18 16:07
Thanks for the response.

I have found a work around for my error (though I'll include details below in case someone has insights). My main concern is that when an error occurs (any error, not just the one below), the error is written to the stderr.txt file, but control is never returned to the build agent forcing me to manually cancel the build. When I use the work around to avoid the error so that my script exits normally, control is returned to the build agent and the entire contents of the stdout.xt and stderr.txt are dumped into the consol on VSTS - so everything works fine. Could webdeploy be looking for a specific flag in the stdout.txt file to tell is that the process is done? I assumed when the script exited, regardless of how, webdeploy would pick back up.


Additionally, looking forward to seeing the output in the Build Agent console again (it works when I use a .bat script to git push my code from VSTS to a webapp in local git mode, which is my current setup). In the meantime, is there a channel over webdeploy that I can have my script send output to (instead of the standard out file) that will make it back to the build agent?

Error details:
The error happens when I'm using Azure's standard python deployment script (deploy.cmd). The error occurs because webdeploy copies the data to the wwwroot folder, which makes means I have to use IN_PLACE_DEPLOYMENT. For some reason, the DEPLOYMENT_TEMP variable is never set so kudu dumps all the temporary files in wwwroot and then my script can't find the files. I think my lack of understanding of how Kudu sets deployment variables is causing some issues. As I said, I have found a work around, but I would rather understand why Kudu is not setting the DEPLOYMENT_TEMP properly.

Thanks,
Matt

**Comment by vincentdass** [comment] 2017-04-22 17:46
@MattPitlyk ,
Thanks for the explanation.
We would like to invesitgate more on this issue.
Can you please send your debug logs to RM_Customer_Queries@Microsoft.com ?

**Comment by vincentdass** [comment] 2017-04-26 06:41
@MattPitlyk , It looks like you are running Kudu deployment hook script from our task.
The script contains few variables which will be set only when you push your changes via Kudu.
In VSTS, we just run the script and do not set any variables prior to the execution.

As you said, You can set IN_PLACE_DEPLOYMENT variable in your deploy.cmd file.
Our script fails to catch any exception and we are working to fix this soon.

Closing this thread.
Please feel free to reopen, if you find any issue.

**Closed by vincentdass** 2017-04-26 06:41 UTC
Labels: Area: Release, AzureAppService

**Comment by MattPitlyk** [comment] 2017-05-09 15:03
@vincentdass Is there an open issue that I can watch for updates about your script catching exceptions from my script?

**Comment by vincentdass** [comment] 2017-05-15 03:51
@MattPitlyk , sorry for the late reply.
The issue is resolved and the fix will be available in a week or two (3.3.4 version).
Can you please ensure that the variables (say IN_PLACE_DEPLOYMENT )  are set  prior to their usage.

**Comment by MattPitlyk** [comment] 2017-06-09 21:34
@vincentdass The fix works! Errors during deployment are now caught by kudu and control is returned to the build agent. Thanks! That fix along with the feature to run a Post Deployment script from the Azure App Service Deploy task have helped us out greatly!
