### ISSUE TITLE
VSTS SqlAzureDacpacDeploymentV1 task does not respect the BlockOnPossibleDataLoss parameter in VSTS release template

### ISSUE THREAD

**Issue by ossentoo** [Microsoft/vsts-tasks#7423] opened 2018-06-11 11:24 UTC
## Environment
- Server - VSTS - organisational.  Please contact us for further information re: logs
       
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - Windows 2016 Datacenter

## Issue Description

In a VSTS release template, a dacpac db schema update for Azure SQL is not being processed because the above task fails with the message: *Msg 50000, Level 16, State 127, Line 6 Rows were detected. The schema update is terminating because data loss might occur*.

Note that we have processed schema updates to this database before. 

However, we then add the parameter /p:BlockOnPossibleDataLoss to the "Additional SqlPackage.exe Arguments" box, which should cause SqlPackage.exe to ignore any data loss warnings.  When we run the release template again however, the same issue occurs.

The parameter "BlockOnPossibleDataLoss" is being passed into the task (see screen shot below). However, it appears that it is being ignored.

[Include task name(s), screenshots and any other relevant details]

![image](https://user-images.githubusercontent.com/7569380/41228692-20100520-6d71-11e8-860f-4c56c66b9b3f.png)

![image](https://user-images.githubusercontent.com/7569380/41228669-0920af4a-6d71-11e8-9300-1966df88c368.png)

This error is very similar to the error reports here, that was never resolved.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/5b9bee46-57d7-4e95-b2af-8b1fef0215e1/sqlpackage-ignoring-blockonpossibledataloss?forum=ssdt 

### Error logs

[Insert error from the logs here]

**Comment by Ajay-MS** [comment] 2018-06-13 06:17
@ossentoo 

Yes, SQLPackage.exe should have ignored the warning when /BlockOnPossibleDataLoss is being set to false. I will check it. 

Meanwhile, can you please check in your DB project properties ( project > properties > debug) that checkbox for "Block on incremental deployment if data loss occurs" is disabled. 

**Screenshot**

![image](https://user-images.githubusercontent.com/16772764/41333279-e0828ede-6efe-11e8-9a8b-f761cf4ec9b4.png)

**Comment by niadak** [comment] 2018-06-26 06:07
@ossentoo ,  Are you still blocked on this? Did you get a chance to verify if "Block on incremental deployment if data loss occurs" is disabled?

**Comment by ossentoo** [comment] 2018-07-02 21:37
Haven't had a chance to check this as we haven't yet had to make the schema change to the next environment.

Will check this then.  For now I'll close the issue

**Comment by muiscatron** [comment] 2018-07-05 15:57
I have also experienced this problem and can verify that changing the debug setting as above doesn't make any difference - mainly because changing this on the Debug tab only seems to result in my .user settings being updated, which I don't have under source control (correctly, I believe).
However I can report that executing the SQLPAckage command exactly from the command line on my local computer results in the desired behaviour. So the problem is specific to the VSTS release task.

**Comment by kmkumaran** [comment] 2018-07-09 04:32
Re-opening based on @muiscatron comment.

**Comment by Ajay-MS** [comment] 2018-07-09 08:29
@muiscatron 

I would like to analyze this issue further. Can you please share debug logs. Debug loss can be enabled by adding a release definition variable `system.debug` with value `true`.

**Comment by SumiranAgg** [comment] 2018-07-16 05:40
Closing since no further customer communication and not enough information provided for investigation.

**Closed by SumiranAgg** 2018-07-16 05:40 UTC
Labels: Area: Release

**Comment by juanluis2017** [comment] 2019-01-19 03:51
I have the same problem with the vsts release task , in my local sql project I disabled lock on incremental deployment if data loss occurs and work ,but   the publish in the release pipeline in vsts this dont work

**Comment by Ajay-MS** [comment] 2019-01-21 08:59
@juanluis2017 

Can you execute SQLPackage.exe cmdlet ( can copy it from logs ) directly via cmd to see if issue persists. 

There are following options to disable the "Block incremental deployment if data loss might occur" option:

1. On the "Debug" tab of "Project Properties"
2. Using the /p:BlockOnPossibleDataLoss=True command-line option
3. Specifying <BlockOnPossibleDataLoss>True</BlockOnPossibleDataLoss> in a publish config file

You have already tried out option 1, can you please also try option 2.

**Comment by juanluis2017** [comment] 2019-01-22 02:34
thanks @Ajay-MS #
finally the task worked fine  but the command  that I used was /p:BlockOnPossibleDataLoss=false
