### ISSUE TITLE
Unable to load service index for source error when install nuget package from VSTS Package Feed

### ISSUE THREAD

**Issue by SayusiAndo** [Microsoft/vsts-tasks#3862] opened 2017-03-24 16:14 UTC
Hi All,

I want to install nuget packages at every build from VSTS nuget feed at every build, but it fails.

**Scenario**:

My application is getting bigger and bigger and it must be splitted. It means multiple modules with with a git repository, two builds (one for release, one for feature branches) and a nuget feed per. And there is a main build where the module packages are met. This build responsible basically only for installing the module nuget packages for release.

This means every module build publishes a package to a VSTS nuget feed at every build. Versioning set up accordingly, it is date based.

The main build nuget.config set up in the way it should install always the lates from a package.

I can't accomplish the scenario above because nuget fails at installing nuget packages from VSTS nuget feed.

I have searched for this bug and basically there are no usable information. I opened a question in [Stackoverflow ](http://stackoverflow.com/questions/40788216/error-when-installing-nuget-package-from-vsts-feed)and there are no usable information so far.

I did not have the chance to setup a private nuget server and POCing whether my setup works or not.

**My questions**:

- Is my setup correct this way?
- What should I do, what modifications are needed to accomplish my goal?
- is there anything you need to work on this/investigate it?

**packages.config**:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Lib1" allowedVersions="[1,2)" version="1.0.0"  targetFramework="net452" />
</packages>
```

**Nuget.config**, which contains credentials to access VSTS nuget feed:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="nugetpocfeedauthed" value="https://sayusiando.pkgs.visualstudio.com/_packaging/NugetPOCFeed/nuget/v3/index.json" />
  </packageSources>
  <activePackageSource>
    <add key="All" value="(Aggregate source)" />
  </activePackageSource>
  <packageSourceCredentials>
    <nugetpocfeedauthed>
      <add key="Username" value="username" />
      <add key="Password" value="encodedpassword" />
    </nugetpocfeedauthed>
  </packageSourceCredentials>
</configuration>
```

**Build setup**:

![image](https://cloud.githubusercontent.com/assets/5106373/24302746/ffe6eab8-10b3-11e7-9e34-b57f6f4fc5ac.png)

Error message:

```
2017-03-24T16:01:34.6853730Z ##[section]Starting: NuGet install NugetStuffAtOnePlace/NugetStuffAtOnePlace.sln
2017-03-24T16:01:34.7123752Z ==============================================================================
2017-03-24T16:01:34.7123752Z Task         : NuGet Installer
2017-03-24T16:01:34.7123752Z Description  : Installs or restores missing NuGet packages
2017-03-24T16:01:34.7123752Z Version      : 0.2.29
2017-03-24T16:01:34.7123752Z Author       : Microsoft Corporation
2017-03-24T16:01:34.7123752Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613747)
2017-03-24T16:01:34.7123752Z ==============================================================================
2017-03-24T16:01:35.4848179Z [command]C:\Windows\system32\chcp.com 65001
2017-03-24T16:01:35.5108180Z Active code page: 65001
2017-03-24T16:01:36.1894368Z Detected NuGet version 3.5.0.1938 / 3.5.0
2017-03-24T16:01:36.1904357Z SYSTEMVSSCONNECTION exists true
2017-03-24T16:01:36.1904357Z [command]C:\a\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe install -NonInteractive C:\a\1\s\NugetStuffAtOnePlace\NugetStuffAtOnePlace.sln -ConfigFile C:\a\1\s\NugetStuffAtOnePlace\.nuget\nuget.config -NoCache -Verbosity Detailed
2017-03-24T16:01:36.8469783Z NuGet Version: 3.5.0.1938
2017-03-24T16:01:36.9095850Z Feeds used:
2017-03-24T16:01:36.9095850Z   https://www.nuget.org/api/v2/
2017-03-24T16:01:36.9095850Z   https://sayusiando.pkgs.visualstudio.com/_packaging/NugetPOCFeed/nuget/v3/index.json
2017-03-24T16:01:36.9095850Z 
2017-03-24T16:01:37.1518885Z   GET https://www.nuget.org/api/v2/FindPackagesById()?id='C:%5Ca%5C1%5Cs%5CNugetStuffAtOnePlace%5CNugetStuffAtOnePlace.sln'
2017-03-24T16:01:37.1788883Z   OK https://www.nuget.org/api/v2/FindPackagesById()?id='C:%5Ca%5C1%5Cs%5CNugetStuffAtOnePlace%5CNugetStuffAtOnePlace.sln' 26ms
2017-03-24T16:01:37.3328348Z System.AggregateException: One or more errors occurred. ---> NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://sayusiando.pkgs.visualstudio.com/_packaging/NugetPOCFeed/nuget/v3/index.json. ---> System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.
2017-03-24T16:01:37.3328348Z 
2017-03-24T16:01:37.3328348Z    at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
2017-03-24T16:01:37.3328348Z    at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
2017-03-24T16:01:37.3328348Z    at NuGet.Configuration.PackageSourceCredential.get_Password()
2017-03-24T16:01:37.3328348Z    at NuGet.Protocol.HttpSourceAuthenticationHandler..ctor(PackageSource packageSource, HttpClientHandler clientHandler, ICredentialService credentialService)
2017-03-24T16:01:37.3328348Z    at NuGet.Protocol.HttpHandlerResourceV3Provider.CreateResource(PackageSource packageSource)
2017-03-24T16:01:37.3328348Z    at NuGet.Protocol.HttpHandlerResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
2017-03-24T16:01:37.3328348Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2017-03-24T16:01:37.3328348Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3328348Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3328348Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3328348Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
2017-03-24T16:01:37.3328348Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3328348Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3328348Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3328348Z    at NuGet.Protocol.HttpSource.<CreateHttpClientAsync>d__18.MoveNext()
2017-03-24T16:01:37.3328348Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3328348Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.HttpSource.<EnsureHttpClientAsync>d__17.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__16.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.HttpSource.<>c__DisplayClass12_0.<<GetAsync>b__0>d.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.HttpSource.<GetAsync>d__12.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
2017-03-24T16:01:37.3338342Z    --- End of inner exception stack trace ---
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.DependencyInfoResourceV3Provider.<TryCreate>d__1.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionCoreAsync>d__80.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass79_1.<<GetLatestVersionAsync>b__0>d.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__79.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3338342Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3338342Z    at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__78.MoveNext()
2017-03-24T16:01:37.3338342Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.CommandLine.InstallCommand.<InstallPackage>d__31.MoveNext()
2017-03-24T16:01:37.3348339Z    --- End of inner exception stack trace ---
2017-03-24T16:01:37.3348339Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2017-03-24T16:01:37.3348339Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2017-03-24T16:01:37.3348339Z    at NuGet.CommandLine.Command.Execute()
2017-03-24T16:01:37.3348339Z    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
2017-03-24T16:01:37.3348339Z ---> (Inner Exception #0) NuGet.Protocol.Core.Types.FatalProtocolException: Unable to load the service index for source https://sayusiando.pkgs.visualstudio.com/_packaging/NugetPOCFeed/nuget/v3/index.json. ---> System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.
2017-03-24T16:01:37.3348339Z 
2017-03-24T16:01:37.3348339Z    at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
2017-03-24T16:01:37.3348339Z    at NuGet.Configuration.EncryptionUtility.DecryptString(String encryptedString)
2017-03-24T16:01:37.3348339Z    at NuGet.Configuration.PackageSourceCredential.get_Password()
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpSourceAuthenticationHandler..ctor(PackageSource packageSource, HttpClientHandler clientHandler, ICredentialService credentialService)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpHandlerResourceV3Provider.CreateResource(PackageSource packageSource)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpHandlerResourceV3Provider.TryCreate(SourceRepository source, CancellationToken token)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpSource.<CreateHttpClientAsync>d__18.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpSource.<EnsureHttpClientAsync>d__17.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpSource.<GetThrottledResponse>d__16.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpSource.<>c__DisplayClass12_0.<<GetAsync>b__0>d.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__2`1.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.HttpSource.<GetAsync>d__12.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
2017-03-24T16:01:37.3348339Z    --- End of inner exception stack trace ---
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.ServiceIndexResourceV3Provider.<GetServiceIndexResourceV3>d__9.MoveNext()
2017-03-24T16:01:37.3348339Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3348339Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3348339Z    at NuGet.Protocol.ServiceIndexResourceV3Provider.<TryCreate>d__8.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.Protocol.DependencyInfoResourceV3Provider.<TryCreate>d__1.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__16`1.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.Protocol.Core.Types.SourceRepository.<GetResourceAsync>d__15`1.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionCoreAsync>d__80.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.PackageManagement.NuGetPackageManager.<>c__DisplayClass79_1.<<GetLatestVersionAsync>b__0>d.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__79.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.PackageManagement.NuGetPackageManager.<GetLatestVersionAsync>d__78.MoveNext()
2017-03-24T16:01:37.3358335Z --- End of stack trace from previous location where exception was thrown ---
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-03-24T16:01:37.3358335Z    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
2017-03-24T16:01:37.3358335Z    at NuGet.CommandLine.InstallCommand.<InstallPackage>d__31.MoveNext()<---
2017-03-24T16:01:37.3358335Z 
2017-03-24T16:01:37.3508450Z ##[error]Error: C:\a\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.29\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe failed with return code: 1
2017-03-24T16:01:37.3508450Z ##[error]Packages failed to install
2017-03-24T16:01:37.3528343Z ##[section]Finishing: NuGet install NugetStuffAtOnePlace/NugetStuffAtOnePlace.sln
```

**Comment by alexmullans** [comment] 2017-05-31 19:42
Closing this as old and not a bug (recommended to use nuget restore instead of nuget install).

**Closed by alexmullans** 2017-05-31 19:42 UTC
Labels: Area: Packaging
