### ISSUE TITLE
PowerShellOnTargetMachines fails on Windows Server 2012 R2 when rebooting by DSC

### ISSUE THREAD

**Issue by Rajat-Jindal** [Microsoft/vsts-tasks#4885] opened 2017-07-27 09:13 UTC
PS Remoting Tasks fails, when the target is rebooted by a DSC configuration.

Whenever the Windows server 2012 R2 reboots the below error appears with the task: 

##[error]System.Management.Automation.RuntimeException: Syntax Error. Number value is not valid: empty number string
At line:1, char:0
Buffer:
^?

Below is the DSC file i am using in task to run: 

configuration Main
{
	param(
		[string[]]$MachineName = 'localhost'
	)

	node ($MachineName)
	{
		localconfigurationmanager
		{
			ConfigurationModeFrequencyMins = 1440
			ConfigurationMode = 'ApplyAndAutoCorrect'
			RebootNodeIfNeeded = $True
		}

		windowsfeature WebServerRole
		{
			Name = "Web-Server"
			Ensure = "Present"
		}

		windowsfeature WebAppDev
		{
			Name = "Web-App-Dev"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebAspNet45
		{
			Name = "Web-Asp-Net45"
			Ensure = "Present"
			Source = $Source
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebNetExt35
		{
			Name = "Web-Net-Ext"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebNetExt45
		{
			Name = "Web-Net-Ext45"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebFtpServer
		{
			Name = "Web-Ftp-Server"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebMgmtCompat
		{
			Name = "Web-Mgmt-Compat"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebISAPIExt
		{
			Name = "Web-ISAPI-Ext"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebISAPIFilter
		{
			Name = "Web-ISAPI-Filter"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebLogLibraries
		{
			Name = "Web-Log-Libraries"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebRequestMonitor
		{
			Name = "Web-Request-Monitor"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebMgmtTools
		{
			Name = "Web-Mgmt-Tools"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WebMgmtConsole
		{
			Name = "Web-Mgmt-Console"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WAS
		{
			Name = "WAS"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WASProcessModel
		{
			Name = "WAS-Process-Model"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WASNetEnvironment
		{
			Name = "WAS-NET-Environment"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		windowsfeature WASConfigAPIs
		{
			Name = "WAS-Config-APIs"
			Ensure = "Present"
			DependsOn = "[WindowsFeature]WebServerRole"
		}

		#script block to download WebPI MSI from the Azure storage blob
		script DownloadWebPIImage
		{
			GetScript = {
				@{
					GetScript = $GetScript
					SetScript = $SetScript
					TestScript = $TestScript					
					Result = ('True' -in (Test-Path C:\ConfigureEnvironment\wpilauncher.exe))
				}
			}
			TestScript = {
				$Status = ('True' -in (Test-Path C:\ConfigureEnvironment\wpilauncher.exe))
				$Status -eq $True
			}
			SetScript = {
				$source = "http://go.microsoft.com/fwlink/?LinkId=255386"
				$destination = "C:\ConfigureEnvironment\wpilauncher.exe"
				Invoke-WebRequest -Uri $source -OutFile $destination
			}
		}

		package WebPi_Installation
		{
			Ensure = "Present"
			Name = "Microsoft Web Platform Installer 5.0"
			Path = "C:\ConfigureEnvironment\wpilauncher.exe"
			ProductId = '4D84C195-86F0-4B34-8FDE-4A17EB41306A'
			Arguments = ''
			DependsOn = "[Script]DownloadWebPIImage"
		}

		package WebDeploy_Installation
		{
			Ensure = "Present"
			Name = "Microsoft Web Deploy 3.5"
			Path = "$env:ProgramFiles\Microsoft\Web Platform Installer\WebPiCmd-x64.exe"
			ProductId = ''
			#Arguments = "/install /products:ASPNET45,ASPNET_REGIIS_NET4,NETFramework452,NETFramework4Update402,NetFx4,NetFx4Extended-ASPNET45,NetFxExtensibility45,DefaultDocument,DirectoryBrowse,StaticContent,StaticContentCompression,WDeploy  /AcceptEula"
			Arguments = "/install /products:WDeploy  /AcceptEula"
			DependsOn = @( "[Package]WebPi_Installation")
		}
		
		#Script block to download .NET Core Windows Server Hosting bundle from the Azure storage blob
		script DownloadCoreWindowServerHostingBundleImage
		{
			GetScript = {
				@{
					GetScript = $GetScript
					SetScript = $SetScript
					TestScript = $TestScript					
					Result = ('True' -in (Test-Path C:\ConfigureEnvironment\DotNetCore.1.0.5_1.1.2-WindowsHosting.exe))
				}
			}
			TestScript = {
				$Status = ('True' -in (Test-Path C:\ConfigureEnvironment\DotNetCore.1.0.5_1.1.2-WindowsHosting.exe))
				$Status -eq $True
			}
			SetScript = {
				$source = "https://go.microsoft.com/fwlink/?linkid=848766"
				$destination = "C:\ConfigureEnvironment\DotNetCore.1.0.5_1.1.2-WindowsHosting.exe"
				Invoke-WebRequest -Uri $source -OutFile $destination
			}
		}

		package CoreWindowServerHostingBundle_Installation
		{
			Ensure = "Present"
			Name = "Microsoft .net Core 1.0.5 & 1.1.2 - Windows Server Hosting"
			Path = "C:\ConfigureEnvironment\DotNetCore.1.0.5_1.1.2-WindowsHosting.exe"
			ProductId = ''
			Arguments = '/S /v/qn'
			DependsOn = "[Script]DownloadCoreWindowServerHostingBundleImage"
		}
	}
}
Main

**Comment by KrishnaAdityaB** [comment] 2017-08-30 19:35
Closing this thread. This will be tracked at #4543

**Comment by KrishnaAdityaB** [comment] 2017-09-20 10:04
@Rajat-Jindal Sorry for the delay in response.
As I was mentioning on other thread - We were not able to reproduce the issue with Windows Server 2012 R2. Can you try a simple script (provided in #4543)

```
Configuration RebootDSC
{     
  Node localhost
  {
    # tell the node to reboot if necessary
    LocalConfigurationManager
    {
      RebootNodeIfNeeded = $true
    }
  
    Script RebootDSC
    {
      GetScript = { return "RebootDSC" }
      TestScript = {
        $value = Get-ItemProperty 'HKLM:\SOFTWARE\ahd\RebootDSC' -name Enabled -ErrorAction silentlycontinue
        if ($value -eq $null) 
        { 
          Write-Verbose "Reboot is needed..."
          return $false
        }
        else
        {
          Write-Verbose "Reboot already in desired state"
          return $true
        }
      }
      SetScript = {
        New-Item 'HKLM:\SOFTWARE\ahd\RebootDSC' -Force | Out-Null
        New-ItemProperty -path 'HKLM:\SOFTWARE\ahd\RebootDSC' -name Enabled -value 1 -PropertyType 'DWord' -Force | Out-Null
        $global:DSCMachineStatus = 1 #force reboot
      }
    }
  }
}

RebootDSC
```

**Comment by vincentdass** [comment] 2017-09-26 14:20
@Rajat-Jindal , Closing this issue  as no response received.
Feel free to open the issue, if required.

**Closed by vincentdass** 2017-09-26 14:20 UTC
Labels: Area: Release

**Comment by KrishnaAdityaB** [comment] 2017-09-27 10:17
@Rajat-Jindal 
Are you in PS5?
Can you try the solution provided in #4543 and share the experience?
