### ISSUE TITLE
Cloud-based Web Performance Test issue

### ISSUE THREAD

**Issue by xingyu217** [Microsoft/vsts-tasks#3668] opened 2017-02-22 07:57 UTC
Succeed setup test agent (Article: [Use cloud load agents on your infrastructure](https://blogs.msdn.microsoft.com/visualstudioalm/2016/08/22/use-cloud-load-agents-on-your-infrastructure/)), after that, the load test works fine on web access and via Visual Studio load test with VSTS by using self-provisioned agents.
But, failed to run load test through VSTS Build with Cloud-based Web Performance Test build step (Configured generic connection with alternate account that has full permission). 

Error:
Getting Clt Endpoint:
2017-02-22T06:01:43.7097715Z Fetching the Clt endpoint for https://starain.visualstudio.com
2017-02-22T06:01:43.7297972Z Fetching the SPS endpoint for https://starain.visualstudio.com
2017-02-22T06:01:45.1428354Z Fetching the CLT endpoint for https://starain.visualstudio.com
2017-02-22T06:01:46.5309085Z VSO account Url = https://starain.visualstudio.com
2017-02-22T06:01:46.5368970Z CLT account Url = https://starain.vsclt.visualstudio.com/
2017-02-22T06:01:54.6652928Z Load test 'webload.loadtest' is in state 'queued|none'.
2017-02-22T06:02:10.9210419Z Load test 'webload.loadtest' is in state 'aborted|none'.
2017-02-22T06:02:11.8510591Z ------------------------------------
2017-02-22T06:02:12.8271249Z [Message]This run was requested by 'Starain' using the Visual Studio Team Services Account 'starain'.
2017-02-22T06:02:12.8280971Z [Message]This load test will run using 1 machines. Learn more about agent core allocation here: https://go.microsoft.com/fwlink/?LinkId=331637
2017-02-22T06:02:12.8301247Z [Message]This load test was run using self-provisioned rig 'default'. No virtual-user minutes (VUMs) will be charged for this run.
2017-02-22T06:02:12.8620978Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: Test run could not be started using the self-provisioned rig 694f8310-2406-4022-b85e-97dd9106a4e9. Number of free machines available in the rig are less than the required number. (Requested – 1, Available - 0, In-Use – 0, Offline – 0).
2017-02-22T06:02:12.8650988Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: Test run could not be started and has been marked as 'Aborted' due to an error while provisioning test agents for the run.
2017-02-22T06:02:12.8660992Z ------------------------------------
2017-02-22T06:02:14.1651581Z Run-id for this load test is 19 and its name is 'webload.loadtest'.

Note: my agent group name is **trial**.

**Comment by CosminGramada** [comment] 2017-02-22 08:13
Reproducible, with the original posts submitted [here](http://stackoverflow.com/questions/42367634/visual-studio-and-jmeter-web-performance-tests-are-unable-to-find-free-machines) and [here](https://social.msdn.microsoft.com/Forums/vstudio/en-US/5616bc22-5898-4eea-a3cb-dd1ec898dfcc/visual-studio-and-jmeter-web-performance-tests-are-unable-to-find-free-machines-on-the?forum=TFService).

Besides this, I'd also add the fact that the Cloud-based Web Performance Test build step is running the test with the ".loadtest" extension. 
I've been able to pinpoint the root in the ~\_work\tasks\Invoke-QuickPerfTest.ps1 PowerShell script from the Agent machine (row 79). 
While I'm not sure what impact this is having on the end test, fortunately manually changing the extension to ".webtest" is persistent (although not sure to what extent or when these scrips are refreshed) but I'm guessing this will have an impact on user trying to run Load and Performance tests on the same agents.

**Comment by deepab1971** [comment] 2017-03-01 03:29
We are also getting the similar exception while using the Self-provisioned agent. 
Exception "Test run has been aborted and marked as 'Error' due to an error while provisioning test agents for the run."

1)  We have setup this agent in on-premise
We tried executing  Visual Studio test by uploading webtest file in the VisualStudio web access. We are able to see our self-provisioned agent in the list and able to pick it.
However it gets stuck in configuring agent for few mins and after that aborts with above exception.
If we stop the agent service locally - it is able to recognize and throw error stating agent not available for execution. However when the agent is available it is not proceeding and completing the test.

Do we need open any specific ports in on-premise for CLT to interact with on-premise agent?

2) Second question is there a way we can connect to this Self-provisioned agent from VSTS?
When we execute the load test from VSTS like [this](https://www.visualstudio.com/en-us/docs/test/performance-testing/getting-started/getting-started-with-performance-testing) 

There we see only Cloud agents get listed and does not list self-provisioned agents

**Comment by cltshivash** [comment] 2017-03-01 03:57
@xingyu217 @CosminGramada We currently aren't exposing the agent group as an input in the tasks. We will update the task to accept the agent group as an input.

@deepab1971 Can you please send your account name to vsoloadtest at microsoft dot com ? We will look into the failures.

**Comment by CosminGramada** [comment] 2017-03-01 07:49
@cltshivash Thank you for the update. Do you have a timeline on when this will be deployed and available?

**Comment by PBoraMSFT** [comment] 2017-03-27 11:52
I don't have the exact dates to share, but we will pick this up in 2-3 sprints from now, once the current set of deliverables are done. 
I am closing this issue since we don't use the issues list to track backlog items.

**Closed by PBoraMSFT** 2017-03-27 11:52 UTC
Labels: Area: Test
