### ISSUE TITLE
[DeployAzureResourceGroup] - Updating Resource Group gives error "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."

### ISSUE THREAD

**Issue by ChrisMelinn** [Microsoft/vsts-tasks#3070] opened 2016-11-11 01:00 UTC
When using the DeployAzureResourceGroup task in VSTS, we often see errors like the following:

```
==============================================================================
Task         : Azure Resource Group Deployment
Description  : Deploy, start, stop, delete Azure Resource Groups
Version      : 1.0.95
Author       : Microsoft Corporation
Help         : [More Information](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployAzureResourceGroup/README.md)
==============================================================================
##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
##[command]Select-AzureRMSubscription -SubscriptionId **removed** -TenantId ********
##[error]Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
```

The same task (release step) executes successfully when **creating** the resource group, but fails when trying to **update** the resource group.  I don't know for sure, but I think it may fail when there have been slight modification to the underlying resources since the last (create) deployment.

We are running this with Deployment Mode = Incremental

If we run a similar deployment locally using `New-AzureRmResourceGroupDeployment` with the same template and parameters files, it also runs successfully.

Any help or ideas would be appreciated.  Thanks!

**Comment by sachinma** [comment] 2016-11-15 12:25
@ChrisMelinn - We would need more information to debug this issue further. Can you set system.debug variable to true, run the task and share the logs with debug information? You can choose to share the logs here or send it us RM_Customer_queries@microsoft.com

**Comment by sachinma** [comment] 2016-11-24 03:44
@ChrisMelinn we would be needing the debug logs to analyze it further. Can you provide the logs if you are still running into this problem.

**Comment by sachinma** [comment] 2016-12-13 04:22
Closing the issue.  Please reopen with additional logs if you hit it again.

**Comment by ChrisMelinn** [comment] 2017-01-19 05:44
Hi @sachinma , as mentioned in emails, we have identified that our issue was due to a problem with the service principal.  We created a new SPN which has resolved the problem.  Should we reopen this issue until the hotfix is ready as well?

**Comment by sachinma** [comment] 2017-01-19 06:44
@ChrisMelinn I have opened the issue. As discussed, it was an SPN issue but there was no good way to trace the exact reason. I will use this issue to track adding the right tracing.

**Comment by sachinma** [comment] 2017-01-30 09:56
Hi @ChrisMelinn we are deploying the updated task; and your account should get the updated task by the end of this week. Then you should be able to run this task again with the old service endpoint and see if you get additional logs (with system.debug=true) to root cause the issue with the service endpoint.

**Closed by sachinma** 2017-01-30 09:56 UTC
Labels: Area: Release
