### ISSUE TITLE
Inline SQL Script UPDATE doesn't work on self-hosted Agent

### ISSUE THREAD

**Issue by PaulMEdwards** [Microsoft/vsts-tasks#7031] opened 2018-04-20 03:54 UTC
Similar to #5817 , I'm encountering problems with the Inline SQL Script task, but the difference is that I'm running it from a deployment group, filtered using a tag to a single machine running SQL Server. I've actually tried 2 different machines, one running SQL 2012 on Windows Server 2012 R2 and another running SQL 2014 on Windows Server 2012 (not R2), both with PowerShell 5.1 & the latest SqlServer module installed via the suggestion on #5817 .

I'm trying to execute a few SQL UPDATE statements, and in one case a SELECT statement first, but the UPDATEs never run and seem to abort the entire task when attempted. I say that because the one task which performs the following, only executes the first SELECT and nothing more:

1. SELECT
2. UPDATE
3. SELECT
4. SELECT
5. UPDATE
6. UPDATE
7. SELECT

The SQL statements run manually in SQL Server Management Studio work fine.

Verbose log attached.

Thanks in advance for any assistance provided, especially pointing out anything I may have overlooked or to try next!

[tasklog_3.log](https://github.com/Microsoft/vsts-tasks/files/1930592/tasklog_3.log)
[tasklog_4.log](https://github.com/Microsoft/vsts-tasks/files/1930593/tasklog_4.log)
[tasklog_5.log](https://github.com/Microsoft/vsts-tasks/files/1930594/tasklog_5.log)

**Comment by Ajay-MS** [comment] 2018-04-20 15:54
I have tried the following scenario and it's worked fine. 

Can you please share your email id so that we can have a call in order to understand the cause of the issue.

**Comment by PaulMEdwards** [comment] 2018-04-20 18:13
@Ajay-MS pedwards@ethoslending.com

**Comment by rokmicrosoft** [comment] 2018-05-15 10:55
@PaulMEdwards Are you still blocked ? If yes is it possible to have a Skype call to debug it further ? You may share your details at RM_Customer_Queries@Microsoft.com

**Comment by niadak** [comment] 2018-06-26 08:19
@PaulMEdwards Are you still blocked ? I am closing the issue for now. Please feel free to reopen if required.

**Closed by niadak** 2018-06-26 08:19 UTC
Labels: Area: Release
