### ISSUE TITLE
"PowerShell on Target Machines" error when scipt contains Set-StrictMode

### ISSUE THREAD

**Issue by ghowlett2020** [Microsoft/vsts-tasks#2991] opened 2016-11-01 10:18 UTC
Hi,

I have a PowerShell script.... a simple example...

`Set-StrictMode -Version Latest

Write-Verbose "test" -Verbose`

Using the Release Management Task - "PowerShell on Target Machines".

When runs it errors with...

2016-11-01T10:10:54.0480931Z System.AggregateException: Failed to apply configuration in the DSC script to the computer. Consult the Logs below for details of the error.

8 
2016-11-01T10:10:54.0480931Z The property 'Length' cannot be found on this object. Verify that the property exists. ---> System.Management.Automation.PropertyNotFoundException: The property 'Length' cannot be found on this object. Verify that the property exists.

Removing option strict resolves this error.

This used to work on the legacy VSTS agent (v1), but the new agent version 2.107.0 this doesn't work any more.

Many Thanks

**Comment by KrishnaAdityaB** [comment] 2016-11-02 14:00
@ghowlett2020 
I am able to reproduce this issue with v2.108. But not with v2.109 (https://github.com/Microsoft/vsts-agent/releases/tag/v2.109.0).

@ericsciple Can this issue be considered fixed with v2.109 and above? 
I am not able to find anything directly related to it in commit descriptions (https://github.com/Microsoft/vsts-agent/commits/v2.109.0). So, I am not sure if this fix is conscious.

**Comment by ericsciple** [comment] 2016-11-02 15:03
since this task uses the old ps handler, it sounds likely that was fixed by the commit that pulled in the client OM update (includes legacy ps host and modules)

**Closed** 2016-11-03 06:33 UTC
Labels: Area: Release
