### ISSUE TITLE
Default registry.npmjs.org registry is not overridden by a NPM Service Endpoint registry

### ISSUE THREAD

**Issue by vbossica** [Microsoft/vsts-tasks#5518] opened 2017-09-29 18:09 UTC
When defining an NPM Service Endpoint, the NPM VSTS task does not use it in the generated `.npmrc` file and defaults to `repository.npmjs.org`.

**Steps to reproduce**

  1. create a NPM Service Endpoint
  2. in a build definition for a node project, add the NPM task and invoke the custom command `config ls -l`
  3. add as custom registry (_Registries in my .npmrc_) the one created previously
  4. execute the build with `system.debug = true`

**Expected behaviour**

  * the custom NPM registry overrides the default one and is used during NPM execution

**Actual behaviour**

  * the default `registry.npmjs.org` registry is not overridden (except from the log):

```
2017-09-29T17:52:50.3384710Z ; userconfig /opt/vsts/work/1/npm/43724.npmrc
2017-09-29T17:52:50.3413570Z //[my_registry]/:always-auth = true
2017-09-29T17:52:50.3446220Z //[my_registry]/:email = "********"
2017-09-29T17:52:50.3478080Z //[my_registry]/:username = "********"
...
2017-09-29T17:52:50.6185000Z registry = "https://registry.npmjs.org/"
```

**First analysis**

Looking at the code, in `npmcustom.ts`, the NPM registries defined as Service Endpoint are always loaded with `authOnly=true` (line 28) and thus can never be used as default registry (line 35.)

But maybe I'm missing something here.

**Comment by zarenner** [comment] 2017-10-03 00:36
I think your understanding is correct.

+@alexmullans to comment here on the intent/design.
Alex, it looks like when you use the "Registries in my .npmrc" setting, it only will supply creds for those registries (somewhat hinted by the text "Credentials for registries...") rather than setting one of them as the default registry as well.

The "Registry I select here" option does set it as the default registry, but doesn't allow using registries in another account (or non-VSTS registries).

@vbossica Does checking in a .npmrc with registry set to the same registry as your service endpoint work for you as a workaround?

**Comment by alexmullans** [comment] 2017-10-03 04:12
Correct. The intent here was to only add _credentials_ to your .npmrc securely, but not to alter the actual restore behavior. The assumption is that the .npmrc you check into your repo will already have a `registry=` line or `@scope\registry=` lines with your desired registry/registries, and we'll add credentials for you.

**Comment by vbossica** [comment] 2017-10-03 08:33
In our case, we do not check in the `.npmrc` file (because of the credentials, obviously) but creating one on the fly works.

Thanks for the clarification.

**Comment by alexmullans** [comment] 2017-10-03 13:19
Glad you've got it working! It's definitely the right move not to check in your credentials. If you like, you can use two separate npmrc files: one with the registries only that you check in and one with the credentials that lives in your profile folder. npm will merge these for you on the machine.

**Comment by keithrob** [comment] 2017-10-11 21:56
Closing as it looks like the issue is resolved.

**Closed by keithrob** 2017-10-11 21:56 UTC
Labels: Area: Packaging
