### ISSUE TITLE
AzureRmWebAppDeploymentV4 v.4.2.2 tempParameterSet.xml etr

### ISSUE THREAD

**Issue by mbialitskiy** [Microsoft/vsts-tasks#7784] opened 2018-07-19 13:02 UTC
## Environment
**VSTS**:          
account name: rapmd
team project name:rapmd
release definition name: QA
release definition number: 248+
**Agent**:
Private (windows 2016, agent ver.2.120.2)

## Issue Description
The error appeared after extension update from version 4.1.12 to 4.2.2
In release I have two successive tasks: deply webapp and function app. 
After first is successfully deployed the second fails with error: 

**Error: Failed cp: cp: dest file already exists: C:\agent3\_work\r1\a\tempSetParameters.xml**

If switch tasks the result is the same.
The workaround for now is to create a step between tasks that removes the tempSetParameters.xml but I think it should be fixed in the service.

### Error logs
2 Logs: 4.1.2 - with success deployment, 4.2.2 - with error

[4.2.2.log](https://github.com/Microsoft/vsts-tasks/files/2210001/4.2.2.log)
[4.1.2.log](https://github.com/Microsoft/vsts-tasks/files/2210002/4.1.2.log)

**Comment by vincentdass** [comment] 2018-07-19 15:16
@mbialitskiy , thanks for reporting the issue. This is a genuine issue and will be fixed.

**Comment by vincentdass** [comment] 2018-07-26 05:57
@mbialitskiy , the issue is fixed and the fix will be available in upcoming deployment.

**Closed by vincentdass** 2018-07-26 05:57 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by joe45sp** [comment] 2018-07-26 14:14
@vincentdass does this fix the issue with appsetting json variables not being replaced as well?

**Comment by joe45sp** [comment] 2018-07-26 14:14
@vincentdass also when is the upcoming deployment? Is there a way to see a schedule of this?

**Comment by vincentdass** [comment] 2018-07-26 16:38
@joe45sp , JSON var. substitution issue is getting hotfixed. This should available this week.
Setparam issue fix will be available in ~3-4 weeks.

**Comment by joe45sp** [comment] 2018-07-26 19:03
@vincentdass is there anyway to see release progress? Also, can you point me to the commit that fixed the json var substitution? Just curious to see what fixed it. Thank you for all your help with this!!!

**Comment by vincentdass** [comment] 2018-07-27 05:59
@joe45sp , JSON variable substitution fix: #7818. (Task replaced the values in JSON but deployed the unmodified (original) package and this created an impression that JSON variable substitution didn't work)
