### ISSUE TITLE
Failed to publish test results: Value was either too large or too small for an Int32.

### ISSUE THREAD

**Issue by shaileshkumar-atos** [Microsoft/vsts-tasks#5563] opened 2017-10-05 08:41 UTC
Running the UFT testcase using Jenkins. And this is triggered from VSTS Release step.
After successful run of UFT testcase in jenkins, collecting the results from Jenkins to VSTS in JUnit format.
In VSTS the release if completing successfully, but the test results are giving the following issue:
          
> **Failed to publish test results: Value was either too large or too small for an Int32.**

When I checked the result xml of testcase in Jenkins, found out that in <testcase> the "time" attribute have very large value of "1.6398392E8".
Just to check, I manually changed this "time" value to "1.6398", then it's displaying the test in VSTS.

In Jenkins test result duration also, it's showing in years:
![error](https://user-images.githubusercontent.com/29246609/31218073-cabcc7d8-a9d6-11e7-98f5-ad3243f61f6a.png)

Configuration of triggering the UFT test cases:
![config](https://user-images.githubusercontent.com/29246609/31218108-e63e33de-a9d6-11e7-9cf3-e52ac257cfbb.png)

Kindly let me know why this much big time is coming in this xml file and how to resolve this issue.

**Comment by pjquirk** [comment] 2017-10-05 19:34
Unless your unit tests really do take 21 years to run, this sounds more like a bug with your test runner on your Jenkins server.  It would probably be ideal for TFS to better handle values this large, but that would likely only handle these buggy scenarios.

Can you post some of your result XML so we can get a sense of what values are too large?  Can you confirm the error comes from the 'Publish Test Results' task?

**Comment by shaileshkumar-atos** [comment] 2017-10-09 10:07
Thanks for your reply pjquirk :)
Following is the result xml file:

`<?xml` `version="1.0"?>`

`<testsuites` xmlns:xsd="http://www.w3.org/2001/XMLSchema" `xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

`<testsuite` package="HPToolsFileSystemRunner" errors="0" failures="0" `tests="1">`

`<testcase` status="pass" classname="All-Tests.<None>" time="89,925759" report="C:\Users\Administrator\Downloads\DevOps_Nokia\Scripts\DevOps_NOKIA\Report" `name="C:\Users\Administrator\Downloads\DevOps_Nokia\Scripts\DevOps_NOKIA">`

`<system-out>05.10.2017` 11:54:00 Running: C:\Users\Administrator\Downloads\DevOps_Nokia\Scripts\DevOps_NOKIA Running test: C:\Users\Administrator\Downloads\DevOps_Nokia\Scripts\DevOps_NOKIA Test result: Passed 05.10.2017 11:55:30 Test complete: C:\Users\Administrator\Downloads\DevOps_Nokia\Scripts\DevOps_NOKIA ------------------------------------------------------------------------------------------------------- `</system-out>`

`</testcase>`
`</testsuite>`
`</testsuites>`

**Comment by shaileshkumar-atos** [comment] 2017-10-11 06:28
@pjquirk I have shared the xml result above.
Kindly let me know if something can be done.

**Comment by pjquirk** [comment] 2017-10-11 13:16
It looks like there could be an internationalization problem here.  Your XML file reports time as `89,925759`, which appears to be using the comma as a decimal separator.  Is it possible this file is being generated on one machine with a culture setting that uses the comma, and then the file is transmitted to the machine your Jenkins server is on, which is using a culture that uses a period as the separator?

**Comment by shaileshkumar-atos** [comment] 2017-10-11 13:20
I have installed the UFT and Jenkins on the same machine.
In this case, what should I check?

**Comment by pjquirk** [comment] 2017-10-11 13:26
I can't really know, at this point I believe it's a problem with Jenkins and UFT not agreeing on how to format fractional numbers.  You should investigate how to get Jenkins to report the correct time first.  Once you can fix this, I believe that VSTS will no longer return the error you've reported.

**Comment by SadagopanRajaram** [comment] 2017-11-15 15:00
Can you confirm that the agent you are using for the VSTS release is on the same machine and you are using the Publish Test Results task? the locale difference might be here and not in the UFT runner and Jenkins server.

**Comment by shaileshkumar-atos** [comment] 2017-11-16 06:11
These two are in different machine.
VSTS agent is running online, and the UFT is running on a local VM on which Jenkins is installed.

**Comment by SadagopanRajaram** [comment] 2017-11-16 11:38
I assume the locale settings on the VM is having a decimal format with comma and not dot and the online agent running VSTS is different causing the parsing issue. I am not sure if there is an easy way in the product to address this - can I suggest changing the locale settings on the local VM to a format which has dot in the decimal format and see if the issue is addressed?

**Comment by shaileshkumar-atos** [comment] 2017-11-16 12:13
Thank you for the reply.
Can you please suggest where I should do the changes on the local VM?

**Comment by SadagopanRajaram** [comment] 2017-11-19 09:24
Control Panel->Clock, Language, Region,->Region->Change Date, Time and Number Formats

**Comment by SadagopanRajaram** [comment] 2017-11-23 06:40
@shaileshkumar-atos - I assume this is resolved and I am closing the issue. Please let me know if you run into anything else.

**Closed by SadagopanRajaram** 2017-11-23 06:40 UTC
Labels: Area: Test
