### ISSUE TITLE
"Remove additional files at destination" tries to remove App_Data\jobs but fails

### ISSUE THREAD

**Issue by jamesaarondevlin** [Microsoft/vsts-tasks#4496] opened 2017-06-08 23:43 UTC
Hi guys,

We noticed that after enabling "Remove additional files at destination" that some of our releases failed with the following message (as a pre-caution we do take the app service offline to ensure files are not in use however web jobs, particularly Application Insights Profile, may fall outside of this scope).

```
2017-06-08T22:31:02.0197305Z ##[section]Starting: Deploy the Website
2017-06-08T22:31:02.0207304Z ==============================================================================
2017-06-08T22:31:02.0207304Z Task         : Azure App Service Deploy
2017-06-08T22:31:02.0207304Z Description  : Update Azure App Service using Web Deploy / Kudu REST APIs
2017-06-08T22:31:02.0207304Z Version      : 3.3.6
2017-06-08T22:31:02.0207304Z Author       : Microsoft Corporation
2017-06-08T22:31:02.0207304Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2017-06-08T22:31:02.0207304Z ==============================================================================
2017-06-08T22:31:02.5947349Z fa2c3c8c-144d-4a56-ba15-1c9de91ed6e3 exists true
2017-06-08T22:31:05.8314062Z Got connection details for Azure App Service:'gcvp-dev-aus'
2017-06-08T22:31:18.6024049Z ConnectionString attributes in Web.config is parameterized by default. Note that the transformation has no effect on connectionString attributes as the value is overridden during deployment by 'Parameters.xml or 'SetParameters.xml' files. You can disable the auto-parameterization by setting /p:AutoParameterizationWebConfigConnectionStrings=False during MSBuild package generation.
2017-06-08T22:31:19.7484060Z [command]d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.3.6\ctt\ctt.exe s:d:\a\r1\a\temp_web_package_6916328397802707\Content\d_C\a\1\s\Gtwm.UI\GetTheWorldMoving\obj\Debug\Package\PackageTmp\Web.config t:d:\a\r1\a\temp_web_package_6916328397802707\Content\d_C\a\1\s\Gtwm.UI\GetTheWorldMoving\obj\Debug\Package\PackageTmp\Web.Development.config d:d:\a\r1\a\temp_web_package_6916328397802707\Content\d_C\a\1\s\Gtwm.UI\GetTheWorldMoving\obj\Debug\Package\PackageTmp\Web.config pw
2017-06-08T22:31:19.9824062Z [command]d:\a\_tasks\AzureRmWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\3.3.6\ctt\ctt.exe s:d:\a\r1\a\temp_web_package_6916328397802707\Content\d_C\a\1\s\Gtwm.UI\GetTheWorldMoving\obj\Debug\Package\PackageTmp\bin\Web.config t:d:\a\r1\a\temp_web_package_6916328397802707\Content\d_C\a\1\s\Gtwm.UI\GetTheWorldMoving\obj\Debug\Package\PackageTmp\bin\Web.Development.config d:d:\a\r1\a\temp_web_package_6916328397802707\Content\d_C\a\1\s\Gtwm.UI\GetTheWorldMoving\obj\Debug\Package\PackageTmp\bin\Web.config pw
2017-06-08T22:31:20.1924058Z XML Transformations applied successfully
2017-06-08T22:31:45.1784063Z [command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='d:\a\r1\a\temp_web_package_3243713071943448.zip' -dest:auto,ComputerName='https://gcvp-dev-aus.scm.azurewebsites.net:443/msdeploy.axd?site=gcvp-dev-aus',UserName='********',Password='********',AuthType='Basic' -setParam:name='IIS Web Application Name',value='gcvp-dev-aus' -userAgent:VSTS_ec22fe19-8121-4cb0-b90f-54a3dcbb6beb_release_7_177_351_1
2017-06-08T22:31:45.9494061Z Info: Using ID '58006f4b-864a-44c0-8ec4-df22b0329e87' for connections to the remote server.
2017-06-08T22:31:52.2212691Z Info: Deleting file (gcvp-dev-aus\App_Data\jobs\continuous\ApplicationInsightsProfiler\ApplicationInsightsProfiler.exe).
2017-06-08T22:31:52.2222688Z Info: Deleting file (gcvp-dev-aus\App_Data\jobs\continuous\ApplicationInsightsProfiler\ApplicationInsightsProfiler.exe.config).
2017-06-08T22:31:52.2222688Z Info: Deleting directory (gcvp-dev-aus\App_Data\jobs\continuous\ApplicationInsightsProfiler).
2017-06-08T22:31:52.2222688Z Info: Deleting directory (gcvp-dev-aus\App_Data\jobs\continuous).
2017-06-08T22:31:52.2222688Z Info: Deleting directory (gcvp-dev-aus\App_Data\jobs).
2017-06-08T22:31:52.4342685Z ##[error]Failed to deploy web package to App Service.
2017-06-08T22:31:52.4352691Z ##[error]Error: (6/8/2017 10:31:52 PM) An error occurred when the request was processed on the remote computer.
Error: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\App_Data\jobs'.
Error: The error code was 0x80070091.
Error: The directory is not empty.

   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.DirectoryEx.Delete(String path)
   at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)
Error count: 1.

2017-06-08T22:31:52.4352691Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
2017-06-08T22:31:52.9850754Z Successfully updated deployment History at https://gcvp-dev-aus.scm.azurewebsites.net/deployments/1771496961112422
2017-06-08T22:31:53.0370736Z ##[section]Finishing: Deploy the Website
```

By either manually removing the App_Data\jobs folder in the SCM site or disabling "Remove additional files at destination" we were able to successfully release. But ideally, we'd like to be able to both remove files we deleted in a prior commit and keep our web jobs running.

Is there something I am missing or is this a conflict between the way App Insights deploys the profiling tool and the way the Azure App Service Deploy tasks deletes files?

**Comment by vincentdass** [comment] 2017-06-12 08:05
@jamesaarondevlin , can you please try the [approach 1 ](https://github.com/Microsoft/vsts-tasks/issues/4143#issuecomment-304197479) and check if the issue still happening?

**Comment by mateuszmcz** [comment] 2017-06-14 08:20
Hi,
I've the same issue:
`Error: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\App_Data\jobs'.
Error: The error code was 0x80070091.
Error: The directory is not empty.`

Tried [approach 1](https://github.com/Microsoft/vsts-tasks/issues/4143#issuecomment-304197479) but issue still occurs.

**Comment by seanfuture** [comment] 2017-06-14 12:12
We use [approach 1](https://github.com/Microsoft/vsts-tasks/issues/4143#issuecomment-304197479) to deploy ( swapping the slots via Invoke-AzureRmResourceAction -Action slotsswap ) but the "continuous" folder is present preventing the deletion of the jobs folder.  This error occurs before the swap can occur:

```
"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath="F:\Jenkins\Workspaces\iiQ - Development\Spark.Web\Deploy" -dest:contentPath=iiq-dev-web-deploy-01,ComputerName='https://iiq-dev-web-deploy-01.scm.azurewebsites.net/msdeploy.axd',UserName='$iiq-dev-web__deploy-01',Password='******************************************',IncludeAcls='False',AuthType='Basic' -enablerule:AppOffline -allowUntrusted
  Info: Using ID 'a03c9751-c707-40fd-a8e3-5d4f9460f9b6' for connections to the remote server.
  Info: Deleting file (iiq-dev-web-deploy-01\App_Data\jobs\continuous\ApplicationInsightsProfiler2\ApplicationInsightsProfiler.exe).
  Info: Deleting file (iiq-dev-web-deploy-01\App_Data\jobs\continuous\ApplicationInsightsProfiler2\ApplicationInsightsProfiler.exe.config).
  Info: Deleting directory (iiq-dev-web-deploy-01\App_Data\jobs\continuous\ApplicationInsightsProfiler2).
  Info: Deleting directory (iiq-dev-web-deploy-01\App_Data\jobs\continuous).
  Info: Deleting directory (iiq-dev-web-deploy-01\App_Data\jobs).
EXEC : error : (6/14/2017 7:26:10 AM) An error occurred when the request was processed on the remote computer. [F:\Jenkins\Workspaces\iiQ - Development\Spark.Deployment\SparkWeb.msbuild]
EXEC : error : An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\App_Data\jobs'. [F:\Jenkins\Workspaces\iiQ - Development\Spark.Deployment\SparkWeb.msbuild]
```

For now we're forced to FTP into the deployment slot and manually delete the "jobs" directory.

Seems that the profiler job is still running or was running at one time when the deployment begins, so it's blocking the deployment ( even on the inactive staging slot ).  Either MSDEPLOY can't handle deleting the folder when Application Insights is or has been running or it needs to communicate w/ Application Insights to get this task done.  

Regardless of whether or not a staging slot is used, developers will still wish to deploy to a target w/ Application Insights having been configured on it.  Once this issue is resolved, they'll be able to.

**Comment by vincentdass** [comment] 2017-06-18 10:31
Hi,
Thanks for trying out the workaround.
Can you please share the same logs to RM_Customer_Queries@Microsoft.com and this issue [Link ](
https://github.com/Microsoft/vsts-tasks/issues/4496)as Subject ?
So, we can take this thread offline ans unblock you soon. :)

**Comment by seanfuture** [comment] 2017-06-18 17:44
We would all prefer it if you would address the issue here on GitHub openly .. If you have any questions for us feel free to ask.

**Comment by vincentdass** [comment] 2017-06-18 18:34
@seanfuture , thanks for the response.
Looks like stopping the App Service has no significance over Webjobs. They need to be stopped separately. But, WebJobs including ApplicationInsights (extension) are copied to temporary location and executed from the same folder. So, this error is likely to happen due to other reasons. 
Currently, I am unable to repro this issue and it requires some further investigation. Inorder to stop the webjob, Can you please change your RD to below format ? If it doesn't work, We can take this thread forward with Azure team.

![image](https://user-images.githubusercontent.com/20121508/27263221-a1704d36-5482-11e7-89d1-4c3822452467.png)

Order of Release Definition as follows:
* Stop WebJob - Azure PowerShell Task (With below PS Script # 1)
* Stop Azure App Service - Azure App Service Manage Task
* Deploy Azure App Service - Azure App Service Deploy task
* Start Azure App Service - Azure App Service Manage Task
* Start Webjob - Azure PowerShell Task (with below PS Script # 2)
* Swap Slot (Optional) - Azure App Service Manage Task

PS Script # 1:
```
$webApp = Get-AzureRmWebAppSlot -ResourceGroupName "<RGName>" -Name "<WebAppname>" -Slot production
$appSettingList = $webApp.SiteConfig.AppSettings
$hash = @{}
ForEach ($kvp in $appSettingList) {
    $hash[$kvp.Name] = $kvp.Value
}
$hash['WEBJOBS_STOPPED'] = "1"
Set-AzureRMWebAppSlot -ResourceGroupName "<RGName>" -Name "<WebAppName>" -AppSettings $hash -Slot production
Write-Host "Set Value"
Start-Sleep -s 15

```

PS Script # 2:

```
$webApp = Get-AzureRmWebAppSlot -ResourceGroupName "<RGName>" -Name "<WebAppName>" -Slot production
$appSettingList = $webApp.SiteConfig.AppSettings
$hash = @{}
ForEach ($kvp in $appSettingList) {
    $hash[$kvp.Name] = $kvp.Value
}
$hash['WEBJOBS_STOPPED'] = "0"
Set-AzureRMWebAppSlot -ResourceGroupName "<RGName>" -Name "<WebAppName>" -AppSettings $hash -Slot production
```

Please do change the RGName and WebAppName in above scripts appropriately.

**Comment by seanfuture** [comment] 2017-06-19 14:01
Thanks @vincentdass, we recently FTP'ed into the deployment slot and manually deleted the folder "Microsoft.ApplicationInsights.AzureWebSites" under "/SiteExtensions" and the issue has, so far, gone away for us.  We're monitoring to see if the issue presents itself again.  For ourselves, please give us a few days to see if the issue is resolved simply by eliminating ApplicationInsights.  If that doesn't fix things we can certainly attempt to use your exact scripts above.  

In terms of reproduction, if you setup an Azure App Service with a deployment slot, then deploy a project: 

`"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath="$(RootFolder)\test\Deploy" -dest:contentPath=$(AzureSlotName),ComputerName='https://$(AzureSlotName).scm.azurewebsites.net/msdeploy.axd',UserName='$(AzureSlotUsername)',Password='$(AzureSlotPassword)',IncludeAcls='False',AuthType='Basic' -enablerule:AppOffline -allowUntrusted` 

.. and then issue: `Invoke-AzureRmResourceAction -ResourceGroupName 'test-resources' -ResourceType Microsoft.Web/sites/slots -ResourceName 'test-dev-web/deploy-01' -Action slotsswap -Parameters $ParametersObject -ApiVersion 2015-07-01 -Force` 

.. I would expect you may see the issue ( during the msdeploy and before the swap can be invoked ) as long as Application Insights is enabled and integrated into the Visual Studio solution deployed and if you deploy twice with the App Service being accessed at least once and monitored by Insights between deployments.  The issue *only* started happening for us immediately after Application Insights was turned on / configured and then deployed for the 1st time.

@jamesaarondevlin I noticed you had Application Insights enabled as well - If you completely disable this feature and remove any reference of Application Insights from your solution and deployment slots is the issue fixed for yourself?

**Comment by vincentdass** [comment] 2017-06-19 18:30
@seanfuture , thanks for the response. Please  do revert back, once you are done.

**Comment by jamesaarondevlin** [comment] 2017-06-19 23:15
thanks @vincentdass - after amending our release definition to use approach 1 we have not encountered this problem since. I suspect though if we ever enabled app insights profile on staging we'd have the same problem, but that's conjecture without actually trying it. In reality, we should be using slots and should not need to use the profile on our staging slot.

**Comment by vincentdass** [comment] 2017-06-27 12:20
@seanfuture , @jamesaarondevlin , Closing the thread, as the issue is resolved. Feel free to re-open the thread or start a new one, if the [workaround proposed](https://github.com/Microsoft/vsts-tasks/issues/4496#issuecomment-309294640) didnt resolve the issue.

**Closed by vincentdass** 2017-06-27 12:20 UTC
Labels: Area: Release, AzureAppService

**Comment by euhm** [comment] 2017-07-24 15:59
I have the same issue, but using the suggested [approach 1](https://github.com/Microsoft/vsts-tasks/issues/4143#issuecomment-304197479) is not possible as I deploy through AMR templates (MS Deploy task)

Will the ARM MS Deploy task be updated with this approach?

**Comment by northtyphoon** [comment] 2017-09-06 15:51
You can add the following MSDeploy arguments to avoid deleting ApplicationInsightsProfiler web job

`-skip:skipaction='Delete',objectname='filePath',absolutepath='\\App_Data\\jobs\\continuous\\ApplicationInsightsProfiler2\\.*' 
-skip:skipaction='Delete',objectname='dirPath',absolutepath='\\App_Data\\jobs\\continuous\\ApplicationInsightsProfiler2\\.*'
`

In VSTS CI/CD, you can add the above arguments in task "Deploy Azure App Service -> Additional Deployment Options -> Additional arguments" when you choose "Publish using Web Deploy".

**Comment by euhm** [comment] 2017-09-29 07:40
@northtyphoon any idea if arguments (!= parameters) can be used in msdeploy arm extension?

**Comment by akuryan** [comment] 2017-12-26 08:47
We still see this issue, while using [approach 1](https://github.com/Microsoft/vsts-tasks/issues/4143#issuecomment-304197479) - deployment is made via ARM template.
Interesting thing is - we are using triggered web job, running on schedule. After deployment fails - ```App_data/jobs``` folder is empty. Next deployment will work OK.
Here is a log:
```
2017-12-26T08:32:58.1987367Z ##[error]8:32:57 AM - Resource Microsoft.Web/sites/slots/extensions 'webAppName/single-staging/MSDeploy' failed with message '{
  "status": "failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'failed'.",
    "details": [
      {
        "code": "Failed",
        "message": "Package deployment failed\r\nAppGallery Deploy Failed: 'Microsoft.Web.Deployment.DeploymentClientServerException: An error was encountered when processing operation 'Delete Directory' on 'D:\\home\\site\\wwwroot\\App_Data\\jobs'. ---&gt; Microsoft.Web.Deployment.DeploymentException: The error code was 0x80070091. ---&gt; System.IO.IOException: The directory is not empty.\r\n\r\n   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)\r\n   at Microsoft.Web.Deployment.DirectoryEx.Delete(String path)\r\n   at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)\r\n   --- End of inner exception stack trace ---\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.Web.Deployment.FilePathProviderBase.HandleKnownRetryableExceptions(DeploymentBaseContext baseContext, Int32[] errorsToIgnore, Exception e, String path, String operation)\r\n   at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)\r\n   at Microsoft.Web.Deployment.DeploymentObject.DeleteOperation(DeploymentSyncContext syncContext)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleDelete(DeploymentObject destObject, DeploymentObject sourceParentObject)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)\r\n   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)\r\n   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)\r\n   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)\r\n   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete)\r\n   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()'"
      }
    ]
  }
}'
2017-12-26T08:33:02.7023706Z ##[error]8:33:02 AM - Package deployment failed
AppGallery Deploy Failed: 'Microsoft.Web.Deployment.DeploymentClientServerException: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\App_Data\jobs'. ---&gt; Microsoft.Web.Deployment.DeploymentException: The error code was 0x80070091. ---&gt; System.IO.IOException: The directory is not empty.

   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.DirectoryEx.Delete(String path)
   at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Microsoft.Web.Deployment.FilePathProviderBase.HandleKnownRetryableExceptions(DeploymentBaseContext baseContext, Int32[] errorsToIgnore, Exception e, String path, String operation)
   at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)
   at Microsoft.Web.Deployment.DeploymentObject.DeleteOperation(DeploymentSyncContext syncContext)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleDelete(DeploymentObject destObject, DeploymentObject sourceParentObject)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncDirPathChildren(DeploymentObject destRoot, DeploymentObject sourceRoot)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentObject.SyncTo(DeploymentProviderOptions providerOptions, DeploymentBaseOptions baseOptions, DeploymentSyncOptions syncOptions)
   at Microsoft.Web.Deployment.WebApi.AppGalleryPackage.Deploy(String deploymentSite, String siteSlotId, Boolean doNotDelete)
   at Microsoft.Web.Deployment.WebApi.DeploymentController.&lt;DownloadAndDeployPackage&gt;d__17.MoveNext()'
```

**Comment by ggirard07** [comment] 2018-01-18 20:15
Same issue here.
```
2018-01-18T19:54:39.5528021Z ##[error]Failed to deploy web package to App Service.
2018-01-18T19:54:39.5532618Z ##[error]Error: (1/18/2018 7:54:39 PM) An error occurred when the request was processed on the remote computer.
Error: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\app_data\jobs'.
Error: The error code was 0x80070091.
Error: The directory is not empty.

   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.DirectoryEx.Delete(String path)
   at Microsoft.Web.Deployment.DirPathProviderBase.Delete(Boolean whatIf)
Error count: 1.

2018-01-18T19:54:39.5538147Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
```

`WEBJOBS_STOPPED` with value `1` is defined at web app level for staging slot with `Slot Setting` checked to make it sticky.
After error occurs, there seemed to be no file on the remote folder (checked from kudu).
We use 3 different webjobs:

- 2 are console app built upon webjob SDK with queue triggers.
- 1 is console app not using webjob SDK and is cheduled by using a simple `settings.job` json file.

**Comment by ggirard07** [comment] 2018-01-22 14:41
@vincentdass commented on a similar issue at #4143.
According to [this comment](https://github.com/Microsoft/vsts-tasks/issues/4143#issuecomment-359350694), `WEBJOBS_STOPPED` set to `1` should have solved the issue...
Looks like issue is still not completely resolved!

**Comment by vincentdass** [comment] 2018-01-22 15:01
@ggirard07 , is this issue occurring consistently or intermittently?
Setting the WEBJOBS_STOPPED to 1 takes some time to take effect on SCM side.
Can you try stopping the webjobs using manage task?

**Comment by ggirard07** [comment] 2018-01-22 15:10
`WEBJOBS_STOPPED` is set to `1` on the staging slot we use to deploy our website updates. This app settings is always there (sticky on staging slot) and we never remove it so I don't expect it to take some time to take effect.

**Comment by vincentdass** [comment] 2018-01-22 15:15
@ggirard07 , Can you share the latest release log, where it failed? To share the logs in private, send to `RM_CUSTOMER_QUERIES@MICROSOFT.COM`.

Also, make sure that the SCM site is not open in portal during deployment. This locks the current folder from deleting during deployment.

**Comment by DirkBoer** [comment] 2018-01-22 22:46
I'm having the same problem. I wrote up a StackOverflow question here:

https://stackoverflow.com/questions/48330962/azure-web-deployment-task-failed-an-error-was-encountered-when-processing-ope

**Comment by ggirard07** [comment] 2018-01-23 17:10
@vincentdass I don't have it reproduced with the `system.debug` property. I will post it as soon as I get one.

**Comment by mattomwit** [comment] 2019-12-16 13:12
Hi I found this post while having issues with similar problem. This link might help: https://forums.iis.net/t/1192163.aspx

Just in case the site gets deleted I will repaste the most useful information from that site: 

it was made by user **silverbyte**
```

> 
> 
> I found it.
> 
> I hope this helps others as well.
> 
> There's no bug in msdeploy.
> 
> 
> It does use regular expression against the destination object's absolute path. The regular expression is exactly like you give it, no mistique in that.
> 
> When deploying to my site, the absolute path is exactly how it appears in the output: MySite\\MobileForms\\Data\\MySite\MobileForms\Data\bd13954b-0cb3-41d8-ab8a-eb988ddb8ad1.xml
> 
> I found this by creating a custom deployment rule and with debugger attached, I saw how the regular expressions are kept in the defined skip rules.
> 
> The way skip rules are applied is based on the order of the synchronization operation(delete, update, add) is done on the actual object(directory or file).
> 
> For example, if there's a delete operation on the directory, the skip rules for files within the directory for the delete operation will NOT PREVENT files from being get DELETED!
> 
> In my case, the directory MySite\MobileForms get deleted entirely. The skip rule I set for the files is useless.
> 
> And for the directory, my mistake is in the regular expression:
> 
> -skip:skipAction='Delete',objectName='dirPath',absolutePath='.*\\MobileForms\\.*'
> 
> Should be:
> 
> -skip:skipAction='Delete',objectName='dirPath',absolutePath='.*\\MobileForms$'
> 
> which says that it should skip deleting directory path MobileForms(the first rule erroneously included slash in the regular expression).
> 
> In order to setup the skip rules correctly, it's important to have in mind the possible actions on the directories first.
> 
> Someone should update the documentation in MSDN for the -skip parameter to demystify the way skipAction works.
> 
> If you find more scenarios which might help in a clearer understanding of how the skip rules are applied, please reply so we all benefit from it.
> 

```
