### ISSUE TITLE
How to package and deploy to azure using Gulp

### ISSUE THREAD

**Issue by jkamstra** [Microsoft/vsts-tasks#468] opened 2015-08-28 20:31 UTC
We have an SPA web app running on Aurelia that is using npm, jspm and gulp during build. 

The good news is we can successfully build everything now on a v.Next hosted build controller. Very cool!

The bad news is we haven't figured out a way to get the /dist and the /jspm_packages folders packed up and copied to our Azure VM running the web project (we have two other web and two cloud projects for a total of five in one solution). 

There are a handful of threads on various workarounds to get this to work, some involve custom targets in the web .csproj to get around pipeline staging issues in msbuild, some involve creating custom cspack powershell scripts, a few links involve copying content into storage blobs and then restoring on the VM.

In the end we want to perform the following tasks on a hosted build agent:

1.) npm install - load the package.json dependencies
2.) npm install jspm - load the jspm dependencies
3.) npm install gulp - load gulp into the web project
4.) build the solution
5.) run gulp build task
6.) package all the projects with gulp and jspm output streams and deploy them to azure

Steps 1-5 work great. Step 6 has us scratching our heads and burnt far too many engineering hours and build minutes trying to figure out as each round trip is about 12-20 minutes.

Is there an easy way to accomplish step 6 either now or in the near future? Has anyone accomplished this goal on a hosted build agent using the publically available build task library?

**Comment by bryanmacfarlane** [comment] 2015-09-01 00:52
I don't think we have anything out of box to do #6 yet with the exception of running another build target.  We don't have a specific jspm task - just gulp.  Question - how do your devs deploy to azure now? (asking because CI should do the same).  I'm trying to figure if this is a build/CI question or if it's a how do I deploy my jspm package to azure question ...

**Comment by jkamstra** [comment] 2015-09-01 02:45
We have a couple hacks currently that are less than optimal. 

Going old school, we run a local build, perform a deploy for the bulk of the content, then manually zip the gulp output folder (./dist) and the jspm output folder (./jspm_packages) and do a simple copy to the web VM, expand in sitesroot - all good sans a CI/CD strategy. 

We can also add the following to the web project .csproj

    <Content Include="dist\**\*.*" />
    <Content Include="jspm_packages\**\*.*" />

This works, but it is dangerous as VS will enumerate these directories and explode our .csproj if someone clicks on either folder in the IDE (both folders are ~2,700 files @ 17.2MB)

We've talked about trying to see if we can redirect gulp and jspm to output to the ./staging directory as getting into the proper stage of msbuild for inclusion in cspack is not without it's challenges.

Allow me to ask the question differently. Given gulp is dynamic, and follows typescript in build pipeline, what is the recommended method of gathering and deploying gulp output on a hosted build agent?

**Comment by bryanmacfarlane** [comment] 2015-09-01 03:07
You don't "deploy gulp".  Gulp is a javascript task based build system and we run it.  Whatever you code in gulp, we will run on the hosted VM.

**Comment by jkamstra** [comment] 2015-09-01 03:26
I didn't say I wanted to "deploy gulp". 

I want to deploy the output of a javascript task based build system (gulp, grunt, bower) that will generate content dynamically (not included in SCC) and I don't want to use NuGet or msbuild for this content. Nor do I want to copy it into my dev storage and deploy it on app launch (hack).

Given your response, are you saying adding dynamic content for inclusion into cspack is a VS issue and we should raise to Hanselman and ScottGu or whoever is publically saying VS 2015 is gulp, grunt and bower friendly?

**Comment by bryanmacfarlane** [comment] 2015-09-01 03:43
No, what I'm saying is this task repo and the gulp task tracks issues in running gulp as part of the build (that's what this task does).  This repo does not track issues on everything you can do with gulp (deploy etc...).  The fact that 1 - 5 worked means the CI system is running gulp.  

What issue/bug are you having with the CI system running your gulpfile with gulp?

**Comment by jkamstra** [comment] 2015-09-01 03:57
Right, CI works fine. Thanks for that. npm and gulp work great, now I just want to use it. 

My issue in your taxonomy is CD, how do I get all of this cool new content gulp and jspm are spewing into my build stream packaged and deployed so I can realize the true nirvana - a hosted CI/CD build agent running against our awesome VSO git based repo.

**Comment by jkamstra** [comment] 2015-09-01 04:09
Feel free to tag this as a question - "if a gulp task succeeds on a hosted VSO build agent and no one is around to hear it, does it make a sound?"

**Comment by chrisrpatterson** [comment] 2015-09-01 12:12
@jkamstra How are you accomplishing this from the command line regardless of CI?  In the end that is the real question.  If you can do that CI can automate that happening on check-in.

**Comment by jkamstra** [comment] 2015-09-01 13:30
@chrisrpatterson See above (about 6 posts) for how we are doing this at the moment. 

My sense is there are two options. 

Option 1. While VS now supports these .js build tools, there is not an obvious mechanism to get these output streams included in cspack as it is 'external' to VS. This is probably a question for someone on the VS team to answer as there are multiple ways being blogged on the interweb, but it would be nice to hear how they think we should accomplish.

Option 2: I believe there is an Azure Copy Files task somewhere on the list - at least I have seen it mentioned in various ALM blog posts. If we can point at a folder on the hosted build agent and recursively grab the content then copy it over to the VM, that would work. The catch in our scenario is we have 5 services - 3 web projects and two cloud projects (Orleans based) riding in one solution so finding the right VM may be a challenge.

Can you own this or should I? Albeit my escalation routes are primarily PSS based.

**Comment by chrisrpatterson** [comment] 2015-09-01 17:38
@jkamstra I don't think the AzureCopy is the right thing to do here, it makes your deployment too tied to the CI system.  The right thing is to make sure your content is appropriately packaged with your website.  I really think this is a good question for @madskristensen

**Comment by madskristensen** [comment] 2015-09-01 17:47
I believe you have to add the folders to your project as you mentioned. However, due to the issues of thousands of files in those folders, you may want to just include them in your project before you deploy. So perhaps a custom MSBuild target is required. I don't think you need to do anything but to add some XML to the project file that you can make conditionally trigger on CI builds for instance. @sayedihashimi might know?

**Comment by bryanmacfarlane** [comment] 2015-09-01 18:26
@madskristensen - I think he's using gulp as his build engine

**Comment by madskristensen** [comment] 2015-09-01 18:28
@bryanmacfarlane Yes, but there is still a .csproj, .jsproj or .xproj project file, right?

**Comment by chrisrpatterson** [comment] 2015-09-02 19:38
@madskristensen Yes there likely is.  However, I think the case here is we have integrated a bunch of other tool chains in VS but they don't really integrate into the packaging and deployment parts of the pipeline.  @jkamstra simply used the tools that he got as part of VS, added some packages and now the files are not deployed.  Having to go and crack the MSBuild file to resolve that does not seem like a great answer.

**Comment by bryanmacfarlane** [comment] 2015-09-02 19:52
@chrisrpatterson - agreed.

Since we're putting the customer on a gulp build path, the gulp model is to have tasks (with dependencies) and build is a task.  publish is a task, so the user just runs gulp, gulp build, gulp publish.  

For example, look it this repo we're having this discussion in.  You run gulp to build and validate the tasks.  Then you run gulp publish to publish the tasks.

It's odd to have them switch build systems for different commands.

**Comment by adriaanthomas** [comment] 2015-09-09 08:32
FWIW we package our front-end app in Gulp into a zip file, which appears to be accepted by the _Azure Web Deployment_ task as a _Web Deploy Package_. It is just a zip of the static site with a `web.config` in the root. I'm not sure if this is supposed to work, but it turns out it does (in our situation, the front-end engineers don't use Visual Studio).

Our deployments only happen from the build pipeline, never from an engineer's workstation, so we wouldn't really need a Gulp task to deploy.

**Comment by jkamstra** [comment] 2015-09-09 14:30
Interesting. Thanks @adriaanthomas . 

While our web project is not static and we have four other projects in the overall solution, we could try putting our primary web project into a separate stand alone solution and see if we can get Gulp to do the packaging. 

We also discussed piping the gulp output into the appropriate ./staging directories to see if cspack would just take it all.

In our case given our use of SignalR wired to eventhubs for certain web functionality, we need cspack to massage our web.config.

Boy, it sure would be great if someone from the VS team would describe the 'supported' mechanism for getting dynamic web content packaged and published.

**Comment by sayedihashimi** [comment] 2015-09-09 19:06
I have a blog post at http://sedodream.com/2010/05/01/WebDeploymentToolMSDeployBuildPackageIncludingExtraFilesOrExcludingSpecificFiles.aspx which describes how to add extra files for publishing. I've never tried this with cspack but I think it should work as long as the targets are executed before the cspack target.

**Comment by ghostinside** [comment] 2015-09-21 12:56
Could you please share the you have the gulp build done? if i try to do that on hosted controller - it shows me error that the local gulp not found, if on my own controller, it shows me the message that  

No agent found in pool 1 which satisfies the specified demands:
npm
npm
gulp
Agent.Version -gtVersion 1.86.0

i have npm installed and can run it from command line, the build flow is 
npm install gulp -g
npm install
gulp

appreciate for help

**Comment by jkamstra** [comment] 2015-09-23 22:10
Thanks @sayedihashimi for the link. 

I believe you nailed the problem in there are slight nuances between how packaging happens for an ASP.NET Web Applications and an Azure Cloud Services.

Again we have an Azure Cloud Service project which holds three ASP.NET Web applications (web roles) and two Azure worker role projects.

The solution you linked above seems to work fine if I edit the ASP.NET Web Application .csproj file in my solution and then click 'Publish to Microsoft Azure ...' but the same targets don't trigger if I click on the Azure Cloud Service project and choose 'Package ...' or 'Publish ...' (cspack??)

Do you happen to have a blog entry or a chapter in a book which describes the differences in these publishing mechanisms?

**Comment by sayedihashimi** [comment] 2015-09-23 22:33
>The solution you linked above seems to work fine if I edit the ASP.NET Web Application .csproj file in my solution and then click 'Publish to Microsoft Azure ...' but the same targets don't trigger if I click on the Azure Cloud Service project and choose 'Package ...' or 'Publish ...' (cspack??)

OK, in that case it's a bug in the Cloud Service Project system. The publish process from those projects should invoke the publish for a web project in a consistent way. Have you tried to reach out to the team? If not if you email me details of what you tried, and what works/doesn't work I will can add some people who may be able to help. My email is sayedha@microsoft.com.

>Do you happen to have a blog entry or a chapter in a book which describes the differences in these publishing mechanisms?

Sorry I don't. I haven't delved deeply into the cloud service support. But in general if you extend the publish process correctly it should ideally be honored by the cloud service project.

One question, when you customized the publish process, did you place the customizations into the project file (i.e. `.csproj` file) or into a publish profile (i.e. `.pubxml` file)? If you placed them into a `.pubxml` file than that may explain why it's not getting invoked. Try moving the customizations to the project file (above the import for the web .targets file).

**Comment by jkamstra** [comment] 2015-09-24 03:36
I put the following section into the ASP.NET Web application `.csproj` file immediately ahead of the `Import ... WebApplications\Microsoft.WebApplication.targets ... `  declaration. 
```
  <PropertyGroup>
    <CopyAllFilesToSingleFolderForMsdeployDependsOn>
      $(CopyAllFilesToSingleFolderForMsdeployDependsOn);
      CollectGulpOutput;
      </CopyAllFilesToSingleFolderForMsdeployDependsOn>
  </PropertyGroup>
  <Target Name="CollectGulpOutput">
    <ItemGroup>
      <_CustomFiles Include="dist\**\*" />
      <FilesForPackagingFromProject Include="%(_CustomFiles.Identity)">
        <DestinationRelativePath>dist\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
    <ItemGroup>
      <_CustomFiles Include="jspm_packages\**\*" />
      <FilesForPackagingFromProject Include="%(_CustomFiles.Identity)">
        <DestinationRelativePath>jspm_packages\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
    <Message Text="CollectGulpOutput list: %(_CustomFiles.Identity)" />
  </Target>
 ```
In further testing, this is what I learned. If I right click on the web application project in the solution and select the "Publish ..." menu item, the dialog appears and it picks up my additional files. Nice, but I'd really like to use a webrole for a handful of reasons.

Sadly, if I select the "Publish to Microsoft Azure ..." menu option on the web application project node or select "Package ..." or "Publish ..." on the cloud service project node it doesn't collect the files. All I get is the following in a detailed build log .
```
4>CopyAllFilesToSingleFolderForMsdeployDependsOn = 
4>      ;
4>      
4>      ;
4>      CollectGulpOutput;
4>      ;
4>    
4>CopyAllFilesToSingleFolderForPackageDependsOn = 
4>      ;
4>      ;
```
Perhaps I am using the wrong xml token? Let me know if you want a repo. Should be pretty easy to create.

**Comment by johnkattenhorn** [comment] 2015-09-26 12:56
We so struggling with exactly the same issue as this; I feel much better that we are not alone in this. We are using Octopus Deploy to do our deployment so are pipeline steps go build --> cspack --> nuget --> octopus. 

Octopus unpacks the cspack file performs some transforms and then re-packages and deploys the cloud service.

I'll be sure to feed back how I get on.

**Comment by johnkattenhorn** [comment] 2015-09-26 16:15
I've got the VSO pipeline doing the npm / gulp / bower steps but I get exactly the same as @jkamstra, it skips the files when using a web role.

**Comment by sayedihashimi** [comment] 2015-09-26 17:54
Maybe @paulyuk can help here?

**Comment by johnkattenhorn** [comment] 2015-09-26 18:07
Here is my current plan of attack; I'm current trying to import a new project file into the existing .ccproj file so I can experiment with seeing if I could use a AfterBuild target or similar to bring the gulp output over from the webrole to the bin or obj directory.

I got the concept from this article:

http://stackoverflow.com/questions/1292351/including-content-files-in-csproj-that-are-outside-the-project-cone

**Comment by johnkattenhorn** [comment] 2015-09-26 19:06
Based on this article this look promising too

http://blogs.msdn.com/b/philliphoff/archive/2012/07/05/dynamically-add-content-to-windows-azure-application-roles.aspx

My current included .csproj file looks like this 
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target Name="BeforeAddRoleContent">
    <ItemGroup>
      <AzureRoleContent Include="..\GP.Impact.Web\App\**">
        <RoleName>GP.Impact.Web</RoleName>
        <Destination>App</Destination>
      </AzureRoleContent>
    </ItemGroup>
  </Target>
</Project>

Still doesn't seem to work though, I see it copy the files into the csx directory but not under APPROOT/App where I need it.

There doesn't seem to be any documentation around either for the Azure.Targets file.

**Comment by johnkattenhorn** [comment] 2015-09-26 20:40
OK, in my case I've resolved this issue, I can now deploy additional files from my gulp tasks using this 

```xml
  <Import Project="$(CloudExtensionsDir)Microsoft.WindowsAzure.targets" />
  <Target Name="BeforeAddRoleContent">
    <ItemGroup>
      <AzureRoleContent Include="..\GP.Impact.Web\App">
        <RoleName>GP.Impact.Web</RoleName>
        <Destination>App</Destination>
      </AzureRoleContent>
    </ItemGroup>
  </Target>
```
I found that I need to put this directly into the ccproj file and not into a separate profile file as this seemed to be the reason that it got the path wrong before.

**Comment by johnkattenhorn** [comment] 2015-09-27 06:31
So I discovered that I still have an issue, despite the files not being present in the web role the IIS configuration is not. If I remote control an web role instance and take a look in IIS sure enough the added directory structure is missing, I've tried various combinations of trying to add empty directories into either the deployment project or the web app project itself but so far nothing has worked.

**Comment by johnkattenhorn** [comment] 2015-09-27 07:48
So this still doesn't work completely. The files indeed do get copied into the approot but they do not appear in the siteroot.

Back to the drawing board.

**Comment by ghostinside** [comment] 2015-09-28 04:47
I use gulp to copy all necessary files and folders to the dist folder and
then gulp-zip to create a package for deployment, for new it works as
expected

Thx Alex
27 сент. 2015 г. 10:48 пользователь "John Kattenhorn" <
notifications@github.com> написал:

**Comment by johnkattenhorn** [comment] 2015-09-29 16:31
It's bad I know but I couldn't find a better way than to put in a startup task in the cloud service and copy the missing files from approot to siteroot. It's working now though both locally and deployed using VSO and Octopus.

**Comment by jkamstra** [comment] 2015-09-29 19:42
@sayedihashimi has this issue been sent over to the team which owns Azure packaging in VS land or should I create a repo?

**Comment by chrisrpatterson** [comment] 2015-09-29 19:43
I pointed them at the issue, they don’t have any comments yet.

**Comment by jkamstra** [comment] 2015-09-29 19:44
@ghostinside thanks for the tip. A couple questions, are you using hosted build servers? Once you do a gulp-zip how do you move the archive to the proper azure VM running the webrole?

**Comment by jkamstra** [comment] 2015-09-29 19:45
thanks @chrisrpatterson, much appreciated!

**Comment by ghostinside** [comment] 2015-09-29 20:13
no, we use our own separate server, we use web application, not role, so it
is pretty simple to deploy package to azure by azure web app deployment task

Thx Alex

2015-09-29 22:44 GMT+03:00 Jeff Kamstra <notifications@github.com>:

**Comment by jkamstra** [comment] 2015-10-16 15:28
Kicking the can. Any update on this topic? Is there somewhere else I should go to monitor progress?

**Comment by johnkattenhorn** [comment] 2015-10-16 15:34
Not from me, the work around start-up task works but is messy. 

Since I've had this issue I'm continually running into issues caused by the deep hierarchy of node_modules structures which get pulled during the build pipeline, anything which scans which happens to run over this structure cause a major headache. 

Not an issue with the Build system or VSO specifically but a major cause of friction of using some of these really good development tools with the Windows stack.

**Comment by janus007** [comment] 2015-11-09 18:45
@jkamstra , if I understand you correct you wish to utilize gulp before deploy, for instance transpiling ecma to js, and then only deploy the transpiled js?

**Comment by jkamstra** [comment] 2015-11-23 16:02
@janus007, Correct.

**Comment by kmkumaran** [comment] 2016-01-08 12:30
Marking this thread closed.

**Comment by marvc1** [comment] 2016-05-07 15:25
This issue hasn't been resolved has it?

I have the same problem. All I want is a method to put the output of a gulp task into the deployed wwwroot of an Azure website. With ProjectKudu you'd 'KuduSync' (copy) the files across in the depoly.cmd. With Team Services, there doesn't look to be away to achieve this.

**Comment by JasonTheProgrammer** [comment] 2016-06-17 01:58
So, this issue was closed without explanation by @kmkumaran ? It seems like still, the only realistic solution is like @chrisrpatterson remarked on 3 Sep 2015:

> Having to go and crack the MSBuild file...

But as he said, and I wholeheartedly agree:

> that does not seem like a great answer.

Until I found this issue I was tearing my hair out feeling like I was alone in this problem. We're all being pushed down the path of grunt, gulp, bower, npm, but the story is incomplete. Are there not yet any better answers than hacking MSBuild? No plans?

**Comment by johnkattenhorn** [comment] 2016-06-17 05:28
@JasonTheProgrammer - Although not officially I think MS have stopped developing anything for CloudServices. After about 6 months we moved our front-end solution to Azure WebApp and connected it to the same Virtual Network that the Worker Roles where in. We just couldn't live with the deployment length of time. This won't help you though if you need the GDI etc.

In newer projects, we are using DotNetCore hosted inside SF, and if I needed full GDI support or something else I'd probably use a virtual machine scale set.

**Comment by JasonTheProgrammer** [comment] 2016-06-17 05:37
@johnkattenhorn It sounds like what you're describing is distinct from my scenario. I have a .NET 4.5 web application project (.csproj) in VS2015 which is being deployed to an Azure WebApp via the "Azure Web App Deployment" task in a Visual Studio Online build. Like @jkamstra , I want to use gulp build tasks to, for example, bundle and minify JavaScript files, and for the output of that build task to be included in the package deployed by "Azure Web App Deployment" task. By default, these outputs are not included, and as discussed above, it seems like MSBuild tinkering is the only way to make it happen.

I don't *think* this has anything to do with CloudServices?

**Comment by johnkattenhorn** [comment] 2016-06-17 05:47
@JasonTheProgrammer Ah my mistake, I guess the root cause is the same though which is if .csproj doesn't know about the files ahead of time then it's difficult. 

In your case what we do is side-step the issue by controlling the delivery using a NuGet package task and then Octopus Deploy to deploy to the Web App and let the nuspec file go grab all the output from the gulp tasks. 

The reason I was in this issue was Cloud Service Packaging made this approach extra hard!

**Comment by spacecat** [comment] 2016-06-22 07:37
I am also interested in knowing how to properly deploy the `dist ` folder generated by the Gulp/Grunt build step using the "Azure Website" template described in following walkthroughs: 

- https://www.visualstudio.com/en-us/docs/build/apps/aspnet/aspnet4-to-azure 
- https://www.visualstudio.com/en-us/docs/build/apps/node/nodejs-to-azure

Also, while writing this post I noticed the following from the second walkthrough for the Gulp build step:

Advanced, Arguments: `--packagePath=$(Build.StagingDirectory)`

What does the argument do? Maybe something similar could be used for the first walkthrough?

**Comment by jmatthewspremierlogic** [comment] 2016-08-18 21:41
I really can't believe there still isn't a way to do this.

**Comment by janus007** [comment] 2016-08-19 09:53
As a .NET programmer I discarded Gulp, I was tired of wasting my life with
tedious work and weird non-working/explaining pipeline-weirdness. I
realized the best way to succeed was to roll my own cigar and lit it with a
simple FileWatcher. Suddenly I can see clearer and guess what, the smoke is
gone even when the cigar is on fire.

**Comment by compulim** [comment] 2016-09-24 09:55
@spacecat We are using Webpack + Gulp on VSTS and deploy to Azure Web App.

We use Gulp to run WebDeploy manually and pack it as a ZIP file. Then the ZIP file can be deployed to Azure Web App using a canned VSTS build task.

There are some parameters you need to set for WebDeploy to pack correctly (e.g. IIS Application Name), you can look at our [repository](https://github.com/candrholdings/webpack-template) for details.

**Comment by bryanmacfarlane** [comment] 2016-09-24 12:59
@compulim - Thanks!

I'm going to re-open this so we can get some step by step docs created.  Even if it's for a sample hello world app.  And even though there's probably dozens of ways to solve this problem, we should document a few (or at least one).

**Comment by chrisrpatterson** [comment] 2016-09-24 14:08
Here is an example of building a website with Gulp and deploying to Azure https://www.visualstudio.com/en-us/docs/build/apps/node/nodejs-to-azure.

**Comment by spacecat** [comment] 2016-09-25 14:02
Reading my old post again I realize I don't mention deploying a .NET app using MSBuild. @chrisrpatterson the link you mentioned is for a Node.js app, what is missing in the docs is how to deploy/include the dist folder in a .NET web app (using MSBuild). Thanks.

**Comment by sujesharukil** [comment] 2016-12-02 03:48
FWIW, I ran in to this issue almost a year ago. What I ended up doing was create a custom targets file, hook in to BeforeTargets="CorePublish" and do my copying there. I call the custom targets file from the cloud project (not the application, but the cloud project). I copy the output of my gulp build inside the scripts directory and the css generated in the Contents directory.

Here is a sample of the target

  <Target Name="CopyBeforeCorePublish" BeforeTargets="CorePublish">
    <PropertyGroup>
      <OutputFolder>$(IntermediateOutputPath)$(MSBuildProjectName)</OutputFolder>
    </PropertyGroup>

    <CreateItem Include="@(ProjectReference -> '%(RootDir)%(Directory)public\scripts\**\*.*')" >
      <Output ItemName="BuildFolder" TaskParameter="Include" />
    </CreateItem>

    <CreateItem Include="@(ProjectReference -> '%(RootDir)%(Directory)public\content\**\*.*')" >
      <Output ItemName="ContentFolder" TaskParameter="Include" />
    </CreateItem>


    <Message Text="Files to copy @(BuildFolder)" Importance="high"/>
    <Copy
      SourceFiles="@(BuildFolder)"
      DestinationFiles="@(BuildFolder -> '$(IntermediateOutputPath)%(Name)\public\scripts\%(RecursiveDir)%(Filename)%(Extension)')"/>

    <Copy
      Condition="'$(TF_BUILD)' == 'true'"
      SourceFiles="@(BuildFolder)"
      DestinationFiles="@(BuildFolder -> '$(OutDir)_PublishedWebsites\%(Name)\public\scripts\%(RecursiveDir)%(Filename)%(Extension)')"/>

    <Message Text="Files to copy @(ContentFolder)" Importance="high"/>
    <Copy
      SourceFiles="@(ContentFolder)"
      DestinationFiles="@(ContentFolder -> '$(IntermediateOutputPath)%(Name)\public\content\%(RecursiveDir)%(Filename)%(Extension)')"/>

    <Copy
      Condition="'$(TF_BUILD)' == 'true'"
      SourceFiles="@(ContentFolder)"
      DestinationFiles="@(ContentFolder -> '$(OutDir)_PublishedWebsites\%(Name)\public\content\%(RecursiveDir)%(Filename)%(Extension)')"/>
  </Target>

Hopefully helps someone. 
Note: This is strictly for Cloud Services. I am actually doing this on a TeamCity build server and using Octopus Deploy to deploy it. Works well.

**Comment by christhreatt** [comment] 2017-05-05 15:04
I believe I have a workable solution if you are only deploying one website to your web role.  For this example, assume that you have an MVC application and you're hosting Angular or some other custom javascript content that is generated by gulp.  The gulp process sends its output to Scripts/client.  The solution looks like this:

`
TestMVCApp
  /Contents
  /Controllers
 ..
  /Scripts
    /client (gulp generated content, not in .csproj)
TestMVCAzure
  /Roles
    /TestWebRole
      /Scripts
        /client
           placeholder.txt
`
Please note that the directory structure below your role directory in the Azure project should match the target destination.  In this case I want my content sent to \approot\Scripts\client.

Modify your Azure .ccproj project file.

`
  <Target Name="BeforeAddRoleContent">
    <ItemGroup>
      <AzureRoleContent Include="..\TestMVCApp\Scripts\client">
        <RoleName>TestWebRole</RoleName>
        <Destination>Scripts\client</Destination>
      </AzureRoleContent>
`
Note the Include path is relative to your .ccproj file.  This path does not contain wildcards or filenames.  It's the path to the top of the directory structure you want to copy.  The destination path is relative to /approot.  At this point if you publish the package for Azure you will end up with:

`
/approot
  <content including the /Scripts/client generated files and directories.>
/sitesroot
  /0
     <content, **excluding** the gulp files>
`

The last step is to edit your .csdef file in the Azure project.

`
<Sites>
  <Site name="TestWebRole" physicalPath="..\..\..\TestMVCApp">
    <Binding ... />
  </Site>
</Sites>
`
When you rename the one site to anything other than "Web" you will need to include the physicalPath attribute.  Note that path is relative to the .\TestMVCAzure\bin\Debug directory, which is why we're stepping up so many levels.  The end result is the following packaged web role:

`
/approot
   <content **including** the gulp files>
`

**Comment by bryanmacfarlane** [comment] 2017-05-31 01:40
As @christhreatt and others have outlined, this is about creating an azure package and deploying it to an azure web role.

**Comment by azooinmyluggage** [comment] 2017-05-31 10:21
**For App Service**
@chrisrpatterson has already provided the link https://www.visualstudio.com/en-us/docs/build/apps/node/nodejs-to-azure.

1. All the App Service Deploy task requires is a package that will be deployed to App service
2. The App Service Deploy task now has the capability to generate the web.config required by Node app (if the app is Nodejs)
3. The task also supports transformation and tokenization so web.config and json files can be manipulated.

**For Cloud Service a build definition will look something like this:**
Add gulp task after NPM if you need gulp tasks to be run
![n](https://cloud.githubusercontent.com/assets/6857119/26627616/b7cc1b50-4618-11e7-8824-4701b0a7d07d.png)

In the release definition just use the Cloud Service Deploy task and consume the artifacts produced by Build.

**Comment by bryanmacfarlane** [comment] 2017-05-31 10:33
Thanks for summarizing.  Closing

**Closed by bryanmacfarlane** 2017-05-31 10:33 UTC
Labels: Area: Release

**Comment by JasonTheProgrammer** [comment] 2017-09-15 00:14
I'm still unclear on what the proposed approach is? The summary by @azooinmyluggage is unclear.

The link refers to an article for packaging output using a gulp task, but that packaging means manually specifying which files and folders are included in the zip.

The strength of the Visual Studio build step is that these flags: `/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true` ensure a single zip that includes all appropriate MSBuild output, so you're not having to manually specify, e.g. inclusion of the `bin` folder. Gulp build outputs though, aren't part of that package because they're not part of the MSBuild process.

Is the proposal that we do away with the MSBuild "Package" approach and go entirely manual with Gulp?

@bryanmacfarlane When you re-opened this issue on 24 Sep 2016 you said:

> I'm going to re-open this so we can get some step by step docs created. Even if it's for a sample hello world app.

But it doesn't look to me like that has happened?

**Comment by Andrew1178** [comment] 2018-03-28 19:43
Any update with this?

**Comment by bryanmacfarlane** [comment] 2018-03-28 21:14
@JasonTheProgrammer - yes, because we realized that at that point we are documenting how to use gulp (to call azure REST apis) or creating an gulp library for automating azure.  From a CI/CD task perspective, if someone creates one of those, you can use it in your gulp script and this task is capable of running that.  There is no issue with the gulp task in this repo - it runs your gulp script.

**Comment by JasonTheProgrammer** [comment] 2018-03-29 00:57
@bryanmacfarlane To be clear, the answer to my question:

> Is the proposal that we do away with the MSBuild "Package" approach and go entirely manual with Gulp?

Is... "yes"?

**Comment by bryanmacfarlane** [comment] 2018-03-29 01:06
@JasonTheProgrammer - from the CI (and it's tasks perspective) it's not opinionated.  We have an msbuild task and a gulp task to run either tool (that's the extent of the tasks in this repo).

**Comment by jkamstra** [comment] 2018-03-29 01:07
I cant for the life of me understand why @bryanmacfarlane continues to miss the core issue. Do you guys do end to end testing any more? Granted this issue is three years old, but please, please, please try to build and deploy an app and stop trying to pretend you are smarter than all of your customers.

@JasonTheProgrammer I concur. The answer is yes.

**Comment by bryanmacfarlane** [comment] 2018-03-29 01:08
The issues in this repo is for running gulp and msbuild as part of CI.  Locking as you are not experiencing a bug with the task in this repo.
