### ISSUE TITLE
Deploy Service Fabric Application task fails every other time when node in cluster is down

### ISSUE THREAD

**Issue by remullig** [Microsoft/vsts-tasks#6164] opened 2018-01-09 01:55 UTC
## Environment
- Server - VSTS
    -Account name: dynamicscrm
    -Team project name: OneCrm
    -Release definition name: Arca_Test, Release 25

- Agent - Hosted or Private: Hosted
    
    - Agent Queue Name: Hosted

## Issue Description
Currently, if any node is down on our cluster, deployment will fail every other time, even though our application will not be placed on the downed node due to placement constraints. On every other release, it fails on line 222 of Publish-NewServiceFabricApplication.ps1, in the Get-ServiceFabricDeployedReplica command. This is because it attempts to connect to a node that isn't up. After this release fails, redeploying results in a success even while the node is still down. It will again fail, then succeed, then fail... etc if the application is subsequently redeployed while the node is down. Logs from both success and failure are attached

Additional details:
Overwrite Behavior is set to SameAppTypeAndVersion
The cluster is running an application with the same type and version running on them every time redeployment is queued

### Error logs
Failure:
[failure.txt](https://github.com/Microsoft/vsts-tasks/files/1613626/failure.txt)
Success:
[success.txt](https://github.com/Microsoft/vsts-tasks/files/1613627/success.txt)

**Comment by remullig** [comment] 2018-01-22 22:09
Any update on this? This is currently a major pain point for our deployment.

**Comment by bishal-pdMSFT** [comment] 2018-01-23 04:43
@remullig thanks for reporting the issue.
Before deploying the application instance, this task will first remove existing instance. And additionally as a precautionary measure it will forcefully drop all application replicas running on each node. 
The issue is that when a node is down, SF SDK(which this task internally uses) throws exception while querying for replica on that node. This is not handled in task.This causes task failure.
The next release is successful as it does not need to go down the path of removing application as it has already been removed previously.
I will raise a PR to fix this.

**Comment by remullig** [comment] 2018-02-03 00:31
Any further update/ETA on when this will be fixed? We may need to stop using this task and write our own powershell scripts for deployment if this isn't fixed soon.

**Comment by bishal-pdMSFT** [comment] 2018-02-05 19:34
This will done by end of week. @kuvinod to raise PR.

**Comment by bishal-pdMSFT** [comment] 2018-02-08 14:15
@remullig we are currently battling some other high priority issue and hence the fix will be delayed - we are hoping mid to end next week.

**Comment by kuvinodms** [comment] 2018-02-16 07:27
@remullig we have fixed the issue and merged the changes. This will reflect to you within a week's time. Hope this is fine but if you are blocked and facing this issue on every run then let us know we will hotfix the same for immediate availability.

**Comment by kuvinodms** [comment] 2018-02-22 09:55
@remullig 
Changes has been rolled out to all the rings. Feel free to reopen in case if you face this issue again.

**Closed by kuvinodms** 2018-02-22 09:55 UTC
Labels: Area: Release, Area: ServiceFabric, Status: Resolved
