### ISSUE TITLE
PowerShellOnTargetMachines fails on Server 2016 when rebooting by DSC

### ISSUE THREAD

**Issue by zivillian** [Microsoft/vsts-tasks#4543] opened 2017-06-14 18:06 UTC
We migrated our deployment targets from Server 2012 R2 to Server 2016 and now the PS Remoting Tasks fails, when the target is rebooted by a DSC configuration.

I was able to reproduce and verify this with the below DSC script. The Task runs fine when deployed on Server 2012 R2, but fails with the following error on Server 2016 after the server is rebooted:

> ##[error]System.Management.Automation.RuntimeException: Syntax Error. Number value is not valid: empty number string
>  At line:1, char:0
>  Buffer:
> ^?

```ps1
Configuration RebootDSC
{     
  Node localhost
  {
    # tell the node to reboot if necessary
    LocalConfigurationManager
    {
      RebootNodeIfNeeded = $true
    }
  
    Script RebootDSC
    {
      GetScript = { return "RebootDSC" }
      TestScript = {
        $value = Get-ItemProperty 'HKLM:\SOFTWARE\ahd\RebootDSC' -name Enabled -ErrorAction silentlycontinue
        if ($value -eq $null) 
        { 
          Write-Verbose "Reboot is needed..."
          return $false
        }
        else
        {
          Write-Verbose "Reboot already in desired state"
          return $true
        }
      }
      SetScript = {
        New-Item 'HKLM:\SOFTWARE\ahd\RebootDSC' -Force | Out-Null
        New-ItemProperty -path 'HKLM:\SOFTWARE\ahd\RebootDSC' -name Enabled -value 1 -PropertyType 'DWord' -Force | Out-Null
        $global:DSCMachineStatus = 1 #force reboot
      }
    }
  }
}

RebootDSC
```

**Comment by Rajat-Jindal** [comment] 2017-07-13 09:30
Me too getting the same error on "Windows 2012 R2" server as well while using Powershell DSC script with PS Remoting Tasks on rebooting of the system.

Path of the script: https://github.com/fabrikamfiber/customerservice/blob/master/DeployTemplate/ConfigureWebServer.ps1

**Comment by KrishnaAdityaB** [comment] 2017-08-30 19:34
@zivillian @Rajat-Jindal 
Were you able to successfully run the DSC from PowerShell remote session manually instead of through VSTS task?

**Comment by Rajat-Jindal** [comment] 2017-08-31 05:20
@KrishnaAdityaB  Yes i am able to run the DSC from PowerShell remote session manually and it will work on rebooting as well.

**Comment by KrishnaAdityaB** [comment] 2017-09-20 09:58
@zivillian We were able to reproduce this issue with 2016 server. I am marking this as a bug and we will work on it.
@Rajat-Jindal We were not able to reproduce the issue with 2012 R2 server. I will re-open the original thread, we can follow up there.

**Comment by DavidKloet** [comment] 2017-09-22 11:13
I had this issue on a Windows 2KR2 machine after I upgraded PS4 to PS5. 
There has been a change from PS4 to PS5: the configuration is now decorated with an attribute and properties are part of Settings instead of LocalConfigurationManager

The following script works for me:

Param 
(
    [string] $ComputerName = [System.Net.Dns]::GetHostByName(($env:ComputerName)).HostName,
    [string] $SourcePath,
    [string] $OutputPath = ".\Bin"
)

[DSCLocalConfigurationManager()]
Configuration ConfigureRebootOnNode5
{
    Param 
    (
        $ComputerName
    )

    Node $ComputerName
    {
        Settings
        {
            RebootNodeIfNeeded = $true
            ActionAfterReboot = "ContinueConfiguration"
        }
    }
}

Configuration ConfigureRebootOnNode4
{
    Param 
    (
        $ComputerName
    )

    Node $ComputerName
    {
        LocalConfigurationManager
        {
            RebootNodeIfNeeded = $true
        }
    }
}

if($PSVersionTable.PSVersion.Major -ge 5){

    ConfigureRebootOnNode5 -ComputerName $ComputerName -OutputPath $OutputPath -Verbose 

}
else{

    ConfigureRebootOnNode4 -ComputerName $ComputerName -OutputPath $OutputPath -Verbose 

}
 
Set-DscLocalConfigurationManager -Path $OutputPath -Verbose

**Comment by KrishnaAdityaB** [comment] 2017-09-27 06:34
Thanks @DavidKloet 
@zivillian Can you try David's suggestion and share the observation?

**Comment by zivillian** [comment] 2017-09-27 09:18
With the following changes the release is working as expected (on Windows Server 2016).

I've also tested to add only `ActionAfterReboot = "ContinueConfiguration"` to `LocalConfigurationManager` section, tried without `Set-DscLocalConfigurationManager` and to combine `RebootDSCConfiguration` with `RebootDSC`, but all of them failed with mostly the same error.

```diff
 RebootDSC.ps1 | 26 ++++++++++++++++++++------
 1 file changed, 20 insertions(+), 6 deletions(-)

diff --git a/RebootDSC.ps1 b/RebootDSC.ps1
index 6c2b0d5..8fbe1a4 100644
--- a/RebootDSC.ps1
+++ b/RebootDSC.ps1
@@ -1,13 +1,25 @@
+Param
+(
+[string] $OutputPath = ".\Bin"
+)
+
+[DSCLocalConfigurationManager()]
+Configuration RebootDSCConfiguration
+{
+	Node localhost
+	{
+		Settings
+		{
+			RebootNodeIfNeeded = $true
+			ActionAfterReboot = "ContinueConfiguration"
+		}
+	}
+}
+
 Configuration RebootDSC
 {     
     Node localhost
     {
-        # tell the node to reboot if necessary
-        LocalConfigurationManager
-        {
-            RebootNodeIfNeeded = $true
-        }
-
 		Script RebootDSC
 		{
 			GetScript = { return "RebootDSC" }
@@ -33,4 +45,6 @@ Configuration RebootDSC
     }
 }
 
+RebootDSCConfiguration -OutputPath $OutputPath -Verbose
+Set-DscLocalConfigurationManager -Path $OutputPath -Verbose
 RebootDSC
\ No newline at end of file
```

**Comment by KrishnaAdityaB** [comment] 2017-09-27 10:13
Thanks for sharing the experience. @zivillian 
I will close the issue as you get unblocked.

**Comment by zivillian** [comment] 2017-09-27 10:43
Sadly I would like to repoen this issue. With the above DSC no error is reported, but the DSC is also not applied - so the target is not rebooted and the release does not fail.
I tried some more variations and every time the target is rebooted by DSC it still fails with the initial error message.

I also found out that the Setting option `ActionAfterReboot` has a default value of [ContinueConfiguration](https://docs.microsoft.com/de-de/powershell/dsc/metaconfig)

**Comment by DavidKloet** [comment] 2017-09-29 07:43
Rebooting requires another step as I found out from in http://jacobbenson.com/?p=654#sthash.HoNHwMyT.dpbs 

In short, you must also include something along the lines of this, **after** you have set RebootIfNeeded = $true

    Configuration RebootServer
    {
        Param 
        (
            [string] $ComputerName
        )

        Import-DscResource –ModuleName PSDesiredStateConfiguration
        Import-DSCResource -ModuleName xPendingReboot

        Node $ComputerName
        {
            xPendingReboot CheckForReboot
            {
                Name = "Check if reboot is required"
            }
        }
    } 

    RebootServer -ComputerName $ComputerName -OutputPath $OutputPath -Verbose 

    Start-DscConfiguration -Path $OutputPath -Wait -Force -Verbose | Out-Host

This will make the server reboot immidiately and works for both PS4 and PS5 (but since you're using Windows Server 2016, your version must be PS5). This works for me, up until now at least :-)
Hope that helps!

Ps. Frankly, my script doesn't work for PS4 clients (since it doesn't recognize the attribute and Settings-node, which were introduced with PS5). I needed to separate them in separate script files.

**Comment by zivillian** [comment] 2017-09-30 09:50
If I'm correct, the xPendingReboot is only a wrapper for [$global:DSCMachineStatus = 1](https://github.com/PowerShell/xPendingReboot/blob/f430664076c13242ebe04d47d24cba5002701fd6/DSCResources/MSFT_xPendingReboot/MSFT_xPendingReboot.psm1#L85), which I'm using in the SetScript section of the Script resource. So I guess it wouldn't make a difference.

**Comment by DavidKloet** [comment] 2017-10-03 14:57
Ok, more pieces for the puzzle this time. I have a configuration that does (worst case) 2 reboots on a W2K12R2.
1: after installing PS5.1
2: after installing .NET 4.6.2

For the first one (with PS4), all works fine
2017-10-03T14:18:31.5201273Z [S0WCOI0001O]:                            [] A reboot is scheduled to progress further. Configuration will be continued after the reboot.
2017-10-03T14:18:31.5201273Z [S0WCOI0001O]: LCM:  [ End    Set      ]    in  77.2070 seconds.
2017-10-03T14:18:31.5201273Z Operation 'Invoke CimMethod' complete.
2017-10-03T14:18:31.5357535Z Time taken for configuration job to complete is 60.882 seconds
2017-10-03T14:18:31.5357535Z   Deployment started on target machine...
2017-10-03T14:18:31.5357535Z Operation '' complete.

The second one (now with PS5.1) fails:
2017-10-03T14:21:44.4424222Z [S0WCOI0001O]:                            [] A reboot is scheduled to progress further. Configuration will be continued after the reboot.
2017-10-03T14:21:44.4424222Z [S0WCOI0001O]: LCM:  [ End    Set      ]
2017-10-03T14:21:44.4424222Z [S0WCOI0001O]: LCM:  [ End    Set      ]    in  5.1210 seconds.
2017-10-03T14:21:44.4424222Z Operation 'Invoke CimMethod' complete.
2017-10-03T14:21:44.4424222Z Time taken for configuration job to complete is 5.531 seconds
2017-10-03T14:21:44.4424222Z   Deployment started on target machine...
2017-10-03T14:21:44.4424222Z System.AggregateException: Failed to apply configuration in the DSC script to the computer. Consult the Logs below for details of the error.
2017-10-03T14:21:44.4580429Z Syntax Error. Number value is not valid: empty number string
2017-10-03T14:21:44.4580429Z  At line:1, char:0
2017-10-03T14:21:44.4580429Z  Buffer:
2017-10-03T14:21:44.4580429Z ^?
2017-10-03T14:21:44.4580429Z  CategoryInfo :SyntaxError: (root/Microsoft/...gurationManager:String) [], CimException
2017-10-03T14:21:44.4580429Z  FullyQualifiedErrorId :MiClientApiError_Failed
2017-10-03T14:21:44.4580429Z  ---> Microsoft.Management.Infrastructure.CimException: Syntax Error. Number value is not valid: empty number string
2017-10-03T14:21:44.4580429Z  At line:1, char:0
2017-10-03T14:21:44.4580429Z  Buffer:
2017-10-03T14:21:44.4580429Z ^?
2017-10-03T14:21:44.4580429Z    at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
2017-10-03T14:21:44.4580429Z    --- End of inner exception stack trace ---
2017-10-03T14:21:44.4580429Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2017-10-03T14:21:44.4580429Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.<>c__DisplayClass5_0.<ExecuteScript>b__3()
2017-10-03T14:21:44.4580429Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2017-10-03T14:21:44.4580429Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2017-10-03T14:21:44.4580429Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2017-10-03T14:21:44.4580429Z ---> (Inner Exception #0) Microsoft.Management.Infrastructure.CimException: Syntax Error. Number value is not valid: empty number string
2017-10-03T14:21:44.4580429Z  At line:1, char:0
2017-10-03T14:21:44.4580429Z  Buffer: 
2017-10-03T14:21:44.4580429Z ^?
2017-10-03T14:21:44.4580429Z    at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)<---
2017-10-03T14:21:44.4580429Z Operation '' complete.

Is this helpful? Or should I post it PowerShell/MMI (which contains Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase<T>)?

Thanks in advance!

**Comment by chshrikh** [comment] 2017-11-03 04:37
We are working on the fix and suspecting this is due to WMF 5.0 and above.  @DavidKloet @Rajat-Jindal for server 2012 r2 where you see this error, could you please confirm the WMF version ? Will be great help you can share the  $PSVersionTable output. Thanks

**Comment by DavidKloet** [comment] 2017-11-14 17:35
Thank you very much @chshrikh! I was on holiday, so I couldn't respond sooner.
I pasted the output of $PSVersionTable below. Hope it helps!

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14409.1012                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14409.1012                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1

**Comment by chshrikh** [comment] 2017-11-15 03:38
@DavidKloet thanks for information. We are able to find the root cause and working on fix. Once fix is rolled out I will update here. Thanks

**Comment by chshrikh** [comment] 2017-12-08 03:41
The fix will be rolled out with next deployment. Will update the thread once it is rolled out on all rings.

**Comment by chshrikh** [comment] 2017-12-30 09:46
this has been fix now

**Closed by chshrikh** 2017-12-30 09:46 UTC
Labels: Area: Release, bug
