### ISSUE TITLE
Azure File Copy: Storage account not found error

### ISSUE THREAD

**Issue by JohanKroese** [Microsoft/vsts-tasks#2416] opened 2016-09-04 09:39 UTC
Since 2 days the Azure File Copy task in my release suddenly started failing with the following error:
##[error]Storage account: <account> not found. Selected Connection 'ServicePrincipal' supports storage account of Azure Resource Manager type only.
The task is configured to copy a build to an Azure (ARM) VM using an ARM storage account. During task configuration the storage acount can still be selected, it is during the execution of the task that the account can suddenly be no longer found. Since the task is running in a hosted agent in VSO I only have the log info to troubleshoot what is going wrong. 

This commit released to VSO exactly 2 days ago https://github.com/Microsoft/vsts-tasks/commit/84f8644eb225be509d873db0a75214761e215de6
seems to influence selection of the storage account. The error occurs regardless of whether standard or premium storage account is used. I have attached the task logs directly before and after the point in the the release task started failing.

[AzureVMs File Copy - 2016-09-01.txt](https://github.com/Microsoft/vsts-tasks/files/453859/AzureVMs.File.Copy.-.2016-09-01.txt)
[AzureVMs File Copy - 2016-09-02.txt](https://github.com/Microsoft/vsts-tasks/files/453858/AzureVMs.File.Copy.-.2016-09-02.txt)

**Comment by scott-kloud** [comment] 2016-09-04 12:03
@JohanKroese I am getting this behavior as well. Have also logged with MS support. Will let you know if I get a solution.

**Comment by kmkumaran** [comment] 2016-09-09 11:17
@JohanKroese @scott-kloud - No. there has not been any recent commit on this regard. When the issue happened, where you able to access the storage from PowerShell command? Want to eliminate if there was nothing flaky in Azure during this time which caused this.

**Comment by kmkumaran** [comment] 2016-09-11 09:05
I am marking this closed as there has been no change in the Task and the issue is likely to be external. If the problem still persists, feel free to reopen the issue. If re-opening, share with us if the container and storage command work fine directly from PowerShell.

**Closed by kmkumaran** 2016-09-11 09:05 UTC
Labels: Area: RM
