### ISSUE TITLE
Azure App Service Deploy (Preview) 4.* - Post Deployment Action 400 Bad Request

### ISSUE THREAD

**Issue by SvenSowa** [Microsoft/vsts-tasks#8093] opened 2018-08-21 20:13 UTC
**In VSTS the post deployment script result is fetched from a broken URL:**

2018-08-21T17:41:58.3933006Z ##[section]Starting: Azure App Service Deploy: www 7z
2018-08-21T17:41:58.3942728Z ==============================================================================
2018-08-21T17:41:58.3943008Z Task         : Azure App Service Deploy
2018-08-21T17:41:58.3943404Z Description  : Update Azure WebApp Services On Windows, Web App On Linux with built-in images or docker containers, ASP.NET, .NET Core, PHP, Python or Node based Web applications, Function Apps, Mobile Apps, Api applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-08-21T17:41:58.3943760Z Version      : 4.2.6
2018-08-21T17:41:58.3943963Z Author       : Microsoft Corporation
2018-08-21T17:41:58.3944190Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2018-08-21T17:41:58.3944479Z ==============================================================================
...
...
2018-08-21T17:45:45.6061011Z ##[debug]Polling started for file:  %Home%\site\VSTS_PostDeployment_501534873363657\script_result.txt with retry count: 2160
2018-08-21T17:45:45.6070124Z ##[debug][GET]https://$hidden-website:***@hidden-website.scm.azurewebsites.net/api/vfs/**site/wwwroot/%Home%\site**\VSTS_PostDeployment_501534873363657\script_result.txt
2018-08-21T17:45:46.1158816Z ##[debug]getFileContent. Status code: 400 - Bad Request

**where a working version shows:**
2018-07-13T14:23:38.4445255Z ##[section]Starting: Azure App Service Deploy: www 7z
2018-07-13T14:23:38.4453912Z ==============================================================================
2018-07-13T14:23:38.4454151Z Task         : Azure App Service Deploy
2018-07-13T14:23:38.4454509Z Description  : Update Azure WebApp Services On Windows, Web App On Linux with built-in images or docker containers, ASP.NET, .NET Core, PHP, Python or Node based Web applications, Function Apps, Mobile Apps, Api applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-07-13T14:23:38.4454876Z Version      : 4.1.12
2018-07-13T14:23:38.4455047Z Author       : Microsoft Corporation
2018-07-13T14:23:38.4455266Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2018-07-13T14:23:38.4455767Z ==============================================================================
...
...
2018-07-13T14:29:12.0563212Z ##[debug]Polling started for file:  script_result_461531491969764.txt with retry count: 2160
2018-07-13T14:29:12.0567374Z ##[debug][GET]https://$hidden-website:***@hidden-website.scm.azurewebsites.net/api/vfs/**site/wwwroot**/script_result_461531491969764.txt
2018-07-13T14:29:12.8778158Z ##[debug]getFileContent. Status code: 404 - Not Found

**This is causing the custom script action to fail and will later on in the logfile show as:**

2018-08-21T17:46:45.0823368Z ##[debug]Unable to delete log files : Error: Failed to delete folder 'site/VSTS_PostDeployment_501534873363657' from Kudu. Error: Conflict (CODE: 409)
2018-08-21T17:46:45.0825200Z ##[debug]Deployment Failed with Error: Error: Unable to run the script on Kudu Service. Error: Error: Failed to get file content 'site/wwwroot/%Home%\site\VSTS_PostDeployment_501534873363657\script_result.txt' from Kudu. Error: Bad Request (CODE: 400)
2018-08-21T17:46:45.0825956Z ##[debug]task result: Failed
2018-08-21T17:46:45.0896479Z ##[error]Error: Unable to run the script on Kudu Service. Error: Error: Failed to get file content 'site/wwwroot/%Home%\site\VSTS_PostDeployment_501534873363657\script_result.txt' from Kudu. Error: Bad Request (CODE: 400)
2018-08-21T17:46:45.0908146Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Unable to run the script on Kudu Service. Error: Error: Failed to get file content 'site/wwwroot/%Home%\site\VSTS_PostDeployment_501534873363657\script_result.txt' from Kudu. Error: Bad Request (CODE: 400)
2018-08-21T17:46:45.0910342Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Unable to run the script on Kudu Service. Error: Error: Failed to get file content 'site/wwwroot/%Home%\site\VSTS_PostDeployment_501534873363657\script_result.txt' from Kudu. Error: Bad Request (CODE: 400)

**Comment by vincentdass** [comment] 2018-08-23 08:09
@SvenSowa, Can you please share the full debug logs to `RM_CUSTOMER_QUERIES@Microsoft.com`?

**Comment by kwilson803** [comment] 2018-08-23 22:13
I'm having a similar issue with Azure App Service Deploy that just started happening recently.
https://github.com/Microsoft/vsts-tasks/issues/8110#issuecomment-415584463

**Comment by vincentdass** [comment] 2018-09-19 09:57
The issue is fixed in 4.* and the fix will be available in 2-3 weeks.

**Closed by vincentdass** 2018-09-19 09:57 UTC
Labels: Area: AzureAppService, Area: Release
