### ISSUE TITLE
Azure Monitor in pre-deployment gates runs forever with message "No samples have yet arrived"

### ISSUE THREAD

**Issue by shkrishms** [Microsoft/vsts-tasks#7902] opened 2018-08-01 19:16 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
AccountName: o365exchange.visualstudio.com
TeamProject: O365 Core/SubstrateDevX
Release pipeline Name: MetagraphCataloging-UtahAPI
Release number: 128

- Agent - Hosted or Private: 
    
Hosted agent. But issues in in the agentless phase i.e in predeployment stage.
  
## Issue Description
I have configured monitoring an application insights alert in predeployment gate. 
The pre-deployment gates runs forever with the message: "No samples have yet arrived, next sample in x min"

The logs do not give much information. The logs only has information about the agent phase of deployment. There are no instructions anywhere or support alias to help troubleshoot.

![image](https://user-images.githubusercontent.com/25833342/43543382-adc934dc-9584-11e8-822a-db2fd9009345.png)

### Error logs

[Insert error from the logs here]

**Comment by Anumita** [comment] 2018-08-03 10:27
@shkrishms , looks like the jobagent was stuck in the queued state and was not picking up any of the server tasks. I have restarted the jobagent and the issue should be fixed now. We are still investigating as to why this happened but you should be unblocked now. Please do confirm whether you are unblocked or not. Thanks for reporting the issue!

**Comment by bansalaseem** [comment] 2018-08-14 06:00
Closing this issue as the issue is fixed.

**Closed by bansalaseem** 2018-08-14 06:00 UTC
Labels: Area: Release

**Comment by kpage-bentley** [comment] 2018-08-17 15:08
@Anumita could you restart the jobagent again? we are facing the same issue
![image](https://user-images.githubusercontent.com/14302108/44273520-520e3880-a205-11e8-9a0a-9cbb6bc07233.png)
![image](https://user-images.githubusercontent.com/14302108/44273567-694d2600-a205-11e8-800f-a7535cd05da0.png)

**Comment by vithati** [comment] 2018-08-20 07:41
@kpage-bentley,  I have checked the issue. I don't see jobs are stuck. Are you still facing the issue?

**Comment by kpage-bentley** [comment] 2018-08-20 14:08
@vithati, tried one more time, same error
![image](https://user-images.githubusercontent.com/14302108/44345301-934a5680-a458-11e8-9566-496794233301.png)

**Comment by vithati** [comment] 2018-08-20 14:19
@kpage-bentley, Can you share the release link or Release pipeline Name and Release number details?

**Comment by kpage-bentley** [comment] 2018-08-20 19:57
@vithati Emailed you the link...

**Comment by vithati** [comment] 2018-08-21 05:58
@kpage-bentley, I looked at server logs,  it's not releated to jobs stuck issue. 'service connection' used in 'Scorecards gate' not present, either it deleted or not exist. Can you verify service conection once and try the release.  Presently UI not showing that error message. I have opened bug to show proper error messages in UI.
