### ISSUE TITLE
cURLUploader broken after version change

### ISSUE THREAD

**Issue by tschleining** [Microsoft/vsts-tasks#1154] opened 2016-01-28 18:48 UTC
I had a build configured to use the cURL agent task that was running successfully using 1.0.1.  The build started to fail Tuesday of this week.  I noticed the new version of the task being used is 1.0.5.  I am attempting to upload a (almost) default wp-content directory from a Wordpress structure.  Log below
`
2016-01-28T17:52:51.8953010Z [command]curl -T {D:/Build/_work/ee568988f/MSG/drop/FetchManifest.xml,D:/Build/_work/ee568988f/MSG/drop/index.php,D:/Build/_work/ee568988f/MSG/drop/plugins,D:/Build/_work/ee568988f/MSG/drop/themes} ftp://waws-prod-bay-####.ftp.azurewebsites.windows.net/site/wwwroot/wp-content/ --stderr - -u MSG__dev:########### 
2016-01-28T17:52:55.0666820Z curl: Can't open 'D:/Build/_work/ee568988f/MSG/drop/plugins'!
2016-01-28T17:52:55.0676860Z curl: try 'curl --help' or 'curl --manual' for more information
2016-01-28T17:52:55.0676860Z curl: Can't open 'D:/Build/_work/ee568988f/MarketMSG/drop/themes'!
2016-01-28T17:52:55.0706887Z curl: try 'curl --help' or 'curl --manual' for more information
2016-01-28T17:52:55.1416800Z ##[debug]rc:26
2016-01-28T17:52:55.1426802Z ##[debug]success:false
2016-01-28T17:52:55.1436801Z ##[debug]ToolRunner execution failure: Error: curl failed with return code: 26
2016-01-28T17:52:55.1446803Z ##[debug]load loc strings from: D:\Build\tasks\cURLUploader\1.0.5\node_modules\vsts-task-lib\lib.json
2016-01-28T17:52:55.1456808Z ##[debug]cache vsts-task-lib loc string: LIB_UnhandledEx
2016-01-28T17:52:55.1456808Z ##[debug]cache vsts-task-lib loc string: LIB_FailOnCode
2016-01-28T17:52:55.1466804Z ##[debug]cache vsts-task-lib loc string: LIB_ReturnCode
2016-01-28T17:52:55.1476809Z ##[debug]cache vsts-task-lib loc string: LIB_ResourceFileNotExist
2016-01-28T17:52:55.1476809Z ##[debug]cache vsts-task-lib loc string: LIB_ResourceFileAlreadySet
2016-01-28T17:52:55.1486808Z ##[debug]cache vsts-task-lib loc string: LIB_ResourceFileNotSet
2016-01-28T17:52:55.1486808Z ##[debug]cache vsts-task-lib loc string: LIB_LocStringNotFound
2016-01-28T17:52:55.1496801Z ##[debug]cache vsts-task-lib loc string: LIB_ParameterIsRequired
2016-01-28T17:52:55.1496801Z ##[debug]cache vsts-task-lib loc string: LIB_InputRequired
2016-01-28T17:52:55.1506806Z ##[debug]cache vsts-task-lib loc string: LIB_EndpointNotExist
2016-01-28T17:52:55.1506806Z ##[debug]cache vsts-task-lib loc string: LIB_InvalidEndpointAuth
2016-01-28T17:52:55.1516814Z ##[debug]cache vsts-task-lib loc string: LIB_PathNotFound
2016-01-28T17:52:55.1516814Z ##[debug]cache vsts-task-lib loc string: LIB_PathHasNullByte
2016-01-28T17:52:55.1526810Z ##[debug]cache vsts-task-lib loc string: LIB_OperationFailed
2016-01-28T17:52:55.1526810Z ##[debug]cache vsts-task-lib loc string: LIB_UseFirstGlobMatch
2016-01-28T17:52:55.1536803Z ##[debug]cache vsts-task-lib loc string: LIB_MergeTestResultNotSupported
2016-01-28T17:52:55.1596815Z ##[error]Return code: 1
2016-01-28T17:52:55.1606806Z ##[debug]task result: Failed
2016-01-28T17:52:55.1856824Z Finishing task: cURLUploader
2016-01-28T17:52:55.1876817Z ##[error]Task cURLUploader failed. This caused the job to fail. Look at the logs for the task for more details.
`

**Comment by yacaovsnc** [comment] 2016-01-28 20:30
@tschleining the curl task is really not meant to upload folders, in fact, I don't believe curl supports uploading folders.  I assume "D:/Build/_work/ee568988f/MSG/drop/plugins" and "D:/Build/_work/ee568988f/MSG/drop/themes" are folders?  

However that doesn't explain why it worked before and not now.  Could you please post the log of a working build so I can see the difference?  

Thanks a lot!

**Comment by tschleining** [comment] 2016-01-28 21:14
Not just folders but contents and structure resembling this  https://github.com/WordPress/WordPress/tree/master/wp-content.  Log below and [here](http://pastebin.com/Bfjxafba).

`2016-01-25T23:35:11.0749472Z SkipArtifactsDownload=False, ReleaseId=451, TeamProjectId=#######-5641-42ac-a467-####b4ea204d
2016-01-25T23:35:11.0829471Z Release folder: ee568988f
2016-01-25T23:35:12.5504973Z ##[section]Cleaning artifacts directory: D:\Build\_work\ee568988f…
2016-01-25T23:35:13.3976971Z ##[section]Cleaned artifacts directory: D:\Build\_work\ee568988f
2016-01-25T23:35:13.4006916Z Number of linked artifacts to download: 1
2016-01-25T23:35:13.4006916Z Starting artifacts download...
2016-01-25T23:35:13.4176921Z Downloading linked artifact: MSG...
2016-01-25T23:35:13.4186923Z Downloading artifact of type: Build
2016-01-25T23:35:13.4196975Z Created artifact folder D:\Build\_work\ee568988f\MSG
2016-01-25T23:35:13.4316926Z Preparing to get the list of available artifacts from build.
2016-01-25T23:35:13.7184444Z Preparing to download artifact: drop
2016-01-25T23:35:13.7274389Z Artifact Type: ServerDrop
2016-01-25T23:35:13.7274389Z The artifact is of older version: False
2016-01-25T23:35:14.0110193Z Caching items under 'drop' in the file container...
2016-01-25T23:35:15.8742212Z Caching complete. (1863 ms)
2016-01-25T23:35:16.3700451Z Downloading files.
2016-01-25T23:35:16.3710479Z Proxy server  is disabled!. Download speed will be impacted.
2016-01-25T23:35:16.4990731Z Proxy  has been disabled.
2016-01-25T23:35:21.4242310Z 3551 downloads remaining.
2016-01-25T23:35:26.4266077Z 3412 downloads remaining.
2016-01-25T23:35:31.4282744Z 3283 downloads remaining.
2016-01-25T23:35:36.4296794Z 3167 downloads remaining.
2016-01-25T23:35:41.4317893Z 3033 downloads remaining.
2016-01-25T23:35:46.4336482Z 2911 downloads remaining.
2016-01-25T23:35:51.4342007Z 2775 downloads remaining.
2016-01-25T23:35:56.4349225Z 2637 downloads remaining.
2016-01-25T23:36:01.4370065Z 2504 downloads remaining.
2016-01-25T23:36:06.4393963Z 2381 downloads remaining.
2016-01-25T23:36:11.4398777Z 2246 downloads remaining.
2016-01-25T23:36:16.4422213Z 2140 downloads remaining.
2016-01-25T23:36:21.4429867Z 2009 downloads remaining.
2016-01-25T23:36:26.4455641Z 1887 downloads remaining.
2016-01-25T23:36:31.4458705Z 1762 downloads remaining.
2016-01-25T23:36:36.4485589Z 1636 downloads remaining.
2016-01-25T23:36:41.4518848Z 1510 downloads remaining.
2016-01-25T23:36:46.4534652Z 1388 downloads remaining.
2016-01-25T23:36:51.4546699Z 1262 downloads remaining.
2016-01-25T23:36:56.4571544Z 1143 downloads remaining.
2016-01-25T23:37:01.4588749Z 1019 downloads remaining.
2016-01-25T23:37:06.4601859Z 891 downloads remaining.
2016-01-25T23:37:11.4620636Z 818 downloads remaining.
2016-01-25T23:37:16.4636947Z 725 downloads remaining.
2016-01-25T23:37:21.4654344Z 631 downloads remaining.
2016-01-25T23:37:26.4667812Z 533 downloads remaining.
2016-01-25T23:37:31.4678813Z 413 downloads remaining.
2016-01-25T23:37:36.4699720Z 303 downloads remaining.
2016-01-25T23:37:41.4844560Z 220 downloads remaining.
2016-01-25T23:37:46.4860632Z 130 downloads remaining.
2016-01-25T23:37:51.4875778Z 24 downloads remaining.
2016-01-25T23:37:56.4944435Z Downloads complete.
2016-01-25T23:37:56.5764440Z 3660 placed file(s): 3658 downloaded, 2 empty and new, 0 preserved.
2016-01-25T23:37:56.5764440Z 58 MB downloaded at 368 KB/sec. Download time: 00:02:40.1247814. Parallel download limit: 8.
2016-01-25T23:37:56.5769438Z Proxy server  was unavailable for some or all downloads.
2016-01-25T23:37:56.5774448Z Download breakdown:
2016-01-25T23:37:56.5774448Z 3660 file(s) are new.
2016-01-25T23:37:56.5774448Z Downloaded linked artifact MSG
2016-01-25T23:37:56.5784485Z Finished artifacts download
2016-01-25T23:37:56.5824481Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
2016-01-25T23:37:56.5824481Z 				[AGENT_NAME] --> [Agent-TSCHLEINING-PC]
2016-01-25T23:37:56.5824481Z 				[AGENT_ROOTDIRECTORY] --> [D:\Build\_work]
2016-01-25T23:37:56.5824481Z 				[AGENT_HOMEDIRECTORY] --> [D:\Build]
2016-01-25T23:37:56.5834489Z 				[AGENT_ID] --> [24]
2016-01-25T23:37:56.5834489Z 				[AGENT_MACHINENAME] --> [TSCHLEINING-PC]
2016-01-25T23:37:56.5834489Z 				[AGENT_JOBNAME] --> [Release]
2016-01-25T23:37:56.5834489Z 				[AGENT_WORKFOLDER] --> [D:\Build\_work]
2016-01-25T23:37:56.5834489Z 				[SYSTEM] --> [release]
2016-01-25T23:37:56.5844482Z 				[RELEASE_RELEASEID] --> [451]
2016-01-25T23:37:56.5854490Z 				[SYSTEM_TEAMPROJECTID] --> [#######-5641-42ac-a467-####b4ea204d]
2016-01-25T23:37:56.5854490Z 				[SYSTEM_TEAMPROJECT] --> [MNM]
2016-01-25T23:37:56.5854490Z 				[RELEASE_RELEASENAME] --> [Release-33]
2016-01-25T23:37:56.5864483Z 				[RELEASE_RELEASEDESCRIPTION] --> [Triggered by MMSG 20160125.5.]
2016-01-25T23:37:56.5864483Z 				[RELEASE_DEFINITIONNAME] --> [MSG]
2016-01-25T23:37:56.5864483Z 				[SYSTEM_HOSTTYPE] --> [release]
2016-01-25T23:37:56.5864483Z 				[RELEASE_RELEASEURI] --> [vstfs:///ReleaseManagement/Release/451]
2016-01-25T23:37:56.5874485Z 				[RELEASE_ENVIRONMENTURI] --> [vstfs:///ReleaseManagement/Environment/847]
2016-01-25T23:37:56.5874485Z 				[RELEASE_ENVIRONMENTNAME] --> [Dev]
2016-01-25T23:37:56.5874485Z 				[RELEASE_SKIPARTIFACTSDOWNLOAD] --> [False]
2016-01-25T23:37:56.5874485Z 				[RELEASE_REQUESTEDFOR] --> [Whitney Gainer]
2016-01-25T23:37:56.5884485Z 				[RELEASE_REQUESTEDFORID] --> [########-0465-45a6-a172-3ce90306afae]
2016-01-25T23:37:56.5884485Z 				[SYSTEM_COLLECTIONID] --> [########-d253-482f-889e-df24ee5727cb]
2016-01-25T23:37:56.5884485Z 				[SYSTEM_TEAMFOUNDATIONCOLLECTIONURI] --> [https://mnm.visualstudio.com/DefaultCollection/]
2016-01-25T23:37:56.5884485Z 				[SYSTEM_TASKDEFINITIONSURI] --> [https://mnm.visualstudio.com/DefaultCollection/]
2016-01-25T23:37:56.5894489Z 				[BUILD_DEFINITIONNAME] --> [MSG]
2016-01-25T23:37:56.5894489Z 				[BUILD_DEFINITIONID] --> [107]
2016-01-25T23:37:56.5894489Z 				[BUILD_BUILDNUMBER] --> [20160125.5]
2016-01-25T23:37:56.5894489Z 				[BUILD_BUILDID] --> [15903]
2016-01-25T23:37:56.5904486Z 				[BUILD_REPOSITORY_NAME] --> [MNM]
2016-01-25T23:37:56.5904486Z 				[BUILD_SOURCEBRANCH] --> [refs/heads/master]
2016-01-25T23:37:56.5904486Z 				[BUILD_SOURCEBRANCHNAME] --> [master]
2016-01-25T23:37:56.5904486Z 				[BUILD_SOURCEVERSION] --> [b9fddecf6819869d60b6ad3738700185811474cf]
2016-01-25T23:37:56.5904486Z 				[BUILD_BUILDURI] --> [vstfs:///Build/Build/15903]
2016-01-25T23:37:56.5914485Z 				[BUILD_REQUESTEDFORID] --> [e33b256f-0465-45a6-a172-3ce90306afae]
2016-01-25T23:37:56.5914485Z 				[BUILD_REPOSITORY_PROVIDER] --> [TfsGit]
2016-01-25T23:37:56.5914485Z 				[BUILD_REQUESTEDFOR] --> [Tristan Schleining]
2016-01-25T23:37:56.5914485Z 				[BUILD_TYPE] --> [Build]
2016-01-25T23:37:56.5924484Z 				[SYSTEM_WORKFOLDER] --> [D:\Build\_work]
2016-01-25T23:37:56.5924484Z 				[AGENT_WORKINGDIRECTORY] --> [D:\Build\_work\SourceRootMapping\1550aad4-d253-482f-889e-df24ee5727cb\Job-abffa909-c723-4639-88d7-f8f6d8e093d2]
2016-01-25T23:37:56.5924484Z 				[AGENT_RELEASEDIRECTORY] --> [D:\Build\_work\ee568988f]
2016-01-25T23:37:56.5924484Z 				[SYSTEM_ARTIFACTSDIRECTORY] --> [D:\Build\_work\ee568988f]
2016-01-25T23:37:56.5934486Z 				[SYSTEM_DEFAULTWORKINGDIRECTORY] --> [D:\Build\_work\ee568988f]
2016-01-25T23:37:56.6864574Z Running tasks
2016-01-25T23:37:56.7054575Z Starting task: Upload $(System.DefaultWorkingDirectory)\MSG\drop\* with cURL
2016-01-25T23:37:56.7639631Z Executing the powershell script: D:\Build\tasks\cURLUploader\1.0.1\cURLUploader.ps1
2016-01-25T23:37:57.2128308Z C:\Program Files (x86)\curl\curl.exe --stderr -  -u "MSG__dev":"####" -T {"D:/Build/_work/ee568988f/MSG/drop/FetchManifest.xml","D:/Build/_work/ee568988f/MSG/drop/index.php"} ftp://waws-prod-bay-###.ftp.azurewebsites.windows.net/site/wwwroot/wp-content/
2016-01-25T23:37:57.2458322Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2016-01-25T23:37:57.2458322Z                                  Dload  Upload   Total   Spent    Left  Speed
2016-01-25T23:37:57.3698727Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2016-01-25T23:37:58.3564876Z   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2016-01-25T23:37:59.3513541Z   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
2016-01-25T23:38:00.1041068Z  39  891k    0     0   39  352k      0   166k  0:00:05  0:00:02  0:00:03  166k
2016-01-25T23:38:00.1051070Z 100  891k    0     0  100  891k      0   311k  0:00:02  0:00:02 --:--:--  311k
2016-01-25T23:38:00.3988572Z   0    52    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2016-01-25T23:38:00.3998569Z 100    52    0     0  100    52      0    175 --:--:-- --:--:-- --:--:--   666
2016-01-25T23:38:00.5199396Z Finishing task: cURLUploader`

**Comment by yacaovsnc** [comment] 2016-01-28 21:31
I see.  Thanks @tschleining.

From the log, it appears we were only uploading two files: 
C:\Program Files (x86)\curl\curl.exe --stderr - -u "MSG__dev":"####" -T **{"D:/Build/_work/ee568988f/MSG/drop/FetchManifest.xml","D:/Build/_work/ee568988f/MSG/drop/index.php"} **ftp://waws-prod-bay-###.ftp.azurewebsites.windows.net/site/wwwroot/wp-content/

which is different from today's run which attempted to upload two additional folders.

With version 1.0.5, we are switching to run typescript/javascript version of the task.  Did your use a wildcard in the "Files" input?  If so, it appears we interpret the wildcard differently in powershell and typescript implementation. 

However, from what you mentioned, I don't think uploading two files were the correct behavior either?

**Comment by bryanmacfarlane** [comment] 2016-01-28 21:33
@yacaovsnc 

correct minimatch is /some/path/**/* not /some/path.  that was actually a bug in the ps/managed one.

**Comment by tschleining** [comment] 2016-01-28 21:41
@yacaovsnc Interesting.  I thought all the files were being uploaded.  I assumed that's what the "FetchManifest.xml" was for.  I will have to look into that.

Yes I do have a wildcard in the Files input.  $(System.DefaultWorkingDirectory)\MSG\drop\*

I would like the entire directory structure uploaded.  Is that possible?

**Comment by bryanmacfarlane** [comment] 2016-01-28 21:42
Does this work?
 $(System.DefaultWorkingDirectory)\MSG\drop\**\*

**Comment by bryanmacfarlane** [comment] 2016-01-28 21:42
```
 $(System.DefaultWorkingDirectory)\MSG\drop\**\*
```

**Comment by tschleining** [comment] 2016-01-28 22:04
`2016-01-28T21:52:07.4093976Z ##[error]Unhandled: spawn ENAMETOOLONG`

Although I suspect this may be a curl error and not the agent task.

**Comment by yacaovsnc** [comment] 2016-01-28 22:42
issue #995 , could be the same issue.  The other user created a FTP uploader task and it seems worked for this situation.

**Comment by TonyValenti** [comment] 2016-02-06 00:20
Wow!  I can't believe that the CURL uploader is broken.  I just spent 6 hours trying to figure this one out.  I am so glad that a community member made the extension.  I just wish I had found it sooner.

By the way, I did a ton of investigating into this and it appears that there are two problems that are playing off of each other.

First, with the CURL app itself, it wants directory names to be specified with a trailing /.  This is fine, but the VSTS web interface removes any trailing slashes from the pattern that is specified.  When the script does the globbing, it removes any slash from directory names and this causes CURL to fail.

**Comment by ycao233** [comment] 2016-02-08 15:48
@TonyValenti Glad you found the community made extension worked for you!  It's really a good model where developers can contribute to and extend the existing functionalities.

I am a curious to know if there is anyway to make curl work against folders.  I thought it only works with files.  This is what I tried:
`curl -T /absolute/path/to/folder/  ftp://myftpserver.com/root/folder/ -u 'user:pass'`

and I got:

`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (3) Uploading to a URL without a file name!`

The man page of curl seems also suggest only Files are supported:
`-T, --upload-file <file>
              This transfers the specified local file to the remote URL. If there is no file part in the specified URL, Curl will append the local file name. NOTE that you must use a trailing / on the last directory to really  prove  to  Curl
              that  there is no file name or curl will think that your last directory name is the remote file name to use. That will most likely cause the upload operation to fail. If this is used on an HTTP(S) server, the PUT command will be
              used.`

I read this as only files is supported, but you can specify a folder name in the URL argument, and if the URL argument is a folder (ending /), then curl will use the local file name when creating remote files.  

What is the syntax you used to upload folders?

**Comment by bryanmacfarlane** [comment] 2016-04-21 11:30
Is there anything actionable for the task to change here? @yacaovsnc @tschleining ??

**Comment by yacaovsnc** [comment] 2016-04-21 13:14
Closing this as the task behaves as designed.

**Closed by yacaovsnc** 2016-04-21 13:14 UTC

**Comment by PatrickKursawe** [comment] 2016-09-07 10:29
My build process creates a setup file with an auto generated name like ProgName-Setup 1.2.3-beta.5 - 2016-09-07.exe - I would like to upload this using the cURL build step. 
Looks like I am doing it wrong:

2016-09-07T10:21:06.4749944Z ##[debug]curl=C:\ProgramData\chocolatey\bin\curl.exe
 
2016-09-07T10:21:06.4749944Z ##[debug]Matching glob pattern: C:\BuildAgent\_work\1\s\Setups\**\*
 
2016-09-07T10:21:06.4749944Z ##[debug]Index of first wildcard: 31
 
2016-09-07T10:21:06.4749944Z ##[debug]find root dir: C:\BuildAgent\_work\1\s
 
2016-09-07T10:21:09.0531534Z ##[debug]find C:\BuildAgent\_work\1\s
 
2016-09-07T10:21:09.0531534Z ##[debug]9497 matches.
 
2016-09-07T10:21:09.1156558Z ##[error]No matching files were found with search pattern: C:\BuildAgent\_work\1\s\Setups\**\*

Any hint which pattern I could use to upload the file that's the only file under "Setups"?

Thanks!

**Comment by ycao233** [comment] 2016-09-07 14:22
Maybe try this pattern? 
`C:\BuildAgent_work\1\s\Setups\*`

**Comment by yacaovsnc** [comment] 2016-09-07 14:23
Maybe try this pattern? 
`C:\BuildAgent_work\1\s\Setups\*`

**Comment by PatrickKursawe** [comment] 2016-09-07 15:35
That was among the first ones I tried.

Outlook for Android<https://aka.ms/ghei36> herunterladen



On Wed, Sep 7, 2016 at 4:23 PM +0200, "ycao233" <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe try this pattern?
C:\BuildAgent_work\1\s\Setups\*

-

**Comment by yacaovsnc** [comment] 2016-09-07 15:39
Can you please email me the details at yacao AT Microsoft dot com and I will take a look.  Specifically, please let me know the exact file path that you are trying to match (get the path from a previous build, or build your project locally and get the path), and what patterns you have tried.
