### ISSUE TITLE
Inconclusive tests should be marked as failed in VS-Test Task

### ISSUE THREAD

**Issue by tomkerkhove** [Microsoft/vsts-tasks#3024] opened 2016-11-03 16:03 UTC
When working with dynamic test data from a 3rd party it can sometime be invalid for your test scenario - This is a good scenario where the test itself can be considered inconclusive because the state is not suitable.

However, when you have inconclusive tests with VS-Test Task it marks it as `Failed` while there should be a different status like `Inconclusive` or `Did not Run` so that we know which ones failed and which ones had bad data.

Does this make sense?

**Comment by tomkerkhove** [comment] 2016-11-11 00:48
Any ideas about this?

**Comment by tomkerkhove** [comment] 2016-11-30 07:19
Let me know if you have any questions about this feature request!

**Comment by vimegh** [comment] 2016-11-30 07:39
@tomkerkhove Thanks for reminding on this. VSTest task reports whatever VS reports in the trx file after running the tests, we have asked for inputs internally on this. I will update the thread as soon as I get a reply on it.

**Comment by tomkerkhove** [comment] 2016-11-30 08:43
@vimegh Thanks for the update!

**Comment by pvlakshm** [comment] 2016-12-06 07:13
By default, inconclusive tests are reported as Skipped (Not Run). If you are using MSTest framework based tests, the way to change that is by using a setting in the runsettings file (see MapInconclusiveToFailed here: https://msdn.microsoft.com/en-us/library/jj635153.aspx). Can you check if such a .runsettings file is in effect?

**Comment by tomkerkhove** [comment] 2016-12-06 07:32
That would be great to have as well - Unfortunately, when you run them in VSTS with the Test-task it marks them as failures instead of Skipped.

Would it be possible to change this to result in Skipped tests?

**Comment by vimegh** [comment] 2016-12-06 09:48
@tomkerkhove As far as I know, if there is a inconclusive/notexecuted test in the trx file generated after running the tests, VsTest task marks it as Others/NotExecuted (doesn't mark is as failed). Can you please share the trx file and run settings file by using which Inconclusive/NotExecuted tests are being marked as failed by vstest task. Thanks.

**Comment by tomkerkhove** [comment] 2016-12-06 10:52
We are using NUnit instead of MSTest but when we run them locally they are marked as `Others/NotExecuted` while on VSTS they are marked as `Failed`.

**Comment by vimegh** [comment] 2016-12-07 10:42
@tomkerkhove Can you share the results file being generated by Vstest task? You can email us the resulted trx file generated by VSTest Task at devops_tools AT microsoft DOT com
Also are you using OnPrem TFS, if yes can you share with us the version. Thanks.

**Comment by tomkerkhove** [comment] 2016-12-07 13:31
@vimegh Thank you very much, mail is on the way!

**Comment by tomkerkhove** [comment] 2016-12-07 13:46
I got a failure delivery for certain people so please let me know if you didn't get it.

**Comment by acesiddhu** [comment] 2016-12-08 04:12
Hi @tomkerkhove we have received the mail. @vimegh will check and reply back

**Comment by zelenp** [comment] 2016-12-08 07:56
Hi, we are probably facing similar problem. I reported it here: https://github.com/Microsoft/vsts-agent/issues/713 It could well be I picked the wrong component when raising the issue, as pointed out in the comments. Could you please check it and let me know whether I should somehow move the issue here (or merge it with this one?). Thanks a lot!

**Comment by vimegh** [comment] 2016-12-09 06:27
I am able to reproduce the issue with Nunit 3.5 and Nunit Test Adapter 3.6 and VS 2015 U3
@tomkerkhove Are you using the same nunit version? 
@zelenp You can follow this issue thread only, instead of creating a new one, as it seems you are facing the same issue.

Also can you please update the thread with following:
1. VS Version you are using
2. TFS version being used (if on premises)

thanks.

**Comment by tomkerkhove** [comment] 2016-12-09 08:27
@vimegh We are still on 3.4.1 but I think it's applicable for a few/all versions. Thank you for looking into this!

**Comment by zelenp** [comment] 2016-12-09 08:40
@vimegh We are using the hosted build agent/pipeline, our account is https://bssai.visualstudio.com

Individual developers use either VS 2015 U3 or Rider, depending on their preference.

The behaviour we experience is following (copied from [the original report](https://github.com/Microsoft/vsts-agent/issues/713) for your convenience):

When NUnit tests are executed on Visual Studio Team Services (VSTS) build server, tests marked as `Explicit` are correctly skipped as per console output:
```
2016-12-06T10:00:47.2789724Z Information: NUnit Adapter 3.6.0.0: Test execution complete
2016-12-06T10:00:47.2789724Z 
2016-12-06T10:00:47.5128672Z Results File: C:\a\1\s\TestResults\buildguest_TASKAGENT5-0027 2016-12-06 09_59_48.trx
2016-12-06T10:00:47.5158684Z 
2016-12-06T10:00:47.5158684Z Attachments:
2016-12-06T10:00:47.5168676Z   C:\a\1\s\TestResults\f3d40ef8-75d5-4756-b1c5-e6338daf9b3c\buildguest_TASKAGENT5-0027 2016-12-06 09_59_37.coverage
2016-12-06T10:00:47.5168676Z 
2016-12-06T10:00:47.5168676Z Total tests: 76. Passed: 62. Failed: 0. Skipped: 0.
2016-12-06T10:00:47.5168676Z Test Run Successful.
2016-12-06T10:00:47.5178694Z Test execution time: 1.1636 Minutes
```
However, all explicit tests are marked as Failed in test record trx file like this:
```
<UnitTestResult executionId="a5898e64-e18b-497c-aaa3-6f0b3c188154" testId="34822bf0-4fc5-43dd-9d33-5979bab83594" testName="TestInspectorConstraint" computerName="TASKAGENT5-0027" duration="00:00:00.0010000" startTime="2016-12-06T09:59:50.0000000+00:00" endTime="2016-12-06T09:59:50.0000000+00:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="a5898e64-e18b-497c-aaa3-6f0b3c188154" />
```
We are using NUnit 3.5 and 3.6.0 NUnitAdapter and hosted build agent.

**Comment by prawalagarwal** [comment] 2016-12-13 10:41
Hi @tomkerkhove  @zelenp 

It looks like the nunit adapter today sets the inconclusive outcome results to None in the test result object returned to vstest.console, which due to being indeterminate is set Failed. We have contacted the owner of the nunit adapter code to resolve the issue. Will update the thread soon.

**Comment by tomkerkhove** [comment] 2016-12-19 08:11
@prawalagarwal Thank you for the update and looking into this. I'm looking forward to having this supported

**Comment by tomkerkhove** [comment] 2017-01-06 09:47
@prawalagarwal Can you provide an update on this status or a link to an issue if one was filed so I can stay up to date?

**Comment by prawalagarwal** [comment] 2017-01-09 07:49
Hi @tomkerkhove 

Sorry for the delays in updating. There is an on going discussion going on this topic on the nunit adapter issues page :[]( https://github.com/nunit/nunit3-vs-adapter/issues/219). Once it reaches a conclusion we should be able to update you what is the way forward. Currently, this seems like a design level blockade in how nunit adapter is used by the VSTest.

**Closed** 2017-02-20 05:13 UTC
Labels: Area: Test, question

**Comment by OsirisTerje** [comment] 2017-02-20 08:17
@prawalagarwal   The NUnit3 adapter issue is clear on needing a change in the vstest task.  See @charliepoole 's comment 
"On January 8, @prawalagarwal noted on that issue that it was being discussed here. As you can see, that's not the case. There has been no further discussion since I outlined the problem as we see it on January 6."
So you can reopen this, and also remove the question tag and mark it as an enhancement.

**Comment by tomkerkhove** [comment] 2017-02-20 10:30
@nigurr Did you close the issue because it was moved to https://github.com/Microsoft/vstest/issues/525 a dedicated issue to get this fixed or what is the reason?

**Comment by nigurr** [comment] 2017-02-20 11:37
@tomkerkhove I moved it to vstest repo so that right set of people can address this issue. Since vsts-task reads TRX and publishes the information, and this issue is more closely related to vstest.console and Nunit adapter.

We already notified the product team about this issue.

**Comment by tomkerkhove** [comment] 2017-02-20 13:28
@nigurr Thanks for the update!
