### ISSUE TITLE
Docker task cannot find dockerfile in staging directory,

### ISSUE THREAD

**Issue by bilalhaider** [Microsoft/vsts-tasks#5641] opened 2017-10-14 04:17 UTC
### Environment
VSTS: provisioinsights / spectre, Build: InitialProcessor / Build 20171014.6
Agent: Hosted VS2017

### Issue Description
Docker task cannot find dockerfile in staging directory, 

**Tasks**
- Copy files: including `**\Dockerfile-Publish` to `$(build.artifactstagingdirectory)`
- Docker: Action: build image, Docker file: `$(build.artifactstagingdirectory)\**\Dockerfile-Publish`

**Error**
No Docker file matching d:\a\1\a\**\Dockerfile-Publish was found.

Copy files task logs show that the file is indeed copied and I can also see the Dockerfile-Publish in artifacts. Is the docker task trying to find this pattern _inside_ the source directory?

### Logs
Copy files task
```
    2017-10-14T03:46:06.6232438Z Copying d:\a\1\s\src\Spectre.InitialProcessor.TestConsole\Dockerfile-Publish to d:\a\1\a\src\Spectre.InitialProcessor.TestConsole\Dockerfile-Publish
```
Docker task
```
2017-10-14T03:46:06.6392417Z ##[debug]Evaluating condition for step: 'Build an image'
2017-10-14T03:46:06.6392417Z ##[debug]Evaluating: succeeded()
2017-10-14T03:46:06.6392417Z ##[debug]Evaluating succeeded:
2017-10-14T03:46:06.6392417Z ##[debug]=> (Boolean) True
2017-10-14T03:46:06.6392417Z ##[debug]Expanded: True
2017-10-14T03:46:06.6392417Z ##[debug]Result: True
2017-10-14T03:46:06.6392417Z ##[section]Starting: Build an image
2017-10-14T03:46:06.6392417Z ==============================================================================
2017-10-14T03:46:06.6392417Z Task         : Docker
2017-10-14T03:46:06.6392417Z Description  : Build, tag, push, or run Docker images, or run a Docker command. Task can be used with Docker or Azure Container registry.
2017-10-14T03:46:06.6392417Z Version      : 0.3.1
2017-10-14T03:46:06.6392417Z Author       : Microsoft Corporation
2017-10-14T03:46:06.6392417Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
2017-10-14T03:46:06.6392417Z ==============================================================================
2017-10-14T03:46:06.8472320Z ##[debug]agent.workFolder=d:\a
2017-10-14T03:46:06.8502325Z ##[debug]loading inputs and endpoints
2017-10-14T03:46:06.8522325Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2017-10-14T03:46:06.8522325Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2017-10-14T03:46:06.8522325Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_ACTION
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_CONTAINERREGISTRYTYPE
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_CONTEXT
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_CWD
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_DEFAULTCONTEXT
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_DETACHED
2017-10-14T03:46:06.8532323Z ##[debug]loading INPUT_DOCKERFILE
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_IMAGEDIGESTFILE
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_IMAGENAME
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_IMAGENAMESPATH
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_INCLUDELATESTTAG
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_INCLUDESOURCETAGS
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_QUALIFYIMAGENAME
2017-10-14T03:46:06.8662318Z ##[debug]loading INPUT_RESTARTPOLICY
2017-10-14T03:46:06.8662318Z ##[debug]loaded 17
2017-10-14T03:46:06.9012299Z ##[debug]check path : d:\a\_tasks\Docker_e28912f1-0114-4464-802a-a3a35437fd16\0.3.1\task.json
2017-10-14T03:46:06.9012299Z ##[debug]set resource file to: d:\a\_tasks\Docker_e28912f1-0114-4464-802a-a3a35437fd16\0.3.1\task.json
2017-10-14T03:46:06.9012299Z ##[debug]system.culture=en-US
2017-10-14T03:46:06.9042294Z ##[debug]cwd=d:\a\1\s
2017-10-14T03:46:06.9052308Z ##[debug]containerregistrytype=Container Registry
2017-10-14T03:46:06.9062298Z ##[debug]dockerRegistryEndpoint=null
2017-10-14T03:46:06.9062298Z ##[debug]Absolute path for pathSegments: d:\a\_tool\NuGet\4.3.0\x64/docker = d:\a\_tool\NuGet\4.3.0\x64\docker
2017-10-14T03:46:06.9072411Z ##[debug]Absolute path for pathSegments: C:\LR\mms\Services\Mms\Provisioner\TaskAgent\agents\2.123.0\externals\git\cmd/docker = C:\LR\mms\Services\Mms\Provisioner\TaskAgent\agents\2.123.0\externals\git\cmd\docker
2017-10-14T03:46:06.9072411Z ##[debug]Absolute path for pathSegments: C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin/docker = C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\docker
2017-10-14T03:46:06.9072411Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft MPI\Bin\/docker = C:\Program Files\Microsoft MPI\Bin\docker
2017-10-14T03:46:06.9072411Z ##[debug]Absolute path for pathSegments: C:\Program Files (x86)\Python36-32\Scripts\/docker = C:\Program Files (x86)\Python36-32\Scripts\docker
2017-10-14T03:46:06.9072411Z ##[debug]Absolute path for pathSegments: C:\Program Files (x86)\Python36-32\/docker = C:\Program Files (x86)\Python36-32\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Windows\system32/docker = C:\Windows\system32\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Windows/docker = C:\Windows\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\Wbem/docker = C:\Windows\System32\Wbem\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Windows\System32\WindowsPowerShell\v1.0\/docker = C:\Windows\System32\WindowsPowerShell\v1.0\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\/docker = C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft SQL Server\130\Tools\Binn\/docker = C:\Program Files\Microsoft SQL Server\130\Tools\Binn\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Program Files (x86)\GtkSharp\2.12\bin/docker = C:\Program Files (x86)\GtkSharp\2.12\bin\docker
2017-10-14T03:46:06.9082294Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft\Web Platform Installer\/docker = C:\Program Files\Microsoft\Web Platform Installer\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\Program Files\nodejs\/docker = C:\Program Files\nodejs\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps/docker = C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\NPM\Modules/docker = C:\NPM\Modules\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\Program Files\Git LFS/docker = C:\Program Files\Git LFS\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\Program Files\CMake\bin/docker = C:\Program Files\CMake\bin\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\java\ant\apache-ant-1.9.7\bin/docker = C:\java\ant\apache-ant-1.9.7\bin\docker
2017-10-14T03:46:06.9092296Z ##[debug]Absolute path for pathSegments: C:\java\maven\apache-maven-3.2.2\bin/docker = C:\java\maven\apache-maven-3.2.2\bin\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: C:\Program Files\Java\jdk1.8.0_112\bin/docker = C:\Program Files\Java\jdk1.8.0_112\bin\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: C:\Program Files\dotnet\/docker = C:\Program Files\dotnet\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code/docker = C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager/docker = C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: C:\Users\testusername\AppData\Local\Microsoft\WindowsApps/docker = C:\Users\testusername\AppData\Local\Microsoft\WindowsApps\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: \Docker/docker = d:\Docker\docker
2017-10-14T03:46:06.9102300Z ##[debug]Absolute path for pathSegments: C:\Users\MMSImgGenVM2017\AppData\Local\Microsoft\WindowsApps/docker = C:\Users\MMSImgGenVM2017\AppData\Local\Microsoft\WindowsApps\docker
2017-10-14T03:46:06.9112304Z ##[debug]Absolute path for pathSegments: C:\Program Files\Python36/docker = C:\Program Files\Python36\docker
2017-10-14T03:46:06.9112304Z ##[debug]Absolute path for pathSegments: C:\Users\MMSImgGenVM2017\AppData\Local\Microsoft\WindowsApps/docker = C:\Users\MMSImgGenVM2017\AppData\Local\Microsoft\WindowsApps\docker
2017-10-14T03:46:06.9112304Z ##[debug]Absolute path for pathSegments: C:\Users\MMSImgGenVM2017\AppData\Local\Microsoft\WindowsApps/docker = C:\Users\MMSImgGenVM2017\AppData\Local\Microsoft\WindowsApps\docker
2017-10-14T03:46:06.9112304Z ##[debug]Absolute path for pathSegments: C:\Program Files\Docker/docker = C:\Program Files\Docker\docker
2017-10-14T03:46:06.9112304Z ##[debug]check path : C:\Program Files\Docker\docker.exe
2017-10-14T03:46:06.9112304Z ##[debug]docker=C:\Program Files\Docker\docker.exe
2017-10-14T03:46:06.9112304Z ##[debug]dockerHostEndpoint=null
2017-10-14T03:46:06.9122301Z ##[debug]action=Build an image
2017-10-14T03:46:06.9152292Z ##[debug]C:\Program Files\Docker\docker.exe arg: build
2017-10-14T03:46:06.9162302Z ##[debug]dockerFile=d:\a\1\a\**\Dockerfile-Publish
2017-10-14T03:46:06.9182294Z ##[debug]Pattern found in docker filepath parameter
2017-10-14T03:46:06.9182294Z ##[debug]System.DefaultWorkingDirectory=d:\a\1\s
2017-10-14T03:46:06.9182294Z ##[debug]findPath: 'd:\a\1\s'
2017-10-14T03:46:06.9182294Z ##[debug]findOptions.followSpecifiedSymbolicLink: 'true'
2017-10-14T03:46:06.9182294Z ##[debug]findOptions.followSymbolicLinks: 'true'
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s (directory)
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s\.git (directory)
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s\.git\config (file)
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s\.git\description (file)
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s\.git\FETCH_HEAD (file)
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s\.git\HEAD (file)
2017-10-14T03:46:06.9202298Z ##[debug]  d:\a\1\s\.git\hooks (directory)
2017-10-14T03:46:06.9292283Z ##[debug]  d:\a\1\s\.gitignore (file)
[truncated]
2017-10-14T03:46:06.9292283Z ##[debug]  d:\a\1\s\nuget.config (file)
2017-10-14T03:46:06.9292283Z ##[debug]  d:\a\1\s\README.md (file)
2017-10-14T03:46:06.9292283Z ##[debug]  d:\a\1\s\src (directory)
2017-10-14T03:46:06.9302295Z ##[debug]  d:\a\1\s\src\docker-compose.ci.build.yml (file)
2017-10-14T03:46:06.9302295Z ##[debug]  d:\a\1\s\src\docker-compose.dcproj (file)
2017-10-14T03:46:06.9302295Z ##[debug]  d:\a\1\s\src\docker-compose.override.yml (file)
2017-10-14T03:46:06.9302295Z ##[debug]  d:\a\1\s\src\docker-compose.yml (file)
2017-10-14T03:46:06.9302295Z ##[debug]  d:\a\1\s\src\InitialProcessor.sln (file)
2017-10-14T03:46:06.9302295Z ##[debug]  d:\a\1\s\src\Spectre.Configuration (directory)
2017-10-14T03:46:06.9312287Z ##[debug]  d:\a\1\s\src\Spectre.Configuration\bin (directory)
2017-10-14T03:46:06.9312287Z ##[debug]  d:\a\1\s\src\Spectre.Configuration\bin\release (directory)
2017-10-14T03:46:06.9312287Z ##[debug]  d:\a\1\s\src\Spectre.Configuration\bin\release\netstandard2.0 (directory)
2017-10-14T03:46:06.9322287Z ##[debug]  d:\a\1\s\src\Spectre.Configuration\bin\release\netstandard2.0\publish (directory)
[truncated]
2017-10-14T03:46:07.0212244Z ##[debug]  d:\a\1\s\src\Spectre.InitialProcessor.TestConsole\Dockerfile (file)
2017-10-14T03:46:07.0212244Z ##[debug]  d:\a\1\s\src\Spectre.InitialProcessor.TestConsole\Dockerfile-Publish (file)
[truncated]
2017-10-14T03:46:07.0222242Z ##[debug]  d:\a\1\s\src\Spectre.InitialProcessor.TestConsole\Program.cs (file)
2017-10-14T03:46:07.0222242Z ##[debug]  d:\a\1\s\src\Spectre.InitialProcessor.TestConsole\Spectre.InitialProcessor.TestConsole.csproj (file)
2017-10-14T03:46:07.0222242Z ##[debug]389 results
2017-10-14T03:46:07.0222242Z ##[debug]patternRoot: 'd:\a\1\s'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.debug: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.nobrace: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.noglobstar: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.dot: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.noext: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.nocase: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.nonull: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.matchBase: 'true'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.nocomment: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.nonegate: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]matchOptions.flipNegate: 'undefined'
2017-10-14T03:46:07.0222242Z ##[debug]pattern: 'd:\a\1\a\**\Dockerfile-Publish'
2017-10-14T03:46:07.0222242Z ##[debug]expanding braces
2017-10-14T03:46:07.0222242Z ##[debug]pattern: 'd:/a/1/a/**/Dockerfile-Publish'
2017-10-14T03:46:07.0222242Z ##[debug]applying include pattern against original list
2017-10-14T03:46:07.0222242Z ##[debug]0 matches
2017-10-14T03:46:07.0222242Z ##[debug]0 final results
2017-10-14T03:46:07.0222242Z ##[debug]task result: Failed
2017-10-14T03:46:07.0222242Z ##[error]Unhandled: No Docker file matching  d:\a\1\a\**\Dockerfile-Publish  was found.
2017-10-14T03:46:07.0222242Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: No Docker file matching  d:\a\1\a\**\Dockerfile-Publish  was found.
2017-10-14T03:46:07.0222242Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: No Docker file matching  d:\a\1\a\**\Dockerfile-Publish  was found.
2017-10-14T03:46:07.0312247Z ##[section]Finishing: Build an image
```

**Comment by bansalaseem** [comment] 2017-10-16 10:39
>> Is the docker task trying to find this pattern inside the source directory?

That's correct. It is trying to find it in the default working directory which is source directory. 

_2017-10-14T03:46:06.9182294Z ##[debug]System.DefaultWorkingDirectory=d:\a\1\s_

**Comment by MikeYeager** [comment] 2017-10-25 23:05
I am having a very similar problem. I created a small .NET Core Docker App for Linux and published and tested it. Then I configured CI in the Azure Portal. First just Docker Container CI, which didn't seem to work at all. Then I configured regular CI. Attached is the .zip file with all of the logs from the failed build.

[logs_3.ziVSTS_DockerBuildLogs.zip](https://github.com/Microsoft/vsts-tasks/files/1416455/logs_3.ziVSTS_DockerBuildLogs.zip)

**Comment by bansalaseem** [comment] 2017-10-26 12:54
Mike, Can you please run the build with System.Debug as true (see this [link](http://blog.devmatter.com/enabling-verbose-output-in-team-foundation-build-logs/) and share the debug logs so that they contain more details?

**Comment by jikuma** [comment] 2017-10-26 13:05
Mike can u check if the docker file input is **\Dockerfile, For linux i think it should be **/Dockerfile.

**Comment by MikeYeager** [comment] 2017-10-26 19:21
We had to delete everything yesterday after a few attempts to fix it. Unfortunately, I'm now running into a different problem. We re-published the app as a new Linux App Service with a new container registry entry and got it all working. (The VS dialog for publishing to Linux has a lot of issues, but that's another story for another day.) This time, I did not go into the Docker Container blade in the App Service, I just went into the Continuous Delivery (Preview) blade and set it up. When I try to create the build definition I get this error, "Failed to configure Continuous Delivery. Error: Setup Continuous Delivery job call failed with error TFS.WebApi.Exception: The Image field is required. Parameter name: provisioningConfiguration.Source.BuildConfiguration.Image." Sounds easy enough to fix, however the image box is read-only. I've attached a photo. I also tried to change the '\' to a '/' as mentioned above, but this dialog does not like the forward slash and gives me an error. I can try editing the slash later if I can get the build created again.
![ci-issue](https://user-images.githubusercontent.com/7063813/32072661-f885aabc-ba58-11e7-8c11-866a2e57a614.png)

**Comment by sachinma** [comment] 2017-11-21 09:06
@aydey can you look at it

**Comment by ds-ms** [comment] 2017-11-21 12:55
Mike, it might be the case because the "linuxFxVersion" is not set for the web app, which might be an issue with old web app. Azure recently made a change following which the image and tag value gets stored in a different property, namely “linuxFxVersion”. 
Can you try using a new web app, or can you try to shuffling the docker container type in Docker Container blade for the existing web-app. If it still doesn't work out can you please open the Resource Explorer blade, follow the link and then update the “linuxFxVersion” property under config->web to the a value in the format “DOCKER|<image_name>:<tag>

**Comment by MikeYeager** [comment] 2017-11-21 18:57
Deepak,

No luck with the work-arounds so I re-created the app service and tried again. I think that the original issue is fixed. I am still getting this error:
Starting: Build an image
******************************************************************************
==============================================================================
Task         : Docker
Description  : Build, tag, push, or run Docker images, or run a Docker command. Task can be used with Docker or Azure Container registry.
Version      : 0.3.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
==============================================================================
7c6439c8-6a44-407f-a42c-958cf72e93cd exists true
Unhandled: No Docker file matching /opt/vsts/work/1/s/**\Dockerfile was found.

I’ve attached the full set of logs.

I think that has to do with having a Solution that has 2 service projects where the source code is in the same Git repository. I’ve been told that doesn’t work. For now I’m manually publishing each service from Visual Studio to the same service plan.

I suppose I could create a Git repository for each service and put each service in its own Solution to get around this. Please let me know if multiple projects CI is supported at some point.

Thanks,
Mike Yeager
CEO and Senior Developer
EPS Software & CODE Consulting
My Bio<http://codemag.com/People/bio/Mike.Yeager>
Seen our videos? CODE Consulting<http://codemag.com/videos/play/consulting> and CODE Staffing<http://codemag.com/videos/play/staffing>

**Comment by sachinma** [comment] 2017-12-06 11:28
@MikeYeager, we ask for the path to the Dockerfile. So you can have multiple Dockerfiles one per service project; and you can provide the path to the Dockerfile when configuring the Continuous Delivery. I think the  current failure is due to the fact that the pattern was not found in the repo, it could be related to the forward vs backward slash. Can you try with the **/Dockerfile or the exact path to the docker file.

**Comment by MikeYeager** [comment] 2017-12-06 20:28
@sachinma, thanks for your reply. I've been told that CD does not support multiple Docker Projects in a solution since the source code is all in the same repository. A check-in would have to trigger deployment of all service projects. As for the forward vs back slash issue, I have tried it both ways with the same result.

**Comment by sachinma** [comment] 2017-12-07 05:23
You cannot configure multiple services in a single go with CD experience in Azure since that is pivoted around a single App Service. However, you can try by providing the full path to the Dockerfile of the service that you want to deploy on a given app service - that should work. Let me know if you get any error with that.

**Comment by sachinma** [comment] 2018-01-02 06:53
@MikeYeager Just reconfirming if you were able to work by providing the full path to the dockerfile.

**Comment by MikeYeager** [comment] 2018-01-02 16:32
@sachinma No, I never was able to get it working with multiple Docker Projects in a solution, even when I provided the full path to one of the dockerfiles. Although, I wonder at this point if that may have been caused by all of the mucking around with it. Unfortunately, I'm not in a position to tear it all down and re-create it to try that, but as thing stand I was not able to get it to work.

**Comment by sachinma** [comment] 2018-02-12 07:04
I am closing this issue. Reopen once you try it again and still run into this issue.

**Closed by sachinma** 2018-02-12 07:04 UTC
Labels: Area: Release

**Comment by ishafqat** [comment] 2018-06-05 08:05
I had the same issue. The docker compose file was not checked in for my solution which caused this error. Adding the file back solved it for me.

**Comment by patware** [comment] 2020-08-20 16:50
In my case, the problem was case sensitivity.  The agent was unix based which is case sensitive.  [Dockerfile].

**Comment by laazik** [comment] 2021-01-23 22:28
For those who are struggling with single solution multi project build setup in Azure pipeline for Docker. I had exactly the same issue, and if you look into the command line that the build server gives out you can see that it tries, by default, to make a build in the project directory.

So to fix this, you most likely need to add a `buildContext: $(Build.SourcesDirectory)` to the actual build file. This forces the Docker context to e.g. Solution level (because the Dockerfile copy commands are based on the solution level directory).

Probably worth adding to somewhere in the comments or smth.

**Comment by Laasya-07** [comment] 2021-12-28 16:37
I faced the same issue and it got fixed by changing the "Task version" in the build pipeline to "2.*". By default it was 0.

**Comment by Daniel-Krzyczkowski** [comment] 2022-12-16 12:37
> For those who are struggling with single solution multi project build setup in Azure pipeline for Docker. I had exactly the same issue, and if you look into the command line that the build server gives out you can see that it tries, by default, to make a build in the project directory.
> 
> So to fix this, you most likely need to add a `buildContext: $(Build.SourcesDirectory)` to the actual build file. This forces the Docker context to e.g. Solution level (because the Dockerfile copy commands are based on the solution level directory).
> 
> Probably worth adding to somewhere in the comments or smth.

It works, thank you so much for help!!!
