### ISSUE TITLE
Build fails after restoring nuget packages

### ISSUE THREAD

**Issue by mobius127** [Microsoft/vsts-tasks#5554] opened 2017-10-04 08:22 UTC
Hi there, 

My builds fails always after restoring nuget packages. In build step is trying to get references from GAC and then from packages folder but It fails.

I found the "optional" option "Destination Directory" but it doesn't works:

2017-10-04T08:17:02.9151536Z ResolveAssemblyReferences:
2017-10-04T08:17:02.9151536Z   Primary reference "log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL".
2017-10-04T08:17:02.9261532Z ##[warning]C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
2017-10-04T08:17:02.9261532Z C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [d:\a\1\s\Sogeti.Core.Log4Net\Sogeti.Core.Log4Net.csproj]
2017-10-04T08:17:02.9261532Z           For SearchPath "{HintPathFromItem}".
2017-10-04T08:17:02.9261532Z           Considered "..\packages\log4net.2.0.8\lib\net45-full\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9261532Z           For SearchPath "{TargetFrameworkDirectory}".
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\Facades\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9261532Z           For SearchPath "{Registry:Software\Microsoft\.NETFramework,v4.6.1,AssemblyFoldersEx}".
2017-10-04T08:17:02.9261532Z           Considered AssemblyFoldersEx locations.
2017-10-04T08:17:02.9261532Z           For SearchPath "{AssemblyFolders}".
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\140\SDK\Assemblies\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\140\SDK\Assemblies\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9261532Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\140\SDK\Assemblies\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9271533Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\110\SDK\Assemblies\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9271533Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\110\SDK\Assemblies\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9271533Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\110\SDK\Assemblies\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9271533Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\100\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9271533Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\100\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9271533Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\100\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files\IIS\Microsoft Web Deploy V3\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.0\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\120\SDK\Assemblies\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9381528Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\120\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\120\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\120\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\110\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\110\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft.NET\ADOMD.NET\110\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\130\SDK\Assemblies\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\WiX Toolset v3.10\SDK\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\WiX Toolset v3.10\SDK\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\WiX Toolset v3.10\SDK\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\100\SDK\Assemblies\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\100\SDK\Assemblies\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "C:\Program Files (x86)\Microsoft SQL Server\100\SDK\Assemblies\log4net.exe", but it didn't exist.
2017-10-04T08:17:02.9391530Z           For SearchPath "{GAC}".
2017-10-04T08:17:02.9391530Z           Considered "log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL", which was not found in the GAC.
2017-10-04T08:17:02.9391530Z           For SearchPath "{RawFileName}".
2017-10-04T08:17:02.9391530Z           Considered treating "log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL" as a file name, but it didn't exist.
2017-10-04T08:17:02.9391530Z           For SearchPath "bin\Release\".
2017-10-04T08:17:02.9391530Z           Considered "bin\Release\log4net.winmd", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "bin\Release\log4net.dll", but it didn't exist.
2017-10-04T08:17:02.9391530Z           Considered "bin\Release\log4net.exe", but it didn't exist.

**Comment by mobius127** [comment] 2017-10-04 08:23
![image](https://user-images.githubusercontent.com/16031601/31166176-20263c98-a8ee-11e7-9c49-d0a546ee66fc.png)

**Comment by mobius127** [comment] 2017-10-04 09:15
My build finally works disabling NuGet Restore 2.0 and put another one with version 0:

![image](https://user-images.githubusercontent.com/16031601/31168286-2494efca-a8f5-11e7-99d0-58596006b385.png)

![image](https://user-images.githubusercontent.com/16031601/31168320-3ec09da4-a8f5-11e7-8003-f46a9f794244.png)

**Comment by chrisrpatterson** [comment] 2017-10-04 12:42
@mobius127 what pool are you building against? 
What version of Visual Studio is your solution built with?

**Comment by mobius127** [comment] 2017-10-04 13:22
I'm working with Visual Studio 2015 Update 3.

The pool, if i'm understanding you is .NET Desktop

![image](https://user-images.githubusercontent.com/16031601/31177945-c78a6486-a917-11e7-9342-9d8e6fcabdcd.png)

The solution is a group of .net libraries built in 4.6.1 framework.

**Comment by mobius127** [comment] 2017-10-04 13:29
if you want a copy of one of .csproj files. Ill put you here the xml:

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{A3EDAA4C-3CA4-4A5C-B2A9-B3C4BDB473AC}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>Sogeti.Core.Log4Net</RootNamespace>
    <AssemblyName>Sogeti.Core.Log4Net</AssemblyName>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <TargetFrameworkProfile />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <RunCodeAnalysis>true</RunCodeAnalysis>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="log4net, Version=2.0.8.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a, processorArchitecture=MSIL">
      <HintPath>..\packages\log4net.2.0.8\lib\net45-full\log4net.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Log4NetLogger.cs" />
    <Compile Include="Log4NetManager.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sogeti.Core\Sogeti.Core.csproj">
      <Project>{d5199253-dd6f-4b95-b32b-62eac2775737}</Project>
      <Name>Sogeti.Core</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
    <None Include="Sogeti.Core.Log4Net.nuspec">
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  
</Project>

**Comment by mobius127** [comment] 2017-10-04 13:34
This is one of my .csproj with log4net dependency

![image](https://user-images.githubusercontent.com/16031601/31178446-66ef49a0-a919-11e7-80cc-acf9f3600908.png)

**Comment by mobius127** [comment] 2017-10-07 15:35
I have another problem....

All of packages of my libraries, NuGet Pack allways mark them in preview....

**Comment by alexmullans** [comment] 2017-10-08 12:22
If you're using the automatic package versioning features, that's currently by design. Each automatic option uses the `-prerelease` part of the Semantic Version of the NuGet package (e.g. `1.0.0-beta` or `1.0.0-20171008.1`), so NuGet considers the package as in preview.

**Comment by aldoms** [comment] 2017-10-11 22:15
@mobius127, what did the logs look like when you were restoring using version 2.x of the NuGet task?

**Comment by mobius127** [comment] 2017-10-11 22:37
The restore task always is fine. But building task always fails because VSTS can't find packages previously restored by Nuget restore task

**Comment by aldoms** [comment] 2017-10-11 22:44
But does it actually restore the packages? If so, then it's just a placing problem so that the build step can find the packages that were actually restored.

**Comment by mobius127** [comment] 2017-10-12 18:07
If you look at the building log it fails whatever you do at Night restore because I fix the location problem and it still fails.

**Comment by phil-hodgson** [comment] 2017-11-17 01:51
@mobius127  Could you share the portions of the build logs where a) the packages are being restored, and b) where compilation is looking for the packages (but failing to find them)? It would be useful to see the actual paths that are being used.

**Comment by keithrob** [comment] 2018-02-19 21:09
Closing.  Reopen as needed.

**Closed by keithrob** 2018-02-19 21:09 UTC
Labels: Area: Packaging
