### ISSUE TITLE
Deploy Test Agent Task Fails if Windows Firewall is turned off.

### ISSUE THREAD

**Issue by ChrisMenegay** [Microsoft/vsts-tasks#4640] opened 2017-06-27 02:54 UTC
For the **Deploy Test Agent Task,** If windows firewall is turned off on the target machine, then the task just crashes.  Here's a snippet from the log.

2017-06-27T00:19:15.9167452Z 
2017-06-27T00:19:15.9167452Z [1234-POS1]    at Microsoft.VisualStudio.TestTools.ConfigCore.BaseConfiguration.RemoveFirewallExceptionIfPresent(FirewallExceptionDataPacket[] applications, DelegateStatusUpdate progressListener)
2017-06-27T00:19:15.9167452Z 
2017-06-27T00:19:15.9167452Z [1234-POS1] V, 2017/06/26, 19:19:15.485, 		Firewall exception could not be removed for application(s) 'Microsoft Visual Studio Test Agent Service'.
2017-06-27T00:19:15.9167452Z 
2017-06-27T00:19:15.9167452Z [1234-POS1] E, 2017/06/26, 19:19:15.485, System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
2017-06-27T00:19:15.9167452Z 
2017-06-27T00:19:15.9167452Z [1234-POS1]    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
2017-06-27T00:19:15.9167452Z 
2017-06-27T00:19:15.9167452Z [1234-POS1]    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
2017-06-27T00:19:15.9167452Z 
2017-06-27T00:19:15.9167452Z [1234-POS1]    at System.String.Format(IFormatProvider provider, String format, Object[] args)

**Comment by dpksinghal** [comment] 2017-06-28 17:50
we are working on this over mail with ChrisMenegay.

**Comment by dpksinghal** [comment] 2017-07-04 06:18
This is by design. Chris was able to make it work using a workaround of enabling the firewall and disabling it later. Closing this thread.

**Closed by dpksinghal** 2017-07-04 06:18 UTC
Labels: Area: Test
