### ISSUE TITLE
Azure Function deploy fails with The user name or password is incorrect

### ISSUE THREAD

**Issue by federicoD** [Microsoft/vsts-tasks#6513] opened 2018-02-26 02:19 UTC
## Environment

I'm using VSTS

- Account name: stamp-dev 
- Release name: Stamp BigBro
- Release number: BigBro-Dev-30
- Agent: Hosted Agent (2.129.1)

## Issue Description

I use Azure Service App Deploy to deploy an Azure Function to my Azure environment, and I keep on getting an error saying that username & password are incorrect.

If I delete the Azure Function and I create it again, the deployment works the first one/two times, than I get the same error.

### Error logs

2018-02-26T00:23:18.1593970Z ##[error]Failed to deploy web package to App Service.
2018-02-26T00:23:18.1611382Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to deploy web package to App Service.
2018-02-26T00:23:18.1612518Z ##[debug]{}
2018-02-26T00:23:18.1613194Z ##[debug]System.DefaultWorkingDirectory=D:\a\r1\a
2018-02-26T00:23:18.1618200Z ##[error]Error: (2/26/2018 12:23:18 AM) An error occurred when the request was processed on the remote computer.
Error: The user name or password is incorrect.

   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)
   at Microsoft.Web.Deployment.DirectoryEx.CreateDirectory(String path)
   at Microsoft.Web.Deployment.DirectoryEx.CreateDirectoriesFromRoot(String path)
   at Microsoft.Web.Deployment.AppOfflineRuleHandler.AddAppOfflineFilesToEachApp(DeploymentBaseContext baseContext, Boolean whatIf)
   at Microsoft.Web.Deployment.AppOfflineRuleHandler.Add(DeploymentSyncContext syncContext, DeploymentObject destinationObject, DeploymentObject& sourceObject, Boolean& proceed)
   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAdd(DeploymentObject destObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)
   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)
   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)
   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)
Error count: 1.

2018-02-26T00:23:18.1622543Z ##[debug]Processed: ##vso[task.issue type=error;]Error: (2/26/2018 12:23:18 AM) An error occurred when the request was processed on the remote computer.%0D%0AError: The user name or password is incorrect.%0D%0A%0D%0A   at Microsoft.Web.Deployment.NativeMethods.RaiseIOExceptionFromErrorCode(Win32ErrorCode errorCode, String maybeFullPath)%0D%0A   at Microsoft.Web.Deployment.DirectoryEx.CreateDirectory(String path)%0D%0A   at Microsoft.Web.Deployment.DirectoryEx.CreateDirectoriesFromRoot(String path)%0D%0A   at Microsoft.Web.Deployment.AppOfflineRuleHandler.AddAppOfflineFilesToEachApp(DeploymentBaseContext baseContext, Boolean whatIf)%0D%0A   at Microsoft.Web.Deployment.AppOfflineRuleHandler.Add(DeploymentSyncContext syncContext, DeploymentObject destinationObject, DeploymentObject& sourceObject, Boolean& proceed)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.HandleAdd(DeploymentObject destObject, DeploymentObject sourceObject)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenNoOrder(DeploymentObject dest, DeploymentObject source)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildrenOrder(DeploymentObject dest, DeploymentObject source)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.SyncChildren(DeploymentObject dest, DeploymentObject source)%0D%0A   at Microsoft.Web.Deployment.DeploymentSyncContext.ProcessSync(DeploymentObject destinationObject, DeploymentObject sourceObject)%0D%0A   at Microsoft.Web.Deployment.DeploymentObject.SyncToInternal(DeploymentObject destObject, DeploymentSyncOptions syncOptions, PayloadTable payloadTable, ContentRootTable contentRootTable, Nullable`1 syncPassId, String syncSessionId)%0D%0A   at Microsoft.Web.Deployment.DeploymentAgent.HandleSync(DeploymentAgentAsyncData asyncData, Nullable`1 passId, String user, String siteName)%0D%0AError count: 1.%0D%0A
2018-02-26T00:23:18.1625647Z ##[debug]rm -rf D:\a\r1\a\error.txt
2018-02-26T00:23:18.1626072Z ##[debug]removing file
2018-02-26T00:23:18.1626432Z ##[debug]task result: Failed
2018-02-26T00:23:18.1627049Z ##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295

**Comment by markbeij** [comment] 2018-02-27 06:56
I'm having the exact same problem. Tried Reset publish credentials, but that didn't help either.

**Comment by markbeij** [comment] 2018-02-27 08:35
Download app content doesn't work either:

The user name or password is incorrect.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.IO.IOException: The user name or password is incorrect.

**Comment by vincentdass** [comment] 2018-02-27 09:03
@federicoD , @markbeij , Can you please share the app names in [private](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)?

Also, share the MSDeploy command from the logs.

**Comment by pmatwiejuk** [comment] 2018-02-28 08:14
Same here, and what's more - I can't even access Kudu:
![image](https://user-images.githubusercontent.com/6411501/36776823-756c6ff0-1c67-11e8-829d-b1981aa9e878.png)

I think that problem is connected somehow with the "Slots", as before enabling that I didn't have any problems like that.

**Comment by vincentdass** [comment] 2018-02-28 08:34
@pmatwiejuk , Please share the app name in [private](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by ahmelsayed** [comment] 2018-02-28 15:54
This error usually happens if you delete or regenerate the keys for the storage account associated with the function app. The one defined in the `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` App Settings for the functionapp.

If you deleted that storage account, you can try recreating it and updating the app settings that point to it. Check for `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`, `AzureWebJobsDashboard`, `AzureWebJobsStorage`

If you just regenerated the keys for that account, then update the connection strings in the App Settings for your app.

**Comment by federicoD** [comment] 2018-03-06 06:58
@ahmelsayed I've a task to add variables to the AppSettings, but the task removes all the variables so I'm missing `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`, `AzureWebJobsDashboard` and `AzureWebJobsStorage`. Do you think that could be the problem?

**Comment by federicoD** [comment] 2018-03-06 07:37
So my problem was due to the fact that the task for replacing the variables was deleting `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING`. So the first time VSTS was able to deploy because the variables where there, the task to set the variables was executed after...so the second time it was failing because of the missing variables.

**Comment by vincentdass** [comment] 2018-03-06 09:18
@federicoD , You can also use Azure App Service Deploy task to update the App Settings / configuration settings. This might reduce the complexity of other task that removes the old value.
![image](https://user-images.githubusercontent.com/20121508/37023835-24daa90e-214d-11e8-8ec8-3295f5506052.png)

To resolve the current issue, you can refer to [this thread](https://social.msdn.microsoft.com/Forums/windowsserver/en-US/4513a2b0-864b-4f30-a74b-d4b843e3b48a/how-to-manage-app-settings-in-azure-function-apps?forum=AzureFunctions).

Proposed answer from above thread:
![image](https://user-images.githubusercontent.com/20121508/37023863-3a94d5b2-214d-11e8-9aa9-b39f05cf13ad.png)

**Comment by markbeij** [comment] 2018-03-06 09:42
Same problem here, I'm using Apply variables to Azure webapp from Pascal Naber (Xpirit)
There is a checkbox 'Overwrite existing configuration' which you should carefully consider

![image](https://user-images.githubusercontent.com/20302465/37024987-c51975b2-212a-11e8-92ec-a967db6a4128.png)

**Comment by vincentdass** [comment] 2018-03-06 10:31
@markbeij , is the issue resolved once you regenerated the keys?

**Comment by markbeij** [comment] 2018-03-07 10:22
Yes

**Comment by vincentdass** [comment] 2018-03-08 06:03
Closing the issue, as the issue is resolved.
You can update the App Settings / Config settings using App Service Deploy task.

**Closed by vincentdass** 2018-03-08 06:03 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by zorkind** [comment] 2018-08-26 16:07
I just want to say that the CONTENT_SHARE and the other connectionstring setting is ONLY for CONSUMPTION plans!

As stated in this artigo:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsstorage

If you apply this settings on a diff plan, your App will stop working.

**Comment by euangordon** [comment] 2019-10-23 15:03
I have been having the same issues here today. After reading the above and the troubleshooting issues document I know what I have done wrong, but it would be nice if the error handling on publish provided a meaningful error and also the Azure Portal could do some validation to stop you from removing required configuration settings. I normally created Azure Functions using my Web App resources, but today ran out of available resources so made one under the consumption plan. I copied my configuration from an existing Azure Function, which caused the issue.
