### ISSUE TITLE
cURL upload files: Unhandled: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by suhu** [Microsoft/vsts-tasks#1914] opened 2016-06-21 12:54 UTC
Hello,

I am trying to use the release management in VSTS to deploy a Angular website to Azure web app. I managed to get a build with Gulp and NPM tasks and produce a artifact. The artifact is not a zip file but gulp distribution folder. I am try to ftp the files with cURL build task. But it fails with this exception. I guess it is because there are many files and argument is too long. But what are my options to pass these file names as parameters to the cURL task? Or is there a better way to achieve what I want?

**Comment by suhu** [comment] 2016-06-21 12:58
[command]curl -T {C:/a/8e99rop/...owser/styles.css} {ftp url} --stderr - -u {username}:{password} 
 ##[debug]task result: Failed 
 ##[error]Unhandled: spawn EAMETOOLONG 
 Finishing task: cURLUploader

**Comment by jasholl** [comment] 2016-06-21 13:00
I've got just the thing for you -- it's still in development, and subject to change, but if you're up for giving this new FTP Upload task a try, it can upload entire folder structures.  https://github.com/Microsoft/vsts-tasks/pull/1899

**Comment by suhu** [comment] 2016-06-21 14:17
I am happy to give it a try. Is this in the market place extension already?

**Comment by jasholl** [comment] 2016-06-21 14:35
No, the ftp task is not available yet; you would need to build it yourself by cloning this git repo, checking out the branch mentioned in the above PR which contains the ftp task, build it locally, and then install the ftp task to your account using the tfx command line utility. If you haven't done this before, it might be a bit cumbersome.

Back to your cUrl issue -- yes, based on your description, it sounds like there are too many parameters arguments (I've run into this exact sort of problem before with other tasks).  Can you confirm that's the issue by uploading just a few files?  If that's the issue, I can't think of anything to suggest other than splitting your uploads up to several cUrl calls.

**Comment by suhu** [comment] 2016-06-21 14:38
Ok. I am uploading close to 800 files. I will try to upload a couple of files and see if it works. I will also try using the tfx command and see where I get. 

What is the best approach to deploy just a javascript application to Azure web app along with the release management in VSTS?

**Comment by jasholl** [comment] 2016-06-21 15:22
Have you tried the Azure Deployment tasks, or the Azure File Copy task?  These seem like they might do exactly what you need to do.  Also, I found this article which might help: https://azure.microsoft.com/en-us/documentation/articles/cloud-services-continuous-delivery-use-vso/

**Comment by suhu** [comment] 2016-06-22 05:40
As I don't have a VS solution file in this project, not sure we can use the Azure Web App Deployment task. With Azure File Copy task, can you copy files to Web APP Service too?

I will try the Ftp task today. Do you have any doc of how to use the tfx command line utility?

**Comment by jasholl** [comment] 2016-06-22 15:46
I have to admit, I'm not familiar with the Azure Web App Deployment task, so I don't know.

This should get you started with tfx: [https://github.com/Microsoft/tfs-cli](https://github.com/Microsoft/tfs-cli)
There are only a few commands you'll need.  First you'll need to login to your account, e.g.
C:\git\github\vsts-tasks-ftp>tfx login
TFS Cross Platform Command Line Interface v0.3.19
Copyright Microsoft Corporation
> Service URL: https://jasholl.visualstudio.com/DefaultCollection
https://jasholl.visualstudio.com/DefaultCollection
> Personal access token:
Logged in successfully

Once you build the FTP Upload task, then you'll need to upload it:
C:\git\github\vsts-tasks-ftp>tfx build tasks upload --task-path _build\Tasks\FtpUpload
TFS Cross Platform Command Line Interface v0.3.19
Copyright Microsoft Corporation

Task at C:\git\github\vsts-tasks-ftp\_build\Tasks\FtpUpload uploaded successfully!

**Comment by yacaovsnc** [comment] 2016-09-01 19:16
FTP task has been released and should be used to upload folders.  Duplicate of #995.

**Closed by yacaovsnc** 2016-09-01 19:16 UTC
Labels: Area: Java, Dev15
