### ISSUE TITLE
Azure File Copy Task does not work well in task group

### ISSUE THREAD

**Issue by joe45sp** [Microsoft/vsts-tasks#5600] opened 2017-10-10 15:39 UTC
When having this task in the task group, it automatically creates the output variables for URI and token as a parameter for the task group. Since it becomes a parameter, I need to set a default value such as "" on the release definition. This then keeps the variables as "" and the azure file copy task does not override the values in these variables.

**Comment by joe45sp** [comment] 2017-10-13 20:55
An update on this. Even if the parameter has a value such as test or "test" it does not override the value in this logic:

`# Get URI and SaSToken for output if needed
    if(-not [string]::IsNullOrEmpty($outputStorageURI))
    {
        $storageAccountContainerURI = $storageContext.BlobEndPoint + $containerName
        Write-Host "##vso[task.setvariable variable=$outputStorageURI;]$storageAccountContainerURI"
    }
    if(-not [string]::IsNullOrEmpty($outputStorageContainerSASToken))
    {
        $storageContainerSaSToken = New-AzureStorageContainerSASToken -Container $containerName -Context $storageContext -Permission r -ExpiryTime (Get-Date).AddHours($defaultSasTokenTimeOutInHours)
        Write-Host "##vso[task.setvariable variable=$outputStorageContainerSASToken;]$storageContainerSasToken"
    }`

**Comment by Ajay-MS** [comment] 2017-10-17 13:33
@joe45sp 

Apologize for replying late on this thread. The issue is because since variable has already got defined in task group and below cmdlet only creates a variable if it doesn't exist. 

"##vso[task.setvariable variable=$outputStorageURI;] 

I am currently looking into this issue will update you soon with the fix.

**Comment by sureshtadisetty** [comment] 2017-10-24 09:23
@joe45sp could you please try pass value as $(outputStorageURI) instead of "" for outputStorageURI taskgroup input parameter in ReleaseDefinition?

**Comment by sureshtadisetty** [comment] 2017-10-27 06:53
@joe45sp  I hope your issue is resolved now. Please let us know if you need any more info. I'm closing this issue now.

**Closed by sureshtadisetty** 2017-10-27 06:53 UTC
Labels: Area: Release

**Comment by joe45sp** [comment] 2017-10-30 21:11
@sureshtadisetty This works now, thank you!!!
