### ISSUE TITLE
Having issue with timeline not updating as complete when using ##vso[task.logdetail

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-tasks#2188] opened 2016-08-02 15:48 UTC
Here's a basic example. I tried to get TFS 2015 Update 3 - On Premise to start logging to a timeline to show progress on powershell actions easily. Not seeing the steps being marked as complete. Not sure if this is an issue, or incorrect syntax usage by me.  Any help appreciated, and if there is a more appropriate forum for submitting this please direct me so I don't cause any issues. thanks

```
#POWERSHELL

#master guid
$MasterGuid =  [GUID]::NewGuid()
write-host "##vso[task.logdetail id=$MasterGuid;name=MasterTimelineStep;type=build;order=1]"

#individualstep on timeline, should finish work and then mark this complete
$StepGUID = [GUID]::NewGuid()
write-host "##vso[task.logdetail id=$StepGUID;name=Initializing Environment;type=build;order=1]Setup the environment with variables"

#do stuff, and then update as complete

#should mark the "nested timeline record" as completed, with green checkmark
write-host "##vso[task.logdetail id=$StepGUID;state=Completed;Result=Succeeded"
$StepGUID = $null

#should identify master step as done
write-host "##vso[task.logdetail id=$MasterGuid;state=Completed;Result=Succeeded"
```

**Comment by ericsciple** [comment] 2016-08-28 05:06
@TingluoHuang  would know offhand.

**Comment by stephenmichaelf** [comment] 2017-11-16 14:08
@sheldonhull Not sure if this is the root cause but it looks like the closing bracket is missing? Can you try adding it.

Are you still having this issue?

**Closed** 2017-11-21 04:45 UTC
Labels: Area: Core
