### ISSUE TITLE
.testsettings deployments items not being

### ISSUE THREAD

**Issue by CodingInTheWoods** [Microsoft/vsts-tasks#8141] opened 2018-08-24 21:51 UTC
## Background
I am working on testing migration from a private TFS server (version 15.117.27024.0) to VSTS.  I have "transcribed" the build definition as close as possible to the original with a hand-full of minor modifications to fit the updated format.  The TFS version builds and tests without issues.  The VSTS version is failing to deploy items specified in the .testsettings file.

## Environment
- Server - VSTS    
- Build Agent - Private - OS: Win7, Agent.Version: 2.117.2
- Test Agent - Private - OS: Win10, Visual Studio Test Agent 2017 version:15.6.27428.2043

## Issue Description
Build is queued in VSTS and runs on private machines.  The definition includes coded UI tests that are executed using version 2 of the Visual Studio Test task.  A .testsettings file is specified with two <DeploymentItem> items...

![image](https://user-images.githubusercontent.com/42683278/44607328-b6a53680-a7b5-11e8-8681-6da3aaa11a52.png)

...when the task in the build executes the specified items are not being found in the _temp folder of the build agent.

![image](https://user-images.githubusercontent.com/42683278/44607442-113e9280-a7b6-11e8-9d80-429962811bfd.png)

The files are present in the sources directory but are not copied to the temp folder where the task seems to be looking.

![image](https://user-images.githubusercontent.com/42683278/44608231-b22e4d00-a7b8-11e8-9ffb-b1a6d8c1f55b.png)

When looking through the build logs and files being generated, it appears that the .testsettings file is being converted to a .tempsettings file which is being referenced by a generated .runsettings file.  I suspect that now with this .tempsettings file the deployment item paths being relative cause the task to look items in the _temp directory instead of the sources directory.

![image](https://user-images.githubusercontent.com/42683278/44608919-4c8f9000-a7bb-11e8-953e-6bf579da23e6.png)

Is there a setting that I am missing somewhere or should these deployment items be getting copied to the same location where the converted .testsettings file is being created?

Please let me know if you have any additional questions or if there is additional information you would like me to post to help with any understanding or troubleshooting.  Thanks for your help.

**Comment by CodingInTheWoods** [comment] 2018-08-27 21:44
In the meantime I've implemented a workaround where I modify the .testsettings deployment items with the absolute file path prior to testing so when these new files are generated they can find the deployment items.

**Comment by prawalagarwal** [comment] 2018-08-29 09:47
Hi @CodingInTheWoods , All your observations are correct about why these files are getting looked into temp folder. Unfortunately, this by design today (due to several reasons reported by other customers) and we recommend using the deployment item attribute with your tests to handle deployments if you cannot continue with absolute paths in the test settings file. Also you may want to start using run settings file instead of test settings file [https://github.com/Microsoft/vstest-docs/blob/master/RFCs/0023-TestSettings-Deprecation.md](url). Thanks!

**Comment by prawalagarwal** [comment] 2018-09-03 06:34
@CodingInTheWoods Can we close this issue? Can we help you with any additional information for your scenario?

**Comment by ShreyasRmsft** [comment] 2018-09-05 06:14
@CodingInTheWoods closing the issue. Pleaes re-open if you need any more assistance or info from our side. Thanks.

**Closed by ShreyasRmsft** 2018-09-05 06:14 UTC
Labels: Area: Test
