### ISSUE TITLE
Cannot generate an .ipa when using the xcode task with "specify" as export option

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/vsts-tasks#5719] opened 2017-10-27 11:26 UTC
Hello, 

I don't know if it is really an issue, or if i'm just not configuring the task correctly.

## Issue Description

When using the task with "specify" as "Export Options", the .plist generated by the task does not contain any provisioning profile, so on Xcode 9, Xcode fails with a message like "error: exportArchive: "....app" requires a provisioning profile."

## Environment
TFS 2015 Update 2 with latest Xcode task version 4.125.0, I know it is not officially supported, but at least in this version there is some code addressing Xcode 9 (I was on release 116 before I had to switch for that Xcode 9 issue).

Private agent on latest OSX with Xcode 9.0
 
PS : it seems related to that line of code : https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Xcode/xcode.ts#L302 (I don't know why that block would be accessible only for "manual", when using "specify", the team id / export method can be provided, but the mobile provision remains unknown, and so must be found by the task )

**Comment by madhurig** [comment] 2017-10-30 23:02
@LiohAu: "specify" is just a convenience option to pass in common properties that are required in the export options plist. We added it for Xcode 8 since users had to create the export options plist manually. The "required" list changed in Xcode 9 to include provisioning profiles. But with Xcode 9, when you run export via Xcode, it generates the exportOptions plist file. Can you commit that to your repo and pass that to the task?

Thanks,
Madhuri

**Comment by madhurig** [comment] 2017-12-17 22:47
Closing this issue since this is expected behavior. Let us know if you have trouble getting the "plist" option to work.

**Closed by madhurig** 2017-12-17 22:47 UTC
Labels: Area: CrossPlatform, Area: Mobile
