### ISSUE TITLE
AzureFileCopy cannot copy to $root container.

### ISSUE THREAD

**Issue by tabeth** [Microsoft/vsts-tasks#3322] opened 2016-12-29 02:26 UTC
```
Upload to container: '$root' in storage account: 'accountName' with blobprefix: '' failed with error: 'Azure Storage container names can only contain lowercase alpha-numeric characters or hyphens
Parameter name: containerName' For more info please refer to https://aka.ms/azurefilecopyreadme
```

**Comment by chshrikh** [comment] 2016-12-29 09:44
@tabeth by any chance have you provided $root as input for container. For container name special characters like $ are not supported

**Comment by rjygraham** [comment] 2017-01-09 05:45
@chshrikh I'm running into same issue. Please see Azure Storage documentation regarding the $root container: https://msdn.microsoft.com/en-us/library/azure/hh488356.aspx

**Comment by vincentdass** [comment] 2017-01-10 12:00
@tabeth , @rjygraham , thanks for reporting this issue. Its a genuine issue and will be fixed.

**Comment by RoopeshNair** [comment] 2017-01-30 11:42
We should support this. Can you please ensure that it works

**Comment by BhaskarDasari** [comment] 2017-03-06 12:11
@vincentdass @RoopeshNair  Hi Did you manage to fix this issue? i am running into the same issue..

Upload to container: '' in storage account: '' with blobprefix: '' failed with error: '' For more info please refer to https://aka.ms/azurefilecopyreadme

PS: I am using team services.. azure file copy task to upload file in to the blob container

**Comment by vincentdass** [comment] 2017-03-07 05:06
@BhaskarDasari , the fix is in progress.
For a workaround, please use other containers, until the issue is resolved.

**Comment by vincentdass** [comment] 2017-03-13 12:00
The issue is resolved and the fix will be available in upcoming deployment.

**Closed by vincentdass** 2017-03-13 12:00 UTC
Labels: Area: Release, bug

**Comment by modikumar** [comment] 2018-07-02 19:10
Is this been fixed? I still see this issue while trying to upload files to an already created blob container. 
![azurefilecopyerror](https://user-images.githubusercontent.com/6173572/42181765-e032dffa-7df0-11e8-88e8-aabda171d10c.PNG)

**Comment by rajatagrawal-dev** [comment] 2018-07-03 16:57
@modikumar It was fixed long ago. From these logs, I assume you have specified "armartifacts/nestedtemplates/automation/scripts" in the Container Name input. That is not the right way for this.

You must specify only "armartifacts" as you Container Name. There is another input called Blob Prefix. Please specify "nestedtemplates/automation/scripts" in the Blob Prefix input.

![image](https://user-images.githubusercontent.com/21691254/42233851-4dbd6048-7f10-11e8-8a61-6bc8a51c9431.png)

**Comment by markusdresch** [comment] 2018-07-20 09:06
are you sure this was fixed? i'm trying to upload to $web (static hosting preview) using azureblob file copy and i get the following error:

> 2018-07-20T08:42:40.6765518Z ##[error]Upload to container: '$web' in storage account: 'xxx' with blob prefix: '' failed with error: 'Azure Storage container names can only contain lowercase alpha-numeric characters or hyphens

$web is the automatically generated webroot container for static hosting.

**Comment by rajatagrawal-dev** [comment] 2018-07-20 09:11
@markusdresch You should be able to upload to $root container. The fix for $web container will be deployed to all accounts in around a week.

**Comment by johnhydemtm365** [comment] 2018-08-15 15:43
Hi, has the fix for deploying the $web folder been deployed yet..?

**Comment by rajatagrawal-dev** [comment] 2018-08-15 17:43
@johnhydemtm365 Yes. It deployed a couple of hours ago. Please check if you are able to successfully deploy to $web containers.
If you have issues with this, please post here #7611.
