### ISSUE TITLE
Deploying with Azure App Service Deploy "encountered request timedou issue in Kudu. Retrying again"

### ISSUE THREAD

**Issue by Banzboy** [Microsoft/vsts-tasks#8182] opened 2018-08-29 02:17 UTC
## Environment

- Server - VSTS

## Issue Description

Currently we have a VSTS Release pipeline that deploys to an  Azure App Service. It does so through Azure App Service Deploy task. 

In Azure App Service Deploy there is an option to include a Post Deployment script. Currently in that script we run an executable. When deploying to the App Service and debugging the deployment we see that the executable has not fully completed but the deployment is marked successful. After setting on **system.debug** to true we see the following in the error log mentioned below.

**encountered request timedou issue in Kudu. Retrying again** message is being logged and therefore it does a retry. I can imagine it times out because the executable takes around 5~10 minutes to execute.

What I don't understand is that we have changed nothing on our end and now it's failing at exactly at the 3 minute mark. You can see it in the 3rd and 4th lines of the output logging.  It started failing after the 9th of August before this it was working fine, could a new timeout have been added?

### Error log
```
2018-08-28T20:42:00.2693461Z Executing given script on Kudu service.
2018-08-28T20:42:00.2700087Z ##[debug]Executing Script on Kudu. Command: mainCmdFile_99971535488919780.cmd 99971535488919780
2018-08-28T20:42:00.2700675Z ##[debug][POST]https://$kentico-cms-tst:***@kentico-cms-tst.scm.azurewebsites.net/api/command
2018-08-28T20:45:00.2997472Z ##[debug]encountered request timedou issue in Kudu. Retrying again
2018-08-28T20:45:00.2998412Z ##[debug][POST]https://$kentico-cms-tst:***@kentico-cms-tst.scm.azurewebsites.net/api/command
2018-08-28T20:45:00.9577362Z ##[debug]runCommand. Data: {"statusCode":200,"statusMessage":"OK","headers":{"cache-control":"no-cache","pragma":"no-cache","content-length":"120","content-type":"application/json; charset=utf-8","expires":"-1","server":"Microsoft-IIS/10.0","x-ms-request-id":"d29f0342-ab16-4211-a1fb-a7a80f60d315","x-aspnet-version":"4.0.30319","x-powered-by":"ASP.NET","set-cookie":["ARRAffinity=92fef5048920c3b7f99a1a7658ac80f165fbe867e0ce517426447f2d65e96772;Path=/;HttpOnly;Domain=kentico-cms-tst.scm.azurewebsites.net"],"date":"Tue, 28 Aug 2018 20:44:59 GMT","connection":"close"},"body":{"Output":"","Error":"The process cannot access the file because it is being used by another process.\r\n","ExitCode":0}}
2018-08-28T20:45:00.9585785Z ##[debug][GET]https://$kentico-cms-tst:***@kentico-cms-tst.scm.azurewebsites.net/api/vfs/site/wwwroot/stdout_99971535488919780.txt
2018-08-28T20:45:01.1949852Z ##[debug]Could not parse response: {}
2018-08-28T20:45:01.1950276Z ##[debug]Response: undefined
2018-08-28T20:45:01.1950523Z ##[debug]getFileContent. Status code: 200 - OK
2018-08-28T20:45:01.1954815Z ##[debug][GET]https://$kentico-cms-tst:***@kentico-cms-tst.scm.azurewebsites.net/api/vfs/site/wwwroot/stderr_99971535488919780.txt
2018-08-28T20:45:01.3620077Z ##[debug]getFileContent. Status code: 200 - OK
2018-08-28T20:45:01.3620727Z ##[debug][GET]https://$kentico-cms-tst:***@kentico-cms-tst.scm.azurewebsites.net/api/vfs/site/wwwroot/script_result_99971535488919780.txt
2018-08-28T20:45:01.5104598Z ##[debug]getFileContent. Status code: 200 - OK
2018-08-28T20:45:01.5104955Z Standard output from script: 
2018-08-28T20:45:01.5141104Z 
```

**Comment by Banzboy** [comment] 2018-08-31 11:37
It looks like retry logic was merged on the 11th of july. So that would explain why it's failing all of a sudden. Is there way to increase the request timeout in Kudu?

**Comment by vincentdass** [comment] 2018-08-31 15:52
@Banzboy , this is a regression on our side and we are working to fix this.
Ideally the task shouldnt retry for request timedout in post deployment script. Instead it should retry to get the script result. Will update the thread once the issue is fixed in master.

**Comment by Banzboy** [comment] 2018-09-04 07:40
@vincentdass Thanks for your reply. It's great news that it's going to be fixed! If possible do have any idea  when this issue will be fixed and included in the next release?

**Comment by cradle77** [comment] 2018-09-11 11:18
Hello, we are experiencing the same issue which is currently preventing us to successfully release to production.

Do you have an ETA for this or, alternatively, a workaround?

Thanks

**Comment by vincentdass** [comment] 2018-09-11 13:44
@cradle77 , we fixed the issue in master and planning to hotfix the issue.
Will update you once the hotfix  is initiated.

**Comment by vincentdass** [comment] 2018-09-11 15:38
@Banzboy , we removed the retry in post deployment script that is common for both Windows & Linux. 
Also the path to poll for script result is changed.

**Comment by Banzboy** [comment] 2018-09-12 08:36
That's clear, thanks for letting me know.

**Comment by vincentdass** [comment] 2018-09-19 09:57
@Banzboy , the issue is fixed in 4.* and the fix will be available n 2-3 weeks.

**Closed by vincentdass** 2018-09-19 09:57 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by Banzboy** [comment] 2018-09-27 12:37
@vincentdass Which version number would this be fixed in?

**Comment by acarlstein** [comment] 2020-09-10 21:46
We are getting `encountered request timedout issue in Kudu.` when trying to deploy an `AzureFunctionApp@1` using the `zipDeploy` or `runFromPackage` deployment method. 

We tried setting the configuration `WEBSITE_RUN_FROM_PACKAGE` to `0` and `1`. 

The funny thing is that this only happen when we rebuilt our resource `Microsoft.Web/sites` of kind `functionapp,linux`! 
If we run the deployment of `AzureFunctionApp@1` then it works

**Comment by jcageman** [comment] 2020-10-27 08:51
> We are getting `encountered request timedout issue in Kudu.` when trying to deploy an `AzureFunctionApp@1` using the `zipDeploy` or `runFromPackage` deployment method.
> 
> We tried setting the configuration `WEBSITE_RUN_FROM_PACKAGE` to `0` and `1`.
> 
> The funny thing is that this only happen when we rebuilt our resource `Microsoft.Web/sites` of kind `functionapp,linux`!
> If we run the deployment of `AzureFunctionApp@1` then it works

We got the same issue. It doesn't always happen, but every 1 out of 3 deployments the linux function app deployment fails with this message

**Comment by chtourou-youssef** [comment] 2021-07-12 16:31
same problem here 
i use linux web app
