### ISSUE TITLE
Azure app service deploy 'Failed to list path'

### ISSUE THREAD

**Issue by marioinz** [Microsoft/vsts-tasks#7137] opened 2018-05-04 10:24 UTC
## Troubleshooting
Error: Failed to list path 'site/wwwroot/_sub' 
while deploy of web app to virtual application with additional argument '–allowUntrusted' (ASE app plan)
no issue to deploy virtual application on non-ASE app plan.

## Environment
VSTS, private agent

### Error logs

2018-05-04T09:59:34.7624959Z ==============================================================================
2018-05-04T09:59:34.7624959Z Task         : Azure App Service Deploy
2018-05-04T09:59:34.7624959Z Description  : Update Azure WebApp Services On Windows, Web App On Linux with built-in images or docker containers, ASP.NET, .NET Core, PHP, Python or Node based Web applications, Function Apps, Mobile Apps, Api applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-05-04T09:59:34.7624959Z Version      : 3.3.46
2018-05-04T09:59:34.7624959Z Author       : Microsoft Corporation
2018-05-04T09:59:34.7624959Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2018-05-04T09:59:34.7624959Z ==============================================================================
2018-05-04T09:59:35.4031197Z Got connection details for Azure App Service:'xxxxxxxxxxxxx'
2018-05-04T09:59:39.2781508Z ##[error]Error: Failed to list path 'site/wwwroot/_sub' from Kudu. Error: Hostname/IP doesn't match certificate's altnames: "Host: xxxxxxxxxxxxxxxxx. is not in the cert's altnames: DNS:*.xxxxxxxxxxx, DNS:xxxxxxxxxxx"
2018-05-04T09:59:40.4501296Z ##[warning]Can\'t find loc string for key: FailedToUpdateDeploymentHistory
2018-05-04T09:59:40.4501296Z ##[warning]Error: FailedToUpdateDeploymentHistory Hostname/IP doesn't match certificate's altnames: "Host: xxxxxxxxxxxx. is not in the cert's altnames: DNS:*.xxxxxxxxxxxxx, DNS:xxxxxxxxxxxxxxxx"

**Comment by rokmicrosoft** [comment] 2018-05-06 17:51
@marioinz can you add variable VSTS_ARM_REST_IGNORE_SSL_ERRORS with value true in Release definition and queue a new release? It will use self signed certificates, basically untrusted connections.
This is duplicate of same [issue](https://github.com/Microsoft/vsts-tasks/issues/6682).

**Closed by rokmicrosoft** 2018-05-06 17:51 UTC
Labels: Area: Release

**Comment by marioinz** [comment] 2018-05-06 21:53
thanks! works perfect
we have legit wildcard cert for ASE envirnment: *.domain.com but this only single layer - do not cover ***.scm**.domain.com - this is reason of untrused connection.

**Comment by rokmicrosoft** [comment] 2018-05-07 05:32
Recommended approach is to install certificates in agents. You can use this approach if you are fine ignoring the cert errors.
