### ISSUE TITLE
Slot settings on app start task doesn't save

### ISSUE THREAD

**Issue by twilly86** [Microsoft/vsts-tasks#4851] opened 2017-07-21 15:35 UTC
I am having an issue with my build definition saving the slot settings on the stop azure app service task.

I check the "specify slot" box and save the build definition and refresh the screen and it goes back to being un-checked.

![image](https://user-images.githubusercontent.com/3496838/28470693-cbcafdb8-6df7-11e7-9a83-dfb81cc6b8ed.png)

**Comment by tjrobinson** [comment] 2017-07-24 14:14
I'm having the same problem. It just caused my Production slot to get stopped! This is critical functionality to be correct.

**Comment by tjrobinson** [comment] 2017-07-24 14:15
Note: This affects Builds, not just Releases.

**Comment by jmiddelkamp** [comment] 2017-07-24 14:22
Same problem here... pretty annoying

**Comment by tjrobinson** [comment] 2017-07-24 14:39
@jmiddelkamp @twilly86 I've emailed the team at Microsoft and had a brief response to say they'll look into it.

**Comment by jmiddelkamp** [comment] 2017-07-24 14:42
@tjrobinson @twilly86 everything works fine if you save it in the old editor. So for the time being we could use this as a work-around.

**Comment by chshrikh** [comment] 2017-07-25 03:49
we are taking a look

**Comment by chshrikh** [comment] 2017-07-25 11:35
We have found the root cause for this issue, we are in process to fix this and get it hot fixed. We will keep you updated on same.

**Comment by jkonecki** [comment] 2017-07-25 14:21
Could you provide ETA for the fix please? This is a critical piece of functionality.

**Comment by youngcm2** [comment] 2017-07-25 18:19
It is in both start and stop to be clear.

**Comment by chshrikh** [comment] 2017-07-26 05:39
If your scenarios is on Build then we have rolled out fix for Build, currently we are in process for rolling out fix for Release Management.

**Comment by Blackbaud-DerekAnderson** [comment] 2017-07-26 20:10
Any update on when this will be resolved for Release Management?

**Comment by chshrikh** [comment] 2017-07-27 08:15
this has been fixed for Release Management as well

**Comment by jmiddelkamp** [comment] 2017-07-27 11:30
@chshrikh Thanks for the update!

**Comment by jkonecki** [comment] 2017-07-31 10:11
@chshrikh Could you please close this issue to reflect its done status?

**Closed** 2017-07-31 10:23 UTC
Labels: Area: Release
