### ISSUE TITLE
Run Functional task not considering the Integration Tests in the pipeline

### ISSUE THREAD

**Issue by girishgoudar** [Microsoft/vsts-tasks#3854] opened 2017-03-24 02:49 UTC
Hi 

We are using functional test task to execute the integation tests. We see that the dll are getting dropped to the test agent machine. when the task is getting exeuted it runs only the unit tets and not the integration tests.

When we run vstest.console.exe against the Integration dll on the test agent agent machine. even then the tests are not recognized 

![error](https://cloud.githubusercontent.com/assets/12731096/24278646/06f870e0-106b-11e7-820b-5fccb83dc9f4.png)

Task log : Only 3 test are recognized which are the unit test and the integration tests are not recognized

2017-03-24T02:34:42.4333009Z DistributedTests: test settings id : 28
 
2017-03-24T02:34:42.4333009Z DistributedTests: build location: C:\Tests
 
2017-03-24T02:34:42.4333009Z DistributedTests: build id: 199
 
2017-03-24T02:34:42.4343829Z DistributedTests: test configuration mapping: 
 
2017-03-24T02:34:43.4414368Z DistributedTests: Test Run with Id 68 Queued
 
2017-03-24T02:34:43.8944367Z DistributedTests: Test run '68' is in 'InProgress' state.
 
2017-03-24T02:34:54.2869993Z DistributedTests: Test run '68' is in 'InProgress' state.
 
2017-03-24T02:35:04.7496734Z DistributedTests: Test run '68' is in 'InProgress' state.
 
2017-03-24T02:35:15.1752393Z DistributedTests: Please use this link to analyze the test run : 
2017-03-24T02:35:15.1752393Z DistributedTests: Test run '68' is in 'InProgress' state.
 
2017-03-24T02:35:15.1752393Z DistributedTests: Total Tests : 3, Passed Tests : 0
 
2017-03-24T02:35:25.5758798Z DistributedTests: Test run '68' is in 'Completed' state.
 
2017-03-24T02:35:25.5758798Z DistributedTests: Total Tests : 3, Passed Tests : 3

**Comment by PBoraMSFT** [comment] 2017-03-24 08:54
The task basically relies on vstest.console to discover the tests. If vstest.console.exe is no able to recognize the tests, the failure in the task is expected.
What framework are your tests based on? 3rd party framework based tests (such as xUnit, NUnit), etc. can be discovered only when their adapters can be found. Can you validate that the relevant adapters are also present on the test agent machines in the test drop location. For e.g., nuget based adapters will generally be contained in a packages folder. Ensure that the packages folder is copied to the test drop location. 
You can also specify paths to custom adapters via a runsettings file. 
Please note that /usevsixextension is only applicable when Visual Studio is present on the machine. If your machine only has test agent, that flag is invalid.

**Comment by girishgoudar** [comment] 2017-03-24 12:21
hi

We are not using any 3rd part framework. we are just using specflow tests which uses MStest framework. All the dll in the packages folder are copied to test drop location.

following are teh executors available on the machine 

![files](https://cloud.githubusercontent.com/assets/12731096/24293980/6c8e45d4-10ba-11e7-8db1-7efab9eeff3f.png)

Should i install VS on the machine?

**Comment by cltshivash** [comment] 2017-03-30 07:49
@girishgoudar Please provide a sample test project that reproduces the problem for us to debug further.

**Comment by tanvi-soni** [comment] 2017-04-06 11:14
@girishgoudar We do not generally require VS to be installed on test agent machine. What version of VS are you using to build your integrationtests?

**Comment by RanjanarMS** [comment] 2017-04-11 06:19
Closing this thread for now. If you feel the issue is not addressed please re-open.

**Closed by RanjanarMS** 2017-04-11 06:19 UTC
Labels: Area: Test
