### ISSUE TITLE
`##vso[task.setvariable]` does not work if the variable name is the same as a secret build variable

### ISSUE THREAD

**Issue by icnocop** [Microsoft/vsts-tasks#1678] opened 2016-05-09 22:52 UTC
According to https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md, I should be able to call `Write-Host ("##vso[task.setvariable variable=testvar;]testvalue")` in a Powershell build step and then call `Write-Host "testvar: $Env:testvar"` in a subsequent Powershell build step. But it doesn't seem like the variable is saved if the variable name is defined in the "Variables" tab of the Build definition and set as Secret because the output is just `testvar:` when I was expecting `testvar: ********`.

If the build variable is not set as Secret, then it works as expected, but the value is not masked in the output.

Thank you.

**Comment by ericsciple** [comment] 2016-05-10 15:38
This looks like a duplicate of https://github.com/Microsoft/vsts-tasks/issues/1677

[Secret variables](https://msdn.microsoft.com/en-us/library/vs/alm/build/scripts/variables#SecretVariables) aren't passed as environment variables. Also, I updated the commands.md.

**Closed by ericsciple** 2016-05-10 15:38 UTC

**Comment by icnocop** [comment] 2016-05-10 17:47
Thank you, I understand that secret variables aren't passed as environment variables, but what if I want to set an environment variable with the same name as a secret variable explicitly using a Powershell inline script build step? Commands.md still doesn't seem to address that it won't get carried forward to another Powershell inline script build step for example.
