### ISSUE TITLE
Azure File Copy Activities Fail with API Version Error

### ISSUE THREAD

**Issue by cdomino** [Microsoft/vsts-tasks#7081] opened 2018-04-26 12:55 UTC
### Issue Description

Hey Guys -

We started getting this on my client's VSTS instance (so I can't give out the details publicly): all Azure File Copy activities started to fail the error below. We simply moving articles from the build drop folder to blob storage. What's ominous is that it started to fail minutes after a successful build back on April 24th, and that the error message references an API version with a future date (May 1, 2018).

Thanks so much!

### Error logs

2018-04-24T02:36:21.3151432Z ##[section]Starting: AzureBlob File Copy: Data Factory Activities
2018-04-24T02:36:21.3157123Z ==============================================================================
2018-04-24T02:36:21.3157578Z Task         : Azure File Copy
2018-04-24T02:36:21.3157905Z Description  : Copy files to Azure blob or VM(s)
2018-04-24T02:36:21.3158226Z Version      : 1.0.112
2018-04-24T02:36:21.3158537Z Author       : Microsoft Corporation
2018-04-24T02:36:21.3158884Z Help         : [More Information](https://aka.ms/azurefilecopyreadme)
2018-04-24T02:36:21.3159289Z ==============================================================================

[sic]

2018-04-24T02:36:45.2887578Z ##[error]"{\"error\":{\"code\":\"InvalidApiVersionParameter\",\"message\":\"The api-version '2018-05-01' is invalid. The supported versions are '2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.\"}}"

2018-04-24T02:36:45.3245396Z ##[section]Finishing: AzureBlob File Copy: Data Factory Activities

**Comment by KrishnaAdityaB** [comment] 2018-04-27 08:12
@cdomino Are you still facing this error?

We have seen this error 3 days back. Lot of customers got impacted.
Root cause and work-around were discussed in this thread https://github.com/Microsoft/vsts-tasks/issues/7059

This is an error is originating from Azure side and has to be fixed there.
Please reach out to the Azure PowerShell team with the cmdlet that is failing.
Here is the thread that we raised and closed 3 days back https://github.com/Azure/azure-powershell/issues/6031

1. Enable debug logging and queue the release (debug logs can be enabled by adding a variable with name _System.Debug_ and value _true_)
2. From the logs figure out the Azure PS Cmdlet that is failing

I am closing this as an external issue. Please link the AzurePowerShell repo issue to this.

**Closed by KrishnaAdityaB** 2018-04-27 08:12 UTC
Labels: Area: Release

**Comment by cdomino** [comment] 2018-04-27 13:36
It does seem to do working now, @KrishnaAdityaB - thanks so much for the quick reply!
