### ISSUE TITLE
SqlAzureDacpacDeployment - Get-AgentIPRange fails when password contains "|"

### ISSUE THREAD

**Issue by wimmeerschman** [Microsoft/vsts-tasks#4316] opened 2017-05-15 07:22 UTC
We have an issue with task /tree/master/Tasks/SqlAzureDacpacDeployment
More specific in file DeploySqlAzure.ps1, line 131.
When putting the firewall rules setting to "AutoDetect" it executes
$ipAddressRange = Get-AgentIPRange -serverName $ServerName -sqlUsername $SqlUsername -sqlPassword $SqlPassword
$sqlPassword = firstPart|secondPart

We have a password which contains a "|"
This cmdlet fails, because it interprets the "|" symbol in the password as a pipe, error:
The term 'secondPart' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by arjgupta** [comment] 2017-05-15 12:18
Hi @wimmeerschman , this is a known issue. We have applied a fix for this, and the updated task will be available in the next couple of days

**Comment by mvvsubbu** [comment] 2017-05-22 06:54
Fix is rolling out in phases to all the accounts, it should reach with in couple of weeks in task version 1.1.15.  Please feel free to reopen if the issue is not addressed in that version

**Closed by mvvsubbu** 2017-05-22 06:54 UTC
Labels: Area: Release
