### ISSUE TITLE
Azure File Copy Fails with Error 404 Not Found

### ISSUE THREAD

**Issue by SushantShaha** [Microsoft/vsts-tasks#5482] opened 2017-09-27 23:47 UTC
We are using Azure File Copy task in VSTS Build and release activities. However it started failing since yesterday morning with following error 
2017-09-27T07:06:38.6807118Z ##[debug]System.Management.Automation.RuntimeException: Failed to enable copy prerequisites. Long running operation failed with status 'Failed'.
2017-09-27T07:06:38.6807118Z ##[debug]ErrorCode: VMExtensionProvisioningError
2017-09-27T07:06:38.6963543Z ##[debug]ErrorMessage: VM has reported a failure when processing extension 'WinRMCustomScriptExtension'. Error message: "Failed to download all specified files. Exiting. Error Message: The remote server returned an error: (404) Not Found.".

After enabling debug logs, we found the command which is failing as below 
Set-AzureRmVMCustomScriptExtension -ResourceGroupName Matrix_APS_Deployment-MatrixAdEmrT401-316404 -VMName MatrixAdEmrT401 -Name WinRMCustomScriptExtension -FileUri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/ConfigureWinRM.ps1 https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/makecert.exe https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd  -Run ConfigureWinRM.ps1 -Argument matrixademrt401.westus.cloudapp.azure.com -Location westus -ErrorAction Stop -Verbose

After digging little further what i found is that this file which it is trying to access doesnt exist on github link here  https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd

Please fix this issue as it is blocking many of our builds in VSTS instance

**Comment by north0779** [comment] 2017-09-28 09:26
I'm seeing the same issue, blocking our deploy.

**Comment by pavanadepu2** [comment] 2017-09-28 10:13
@SushantShaha, @north0779 thanks for reporting the issue. We are currently working on it, I will update you once it is fixed.

**Comment by ds-ms** [comment] 2017-09-28 11:03
This issue has been hotfixed. Please verify your scenarios and close this issue accordingly.

**Comment by north0779** [comment] 2017-09-28 12:36
We're still seeing it. We're using on-prem TFS - is there anything we need to do our end?

**Comment by mdesenfants** [comment] 2017-09-28 16:30
We're seeing this issue with our deployments as well.

**Comment by SushantShaha** [comment] 2017-09-28 16:39
It seems to have fixed our issue in our VSTS instance.

Thanks & Regards,

Sushant Shaha

On Sep 28, 2017, at 4:03 AM, Deepak Sattiraju <notifications@github.com<mailto:notifications@github.com>> wrote:


This issue has been hotfixed. Please verify your scenarios and close this issue accordingly.

**Comment by pavanadepu2** [comment] 2017-09-28 16:43
The issue is fixed in VSTS, we are still working on OnPremise fix.

**Comment by SushantShaha** [comment] 2017-09-28 16:55
Thanks team for fixing it in VSTS ASAP.

However couple of quick questions/feedback:
1. We did not update our VSTS-tasks to new version neither it shows that new version is available but still we got broken.
2. Whenever such new changes gets pushed, don’t Ms release new version of these tasks that one can upgrade on need basis ? What testing methods are in place before promoting such fixes to production ?
3. How can it be avoided in future ? Believe me we burnt our heads until midnight 3 am from morning (18hrs. almost) to figure out this issue as why it broke suddenly because we had to deliver new Release yesterday and this issue came as monster.

Thanks & Regards,

Sushant Shaha

On Sep 28, 2017, at 9:44 AM, Pavan Adepu <notifications@github.com<mailto:notifications@github.com>> wrote:


The issue is fixed in VSTS, we are still working on OnPremise fix.

**Comment by pavanadepu2** [comment] 2017-09-28 17:00
@north0779, you need to update the file Tasks/AzureFileCopy/Utility.ps1 present in your agent directory structure, with the changes as shown in this [PR#5484](https://github.com/Microsoft/vsts-tasks/pull/5484/files#diff-5e20439d3669bfb2afd0f5c18572fe3e).

**Comment by vincentdass** [comment] 2017-09-29 07:56
The issue is fixed and the task should be succeeding now.

**Closed by vincentdass** 2017-09-29 07:56 UTC
Labels: Area: Release
