### ISSUE TITLE
npm task doesn't refresh display name when args change

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vsts-tasks#1509] opened 2016-04-09 14:27 UTC
When first adding an npm step to "install --force", the display name for the step became *npm install --force*. But later, I removed the `--force` from the arguments, but the display name still shows that argument. Saving and reopening, refresh, etc. does *not* fix the problem.

![image](https://cloud.githubusercontent.com/assets/3548/14404143/63e0ffde-fe24-11e5-8d19-178db841095e.png)

**Comment by bryanmacfarlane** [comment] 2016-04-21 11:06
Yash, please investigate as part of 99 testing.

**Comment by yaananth** [comment] 2016-04-21 15:13
![issue](https://cloud.githubusercontent.com/assets/12280011/14714168/e78e03e0-07b1-11e6-9695-887a5f19c181.gif)
attached, I just tried locally and can't repro.
Please mention repro steps.

**Comment by AArnott** [comment] 2016-04-21 15:49
My repro steps look to be the same as yours (but it repros for me):

![microsoft_visual_studio_team_services_-_google_chr](https://cloud.githubusercontent.com/assets/3548/14715525/ff901708-079d-11e6-8481-d40e7fa58526.gif)

**Comment by yaananth** [comment] 2016-04-21 15:51
could you click on little pencil icon on the top and click "reset"?

**Comment by AArnott** [comment] 2016-04-21 15:53
The reset and generate links don't do anything.

**Comment by yaananth** [comment] 2016-04-21 15:56
Actually, now I look at it, it is as designed, that little text only responds to "command" textbox and not "arguments" textbox.

**Comment by yaananth** [comment] 2016-04-21 16:02
closing as designed, if it doesn't respond to the "command" textbox, try "reset" it should fix it.

**Closed by yaananth** 2016-04-21 16:02 UTC

**Comment by AArnott** [comment] 2016-04-21 16:08
@yaananth: that doesn't explain the initial screenshot that demonstrates that `--force` was part of the name.

**Comment by AArnott** [comment] 2016-04-21 16:11
Did the task perhaps used to include parameters in the name calculation, then later that functionality was removed, leaving the existing tasks people had 'orphaned' with an old name?

**Comment by yaananth** [comment] 2016-04-21 16:11
That probably because the command itself has "install -force", we only trigger based on "command" textbox. The reason it didn't update may be because of something ( which I don't quite remember, we keep it the same in some cases ) that triggered it to stay, doing "reset" should fix that.

With that said, it may also be true that the task it'self changed it's param calculations, I will check that.

**Comment by yaananth** [comment] 2016-04-21 16:19
Yep https://github.com/Microsoft/vsts-tasks/commit/28b92c10e37076ae6475103ccc8470a6c150d324 
so yeah, it did change :)
