### ISSUE TITLE
Cannot copy files over SSH, as "Endpoint auth data not present"

### ISSUE THREAD

**Issue by CookieCookson** [Microsoft/vsts-tasks#3369] opened 2017-01-05 16:46 UTC
I have set up a build to install npm packages, perform a gulp build and then copy the build artefacts across to a remote server. When asking it to copy across to my remote server via SSH, it immediately throws an error.

I have filled out the hostname as the URL of the server, port, ssh username, passphrase for the key and the contents of the private key and it throws the following error:

`Endpoint auth data not present: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`

**Comment by jeffyoung** [comment] 2017-01-09 22:22
Based on the SSH task code, it appears to be failing trying to get the first parameter (username) as it's required.  I don't know why that it'd be failing to do that.

Would it be possible for you to set the "system.debug" build variable on your build definition to true, re-run the build and post the build log here?  You may want to check for any PII information before posting.  Also, I assume you're using hosted build (and not your own build agent)?

**Comment by CookieCookson** [comment] 2017-01-10 09:23
Thanks for your reply @jeffyoung! Apologies, I am hosting my own build agent on OSX. Here is my build log with system.debug enabled:
```
agent.workFolder=/Users/xxxxxxxx/myagent/_work
Processed logging command: ##vso[task.debug]agent.workFolder=/Users/xxxxxxxx/myagent/_work
loading inputs and endpoints
Processed logging command: ##vso[task.debug]loading inputs and endpoints
loading INPUT_SSHENDPOINT
Processed logging command: ##vso[task.debug]loading INPUT_SSHENDPOINT
loading INPUT_SOURCEFOLDER
Processed logging command: ##vso[task.debug]loading INPUT_SOURCEFOLDER
loading INPUT_CONTENTS
Processed logging command: ##vso[task.debug]loading INPUT_CONTENTS
loading INPUT_TARGETFOLDER
Processed logging command: ##vso[task.debug]loading INPUT_TARGETFOLDER
loading INPUT_CLEANTARGETFOLDER
Processed logging command: ##vso[task.debug]loading INPUT_CLEANTARGETFOLDER
loading INPUT_OVERWRITE
Processed logging command: ##vso[task.debug]loading INPUT_OVERWRITE
loading INPUT_FLATTENFOLDERS
Processed logging command: ##vso[task.debug]loading INPUT_FLATTENFOLDERS
loading ENDPOINT_AUTH_180a1f64-121a-46a9-919a-6901498cae14
Processed logging command: ##vso[task.debug]loading ENDPOINT_AUTH_180a1f64-121a-46a9-919a-6901498cae14
loading ENDPOINT_AUTH_https://xxxxxxxx@bitbucket.org/xxxxxxxx/xxxxxxxx.git
Processed logging command: ##vso[task.debug]loading ENDPOINT_AUTH_https://xxxxxxxx@bitbucket.org/xxxxxxxx/xxxxxxxx.git
loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
Processed logging command: ##vso[task.debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
loaded 10
Processed logging command: ##vso[task.debug]loaded 10
check path : /Users/xxxxxxxx/myagent/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.1.2/task.json
Processed logging command: ##vso[task.debug]check path : /Users/xxxxxxxx/myagent/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.1.2/task.json
set resource file to: /Users/xxxxxxxx/myagent/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.1.2/task.json
Processed logging command: ##vso[task.debug]set resource file to: /Users/xxxxxxxx/myagent/_work/_tasks/CopyFilesOverSSH_67cec91b-0351-4c2f-8465-d74b3d2a2d96/0.1.2/task.json
system.culture=en-US
Processed logging command: ##vso[task.debug]system.culture=en-US
sshEndpoint=180a1f64-121a-46a9-919a-6901498cae14
Processed logging command: ##vso[task.debug]sshEndpoint=180a1f64-121a-46a9-919a-6901498cae14
task result: Failed
Processed logging command: ##vso[task.debug]task result: Failed
Error: Endpoint auth data not present: 180a1f64-121a-46a9-919a-6901498cae14
Processed logging command: ##vso[task.issue type=error;]Error: Endpoint auth data not present: 180a1f64-121a-46a9-919a-6901498cae14
Processed logging command: ##vso[task.complete result=Failed;]Error: Endpoint auth data not present: 180a1f64-121a-46a9-919a-6901498cae14
```

**Comment by jeffyoung** [comment] 2017-01-10 14:26
Thanks @CookieCookson.  This certainly looks like the endpoint no longer exists which could happen if the definition points to an endpoint and is able to use it, then the endpoint is removed (via the services admin page).  I was able to reproduce that behavior simply by deleting an existing endpoint my SSH build was using.

Interestingly enough, my build definition didn't have system.debug set to true at the time I broke my build (testing out this scenario).  When I went to set it to true, I couldn't save the definition because the endpoint no longer existed.  Unless you had the build variables tab open at the time, I would suspect that if the endpoint was removed, you wouldn't be able to change the value of system.debug either.  That said, can you double-check that the endpoint exists?

Assuming it does, is it possible for you to create another endpoint with the same information (use a similar but different name) and try that out?  On our hosted account, I was able to create another endpoint (similar but different name), get it to build, delete it, re-queue the build and see the failure.  However, at this point, based on the code, it appears that either the endpoint doesn't exist or the task can't retrieve it.

**Comment by CookieCookson** [comment] 2017-01-10 16:52
Hey @jeffyoung, thanks for your input, I tried creating another endpoint etc but to no avail.

However, I decided to have a dig around `copyfilesoverssh.js` which was listed in the debug output and started logging out some values. It turns out when performing `getEndpointAuthorizationParameter` and `getEndpointDataParameter` it is now stored as a secret as a stringified JSON object instead of individual `_KEY` references! I am not sure whether this is a new change to VSTS which is not in VST, but I have worked out a fix which has now allowed me to progress temporarily.
 
Modified functions in task.js:
```
function getEndpointAuthorizationParameter(id, key, optional) {
    var authParam = JSON.parse(vault.retrieveSecret('ENDPOINT_AUTH_' + id)).parameters[key];
    if (!optional && !authParam) {
        throw new Error(loc('LIB_EndpointAuthNotExist', id));
    }
    debug(id + ' auth param ' + key + ' = ' + authParam);
    return authParam;
}
```
```
function getEndpointDataParameter(id, key, optional) {
    var dataParamVal = JSON.parse(process.env['ENDPOINT_DATA_' + id])[key];
    if (!optional && !dataParamVal) {
        throw new Error(loc('LIB_EndpointDataNotExist', id, key));
    }
    debug(id + ' data ' + key + ' = ' + dataParamVal);
    return dataParamVal;
}
```

Modified requests in `copyfilesoverssh.js`:
```
var privateKey = tl.getEndpointDataParameter(sshEndpoint, 'privateKey', false); //private key is optional, password can be used for connecting
```

**Comment by jeffyoung** [comment] 2017-01-10 18:22
Well, for one, I read "copy files of SSH" and thought of the SSH task (so I was looking at the wrong code).  :(  Oops.

Let me do some digging around this area and see what I can find out.  BTW, what do you mean by "VST"?  Did you mean TFS (on-prem)?  Are you using our on-prem product or team services?  (I should have asked that question earlier.)

**Comment by jeffyoung** [comment] 2017-01-10 18:42
Could you also let me know which version of the build agent you're using?

**Comment by CookieCookson** [comment] 2017-01-10 20:02
Err yeah I meant TFS! I'm using the team services product. Would updating the build agent solve things? I haven't updated it since I installed it about 7 months ago. How would I get the build agent version?

**Comment by jeffyoung** [comment] 2017-01-10 22:08
I believe the build agent was updated back in June to handle changing Auth Data parameters from JSON to strings.  (See https://github.com/Microsoft/vsts-agent/commit/b70f8c7ec9c121a7562fc61a21a5d44c37eac8fd)

The version of the agent that you have should be displayed towards the top of your detailed build log.  Something like:
![image](https://cloud.githubusercontent.com/assets/2796865/21826483/a9c73242-d755-11e6-90a0-9d0b1c19d009.png)

To update the build agent, first go to your "agent queues" administration page (Settings | Agent queues where "Settings" is the gear icon at the top of the page).  This settings page is available from the team _project-level_ (not collection/account level).  Find the queue that your agent is a part of (there may only be one; larger organizations have many). Right-click on that queue and choose "Update All Agents":
![image](https://cloud.githubusercontent.com/assets/2796865/21826585/18a7cbc2-d756-11e6-9ae5-a924c6f688e9.png)

That will, of course, update *all* agents in that queue but if you just have one, you should be good to go.  That menu item sends a message to the connected agent that it needs to update itself.  Once it receives that message, it'll do the update and re-connect to the queue.  Once complete, you should be able to run more builds and see the updated version.

Otherwise, you can also simply deploy a new agent over the top of your existing agent.  This requires you to log onto the agent machine, download the new agent bits (which can be done from Settings | _Agent pools_ which, unlike the 'Update' option above, _is_ at the account/collection level) via the "Download agent" option:
![image](https://cloud.githubusercontent.com/assets/2796865/21826907/5147277e-d757-11e6-9b7a-36e6d7e76628.png)

**Comment by CookieCookson** [comment] 2017-01-18 09:26
This seems to have fixed things @jeffyoung, thanks! Would the plugin need a minimum version of the build agent set?

**Comment by jeffyoung** [comment] 2017-01-18 15:13
That's great to hear!  Yes, that is likely what we'll need to do.  I'll file a bug on our end for this (and close this issue).  Thanks @CookieCookson!

**Closed by jeffyoung** 2017-01-18 15:13 UTC
Labels: Area: CrossPlatform
