### ISSUE TITLE
Updating from VSTest 1.* to 2.* reverts testassemblies setting to default.

### ISSUE THREAD

**Issue by sanderaernouts** [Microsoft/vsts-tasks#6277] opened 2018-01-24 08:48 UTC
## Environment
On-Prem TFS 2017 Version 15.117.26714.0

## Issue Description
When I update the VSTest task from version 1.* to 2.* using the dropdown in the build editor. It will copy most settings to the 2.* version of the task but the value of testAssembly is not copied. This seems to be caused by the fact that the testAssembly input paramater has been renamed to testAssemblyVer2.
![image](https://user-images.githubusercontent.com/6184673/35322640-3e6c79c4-00eb-11e8-90e1-2d4108077209.png)

This causes assemblies to be scanned for tests that would not have been selected otherwise. We have also seen the VSTest step go yellow because it then cannot find tests that satisfy the filters in one more assemblies.

**Comment by acesiddhu** [comment] 2018-02-06 09:00
@sanderaernouts sorry for the delay here.
This is by design. the format of test assemblies specified in vstest v1 task and v2 task has changed and we cant migrate those automatically. Vstest v2 task uses minimatch pattern. You need to specify the sources manually for it to work.

**Comment by acesiddhu** [comment] 2018-02-09 06:14
Closing the issue

**Closed by acesiddhu** 2018-02-09 06:14 UTC
Labels: Area: Test
