### ISSUE TITLE
Tests don't run reliably

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vsts-tasks#6073] opened 2017-12-19 14:45 UTC
VSTS:
intreba.visualstudio.com
Project: Products
Build definition: FastPACE.Server - Build, Package, Push and create release.
Failing ids: 2222 and 2225
Hosted agent queue name: Hosted VS2017

## Issue Description

Sometimes the tests fail with below errors. Currently 50% of the time this happens (well, of 4 builds). 
Possibly relation: it looks like it runs really, really slowly, even though we're directed to North Europe instead of West Europe, a dotnet publish takes a really long time compared to the usual time needed.

### Error logs

2017-12-19T14:00:42.1569213Z Starting test execution, please wait...
2017-12-19T14:03:57.7852885Z Error: Failed to initialize client proxy: could not connect to test process .
2017-12-19T14:03:57.7855065Z 
2017-12-19T14:03:57.7855772Z Error: There was no endpoint listening at net.pipe://factoryvm-az248/TestExecutor/5080 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
2017-12-19T14:03:57.7856295Z 
2017-12-19T14:04:06.2280904Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2017-12-19T14:04:08.7056314Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
2017-12-19T14:04:08.7831846Z ##[warning]No results found to publish.
2017-12-19T14:04:08.8586371Z ##[error]VsTest task failed.

**Comment by makhdumi** [comment] 2017-12-19 17:21
Are you sure this is an issue with vsts-tasks? It looks like it runs vstest.console, which is about the extent of the task's responsibility.

Maybe this team could help you though if it's an issue with your Hosted VS2017 server.

What I would do though is just deploy my own VS2017 agent (super easy. Just create a VM with VS2017 installed on it in Azure, and download+install the VSTS agent with your Personal Access Token), and then try to run the exact same vstest.console.exe command on the machine in an RDP session.

**Comment by ShreyasRmsft** [comment] 2017-12-26 06:04
Hi @janpieterz, 
Could you please share the complete build logs of a successful build and a failed build? Also running the same build with system.debug set to true and sharing the logs of a failed build will help a lot.

**Comment by ShreyasRmsft** [comment] 2017-12-26 06:07
You can mail the logs to devops_tools@microsoft.com

**Comment by ShreyasRmsft** [comment] 2018-01-03 05:55
Closing the issue due to no reply, please re-open if needed.

**Comment by janpieterz** [comment] 2018-01-03 06:21
Hi @ShreyasRmsft , still occurred yesterday, could you re-open.?

Have failing and successful logs, now set the system.debug to true for all tests and waiting for one to fail there. Christmas and New Years made a lot less builds happen ;)

**Comment by ShreyasRmsft** [comment] 2018-01-03 06:31
@janpieterz can you please share the logs?

**Comment by janpieterz** [comment] 2018-01-03 06:42
Sure, just send the two ones! I did see the error has changed to another one (We setup a database, LocalDB, and the connection to this fails sometimes now, sometimes just passes).

The above SOAP exception does not occur anymore, but this error keeps happening now and then as well.

**Comment by ShreyasRmsft** [comment] 2018-01-03 06:58
@janpieterz The failed logs here indicates its the db connection only that's failing and this seems to be a test/machine issue. Lemme know if the SOAP issue repros.

**Comment by ShreyasRmsft** [comment] 2018-01-03 06:59
@janpieterz and you are claiming that these sql issues are also intermittent and not consistent?

**Comment by janpieterz** [comment] 2018-01-03 07:02
I think the SOAP had to do with whatever was causing the machines to be running in North Europe, probably a temporary issue.

The SQL issues are indeed also intermittent and not consistent, both logs from yesterday were kicked off almost right after each other, no change in code, happens now and then _only_ on hosted VSTS.

Want me to open a new issue for this or can we use this one?

**Comment by ShreyasRmsft** [comment] 2018-01-03 07:08
The test agents you are using are private machines/vms? When you manually go run the tests on the machines they always succeed?

**Comment by janpieterz** [comment] 2018-01-03 07:12
They're hosted public ones, using visualstudio.com hosted VS2017 agents.
Manually locally they always succeed with the database connection.

Maybe localdb is setup on some machines and others not, or not correctly?

Connection code that sometimes does work and sometimes not:

```c#
string masterDbString = "Server=(localdb)\\mssqllocaldb;Database=master;Trusted_Connection=True;MultipleActiveResultSets=true;Integrated Security=SSPI;";
MasterDbConnection = new SqlConnection(masterDbString);
MasterDbConnection.Open();
```

**Comment by ShreyasRmsft** [comment] 2018-01-03 07:14
So there was a change recently made where permissions were changed for local db access on the hosted machines. This might be causing the issues.

**Comment by janpieterz** [comment] 2018-01-03 07:30
So some machines might be on this new permission policy while others aren't?
Any way to get consistent behavior _and_ use a localdb ? Certain permissions/capabilities I'd need to request?

**Comment by ShreyasRmsft** [comment] 2018-01-03 08:15
@janpieterz Scrap that last comment. It was something unrelated. I don't think it may have been the cause.

**Comment by janpieterz** [comment] 2018-01-03 09:34
@ShreyasRmsft just ran into the original (SOAP) issue again. 
Will send email shortly, but currently doing a production deployment related to this code.

**Comment by ShreyasRmsft** [comment] 2018-01-03 10:12
Hi @janpieterz, this apparently is a known issue with older versions of the testplatform. I can give you a simple workaround to get the latest test platform on the Hosted machines. There is a task called the VsTest Tool Installer. Use it to install the latest testplatform and in the VsTest task select the Installed by tools installer option In the VS version selector dropdown.

**Comment by janpieterz** [comment] 2018-01-03 13:42
Looks solved, I've kicked off a lot of builds and they all succeeded, thanks! 
Any place to track the deployment of this new test platform so I can remove these steps?

**Comment by janpieterz** [comment] 2018-01-04 08:25
@ShreyasRmsft just sent you 3 more logs, 2 randomly failed again (kicking off again fixed one of them, other still running).

Odd thing as well, the test step takes considerably longer than locally. Locally it runs ~15 seconds for all tests, on the build server it seems to sometimes just hang, even when succeeding.

**Comment by ShreyasRmsft** [comment] 2018-01-05 09:02
@janpieterz for your sql connection timeouts can you try increasing the default connection timeout in your tests? The hosted agents might just be slow.

For the other issue can you run all your build with System.debug set to true and share all the build attachments you get? I am hoping to get the detailed logs from vstest.console.exe.

Also as a workaround can you try by providing one version older to the VsTest Platform Installer. (15.6.0-preview-20171108-02)

But do provide the debug logs (build attachments: we attach the test platform logs when system.deubg is set to true) so that we can investigate and fix this issue.

Thanks.

**Comment by janpieterz** [comment] 2018-01-05 09:09
I've increased the timeout to 60 seconds to check. I've also set the debug=true. If I get it I'll send the logs again and then try the older version so at least we have a debug=true failing.

They do seem to be extremely slow, I did a manual local build and it goes so much faster. Is there any way to upgrade to a more sped-up pipeline? 
5-7 minutes of test instead of 15 seconds is quite a difference, a relatively normal build takes about 15-20 minutes now, copying the build process to run locally (including a total clean install from nuget etc) is more in the range of 5 minutes.

**Comment by ShreyasRmsft** [comment] 2018-01-05 09:47
@janpieterz Can you setup a private build agent on your box and run the whole build once? This will ascertain whether the slowness is purely related to the hosted machine having lesser configuration.

**Comment by janpieterz** [comment] 2018-01-05 11:42
3 runs locally:
4.3, 4.6 and 4.4 minutes

Last 3 successful hosted ones:
17:29, 23:22, 24.1 minutes

Everything takes about 2 times as much, nuget/npm installs a lot more (probably no caching?), tests take 8 times as much (1 minute local, 8.x hosted)

**Comment by janpieterz** [comment] 2018-01-05 16:04
Two more failures just recorded on latest with 60 seconds timeout in connections string.

[logs_2306_protocol timeout.zip](https://github.com/Microsoft/vsts-tasks/files/1607082/logs_2306_protocol.timeout.zip)
[logs_2303_sql timeout.zip](https://github.com/Microsoft/vsts-tasks/files/1607083/logs_2303_sql.timeout.zip)

**Comment by ShreyasRmsft** [comment] 2018-01-08 06:58
@janpieterz The differences in run times is clearly because the hosted vms are 2 core machines

**Comment by ShreyasRmsft** [comment] 2018-01-08 07:03
@janpieterz The sql timeouts i looked into a bit more. [link](https://social.technet.microsoft.com/Forums/en-US/3bbcd9a3-f90b-4ef2-8244-f06ee8d9cfa3/timeout-error-while-attempting-to-consume-the-prelogin-handshake?forum=sqldataaccess). It can't be reasons 4,5,6 or 7 as you are using localDb and the hosted machines are reimaged after every build. 1,2 or 3 might however be a possibility. 

Also you are sure these sql errors only occur on the hosted agents and not on a private agent when you run say 10-15 times?

**Comment by ShreyasRmsft** [comment] 2018-01-08 07:04
@janpieterz The protocol negotiation timeout I've logged a bug and we are investigating into it.

**Comment by ShreyasRmsft** [comment] 2018-01-09 11:36
@janpieterz are your tests .NetCoreTests? If so can you use the .Net Core task to run your tests. 

VsTest at the moment does not support .NET core tests.

**Comment by janpieterz** [comment] 2018-01-10 09:24
They're not .net core tests, just net47 tests (they do run in new project model).

I just ran it 17 times straight in a row and it occurred 0 times locally.

Funny they run on 2 core machines, I'd expect more. It might make us consider for future builds to  run them locally indeed.

**Comment by ShreyasRmsft** [comment] 2018-01-10 09:49
@janpieterz one small suggestion in your test assemblies input you've given this **\*test*.dll,!**\obj\**

This is causing a bunch of unnecessary dlls being picked up:
8-01-03T20:36:15.6386525Z "d:\a\1\s\Tests\bin\Debug\net47\cs\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6387099Z "d:\a\1\s\Tests\bin\Debug\net47\cs\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6387570Z "d:\a\1\s\Tests\bin\Debug\net47\cs\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6388039Z "d:\a\1\s\Tests\bin\Debug\net47\de\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6388768Z "d:\a\1\s\Tests\bin\Debug\net47\de\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6389232Z "d:\a\1\s\Tests\bin\Debug\net47\de\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6389689Z "d:\a\1\s\Tests\bin\Debug\net47\es\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6390187Z "d:\a\1\s\Tests\bin\Debug\net47\es\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6390672Z "d:\a\1\s\Tests\bin\Debug\net47\es\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6391134Z "d:\a\1\s\Tests\bin\Debug\net47\fr\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6392152Z "d:\a\1\s\Tests\bin\Debug\net47\fr\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6392803Z "d:\a\1\s\Tests\bin\Debug\net47\fr\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6393470Z "d:\a\1\s\Tests\bin\Debug\net47\it\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6394107Z "d:\a\1\s\Tests\bin\Debug\net47\it\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6394741Z "d:\a\1\s\Tests\bin\Debug\net47\it\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6397578Z "d:\a\1\s\Tests\bin\Debug\net47\ja\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6398235Z "d:\a\1\s\Tests\bin\Debug\net47\ja\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6398906Z "d:\a\1\s\Tests\bin\Debug\net47\ja\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6399394Z "d:\a\1\s\Tests\bin\Debug\net47\ko\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6399936Z "d:\a\1\s\Tests\bin\Debug\net47\ko\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6400438Z "d:\a\1\s\Tests\bin\Debug\net47\ko\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6401291Z "d:\a\1\s\Tests\bin\Debug\net47\pl\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6402008Z "d:\a\1\s\Tests\bin\Debug\net47\pl\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6402642Z "d:\a\1\s\Tests\bin\Debug\net47\pl\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6403284Z "d:\a\1\s\Tests\bin\Debug\net47\pt-BR\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6403936Z "d:\a\1\s\Tests\bin\Debug\net47\pt-BR\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6404725Z "d:\a\1\s\Tests\bin\Debug\net47\pt-BR\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6405380Z "d:\a\1\s\Tests\bin\Debug\net47\ru\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6405881Z "d:\a\1\s\Tests\bin\Debug\net47\ru\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6406361Z "d:\a\1\s\Tests\bin\Debug\net47\ru\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6406845Z "d:\a\1\s\Tests\bin\Debug\net47\tr\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6407393Z "d:\a\1\s\Tests\bin\Debug\net47\tr\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6407896Z "d:\a\1\s\Tests\bin\Debug\net47\tr\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6408354Z "d:\a\1\s\Tests\bin\Debug\net47\xunit.runner.visualstudio.testadapter.dll"
2018-01-03T20:36:15.6408834Z "d:\a\1\s\Tests\bin\Debug\net47\zh-Hans\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6409304Z "d:\a\1\s\Tests\bin\Debug\net47\zh-Hans\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6409819Z "d:\a\1\s\Tests\bin\Debug\net47\zh-Hans\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"
2018-01-03T20:36:15.6410565Z "d:\a\1\s\Tests\bin\Debug\net47\zh-Hant\Microsoft.TestPlatform.CommunicationUtilities.resources.dll"
2018-01-03T20:36:15.6411061Z "d:\a\1\s\Tests\bin\Debug\net47\zh-Hant\Microsoft.TestPlatform.CrossPlatEngine.resources.dll"
2018-01-03T20:36:15.6411954Z "d:\a\1\s\Tests\bin\Debug\net47\zh-Hant\Microsoft.VisualStudio.TestPlatform.Common.resources.dll"

Can you refine the minimatch patter to avoid this.

Also turn off code coverage and see if this error occurs.

Also did the workaround of using one version older work?

**Comment by ShreyasRmsft** [comment] 2018-01-16 06:18
Tracking this issue [here](https://github.com/Microsoft/vstest/issues/1361).

**Closed by ShreyasRmsft** 2018-01-16 06:18 UTC
Labels: Area: Test
