### ISSUE TITLE
SqlAzureDacpacDeployment - Issue with special character in password

### ISSUE THREAD

**Issue by paddyfink** [Microsoft/vsts-tasks#3998] opened 2017-04-11 21:35 UTC
Hello, Since today my release fail to deploy my Database due to special charater in password:

```
2017-04-11T21:15:48.4998550Z ##[section]Starting: Execute Azure SQL : DacpacTask
2017-04-11T21:15:48.5108556Z ==============================================================================
2017-04-11T21:15:48.5108556Z Task         : Azure SQL Database Deployment
2017-04-11T21:15:48.5108556Z Description  : Deploy Azure SQL DB using DACPAC or run scripts using SQLCMD
2017-04-11T21:15:48.5108556Z Version      : 1.1.9
2017-04-11T21:15:48.5108556Z Author       : Microsoft Corporation
2017-04-11T21:15:48.5108556Z Help         : [More Information](https://aka.ms/sqlazuredeployreadme)
2017-04-11T21:15:48.5108556Z ==============================================================================
2017-04-11T21:15:50.9385171Z packageFile= d:\a\r1\a\Master Build\DB\xxx.DB.dacpac
2017-04-11T21:15:51.1705161Z ##[error]At line:1 char:75
+ ... -% -S xxxx.database.windows.net -U login-P |2d.7\M/#:Cw ...
+                                                                  ~
Missing property name after reference operator.

At line:1 char:87
+ ... xxx.database.windows.net -U login-P ******** -Q "select ...
+                                                                ~~
Unexpected token '-Q' in expression or statement.

At line:1 char:72
+ ... xxxx.database.windows.net -U login-P ******** -Q "select ...
+                                                 ~~~~~~~~~~~~~~~~~
Expressions are only allowed as the first element of a pipeline.

At line:1 char:90
+ ... .windows.net -U login-P ******** -Q "select getdate()"
+                                                        ~~~~~~~~~~~~~~~~~~
Unexpected token '"select getdate()"' in expression or statement.
2017-04-11T21:15:51.1835153Z ##[section]Finishing: Execute Azure SQL : DacpacTask
```
It was working fine before.
The problems seems to be the @ sign. How Can I fix it? is there a way to go back to the previous version?

**Comment by mvvsubbu** [comment] 2017-04-12 09:36
Sorry for the trouble. I tried to reproduce the issue with @ sign in password, it was working for me.  To help you getting unblocked, can you share the following details

1. Can you share the release logs by setting system.debug variable value to true?
2. Are you using your own agent, if yes what is the PS Version?

**Comment by paddyfink** [comment] 2017-04-12 14:58
Hi @mvvsubbu , I sent the log via email. I use vsts hosted agent

**Comment by paddyfink** [comment] 2017-04-17 18:53
hello @mvvsubbu no news on this? Our CI is blocked because of this bug

**Comment by mvvsubbu** [comment] 2017-04-18 03:04
It doesn't seem to be happening because of @ symbol.  We can have a call, tell me your preferred time, my preferred time is 9AM - 6PM IST, if that doesn't work I can join late night around 9 - 11 PM IST

The following command we are running, can you try running the following command in your automation agent in PowerShell ISE editor.

( Invoke-Expression "&sqlcmd.exe --% -S askpamdbqa.database.windows.net -U pamalexander -P <YourPassword> -Q `"select getdate()`"" -ErrorVariable errors -OutVariable output 2>&1 ) | Out-Null

**Comment by mvvsubbu** [comment] 2017-04-24 04:04
Fix checked in will be delivered in next deployment and hence closing the issue. If anyone runs into this issue, send mail to RM_Customer_Queries at Microsoft dot com we can work together to get the fix applied to your account.

**Closed by mvvsubbu** 2017-04-24 04:04 UTC
Labels: Area: Release
