### ISSUE TITLE
Publishing test results with failed tests does not fail the build

### ISSUE THREAD

**Issue by strtdusty** [Microsoft/vsts-tasks#1268] opened 2016-02-20 22:01 UTC
I am using xunit test through DNX.  For each project we generate a test result xml file and use the "publish test results" task to publish the results to the build.  The results get published correctly and we can see that some tests failed.  When tests fail, however, the build is not marked as failed.  I could fail the build when running xunit, but the results would not get published.  Is there a way for the build to look at the published test results and fail if there are test failures?

**Comment by chrisrpatterson** [comment] 2016-02-22 15:52
You can mark the Publish Test Results task as Always Run and it will run even for a failed build.

**Comment by richardszalay** [comment] 2017-01-10 01:10
@chrisrpatterson Your response is unrelated to @strtdusty's issue. The issue is that if a test fail, the "build" is still marked as successful. The successful build contains a failed test, sure, but it will go unnoticed so it's almost irrelevant.

**Comment by liamnichols** [comment] 2017-02-25 18:55
+1 for this. I want to use the VSTS build system for our mobile projects but back it via Jenkins jobs as the Xcode support is somewhat lacking for my needs.

My problem is that I have to mark the Jenkins job as unstable as I can only download artefacts (my junit results) from the "last successful build". This then means that my build appears to have succeeded if the user doesn't actually click into the build to investigate.

**Comment by Yaash19** [comment] 2017-05-17 19:54
@strtdusty 

how did you resolve this ? i am having similar issue.

**Comment by strtdusty** [comment] 2017-05-17 20:06
I used @chrisrpatterson 's suggestion.  Our builds end up being marked as failed though which is correct.

**Comment by asinitson** [comment] 2017-06-22 07:43
Why this is marked as closed? Although problem is resolved for the original request, the issue **Publishing test results with failed tests does not fail the build** is still not resolved as @liamnichols mentioned. Here are the steps to reproduce:

1. Create build definition with only one step: "Publish Test Results"
2. Run the build

Expected result:
If some of the tests are failed, then build should also failed.

Actual result:
Build always passes, irrespective of the results of the test.

Solution proposed above only works if you run the tests as a previous build step. But it is still impossible to fail the build purely depending on the published results. 

Why is this important? If you have your build running outside of TFS bubble and just "publish" the results of the tests, then you still want to know a status of the build.

**Comment by cmuris** [comment] 2017-07-12 08:54
@chrisrpatterson: Can you reopen this? as mentioned by @asinitson this is still a problem if you do not run your tests in TFS/Team Services. The build does not fail when the published results contain failed tests.

**Comment by pakdev** [comment] 2017-10-31 22:09
@chrisrpatterson Can you please re-open this issue given @asinitson's rationale?

**Comment by alejandro5042** [comment] 2017-10-31 22:13
There should _at least_ be a checkbox for selecting whether the published test results can fail the build.

**Comment by kngrace** [comment] 2017-11-15 23:32
I'm running two different test suites and I am able to fail the build with the test task itself for only one of them but not for the other. I'd like to be able to rely on the Publish Test Results task to mark a build failure if any of the tests it has published have failed.

**Comment by pakdev** [comment] 2017-11-16 19:36
This is also a problem for Javascript tests/linting. My jshint/jscs failures are reported in the Tests tab, but the "npm test" and "Publish Test Results" tasks pass.

**Comment by asinitson** [comment] 2017-11-17 05:00
Hey, everyone!

Since original bug reporter has his problem solved and this bug report is closed, I guess it makes sense to add another bug report. @chrisrpatterson: Is anybody looking at the comments for this closed bug reports? Are you considering re-opening it?

I will wait a day or two for the reply and then create another report, so we at least would have some kind of statement: "won't fix" or "planned in some future release".

**Comment by ericsciple** [comment] 2017-11-17 07:06
User voice is probably a better place for this feedback.

I'll re-open and assign to the appropriate team to see the feedback. This repo isn't used to track feature requests, so I would expect the issue to get closed again.

**Comment by alejandro5042** [comment] 2017-11-17 15:46
@ericsciple I think this is a bug, not a feature request. Do you track bugs in this repo?

At any rate, I suggest making it clear in your README that the UserVoice (link?) is the primary place for feature feedback. I certainly didn't know that--others won't either. You could even consider [disabling the issues tab](https://help.github.com/articles/disabling-issues/) if truly no one is checking these. Otherwise, it might be good to do a weekly review or risk appearing like Microsoft doesn't care about this repo. Just a friendly suggestion :)

**Comment by ncunning** [comment] 2018-01-03 09:58
Is the solution to this from @chrisrpatterson not correct.
In my case: I use Command Line Step and Set the Task to "Fail on Standard Error". 
Then ensure that the Publish Test Results Under Control Options -> "Run this Task" is set to "Even if a previous task has failed, unless the build was canceled"

I have this solution working for karma tests which fail yet still return the test results.
Using JUnit as my test reporter for an Angular Project. 

Note: Also if running tests where don;t force a clean checkout. Ensure that there is a task to remove the test and coverage folders prior to running the tests otherwise the Publish task step will pick up the xml test results from a previous test

**Comment by pakdev** [comment] 2018-01-03 17:11
@ncunning Interesting, I didn't know the Command Line task allowed "Fail on Standard Error". My workaround was to use/create "reporters" specific to VSTS ([jscs-reporter-vso](https://github.com/EngageSoftware/jscs-reporter-vso), [jshint-vso-reporter](https://github.com/pakdev/jshint-vso-reporter)) and to manually parse C# TRX files. Now, if a test failure is detected, [logging commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) are written to stdout to fail the build. I think this is the most appropriate solution since the step that fails is the actual testing step - not the publishing step. The only downside is that the test results need to be parsed twice: once to determine if there are failing tests and once in Publish Test Results.

**Comment by ncunning** [comment] 2018-01-03 17:23
@parkdev my current setup has both npm task with custom command  "npm run test-ci" where in my package.json scripts section I use
"test-ci": "karma start ./test-config/karma.conf.js --single-run --code-coverage",
and also a command line task with ng test --single-run --code-coverage

Both Fail the Build but return results to the Tests section with Fail on Standard Error checked

This way i get Test Result of format JUnit which the Publish Test Reusult Task can deal with and I also have  code coverage using cobertura which Publish Code Coverage Results Task can also display

**Comment by ncunning** [comment] 2018-01-03 17:28
@pakdev When i look at the output it is the actual testing step which fails. The Publishing Tests Results allow the Tests section to display the charts and failed test etc..

**Comment by pakdev** [comment] 2018-01-04 02:34
@ncunning Sorry, I meant our solutions are better than failing the Publish Test Results task as suggested by this issue.

**Comment by vinodjo** [comment] 2018-01-04 08:18
The purpose of Publish Test Results Task is to report the test results, hence if task is able to report all the results successfully it is marked as success even if it there were test failures. If the test execution does not return failure for a failed test, here is a sample that queries the failed tests and returns failure, which you can refer to drive the expected behavior https://github.com/ManojBableshwar/VstsTestRestApiSamples/blob/master/QueryTestRunResultsAndFailBuild/QueryTestRunResultsAndFailBuild.cs

**Comment by vinodjo** [comment] 2018-01-16 06:57
As suggested above, closing the issue.

**Closed by vinodjo** 2018-01-16 06:57 UTC
Labels: Area: Test, enhancement

**Comment by Nekobravo** [comment] 2018-05-24 02:35
help´
![image](https://user-images.githubusercontent.com/23462665/40461482-97beb568-5ed9-11e8-8ff3-364513ba344e.png)

**Comment by DalSoft** [comment] 2018-05-25 16:09
The new .NET Core VSTS tasks for dotnet test allow you to publish as part of the one step.

If you can't use them go with @chrisrpatterson suggestion Publish Test Results task as Always Run, then add the following command line task to fail the build:

```
if not "%agent.jobstatus%"=="Succeeded" (
    exit /b 666
)
```

**Comment by ed-alertedh** [comment] 2018-10-17 06:05
A key detail that I hadn't thought about is that my test runner script needed to exit with a non-zero status code when any tests failed. Because I was running two sets of tests with the same bash script, that wasn't always the case if the second set of tests all passed.

I found a similar workaround to what @DalSoft suggests here: http://hermit.no/conditionally-fail-build-pull-requests-tfs-vsts/. In YAML the workaround from the linked blog post essentially looks like this (I opted to make it always fail, not just on PR's):
```
- script: 'echo 1>&2'
  failOnStderr: true
  displayName: 'If above is partially succeeded, then fail'
  condition: eq(variables['Agent.JobStatus'], 'SucceededWithIssues')
```

**Comment by brcrista** [comment] 2018-10-22 15:13
This keeps coming up, so let me try to clarify the expected behavior here:
- Your *test step* should succeed if your tests succeed, and fail if any of your tests fail.
- *Publish Test Results* should succeed if the JUnit XML file (or whatever format it is) was successfully uploaded, and fail if any of your tests fail.
- Since the default behavior is to fail fast when a step fails, Publish Test Results must be marked as "Run always."  Otherwise, it will get skipped if the test step fails.

I hear people suggesting that uploading failed tests with "Publish Test Results" should cause that step to fail (and therefore cause the build to fail).  I would argue that failing the "Publish" step is reporting the failure in the wrong place if the failure is actually in your test run.  Moreover, a failed test run should fail the build on its own -- it shouldn't require "Publish Test Results" to detect the failure, since that's just for reporting in your build summary.

I admit, it might take a minute to figure out the "Run always" setting.  But the intent of having build steps is to localize failures.  Feel free to speak up if you still disagree, but I hope that helps clear things up.

**Comment by DalSoft** [comment] 2018-10-22 16:02
@brcrista whilst technically correct as the publish hasn't failed the test task did - I think the confusion is because It's counter-intuitive to see green on the last build step if there is a failure. I expect to see red in the place that reports if my tests failed. 

This is why the dotnet core task runs and publishes the tests in together in one step.

**Comment by asinitson** [comment] 2018-10-24 19:32
@brcrista: Technically correct does not equal useful.

It might be that some people were confused. For me there was never any confusion. But maybe I missed some kind of guideline in the spirit of "task should only fail with single condition"?

Let me reiterate the use case:

0. Your tests run **outside of the Build Definition**, so **there is no return value you can use**. In other words **there is no test step** Build Definition could know of.
1. In Build Definition the only task you have is "Publish Test Results" (in my case I just read a file from a file share).

The outcome I wish I could have:
_Build is marked green when **test results were read and test results are positive**. I can have build results on the dashboard and if I see green I move on and I know that everything works._

Actual outcome:
_Unless your test results are not published (something is badly broken) your build is always green. So if you use dashboard green color is kind of useless, since it just means "test results were read out", not "everything is working correctly". Every time you have to go in and check it out._

Now to the solution:

* "Publish Task Results" might have provided an option "Fail, if any tests failed". I don't think it contradicts the current behavior in any way. "Pass if publishing passed" just becomes "Pass if publishing passed AND if all tests passed".

* Having another built in task the sole purpose of which is failing the build depending on the test results. That would also work (although would seem a bit strange that you need to read out the test results file yet again).

* The actual solution I have (ugly! I wish I could use something built in instead, but produces the result I want)
1. The test runner (which runs outside of build definition) writes a file if all test pass called `pass`
2. After publishing test results there is command line task which looks for the file named `pass`, if file is not found it returns non-zero value.

I even thought about parsing the test result file and deciding on the outcome, but that seems especially ridiculous if you consider that "Publish Test Results" already parses test results and has all the information needed to signal pass/fail.

**Comment by brcrista** [comment] 2018-10-25 13:43
Ok, I hear you.  Right now, Publish Test Results doesn't parse the results files, it just uploads them to the service, which does the actual processing when it displays your results on the "Tests" tab (much like publishing artifacts):

![image](https://user-images.githubusercontent.com/33549821/47504392-2bd6cb80-d83a-11e8-884e-30454d400d45.png)

That's why this suggestion would be a big change to the task.

I think the reason we haven't done the work for a special "Validate Test Results" task, or adding this functionality to Publish, is that most workflows do run and publish tests in the same job, and the step that runs the tests is usually the easiest and fastest place to fail the build.  It already has the knowledge and no files need to get parsed.

It sounds like there are some workflows that want this step.  Sorry to point you somewhere else, but <https://developercommunity.visualstudio.com/> is where we'd like you to suggest this -- we prefer to use Issues to track tasks that not working as intended.  Click "Suggest a feature:"

![image](https://user-images.githubusercontent.com/33549821/47500773-b7982a00-d831-11e8-8dc4-25f0005f7ebe.png)

That said, here's a short PowerShell script that will find the number of failures in a JUnit XML (even works on hosted *nix agents 😉):

```yaml
- powershell: |
    $junitXml = "junit/unit-test.xml"
    $(Get-Content $junitXml | Out-String) -match 'failures="(.*?)"'
    if ($matches[1] -eq 0)
    {
      Write-Host "No test failures"
    }
    else
    {
      # note that this will produce $LASTEXITCODE=1
      Write-Error "$($matches[1]) tests failed"
    }
  displayName: Check for test failures
```

**Comment by benken-parasoft** [comment] 2018-12-19 01:48
Is this new feature live in VSTS?  I'm not seeing the new checkbox.  When will it be available?

**Comment by brcrista** [comment] 2018-12-19 21:24
Yes, I meant this:

![image](https://user-images.githubusercontent.com/33549821/50248810-3fba2c00-03aa-11e9-9f20-517e23a92e07.png)

In YAML:
```yaml
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
```

**Comment by nigurr** [comment] 2018-12-20 01:49
@benken-parasoft, it will be available with next Azure Devops deployment (3 weeks away)

**Comment by divais** [comment] 2018-12-20 08:30
Hi, it isn't live yet and will be available in few weeks as we have deployment freeze for the holiday season. Sorry for the delay.

**Comment by hisuwh** [comment] 2019-01-29 10:30
Why has this been closed - this isn't available yet

**Comment by nigurr** [comment] 2019-01-29 10:47
@hisuwh It's getting rolled out. It should be available within 2-3 days for everyone.

**Comment by hisuwh** [comment] 2019-01-29 10:50
Ok thanks.  You're documentation has already been updated which adds to the confusion

**Comment by hisuwh** [comment] 2019-01-29 10:51
I'm using the YAML pipelines how will I know when I can use this feature?

**Comment by nigurr** [comment] 2019-01-29 11:30
Please follow this - https://docs.microsoft.com/en-us/azure/devops/release-notes/
Since deployment goes stages by stages, everyone should be getting update within 2-3 weeks.

**Comment by Huffers** [comment] 2019-01-31 15:21
Just found out a bunch of our tests had been failing for weeks but we didn't know because the build was green, hiding a bug in our production code. So infuriating.

Our build ran "dotnet test" a bunch of times manually in a PowerShell task because the tests need environment variables set, and the task ignored the exit codes of all but the last call to "dotnet test". 

Good to see "Fail if there are test failures" appear as an option, but seems to just be inviting mess-ups by not having it checked by default. Maybe checked by default in the next version of the Publish Test Results task?

**Comment by nigurr** [comment] 2019-02-01 06:09
@Huffers while we agree with "by default" it should be enabled, it breaks the compat scenario and cause more customer issues.
There could be existing pipelines which are already publishing results (with failed tests) however they might continue to run pipeline.
