### ISSUE TITLE
Run Functional Tests in TFS on Premise using NUnit3 Adapter

### ISSUE THREAD

**Issue by gedeh** [Microsoft/vsts-tasks#3206] opened 2016-12-07 16:45 UTC
We've been trying to run our Selenium tests directly in Selenium GRID VM to achieve faster tests run using TFS Run Functional tasks. Same set of test project, filter, and adapter works with regular Visual Studio Test task.

### Using Test Case filter
It keeps failing after test discovery by NUnit3 Adapter is finished. I suspect it is due to NUnit3 Adapter writes: `NUnit Adapter 3.6.0.0: Test discovery complete` to its output log as information which then seen as an error by DTAExecutionHost process as written in the log: `ExecutionTaskStateModel.AbortSlice : System.Exception: NUnit Adapter 3.6.0.0: Test discovery complete`

Attached below is the few last part of DTAExecutionHost.exe.log with obscured TFS app server and build server name: [DTAExecutionHost.exe.log.zip](https://github.com/Microsoft/vsts-tasks/files/637097/DTAExecutionHost.exe.log.zip)

For the task Test Filter criteria field, we tried:

- Without double quote: TestCategory=chrome&TestCategory=pbi&TestCategory=P1
- With double quote: "TestCategory=chrome&TestCategory=pbi&TestCategory=P1"

### Without Test Case filter
When we remove the value in Test Case filter, the task actually runs longer but all the tests status are Aborted. Similar message is written in the log: `NUnit Adapter 3.6.0.0: Test discovery complete`, but this time without `ExecutionTaskStateModel.AbortSlice : System.Exception: ` preceding the message. Instead, it is preceded by `DTAExecutionHost.exe, TAEF Engine Discovery: `.

And also, at the end of task, it shows warning `Error : One or more errors occurred.--->No matching tcm test case result found for test case result given by agent to publisher.`. I think this is may be an issue with the task itself.

Another DTAExecutionHost.exe.log is attached for issue without Test Case filter: [DTAExecutionHost.exe.log - without filter.txt.zip](https://github.com/Microsoft/vsts-tasks/files/637164/DTAExecutionHost.exe.log.-.without.filter.txt.zip)

Thanks,
Hendra

**Comment by gedeh** [comment] 2016-12-07 16:46
Almost forgot, Using TFS 2015 Update 3 On Premise. Thanks!

**Comment by prawalagarwal** [comment] 2016-12-15 13:50
Hi @gedeh 

Please use **Category=chrome&Category=pbi&Category=P1** instead of the filters you mentioned. NUnit has "Category" attribute in place of TestCategory. Please let us know if it worked.

Thanks

**Comment by gedeh** [comment] 2016-12-15 14:26
Hi @prawalagarwal,

Thanks for your reply, very much appreciated!

As described in my original issue post, exactly same filter (without double quote) works with _Visual Studio Tests_ task. _NUnit3 Test Adapter) translates _TestCategory_ filter passed to _VSTest.console.exe_ into NUnit _Category_ attribute. And more, _Trait_ filter in _Visual Studio Test Explorer_ also translated properly by the adapter.

I've tried your suggestion also, the result is still the same with above issue in section **Using Test Case Filter**

Thanks

**Comment by prawalagarwal** [comment] 2016-12-16 06:45
@gedeh  Run Functional Test task doesn't invoke Vstest.Console.exe. This task calls the Test Platform APIs directly and hence translation is not happening. I tried to reproduce your scenario and I hit the issue (with the same error messages) with TestCategory filter and when I changed it to Category it ran fine. Can you try once more?

In case the issue persists, can you send your RFT task snapshot at devops_tools@microsoft.com.

Thanks

**Comment by gedeh** [comment] 2016-12-16 11:24
@prawalagarwal Ah thanks for your clarification about relation between the task and VSTest.console.exe! I have run the build again but still no luck, so this could be problem with NUnit3 Test Adapter?

Attached the debug test task log here: 
[9_Run Tests Foo.Automation.Tests.dll on test machines.txt](https://github.com/Microsoft/vsts-tasks/files/656995/9_Run.Tests.Foo.Automation.Tests.dll.on.test.machines.txt)

Also the full DTAExecutionHost.exe.log file: 
[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vsts-tasks/files/657002/DTAExecutionHost.exe.log.txt)

I still get similar issue where the task is aborted with error messages I can look in DTAExecutionHost.exe.log like this:
`AddTestCasesToTcmRun.GetRunDetails : TestRun Id 111670`
`PERF WARNING: DiscoverTests:AddTestCases: took 986.5883 ms`
`DiscoverTests.PerformDiscovery : Test Discovery completed.`
`WARNING: DiscoverTests.PerformDiscovery: took 33128.2986 ms`
`Discovery.Run : Discovery run completed.`
`ExecutionTaskStateModel.AbortSlice : System.Exception: NUnit Adapter 3.6.0.0: Test discovery complete`

**Comment by grajdeanserghei** [comment] 2016-12-16 20:18
I'm getting same error.

```
DistributedTests: Test run '717' is in 'Aborted' state.
##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.
##[warning]DistributedTests: New test run created.
Test Run queued for Project Collection Build Service (amdaris).

##[warning]DistributedTests: Test discovery started.
##[warning]DistributedTests: Test Run Discovery Aborted . Test run id : 717
##[warning]DistributedTests: UnExpected error occured during test execution. Try again.
##[warning]DistributedTests: Error : NUnit Adapter 3.6.0.0: Test discovery complete

##[warning]DistributedTests: Test run aborted. Test run id: 717
##[error]System.Exception: The test run was aborted, failing the task.
##[error]PowerShell script completed with 1 errors.
```

@gedeh  how do you specify the test adapter path for NUnit? I've added NUnit test adapter dlls to " _C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions_" folder on machnie where test agent is installed.

**Comment by gedeh** [comment] 2016-12-16 21:00
@grajdeanserghei I copied both test solution source and output files to the remote test machine (where the test agent is deployed) in the folder as specified in **Test Drop Location** field. It's just like whats described [here](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/RunDistributedTests) in section **Test Adapters**

> Test Adapters: There is no explicit field to specify Test Adapter path in the task. The task automatically searches for "packages" directory that exists in the same folder as the .sln file (nuget restored directory structure). If your adapters are in a different directory or you did not copy over the source files, use a runsettings file with TestAdaptersPaths as described at https://msdn.microsoft.com/en-us/library/jj635153.aspx

**Comment by grajdeanserghei** [comment] 2016-12-16 23:55
@gedeh I see. My scenario is little bit different because I don't want to copy source code to the remote machine.
Thanks.

**Comment by gedeh** [comment] 2016-12-19 14:20
Yes if you can't copy source code you have to install the adapter as extensions in remote test machine. I am avoiding that to reduce maintenance of the remote test agent machine and flexibility to spawn new VM without setting them up manually.

I think you also can just copy .sln file and content of packages folder without all the source code to remote test agent machine. Honestly haven't tried this approach as well.

**Comment by prawalagarwal** [comment] 2016-12-20 12:48
@gedeh 
I was going through your logs and I came across this error:
_Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified._

Does your packages folder contain the nunit.framework dll?  My packages folder looks like this today
![image](https://cloud.githubusercontent.com/assets/13520100/21351013/8115aa98-c6e0-11e6-8bbb-7dd4fb89e9c4.png)

If the issue persists can we have a skype call? You can reach out to us at devops_tools[at]microsoft[dot]com for meetings details. Thanks.

**Comment by prawalagarwal** [comment] 2016-12-21 12:31
@gedeh 

One more thing we noticed in your logs (without the test case filter). The test case names in your plan (starting as KanaExpress.Auto....) are longer than 256 characters which is not supported in TFS. Please truncate or reduce the name of your test case to less than 256 characters. 
Thanks

**Comment by gedeh** [comment] 2016-12-21 15:19
@prawalagarwal thanks for the response, unfortunately I have no access to TFS recently, will update you with the details which:

- nunit nuget package properly copied along adapter
- truncate the test name should help

**Comment by gedeh** [comment] 2016-12-21 16:03
@prawalagarwal for the first one I can confirm boht NUnit and Nunit3TestAdapter packages are copied into solution packages folder in remote test VM. Notice the packages date time is 5 days ago:

![image](https://cloud.githubusercontent.com/assets/6280668/21395797/cdfec8c0-c795-11e6-9665-55ac49c77366.png)

I will try to ask one of our team member to clean the remote test machine and re-run it again to ensure if packages is copied from the  build

About test name, I will try to run another set of tests from same DLL with shorter names. Unfortunately our UI tests use associated Test Case work item title to ease re-running failed TC manually if we found some tests failed to confirm regression occurs. Will let the guys know about this limitation too.

Will update you with our latest trial result. 

Thanks

**Comment by gedeh** [comment] 2016-12-21 17:00
@prawalagarwal seems message _Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified._ is because it try to use test DLL in obj folder instead of ones in bin folder. 

Will try to update my build definition to skip copying content of obj folder

**Comment by gedeh** [comment] 2016-12-21 19:28
@prawalagarwal Excellent! Now the build went fine! Here's an overview of my build steps:

1. Build the solution
2. Copies everything in $(Build.SourcesDirectory under bin and packages folder, also .sln file to $(Build.BinariesDirectory)
3. Copies everything in $(Build.BinariesDirectory) to remote test machine
4. Deploy test agent to remote test machine
5. Run Functional tests in remote test machine

Step 2 is what I modified. Before, it copies everything in $(Build.SourcesDirectory), so we see that error _Could not load file or assembly 'nunit.framework' or one of its dependencies. The system cannot find the file specified_ simply because in step 5, I use **\Foo.Tests.dll so it also try to include what's in obj folder. I tried to modify step 5 to use **\bin\Release\Foo.Tests.dll, the log complains that the path is wrong.

Note that I still use same test dll, this time I use Category with a short test names with filter as you mentioned before: _Category=Foo_

So the summary is:

1. Do not use test name longer than 256 characters
2. Do not include obj folder in copy to remote test machine task
3. For NUnit, use _Category_ instead of _TestCategory_ to filter the tests

Many thanks for your support!

**Comment by gedeh** [comment] 2016-12-21 19:41
@grajdeanserghei If its OK for you, this issue might better be closed

**Comment by prawalagarwal** [comment] 2016-12-22 09:39
@gedeh Thanks for the detailed summary.
@grajdeanserghei  we are closing this issue now. If you are still facing the same, feel free to reopen.

**Closed by prawalagarwal** 2016-12-22 09:39 UTC
Labels: Area: Test

**Comment by wergil123** [comment] 2017-09-25 04:35
@gedeh 

Hi, can you provide some snapshots regarding the build steps you provided? I'm lost, beginner here :) By the way, i'm using NUnit 2..will it be different?

Hope to hear from you soon.

Thank you.

Regards,
WL.
