### ISSUE TITLE
Cannot build Xamarin.IOS project on Mac -> missing parameterless constructor?

### ISSUE THREAD

**Issue by mauritsb** [Microsoft/vsts-tasks#6273] opened 2018-01-23 10:33 UTC
This problem was mentioned in a wrong thread.
See issue here: [https://github.com/Microsoft/vsts-agent/issues/1373](https://github.com/Microsoft/vsts-agent/issues/1373)

**Comment by bryanmacfarlane** [comment] 2018-01-23 12:42
Pasting in context from the other thread

## Agent version and platform

Version of your agent?
2.122.1

OS of the machine running the agent? 
OSX

## VSTS type and version
On-Prem TFS

If On-Prem TFS, which release
2017 Update 3

## What's not working?
I'm setting up a build environment for build our xamarin.forms apps via tfs builds. I've successfully set up the android build on a windows build machine, now I'm trying to build the IOS app on a Mac. I've installed an configured the OSX build agent, and installed visual studio for mac. Now when building our app, I get an error that the Version object (System.Version) doesn't have a parameterless constructor. The error is in the .net Standard 2.0 project which is the shared library used in both versions of the app:

General/Settings.cs(62,32): error CS1729: 'Version' does not contain a constructor that takes 0 arguments 

The compiler used is:
/Library/Frameworks/Mono.framework/Versions/5.4.1/lib/mono/4.5/csc.exe
might this be the wrong one? and if so. Why it is using this compiler?

I am using msbuild 15 (which is confirmed in the build log). This is full compiler command being executed:
[completecsccommand.txt](https://github.com/Microsoft/vsts-agent/files/1639711/completecsccommand.txt)
The system.Version we use from .net standard 2.0 is in the netstandard.dll of .net standard 2.0. Might it be that a wrong version of .net standard is being used for compiling? And if so. Why? Am I doing something wrong, or is it a bug?


Now this guide: https://docs.microsoft.com/en-us/vsts/build-release/apps/mobile/xamarin?tabs=vsts
states that I should create a separate configuration for IOS builds containing only the IOS app project, but this doesn't make any sense, because then I get all kinds of errors about classes from the shared library missing (duh, the shared library is not built in this configuration). However, I found a different guide (https://blog.xamarin.com/continuous-integration-for-ios-apps-with-visual-studio-team-services/) that DOES enable the shared projects in the IOS configuration. However, that causes the parameterless constructor error to re-appear. 

I might be doing something fundamentally wrong. But I've googled my ass off, and there seems to be no guide in how to do this.

## Agent and Worker's diag log
[Agent_20180117-154648-utc.log](https://github.com/Microsoft/vsts-agent/files/1639651/Agent_20180117-154648-utc.log)

**Comment by madhurig** [comment] 2018-01-23 18:27
The issue seems to be with restoring the nuget packages target .NET standard. You can see warnings in your logs:

2018-01-18T07:40:13.2365830Z   /Applications/AppsTFSAgent/_work/1/s/iProva/Mobile apps/Dev/iProvaCapture/iProvaCapture/iProvaCapture.csproj : warning NU1701: Package 'PCLCrypto 2.0.147' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

Please check the default version of mono and nuget on your OSX build server. What version of VS for Mac do you have installed?

Thanks,
Madhuri

**Comment by PaulVrugt** [comment] 2018-01-23 18:59
The warning you mention doesn't have anything to do with the build error. The same warning appears on the vs for Mac and windows machine where the build does work, and I know the cause of the warning.  I have the latest version of vs for mac installed (installed last week). My colleagues can probably tell you the version of mono and nuget (they'll reply to this thread)

**Comment by mauritsb** [comment] 2018-01-25 08:54
Below are the current versions that we are using on the OSX build server.

- Visual studio community 2017 for Mac Version 7.3.3 (build 5)
- Mono 5.4.1.7
- NuGet 4.3.1.4445

**Comment by madhurig** [comment] 2018-01-25 21:34
Can you please try using NuGet 4.5? I recently found that .NET standard packages were not being restored correctly with Nuget 4.3 and nuget 4.5 helped.

Thanks,
Madhuri

**Comment by PaulVrugt** [comment] 2018-01-30 11:11
Hello,

I've updated nuget to 4.5, but it doesn't seem to help.
Besides this, is there any way to show the version of nuget used in the "xamarin.ios" task? 

When using a separate "nuget restore" task, it lists the version used (this one uses 4.0.0 so it fails, and I can't seem to point it to 4.5, even when it is installed on the mac). 

However, I cannot verify nuget 4.5 is used when performing the nuget restore within the "xamarin.ios" task since it doesn't log it, and i don't seem to have a way to set the nuget verbosity in the task.

I do see nuget restores .net standard 1.6 from nuget for the ios project, and no restore for .net standard 2.0 for this project. I find this weird, since the ios project only has a package reference to xamarin.forms, and xamarin.forms doesn't have any package references. I tried to explicitly add a package reference to .net standard 2.0 to the ios project, but this didn't help.

What else can i try here?

**Comment by madhurig** [comment] 2018-01-30 21:42
@PaulVrugt: Sorry you are still having issues. "Xamarin iOS" task will use the default version of "nuget" that is in the PATH. You can run "which nuget" on the macOS build server to find it's location or just run "nuget" on the terminal. 

Can you try running "dotnet restore" and see if it works for the .NET standard 2.0 packages? Similar issue is described here:
https://developercommunity.visualstudio.com/content/problem/96670/package-restore-failed-nuget-1.html  

Thanks,
Madhuri

**Comment by PaulVrugt** [comment] 2018-01-31 10:01
@madhurig 

I can confirm the default version of nuget on the mac (in the path) is now nuget 4.5, so that doesn't seem to be the issue

running dotnet restore on the solution i'm trying to build shows some errors.
[dotnetrestoreoutput.txt](https://github.com/Microsoft/vsts-tasks/files/1681208/dotnetrestoreoutput.txt)

The issue in the link you gave me doesn't seem to be related to this issue. In that issue, errors about not being able to restore packages are displayed, but that is not the case in this issue. The nuget doesn't fail, the build does, because it uses the wrong .net standard version for some reason.

About the warnings about the restore you mentioned earlier:
2018-01-18T07:40:13.2365830Z /Applications/AppsTFSAgent/_work/1/s/iProva/Mobile apps/Dev/iProvaCapture/iProvaCapture/iProvaCapture.csproj : warning NU1701: Package 'PCLCrypto 2.0.147' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

this is caused by the fact that I use some packages that are not compatible with .net standard. They are still included by using the assetfallback to .net framework. The same warnings appear in the successful builds on visual studio for windows and mac, so they don't seem to be related to the issue.

**Comment by PaulVrugt** [comment] 2018-01-31 15:44
@madhurig 

I've done some more investigation, and it seems a reboot of the mac and restarting the build agent has fixed the issue. The build now succeeds and uses the correct version of .net standard

Thanks for your help!

**Comment by madhurig** [comment] 2018-01-31 16:35
@PaulVrugt: Thanks for posting your solution. If reboot helped, I am curious if you were running into some nuget client issue that got resolved by reboot. 

We have found that with .NET standard DLLs, running both dotnet restore and nuget restore with latest version of nuget (4.5) helps get the right set of packages installed. In VSTS we have a task to install latest version of nuget and run nuget restore which helps most of the customers. Your version of TFS does not have those tasks. We understand the pain points and are trying to improve the experience.

Thanks,
Madhuri

**Closed by madhurig** 2018-01-31 16:35 UTC
Labels: Area: CrossPlatform, Area: Mobile, Area: Packaging
