### ISSUE TITLE
ConfigureWinRM.ps1 downloads from non existing urls

### ISSUE THREAD

**Issue by RomanDidenko** [Microsoft/vsts-tasks#2908] opened 2016-10-21 01:11 UTC
Tasks/PowerShellOnTargetMachines/ConfigureWinRM.ps1 script try to download tools from non existing url https://azurergtaskstorage.blob.core.windows.net/winrm/makecert.exe

**Comment by zhy2002** [comment] 2016-10-21 03:00
+1

**Comment by ignacy130** [comment] 2016-10-21 07:25
+1

**Comment by pavanadepu2** [comment] 2016-10-21 13:16
@RomanDidenko , @zhy2002 , @ignacy130 , Thanks much for reporting the issue. 
The issue is fixed, you may retry your script to configure the WinRM.

**Comment by asranja** [comment] 2016-10-24 12:57
Closing this issue as it has been resolved by @pavanadepu2

**Closed by asranja** 2016-10-24 12:57 UTC
Labels: Area: Release
