### ISSUE TITLE
DotNetCoreInstaller Task needs to set DOTNET_ROOT

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vsts-tasks#7255] opened 2018-05-19 12:47 UTC
## Issue Description

.NET Core 2.1 Global Tools will error out if the .NET Core SDK is installed to a non-default location. Setting and exporting DOTNET_ROOT as an environment variable solves this:

https://natemcmaster.com/blog/2018/05/12/dotnet-global-tools/#installing-the-net-core-cli-into-a-non-default-location
https://github.com/dotnet/cli/issues/9114

### Error logs

`The required library C:\Program Files\dotnet\host\fxr\2.0.7\hostfxr.dll does not support relative app dll paths.`

**Comment by wli3** [comment] 2018-05-23 22:46
https://github.com/Microsoft/vsts-tasks/compare/master...wli3:export-dotnet-root?expand=1

I think the above should be enough. However, I don't know how to generate VSIX(no vss-extension.json
) so I can test it on my Account.

**Comment by bryanmacfarlane** [comment] 2018-05-23 22:51
@wli3 - you want to do toolLib.setVariable

https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L120

It will set the envvar but it will also echo to agent to ensure variable is set downstream for other out of proc tasks.  That's also what the prepend line does above it - instructs the agent to alter path for future out of proc tasks

hth

**Comment by wli3** [comment] 2018-05-23 22:58
Thank you! I changed my branch to 

```typescript
+    // set DOTNET_ROOT for dotnet core Apphost to find runtime since it is installed to a non well-known location.
+    taskLib.setVariable('DOTNET_ROOT', toolPath);
```

However I still don't know how to test it, what is the command to build vsix? I cannot find it on the repo easily. Also what is the shipping cadence if this is merged?

**Comment by bryanmacfarlane** [comment] 2018-05-23 23:12
@sachinma can help you test.

Details if you're interested ...

Here's how to build:

https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md

You can run the the task interactively :) 

https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/stepbystep.md#run-the-task

You will have to set this var:
https://github.com/Microsoft/vsts-task-tool-lib/blob/master/tool.ts#L500

These are in the box tasks so they are not vsix extensions.  You can upload directly to your account using tfx.  (vsix in marketplace ends up being a vehicle to backend while tfx does it directly to your backend).

Ensure you bump task.json patch version.

**Comment by wli3** [comment] 2018-05-25 21:16
Thanks! I managed to upload with `tfx build tasks upload --task-path .` and tested on my Account. I am sending pull request

**Comment by onovotny** [comment] 2018-05-30 13:17
@wli3 @bryanmacfarlane Any idea how long it'll take this task to get pushed out to the instances and available on the agents?

I'm seeing this now

```
2018-05-30T13:14:48.6153043Z Submitting D:\a\1\a\Client\SignClient.1.0.18-preview.g5beca77a59.nupkg for signing
2018-05-30T13:14:48.6474148Z It was not possible to find any compatible framework version
2018-05-30T13:14:48.6477080Z The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
2018-05-30T13:14:48.6478870Z   - Check application dependencies and target a framework version installed at:
2018-05-30T13:14:48.6479462Z       C:\Program Files\dotnet
2018-05-30T13:14:48.6480529Z   - Installing .NET Core prerequisites might help resolve this problem:
2018-05-30T13:14:48.6481582Z       http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
2018-05-30T13:14:48.6482768Z   - The .NET Core framework and SDK can be installed from:
2018-05-30T13:14:48.6483355Z       https://aka.ms/dotnet-download
2018-05-30T13:14:48.6484726Z   - The following versions are installed:
```

**Comment by wli3** [comment] 2018-05-30 17:56
@onovotny could you also include the text after "The following versions are installed:" ? 

I think this should be a different issue. The runtime you packed with is different than the runtime available on the build agent. And because preview runtime won't move forward you need to make sure the build agent version is higher than the version you pack your tool with. However, release version of 2.1.300 is just out, it is a good time to repackage and republish your tool to nuget.

**Comment by onovotny** [comment] 2018-05-30 18:34
@wli3 It was packed and run on the same framework -- I built it in a previous step and am installing it from a local path to execute.

Full build is here and you can see the failing step.
https://orennovotny.visualstudio.com/GitBuilds/_build/index?buildId=696&_a=summary

It's not finding the final 2.1 framework:

```
2018-05-30T13:14:48.6484726Z   - The following versions are installed:
2018-05-30T13:14:48.6485518Z       1.0.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6485784Z       1.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6486615Z       1.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6487468Z       1.0.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6488407Z       1.0.9 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6489739Z       1.0.10 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6491648Z       1.0.11 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6493427Z       1.1.1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6495318Z       1.1.2 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6496382Z       1.1.4 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6500727Z       1.1.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6501185Z       1.1.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6501587Z       1.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6503551Z       1.1.8 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6503844Z       2.0.0 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6504598Z       2.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6505622Z       2.0.5 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6507354Z       2.0.6 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6508806Z       2.0.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
2018-05-30T13:14:48.6510944Z       2.1.0-rc1 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by wli3** [comment] 2018-05-30 18:41
@onovotny i see the problem. VSTS task has not been deployed yet. The version should be "0.1.8". It is still 0.1.7 from the log. Meanwhile, there is some SDK built in agent in under directory `C:\Program Files\dotnet`. Since apphost will search `C:\Program Files\dotnet` when DOTNET_ROOT is not set. So it only finds the following old SDKs. We still need to wait for deployment of the VSTS task.

```
2018-05-30T13:12:49.3508667Z ##[section]Starting: DotNetCoreInstaller
2018-05-30T13:12:49.3705025Z ==============================================================================
2018-05-30T13:12:49.3705368Z Task         : .NET Core Tool Installer
2018-05-30T13:12:49.3705661Z Description  : Acquires a specific version of .NET Core from internet or the tools cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
2018-05-30T13:12:49.3705950Z Version      : 0.1.7
2018-05-30T13:12:49.3706136Z Author       : Microsoft Corporation
2018-05-30T13:12:49.3706347Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=853651)
2018-05-30T13:12:49.3706592Z ==============================================================================
```

**Comment by onovotny** [comment] 2018-05-30 18:43
Right...any idea when that's going to be @bryanmacfarlane?

**Comment by bryanmacfarlane** [comment] 2018-05-30 19:02
It won't be for a few weeks unless it's patched.

Re-opening.  @sachinma team owns it so they can patch prod.

**Comment by onovotny** [comment] 2018-05-30 19:32
This is critical....

**Comment by bishal-pdMSFT** [comment] 2018-05-31 08:49
@wli3 @onovotny I get following output when I do "dotnet --info" after installing version 2.1.300 using installer task. I can see that 2.1.300 is listed with correct path

> 2018-05-31T08:33:08.7803823Z .NET Core SDKs installed:
> 2018-05-31T08:33:08.7804008Z   1.0.1 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7804216Z   1.0.4 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7804402Z   1.1.4 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7804609Z   1.1.5 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7804812Z   1.1.7 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7804998Z   1.1.8 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7805195Z   1.1.9 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7805602Z   2.0.0 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7806564Z   2.0.3 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7807332Z   2.1.2 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7807598Z   2.1.4 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7807768Z   2.1.100 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7807915Z   2.1.101 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7808081Z   2.1.102 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7808223Z   2.1.103 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7808364Z   2.1.104 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7809014Z   2.1.105 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7809181Z   2.1.200 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7809329Z   2.1.300-rc1-008673 [C:\Program Files\dotnet\sdk]
> 2018-05-31T08:33:08.7809552Z   2.1.300 [C:\hostedtoolcache\windows\dncs\2.1.300\x64\sdk]

I am still using old task version. Can you tell me how to repro this?

**Comment by onovotny** [comment] 2018-05-31 10:18
In a script, you should be able to do the following:

```
dotnet tool install --tool-path . dotnetsay
dotnetsay
```

**Comment by onovotny** [comment] 2018-05-31 10:31
I can confirm that it's working for me as well: https://orennovotny.visualstudio.com/GitBuilds/_build/index?buildId=708

**Comment by bishal-pdMSFT** [comment] 2018-05-31 11:45
Cool! Closing this issue.

**Closed by bishal-pdMSFT** 2018-05-31 11:46 UTC
Labels: Area: Release

**Comment by wli3** [comment] 2018-05-31 17:41
Thank you @sachinma @bishal-pdMSFT

**Comment by wli3** [comment] 2018-09-27 16:34
@bishal-pdMSFT bryanmacfarlane  I am wondering is you know why there is a regression on Azure DevOps? 
 https://github.com/dotnet/cli/issues/8368#issuecomment-424963647

**Comment by bishal-pdMSFT** [comment] 2018-09-27 16:42
This is working. Why do you think there is a regression? The issue here was that dotnet was not able to run tool even when it was provided with full path for the tool location.
