### ISSUE TITLE
[AzurePS] Service principal authentication appears broken

### ISSUE THREAD

**Issue by blbrekelmans** [Microsoft/vsts-tasks#1681] opened 2016-05-10 02:47 UTC
My releases appear to be broken - something which I think is related to the VSTS Agent. I tried a number of different pools and the errors are consistent:

Agents using 1.0.21 AzurePowershell.ps1
version: 1.98.1, OSVersion: Microsoft Windows NT 6.2.9200.0 _ <- identical for all 3 below_
##[error]Service principal authentication is not supported in version '1.0.3' of the Azure module.
##[error]Service principal authentication is not supported in version '1.3.0' of the Azure module.
##[error]Service principal authentication is not supported in version '1.3.2' of the Azure module.

Another agent is running an older version of azure PS, which is working (but failing later)
Executing the powershell script: C:\...\AzurePowerShell\1.0.21\AzurePowerShell-Legacy.ps1 
Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1 
AzurePSCmdletsVersion= 0.9.4

Any clue? Using a connected service with client ID and secret.

**Comment by ericsciple** [comment] 2016-05-10 05:53
I think you may need to use certificate authentication with the (classic) Azure module or switch to AzureRM for service principal authentication.

I just tested service principal auth with the version of AzureRM module on my box. It's working. I installed from the gallery (`Find-Module`/`Install-Module`) and have this version:
```
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM\1.2.2\AzureRM.psd1 -Global
Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\AzureRM.profile\1.0.5\AzureRM.profile.psd1 -Global
```

After you install the AzureRM module, it contains exactly one command which can be used to install the rest of the AzureRM modules.

**Comment by blbrekelmans** [comment] 2016-05-10 15:55
We are using ARM connections everywhere - and deployment agents with the same Azure PS have worked before - I think it may be related to the agent or tasks update.

**Comment by ericsciple** [comment] 2016-05-10 17:35
You try setting a variable `preferazpsoverps3` to `true`. That reverts to previous sprint's task handler. That may unblock you. The updated task prefers the Azure/AzureRM module installed from the gallery over the one installed from the web platform installer. I think it may be finding one installed from the gallery now, whereas it was picking the other before.

**Comment by ericsciple** [comment] 2016-05-12 05:25
I have a PR that I think will fix your issue https://github.com/Microsoft/vsts-tasks/pull/1706

Let me know if you'd be willing to try out the fix before it rolls out everywhere in production. The back-compat variable will still work, so even if it doesn't fix it then you're in the same place :)

**Comment by ericsciple** [comment] 2016-05-12 15:41
Nevermind, I think I see the issue you ran into. Prepping a PR now.

**Comment by ericsciple** [comment] 2016-05-12 19:33
This PR should fix it: https://github.com/Microsoft/vsts-tasks/pull/1714

Let me know if you'd be willing to try it out before it rolls out with the next production. I'd like to get validation sooner.

**Comment by ericsciple** [comment] 2016-05-16 20:27
Discussed offline. Updating the connection type worked around the issue. My PR should fix it as well when it rolls out with the next release (if anyone else is running into it). I'll leave the issue open until the next release finishes rolling out.

The issue is related to this history of the task. RM connections originally didn't have their own endpoint type and the task was not taking that into account.

**Comment by ericsciple** [comment] 2016-06-03 19:00
Closing now that the deployment has rolled out.

**Closed by ericsciple** 2016-06-03 19:00 UTC
