### ISSUE TITLE
Azure App Service Deploy: SetParameters are not written to Web.config consistently

### ISSUE THREAD

**Issue by Turochamp** [Microsoft/vsts-tasks#4004] opened 2017-04-12 13:17 UTC
I've trying to use web.config transformation and release manager according to the instructions in this post:
https://blogs.msdn.microsoft.com/alming/2017/02/09/using-web-config-transforms-and-release-manager-tfs-2017team-services-edition/

Problem is settings in the SetParameter.xml file are not written to Web.config consistently. Usually it's not written, but sometimes it is. I've yet to understand the cause. 

Are the instructions in the post (written February 9, 2017) supported? 

Attached is JSON for the tasks.
[JSON RM tasks.txt](https://github.com/Microsoft/vsts-tasks/files/916598/JSON.RM.tasks.txt)

**Comment by vincentdass** [comment] 2017-04-14 07:04
@Turochamp , thanks for reporting the issue.
XML variable substitution feature is available in **3.*** version of  Azure App Service Deploy task.
Now, you can directly substitute values in web.config using the same feature.
![image](https://cloud.githubusercontent.com/assets/20121508/25035978/99b0c118-210e-11e7-9aa6-e4e1645dcfb8.png)
Please do try this instead of tokenizer task to update config files.

**Comment by Turochamp** [comment] 2017-04-14 08:06
@vincentdass, thanks for prompt reply.

As far as I know, the XML variable substitution feature in 3.* does is not an suitable replacements as it does not support fail on missing variable. This is important as Fail Fast is one of the requirements. The JSON variable substitution feature looks interesting though as a possible solution. I would like to see more documentation for this feature though (my Google searches finds nothing). Do you access to this or know who does?

I've emailed logs of previous releases. I've checked the updated values of web.config using Kudo Debug Console. Ensuing the release indeed created the file by deleting it beforehand.

**Comment by vincentdass** [comment] 2017-04-26 09:26
@Turochamp , Is the issue resolved ?
If not, please follow the instructions we provided you via mail and send the logs.

**Comment by mvvsubbu** [comment] 2017-05-24 09:32
Any update?

**Comment by mvvsubbu** [comment] 2017-05-30 04:34
As the issue is more than a month I am assuming you are unblocked and closing it. Feel free to re open the issue, if you are still facing

**Closed by mvvsubbu** 2017-05-30 04:34 UTC
Labels: Area: Release, AzureAppService
