### ISSUE TITLE
Allow skipping artifact creation for Publish Symbols

### ISSUE THREAD

**Issue by brett3210** [Microsoft/vsts-tasks#3284] opened 2016-12-21 02:45 UTC
The following site:
https://www.visualstudio.com/en-gb/docs/build/steps/build/index-sources-publish-symbols
states:
"You can also store your symbols with your drops"

However, if I set "Path to publish symbols" in the "Publish Symbols Path" Task to:
$(build.artifactstagingdirectory)

I receive the following error:
2016-12-21T02:13:27.6848873Z ##[error]Unable to process command '##vso[artifact.associate TransactionId=0000000001;artifactname=Symbols_release;artifacttype=SymbolStore]C:\a\1\a' successfully. Please reference documentaion (http://go.microsoft.com/fwlink/?LinkId=817296)
2016-12-21T02:13:27.6908873Z ##[error]Unsupport artifact location: C:\a\1\a

**Comment by ericsciple** [comment] 2016-12-21 04:22
@brett3210 does it fail the build or just create a warning issue?

do you really need to publish the symbols, or would indexing-only suffice? indexing will inject the source server info into the pdb files, and then leave the "Path to publish symbols" as empty. would that work for your scenario?

**Comment by brett3210** [comment] 2016-12-21 04:59
Yes, we do require the symbols to be published sorry

**Comment by ericsciple** [comment] 2016-12-21 06:50
ok if you need the layout of the symbols to be organized into a symbol store layout, then i think your option today would be to perform that portion in a custom script or fork the task (change guid and name). if you go the custom script route, then you would leave the "path to publish symbols" empty.

i think the reason you are getting the error is because the path is not a UNC path. i'm not sure offhand what the best solution is. probably add an option not to create the artifact. artifacts have implications for cleanup: a build cleanup job may run on a different agent, so it needs UNC path in order to successfully run "symstore del" command to remove the transaction from the symbol server.

**Comment by ericsciple** [comment] 2016-12-28 19:22
@chrisrpatterson to consider and closing issue here (backlog items not tracked here)

**Closed by ericsciple** 2016-12-28 19:22 UTC
Labels: Area: Build, enhancement

**Comment by brett3210** [comment] 2016-12-29 00:39
Hi Eric.  Can you please clarify why you've changed the Title of this Issue, closed the Issue, and set it as an enhancement, as I'm not sure this reflects the error I'm experiencing and the Microsoft documentation?

**Comment by ericsciple** [comment] 2016-12-29 01:10
sorry i forgot to speak to the documentation issue. the statement you are referencing in the docs is about leaving the "Path to publish symbols" input blank. it is not about publishing to a local file path symbol server. UNC is required and has been. it's a requirement due to artifact cleanup potentially landing on a different agent.

>If you leave this argument blank, your symbols will be source indexed but not published. (You can also store your symbols with your drops. See Publish Build Artifacts).

when you leave the "Path to publish symbols" input blank, indexing still happens (i.e. PDBs are modified in-place). so if you then publish your layout directory (containing the DLLs and PDBs), then you will be "stor[ing] your symbols with your drops".

i was thinking about concise ways to reword the statement "(You can also store your symbols with your drops. See Publish Build Artifacts)". but it might be better to remove it since it's confusing. i'm not sure that it adds much value since it's essentially saying "if your drop folder contains PDB files, then your PDB files will be in your drop folder"

the current behavior is by design. it's not a bug, so closing the issue here - feature backlog is not tracked here.

i changed the title so feature owner would be able to more easily understand the scenario without sifting through the details of the thread.

**Comment by brett3210** [comment] 2016-12-29 01:51
Thanks, I think rewording/removing the statement would be useful for others.  The following related links may also be of interest to others facing this issue:
http://stackoverflow.com/questions/28120413/how-to-set-up-a-symbol-server-for-visual-studio-team-services
https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/2564053-treat-tfs-as-an-enterprise-symbol-server
https://github.com/Microsoft/vsts-tasks/issues/1313
