### ISSUE TITLE
VSTest: All test tasks have started to fail unexpectedly

### ISSUE THREAD

**Issue by cervengoc** [Microsoft/vsts-tasks#7485] opened 2018-06-15 13:36 UTC
## Environment
- Server - VSTS, dealogic.visualstudio.com
- Agent - Private, 2.134.2, Windows Server 2012R2,
    
## Issue Description

We're using the VsTest Platform Installer task to set up our environment, using latest pre-release version.

Visual Studio Test tasks constantly fails on every environment since about beginning of this week. The error log is the following on every environment. We use test plan/suite based test runs, without testsettings or runsettings files. This setup was working fine previously.

Please help resolving these issues.

### Error logs

2018-06-15T13:21:43.8367406Z ==============================================================================
2018-06-15T13:21:43.8367551Z Task         : Visual Studio Test
2018-06-15T13:21:43.8367758Z Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test runner. Test frameworks that have a Visual Studio test adapter such as xUnit, NUnit, Chutzpah, etc. can also be run. Tests can be distributed on multiple agents using this task (version 2).
2018-06-15T13:21:43.8367967Z Version      : 2.136.5
2018-06-15T13:21:43.8368071Z Author       : Microsoft Corporation
2018-06-15T13:21:43.8368190Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=835764)
2018-06-15T13:21:43.8368331Z ==============================================================================
2018-06-15T13:21:44.3805420Z In distributed testing flow
2018-06-15T13:21:44.3806304Z ======================================================
2018-06-15T13:21:44.3807162Z Test selector : Test plan
2018-06-15T13:21:44.3807921Z Test plan Id : *****
2018-06-15T13:21:44.3808363Z Test plan configuration Id : ***
2018-06-15T13:21:44.3808774Z Test suite Id selected: ******
2018-06-15T13:21:44.3809207Z Search folder : C:\agent\work\0\r1\a
2018-06-15T13:21:44.5502264Z Distributed test execution, number of agents in phase : 1
2018-06-15T13:21:44.5503367Z Run settings file : C:\agent\work\0\r1\a
2018-06-15T13:21:44.5504014Z Run in parallel : false
2018-06-15T13:21:44.5504632Z Path to custom adapters : null
2018-06-15T13:21:44.5506052Z Code coverage enabled : true
2018-06-15T13:21:44.5507502Z SystemVssConnection exists true
2018-06-15T13:21:44.5510226Z ======================================================
2018-06-15T13:21:44.8724461Z [command]C:\agent\work\0\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.136.5\Modules\DTAExecutionHost.exe --inputFile C:\agent\work\0\_temp\input_0c9d5a70-709f-11e8-a6f8-ebbf43182a0f.json
2018-06-15T13:21:44.9380553Z ##########################################################################
2018-06-15T13:21:45.2629316Z ##[error]Input validation failed with exception: Microsoft.VisualStudio.TestService.AgentExecutionHost.InputException: Provided settings file C:\agent\work\0\r1\a, does not exist.
2018-06-15T13:21:45.2644799Z    at Microsoft.VisualStudio.TestService.AgentExecutionHost.InputValidator.ValidateAndFormatInputs() in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.AgentExecutionHost\InputValidator.cs:line 60
2018-06-15T13:21:45.2645100Z    at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.Main(String[] args) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.AgentExecutionHost\Program.cs:line 37
2018-06-15T13:21:45.3295693Z ##[error]Failure attempting to call the restapis. Method: System.Threading.Tasks.Task <.ctor>b__0(), Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
2018-06-15T13:21:45.3296276Z Parameter name: uriString
2018-06-15T13:21:45.3296389Z    at System.Uri..ctor(String uriString)
2018-06-15T13:21:45.3296597Z    at MS.VS.TestService.Task.Common.VssConnectionHelper.GetVssConnection(String baseUrl, VssCredentials creds, TimeSpan timeout) in D:\V2.0\A1\_work\38\s\Ta\Tasks\VS.TestServices.Task.Common\VssConnectionHelper.cs:line 76
2018-06-15T13:21:45.3296850Z    at Microsoft.VisualStudio.TestService.Utility.VssConnectionHelper.GetTestClient(String baseUrl, VssCredentials creds) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.Utility\Client\VssConnectionHelper.cs:line 17
2018-06-15T13:21:45.3297095Z    at Microsoft.VisualStudio.TestService.Utility.TestExecutionServiceRestApiHelper.Initialize(String serviceUrl, String accesToken) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.Utility\Client\TestExecutionServiceRestApiHelper.cs:line 119
2018-06-15T13:21:45.3297279Z    at System.Threading.Tasks.Task.Execute()
2018-06-15T13:21:45.3297392Z    --- End of inner exception stack trace ---
2018-06-15T13:21:45.3298769Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2018-06-15T13:21:45.3298958Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2018-06-15T13:21:45.3299159Z    at Microsoft.VisualStudio.TestService.Utility.HttpUtil.RunTaskWithRetriesOnServiceUnavailability[T](Func`1 getTask, Boolean ignoreFailure) in D:\V2.0\A1\_work\38\s\Ta\Agent\VS.TestService.Utility\HttpUtil.cs:line 30

**Comment by kaadhina** [comment] 2018-06-18 05:16
@cervengoc The settings file specified seems to be wrong. Can you please clear out that input or try with a valid file ?

**Comment by cervengoc** [comment] 2018-06-18 05:58
Hi @kaadhina, thanks for your response. The settings file is left empty, and was always empty. This can be seen in the log section, which was the same when it worked.

```
2018-06-15T13:21:44.3809207Z Search folder : C:\agent\work\0\r1\a
2018-06-15T13:21:44.5502264Z Distributed test execution, number of agents in phase : 1
2018-06-15T13:21:44.5503367Z **Run settings file : C:\agent\work\0\r1\a**
```

We did not modify any settings in the near-past.

**Comment by ShreyasRmsft** [comment] 2018-06-18 06:30
@cervengoc can you also make sure there isn't like a space in the settings file input? The quickest way to get unblocked is probably to add another instance of the task copy all inputs except for the settings file leave it as it is when you add a new instance of the task.

Reason i'm suggesting this is because i tried to re-pro the issue and it does not re-pro if the field is left untouched after you add a fresh instance of the task.

We can continue investigating after you get unblocked also and get to the root cause but to quickly unblock yourself please try out the above step. You can disable the original instance of the task for now and later we can enable it back to see why it was failing. Also do provide the json also (atleast the part that has the inputs for the vstest task).

**Comment by cervengoc** [comment] 2018-06-18 08:29
Hi @ShreyasRmsft, here is the JSON excerpt from our release definition. It is a release definition, not a build actually.

```
{
              "taskId": "ef087383-ee5e-42c7-9a53-ab56c98420f9",
              "version": "2.*",
              "name": "Run service tests from MTM",
              "refName": "",
              "enabled": true,
              "alwaysRun": false,
              "continueOnError": false,
              "timeoutInMinutes": 0,
              "definitionType": "task",
              "overrideInputs": {},
              "condition": "succeededOrFailed()",
              "inputs": {
                "testSelector": "testPlan",
                "testAssemblyVer2": "**\\*test*.dll\n!**\\*TestAdapter.dll\n!**\\obj\\**",
                "testPlan": "******",
                "testSuite": "******",
                "testConfiguration": "51",
                "tcmTestRun": "$(test.RunId)",
                "searchFolder": "$(System.DefaultWorkingDirectory)",
                "testFiltercriteria": "",
                "runOnlyImpactedTests": "False",
                "runAllTestsAfterXBuilds": "50",
                "uiTests": "false",
                "vstestLocationMethod": "version",
                "vsTestVersion": "toolsInstaller",
                "vstestLocation": "",
                "runSettingsFile": "",
                "overrideTestrunParameters": "",
                "pathtoCustomTestAdapters": "",
                "runInParallel": "False",
                "runTestsInIsolation": "False",
                "codeCoverageEnabled": "true",
                "otherConsoleOptions": "",
                "distributionBatchType": "basedOnTestCases",
                "batchingBasedOnAgentsOption": "autoBatchSize",
                "customBatchSizeValue": "10",
                "batchingBasedOnExecutionTimeOption": "autoBatchSize",
                "customRunTimePerBatchValue": "60",
                "dontDistribute": "False",
                "testRunTitle": "",
                "platform": "",
                "configuration": "",
                "publishRunAttachments": "true",
                "rerunFailedTests": "False",
                "rerunType": "basedOnTestFailurePercentage",
                "rerunFailedThreshold": "30",
                "rerunFailedTestCasesMaxLimit": "5",
                "rerunMaxAttempts": "3"
              }
            },
```

**Comment by cervengoc** [comment] 2018-06-18 08:39
Hi @ShreyasRmsft, we tried to recreate the task from scratch with the same settings, and the result is exactly the same, we get the same error with the same log.

**Comment by cervengoc** [comment] 2018-06-18 08:57
Hi @ShreyasRmsft, we managed to compare our task with a very similar one which does work. One thing we've noticed is that at the working one, in the log we see 

```
Run settings file: undefined
```
while at ours it's

```
Run settings file : C:\agent\work\0\r1\a
```

In the JSON we see the same empty string in the corresponding property. Probably there's some issue with resolving the settings file path in case when it's empty.

**Comment by ShreyasRmsft** [comment] 2018-06-18 10:41
@cervengoc so this is [starting of the code](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTestV2/inputparser.ts#L262) where we read the settings file.

By default if the field is empty the value that vsts tasks infra passes is the value of the system.defaultworkingdirectory.

We compare if the vaue is this and if it is we set it to undefined meaning that no file was passed by the user.

if (inputDataContract.ExecutionSettings.SettingsFile === tl.getVariable('System.DefaultWorkingDirectory')) {

this check is clearly failing in your definition.

weirdly enough it doesn't fail when i run it without providing a settings file. Can you add a powershell task just before the vstest task to your build definition and print the value of the environment variable System.DefaultWorkingDirectory?

This will tell why the condition check is failing. In case the variable is getting overwritten by someone or some task.

**Comment by cervengoc** [comment] 2018-06-18 10:58
@ShreyasRmsft, you can see the working directory in

```
Search folder : C:\agent\work\0\r1\a
```

In this variable we purely use `$(System.DefaultWorkingDirectory)`. So it seems like it's OK. 

Besdies these, we found that the working instance uses a different on-premise Agent queue, having an earlier agent version `2.119.1`. Do you think the agent itself can introduce such an issue?

**Comment by ShreyasRmsft** [comment] 2018-06-18 11:17
Yes. It's entirely possible. These build variables (ex: System.DefaultWorkingDirectory) are dependent on the agent. We generally test on the latest but its entirely possible that it may have broken on an older agent. Can you give me the agent versions where it works and where it doesn't? Will try to repro on those versions.

**Comment by cervengoc** [comment] 2018-06-18 11:19
@ShreyasRmsft, interestingly enough, it seems like it **does work** on an old agent `2.119.1`, and it **does not** on the latest `2.134.2`

**Comment by ShreyasRmsft** [comment] 2018-06-18 11:28
@cervengoc will check and get back to you.

**Comment by cervengoc** [comment] 2018-06-18 11:42
@ShreyasRmsft thank you for your efforts.

We now tried to downgrade our failing agent to `2.119.1`, and unfortunately we had no luck, so this might not be related only to the agent binary. Now I'm trying to clear the entire working folder of the agent.

**Comment by cervengoc** [comment] 2018-06-18 11:47
Still the same issue after clearing the working directory :(

**Comment by bryanmacfarlane** [comment] 2018-06-18 11:48
To my knowledge there was no agent bug where working directory was set incorrectly.  Certainly not the a (artifacts) directory.

**Comment by cervengoc** [comment] 2018-06-18 11:51
@ShreyasRmsft  Just another information: it seems like the task breaks only when using the Test Plan mode. We could successfully run tests using the Test Assembly mode. Hope this helps in any way.

**Comment by ShreyasRmsft** [comment] 2018-06-18 12:04
@bryanmacfarlane apologies. I meant we may have broken the working of the task on an older agent version since we did not test.

**Comment by bryanmacfarlane** [comment] 2018-06-18 12:05
No worries - just trying to help narrow. :)

**Comment by cervengoc** [comment] 2018-06-18 12:12
Another information, it seems like the behavior depends on the machine context too, as pointing the phase to another agent queue running `2.119.1` agents made the task work properly. However, the same agent version was not working on out queue. 

Could there be any environmental setting which may affect this behavior?

**Comment by ShreyasRmsft** [comment] 2018-06-18 12:13
@bryanmacfarlane can system env variables override agent variables (for example: System.DefaultWorkingDirectory)?

**Comment by ShreyasRmsft** [comment] 2018-06-19 09:18
@cervengoc can you reinstall the agent on the machine in which this is happening on? 
Also how many agents in the queue where this doesn't work? Do all of them exhibit the same behavior?

**Comment by cervengoc** [comment] 2018-06-19 14:33
Hi @ShreyasRmsft,

We've investigated the issue deeply by adding some custom logging statements to the task code. It turned out that on the failing machine the `System.DefaultWorkingDirectory` variable resolves to an absolute path containing slashes instead of backslashes, hence the check you mentioned fails.

The machine is a Windows Server 2016 box, if that matters.

![image](https://user-images.githubusercontent.com/6099330/41603861-253e9e94-73de-11e8-955f-9ce975cb1c29.png)

**Comment by ShreyasRmsft** [comment] 2018-06-20 05:44
@cervengoc great work with the debugging! You're right, will make this change. Keeping this issue open till I get a PR out to make this fix. Meanwhile hope you are unblocked.

**Comment by ShreyasRmsft** [comment] 2018-06-20 08:54
@cervengoc the reason we are facing this issue is that the when the input field (of type filepath) is left blank in the UI it doesn't send us an empty string it instead sends us the relative path to the working directory. The test team does not own this UI and I will speak to the team that owns the UI to fix this issue at the root.

We can add the normalize in the code but come to think of it will start causing issues in cases such as when it's a UNC path etc.

**Comment by cervengoc** [comment] 2018-06-20 08:58
@ShreyasRmsft, thanks for your updates. We definitely support the idea of fixing the root cause, so I guess in that case you wouldn't even need this path comparison at all.

**Comment by bryanmacfarlane** [comment] 2018-07-23 12:35
@ShreyasRmsft - that's by design.  FilePath defaults to the root of the repo if no path is given.  That's the difference between a string input field and a filePath input field.  This has always been the case since the creation of build.vnext.

https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L234

That's also why that lib method exists.

**Comment by ShreyasRmsft** [comment] 2018-07-25 08:07
@bryanmacfarlane wanted to know what the recommended way to detect if this field was left blank.

A simple string comparison with system.defaultworkingdirectory did not work due to the reasons stated above. One possible way was to normalize directory separators but that seems very hacky.

Ideally a string comparison with system.defaultworkingdirectory should have sufficed but for some reason the build variable had the original value but the input was getting resolving to the same path but with backslashes and not the value set by the user.

Any thoughts here?

**Comment by ShreyasRmsft** [comment] 2018-08-28 11:43
Fixed in PR https://github.com/Microsoft/vsts-tasks/pull/8168

**Closed by ShreyasRmsft** 2018-08-28 11:43 UTC
Labels: Area: Test

**Comment by salarzobir** [comment] 2025-03-19 05:48
In my case I am getting the same error because I changed the default checked out repository path to an upper folder inside working directory.
I am checking out 2 repos like this:

```
- checkout: self
  lfs: true
  submodules: true
  clean: true
  path: ../repos/my-repo-1
  workspaceRepo: true

- checkout: my-repo-2
  lfs: true
  submodules: true
  clean: true
  path: ../repos/my-repo-2
  workspaceRepo: true
```

And my test task is like this:

```
- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(tests)'
    codeCoverageEnabled: true
    failOnMinTestsNotRun: true
    rerunFailedTests: true
    rerunType: 'basedOnTestFailureCount'
```

And I am getting this error:

##[error]Input validation failed with exception: Provided settings file C:\agent\_work\repos\my-repo-1, does not exist.
