### ISSUE TITLE
XML Transformation wasn't applied for Azure App Service deploy

### ISSUE THREAD

**Issue by serg-s** [Microsoft/vsts-tasks#7310] opened 2018-05-28 10:48 UTC
I have the following structure of configs:
Web.config, Web.Debug.config, Web.Dev.config, Web.Production.config, Web.Staging.config.

Each of environment configuration has connection string params like this:
`<add name="DefaultConnection" connectionString="..." xdt:Transform="SetAttributes" xdt:Locator="Match(name)"/>`

I have followed by this tutorial (https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution?view=vsts#xml-transformation)
to enable XML transformation for each environment during deploying to Azure App Service.

The following warning in logs appears when try to deploy:

> ##[warning]Unable to apply transformation for the given package. Verify the following.
> ##[warning]1. Whether the Transformation is already applied for the MSBuild generated package during build. If yes, remove the <DependentUpon> tag for each config in the csproj file and rebuild. 
> ##[warning]2. Ensure that the config file and transformation files are present in the same folder inside the package.

As a result, XML transformation wasn't applied and app service using connection string from Web.config.
I wonder why this happening.
Thanks

**Comment by vincentdass** [comment] 2018-05-28 14:44
@serg-s , Can u share the debug logs for the release? (set variable `system.debug` to `true` and re-run the release)

**Comment by vincentdass** [comment] 2018-05-30 08:06
@serg-s ,thanks for the info.
Can you please share your `web.config` and `web.staging.config` to `RM_CUSTOMER_QUERIES@MICROSOFT.COM` to debug further?

**Comment by serg-s** [comment] 2018-05-30 12:27
@vincentdass I'm receiving an error message that my email couldn't be delivered, so I'll `web.config` here.
I've removed sensitive data there. 
[configs.zip](https://github.com/Microsoft/vsts-tasks/files/2053843/configs.zip)

**Comment by vincentdass** [comment] 2018-05-31 13:35
Closing the issue, as the issue is resolved offline.

**Closed by vincentdass** 2018-05-31 13:35 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by kimwandev** [comment] 2019-04-09 15:56
I have similar issue. What could be the possible cause for this?

**Comment by vincentdass** [comment] 2019-04-10 06:55
@kimwandev , please refer [here](https://docs.microsoft.com/en-in/azure/devops/pipelines/tasks/transforms-variable-substitution?view=azure-devops#xml-transformation-notes) for troubleshooting.
