### ISSUE TITLE
VsTest v2.0 issue with Coded UI Test

### ISSUE THREAD

**Issue by fbouteruche** [Microsoft/vsts-tasks#3930] opened 2017-04-03 22:12 UTC
Hello,

I try to use the VsTest v2 preview task to run Coded UI Test in my release pipeline. The task fails because it can't find Microsoft.VisualStudio.* dependencies although I've got Visual Studio 2017 enterprise on my build and release agent.

Here is the log :

2017-04-03T21:26:46.5932338Z ##[section]Starting: Release
2017-04-03T21:26:46.5952326Z Current agent version: '2.115.0'
2017-04-03T21:26:47.6274498Z ##[section]Starting: Initialize Job
2017-04-03T21:26:47.6304499Z Prepare release directory.
2017-04-03T21:26:47.6304499Z ReleaseId=15, TeamProjectId=5b166bb0-9e25-40d0-81ac-4e84536f497f, ReleaseDefinitionName=softwaretestingprepa
2017-04-03T21:26:47.6414502Z Release folder: C:\agent\_work\r1\a
2017-04-03T21:26:47.6594526Z Environment variables available are below.  Note that these environment variables can be referred to in the task (in the ReleaseDefinition) by replacing "_" with "." e.g. AGENT_NAME environment variable can be referenced using Agent.Name in the ReleaseDefinition: 
				[ADMINISTRATORLOGIN] --> []
				[AGENT_HOMEDIRECTORY] --> [C:\agent]
				[AGENT_ID] --> [8]
				[AGENT_JOBNAME] --> [Release]
				[AGENT_MACHINENAME] --> 
				[AGENT_NAME] --> 
				[AGENT_RELEASEDIRECTORY] --> [C:\agent\_work\r1\a]
				[AGENT_ROOTDIRECTORY] --> [C:\agent\_work]
				[AGENT_SERVEROMDIRECTORY] --> [C:\agent\externals\vstsom]
				[AGENT_TEMPDIRECTORY] --> [C:\agent\_work\_temp]
				[AGENT_TOOLSDIRECTORY] --> [C:\agent\_work\_tool]
				[AGENT_VERSION] --> [2.115.0]
				[AGENT_WORKFOLDER] --> [C:\agent\_work]
				[AZURE_HTTP_USER_AGENT] --> [VSTS_7538361c-b06f-4b68-8b0e-93c6c3a2d38d_release_1_15_15_1]
				[BUILD_BUILDID] --> [167]
				[BUILD_BUILDNUMBER] --> [20170403.10]
				[BUILD_BUILDURI] --> [vstfs:///Build/Build/167]
				[BUILD_DEFINITIONID] --> [22]
				[BUILD_DEFINITIONNAME] --> [22]
				[BUILD_REPOSITORY_NAME] --> [SoftwareTestingPrepa]
				[BUILD_REPOSITORY_PROVIDER] --> [TfsGit]
				[BUILD_REQUESTEDFOR] --> 
				[BUILD_REQUESTEDFORID] --> 
				[BUILD_SOURCEBRANCH] --> [refs/heads/master]
				[BUILD_SOURCEBRANCHNAME] --> [master]
				[BUILD_SOURCEVERSION] --> [5e80d6328198a47698bf7aba9264467a6d31c54f]
				[BUILD_TYPE] --> [Build]
				[CONNECTIONSTRINGNAME] --> []
				[DATABASENAME] --> []
				[MSDEPLOY_HTTP_USER_AGENT] --> [VSTS_7538361c-b06f-4b68-8b0e-93c6c3a2d38d_release_1_15_15_1]
				[RELEASE_ARTIFACTS_DROP_BUILDID] --> [167]
				[RELEASE_ARTIFACTS_DROP_BUILDNUMBER] --> [20170403.10]
				[RELEASE_ARTIFACTS_DROP_BUILDURI] --> [vstfs:///Build/Build/167]
				[RELEASE_ARTIFACTS_DROP_DEFINITIONID] --> [22]
				[RELEASE_ARTIFACTS_DROP_DEFINITIONNAME] --> [22]
				[RELEASE_ARTIFACTS_DROP_REPOSITORY_NAME] --> [SoftwareTestingPrepa]
				[RELEASE_ARTIFACTS_DROP_REPOSITORY_PROVIDER] --> [TfsGit]
				[RELEASE_ARTIFACTS_DROP_REQUESTEDFOR] --> []
				[RELEASE_ARTIFACTS_DROP_REQUESTEDFORID] --> []
				[RELEASE_ARTIFACTS_DROP_SOURCEBRANCH] --> [refs/heads/master]
				[RELEASE_ARTIFACTS_DROP_SOURCEBRANCHNAME] --> [master]
				[RELEASE_ARTIFACTS_DROP_SOURCEVERSION] --> [5e80d6328198a47698bf7aba9264467a6d31c54f]
				[RELEASE_ARTIFACTS_DROP_TYPE] --> [Build]
				[RELEASE_ATTEMPTNUMBER] --> [1]
				[RELEASE_DEFINITIONENVIRONMENTID] --> [1]
				[RELEASE_DEFINITIONID] --> [1]
				[RELEASE_DEFINITIONNAME] --> [softwaretestingprepa]
				[RELEASE_DEPLOYMENTID] --> [15]
				[RELEASE_DEPLOYPHASEID] --> [29]
				[RELEASE_ENVIRONMENTID] --> [15]
				[RELEASE_ENVIRONMENTNAME] --> [Dev]
				[RELEASE_ENVIRONMENTS_DEV_STATUS] --> [InProgress]
				[RELEASE_ENVIRONMENTURI] --> [vstfs:///ReleaseManagement/Environment/15]
				[RELEASE_RELEASEDESCRIPTION] --> []
				[RELEASE_RELEASEID] --> [15]
				[RELEASE_RELEASENAME] --> [Release-15]
				[RELEASE_RELEASEURI] --> [vstfs:///ReleaseManagement/Release/15]
				[RELEASE_RELEASEWEBURL] --> [https://xxxxx.visualstudio.com/5b166bb0-9e25-40d0-81ac-4e84536f497f/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=15&_a=release-summary]
				[RELEASE_REQUESTEDFOR] --> []
				[RELEASE_REQUESTEDFOREMAIL] --> []
				[RELEASE_REQUESTEDFORID] --> []
				[RELEASE_SKIPARTIFACTSDOWNLOAD] --> [False]
				[RELEASECONFIGURATION] --> [Release]
				[RELEASEPLATFORM] --> [Any CPU]
				[REQUESTEDFORID] --> []
				[SERVERNAME] --> []
				[SYSTEM] --> [release]
				[SYSTEM_ARTIFACTSDIRECTORY] --> [C:\agent\_work\r1\a]
				[SYSTEM_COLLECTIONID] --> [7538361c-b06f-4b68-8b0e-93c6c3a2d38d]
				[SYSTEM_CULTURE] --> [en-US]
				[SYSTEM_DEFAULTWORKINGDIRECTORY] --> [C:\agent\_work\r1\a]
				[SYSTEM_ENABLEACCESSTOKEN] --> [False]
				[SYSTEM_HOSTTYPE] --> [release]
				[SYSTEM_JOBID] --> [782ef913-22e7-4625-80b3-500433ba69ce]
				[SYSTEM_JOBPOSITIONINPHASE] --> [1]
				[SYSTEM_PARALLELEXECUTIONTYPE] --> [None]
				[SYSTEM_PLANID] --> [3f7c9ae4-5a88-40fe-8da5-a84a3963053c]
				[SYSTEM_TASKDEFINITIONSURI] --> [https://xxxxxx.visualstudio.com/]
				[SYSTEM_TEAMFOUNDATIONCOLLECTIONURI] --> [https://xxxxx.visualstudio.com/]
				[SYSTEM_TEAMFOUNDATIONSERVERURI] --> [https://xxxxx.vsrm.visualstudio.com/]
				[SYSTEM_TEAMPROJECT] --> [PrepaPetitDejTest]
				[SYSTEM_TEAMPROJECTID] --> [5b166bb0-9e25-40d0-81ac-4e84536f497f]
				[SYSTEM_TIMELINEID] --> [ef9f73e0-cf08-4157-8739-310af1fdaf1c]
				[SYSTEM_TOTALJOBSINPHASE] --> [1]
				[SYSTEM_WORKFOLDER] --> [C:\agent\_work]
2017-04-03T21:26:47.6644618Z Download all requried tasks.
2017-04-03T21:26:47.6964533Z ##[section]Finishing: Initialize Job
2017-04-03T21:26:47.7344513Z ##[section]Starting: Download Artifacts
2017-04-03T21:26:47.7374514Z Downloading artifact
2017-04-03T21:26:47.9854561Z Cleaning artifacts directory: C:\agent\_work\r1\a
2017-04-03T21:26:48.1144582Z Failed to cleanup Release's artifact directory 'C:\agent\_work\r1\a' with an exception System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass30_0.<CleanUpArtifactsFolder>b__1()
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.Execute(Action action). Retrying the cleanup of Release artifact directory.
2017-04-03T21:26:48.1164585Z Cleaning artifacts directory: C:\agent\_work\r1\a
2017-04-03T21:26:48.1174580Z Cleaned artifacts directory: C:\agent\_work\r1\a
2017-04-03T21:26:48.1244584Z Starting artifacts download...
2017-04-03T21:26:48.1264583Z Downloading linked artifact Drop of type Build...
2017-04-03T21:26:48.1304566Z Ensuring artifact folder C:\agent\_work\r1\a\Drop exists and is clean.
2017-04-03T21:26:48.1374582Z Preparing to get the list of available artifacts from build
2017-04-03T21:26:48.1974592Z Preparing to download artifact: drop
2017-04-03T21:26:48.2014619Z Artifact Type: ServerDrop
2017-04-03T21:26:48.2794603Z Caching items under 'drop' in the file container...
2017-04-03T21:26:48.3184608Z Caching complete. (39 ms)
2017-04-03T21:26:50.0430929Z Download complete.
2017-04-03T21:26:50.0430929Z 7 placed file(s): 7 downloaded, 0 empty
2017-04-03T21:26:50.0430929Z 9 MB downloaded at 4898 KB/sec. Download time: 00:00:01.7142496. Parallel download limit: 4.
2017-04-03T21:26:50.0430929Z Downloaded linked artifact Drop
2017-04-03T21:26:50.0430929Z Finished artifacts download
2017-04-03T21:26:50.0440920Z ##[section]Finishing: Download Artifacts
2017-04-03T21:26:50.0520918Z ##[section]Starting: Test Assemblies **\*test*.dll;-:**\obj\**
2017-04-03T21:26:50.0640918Z ==============================================================================
2017-04-03T21:26:50.0640918Z Task         : Visual Studio Test
2017-04-03T21:26:50.0640918Z Description  : Run tests with Visual Studio test runner
2017-04-03T21:26:50.0640918Z Version      : 2.0.19
2017-04-03T21:26:50.0640918Z Author       : Microsoft Corporation
2017-04-03T21:26:50.0640918Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=835764)
2017-04-03T21:26:50.0640918Z ==============================================================================
2017-04-03T21:26:50.7701032Z !**\obj\**
2017-04-03T21:26:50.7761029Z [command]powershell -NonInteractive -ExecutionPolicy Unrestricted -file C:\agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.19\vs15Helper.ps1
2017-04-03T21:26:52.5671611Z <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
2017-04-03T21:26:52.5671611Z   <S>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise</S>
2017-04-03T21:26:52.5671611Z </Objs>
2017-04-03T21:26:52.6081628Z [command]"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\agent\_work\r1\a\Drop\drop\SoftwareTestingPrepa.FunctionalTests\bin\Release\SoftwareTestingPrepa.FunctionalTests.dll /logger:trx
2017-04-03T21:26:52.7331641Z Microsoft (R) Test Execution Command Line Tool Version 15.0.26228.0
2017-04-03T21:26:52.7331641Z Copyright (c) Microsoft Corporation.  All rights reserved.
2017-04-03T21:26:52.7331641Z 
2017-04-03T21:26:52.8941662Z Starting test execution, please wait...
2017-04-03T21:26:53.2541699Z Warning: Unable to load types from the test source 'C:\agent\_work\r1\a\Drop\drop\SoftwareTestingPrepa.FunctionalTests\bin\Release\SoftwareTestingPrepa.FunctionalTests.dll'. Some or all of the tests in this source may not be discovered. If you are running unit tests for Windows Store apps and referencing custom WinMD type then please visit http://go.microsoft.com/fwlink/?LinkId=238340 for more info. Error details: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestTools.UITesting, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2017-04-03T21:26:53.2541699Z .
2017-04-03T21:26:53.2541699Z 
2017-04-03T21:26:53.2541699Z Warning: MSTestAdapter failed to discover tests in class 'SoftwareTestingPrepa.FunctionalTests.CodedUITest1' of assembly 'C:\agent\_work\r1\a\Drop\drop\SoftwareTestingPrepa.FunctionalTests\bin\Release\SoftwareTestingPrepa.FunctionalTests.dll'. Reason Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
2017-04-03T21:26:53.2541699Z 
2017-04-03T21:26:53.2541699Z Warning: No test is available in C:\agent\_work\r1\a\Drop\drop\SoftwareTestingPrepa.FunctionalTests\bin\Release\SoftwareTestingPrepa.FunctionalTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
2017-04-03T21:26:53.2541699Z 
2017-04-03T21:26:53.2541699Z 
2017-04-03T21:26:53.5591750Z Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
2017-04-03T21:26:53.5591750Z 
2017-04-03T21:26:54.1919766Z ##[warning]No results found to publish.
2017-04-03T21:26:54.1999765Z ##[section]Finishing: Test Assemblies **\*test*.dll;-:**\obj\**

**Comment by nigurr** [comment] 2017-04-04 03:32
@fbouteruche by default CodedUI is not installed in Visual Studio 2017. Can you verify that you have installed CodedUI extension in Vs2017.

**Comment by fbouteruche** [comment] 2017-04-04 13:00
Hello @ni, CodedUI extension is installed. I've run the tests directly in Visual Studio 2017 on the test agent machine and it works very well.

**Comment by acesiddhu** [comment] 2017-04-04 13:32
'Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..

this exception clearly means that the test assemblies are build against VS 2015 and we are trying to run them in VS 2017. Can you confirm this

**Comment by acesiddhu** [comment] 2017-04-04 13:35
Version 14.0.0.0 means the test assembly was build with vs2015

**Comment by RanjanarMS** [comment] 2017-04-11 06:09
Closing this thread for now. If you feel the issue is not addressed please re-open.

**Closed by RanjanarMS** 2017-04-11 06:09 UTC
Labels: Area: Test
