### ISSUE TITLE
VSTS Cloud Deployment fails and throws - “ ##[error]TooManyRequests: Too many requests received. Retry after some time.”

### ISSUE THREAD

**Issue by lbalams** [Microsoft/vsts-tasks#4445] opened 2017-06-01 17:06 UTC
We have 20+ services all under 1 subscription, for multiple regions, currently deploying via an exe using Azure Api which is working absolutely fine. Now, we want to move to using VSTS, enable CICD and trying to deploy them in parallel - https://skype.visualstudio.com/ARIA/Aria%20Data%20Apps%20Team/_release?definitionId=97&_a=releases

It works fine if we deploy <= 3 services at give point in time and anything more than that, it throws this error. There are no options in the deployment for retry and beats the VSTS CICD purpose. Reading up online looks to me like the subscription is getting throttled but I am not how to fix this. Any ideas on how to solve this or workarounds or is this a limitation of VSRM deployments?

**Comment by mvvsubbu** [comment] 2017-06-08 10:39
As the issue is directly coming from Azure Key Vault you need to file a support ticket with Azure that should help. I am going head and closing the issue as it is not related VSTS

**Closed by mvvsubbu** 2017-06-08 10:39 UTC
Labels: Area: Release
