### ISSUE TITLE
NuGet Pack - path to csproj files returns no files with minimatch pattern

### ISSUE THREAD

**Issue by TThat17** [Microsoft/vsts-tasks#4702] opened 2017-06-30 23:39 UTC
If I enter the following in the 'path to csproj or nuspec file(s) to pack' field, it will find all csProj files - including the test project:
**\*.csproj

However, if I use the pattern from the example (which is shown below), it returns zero files.  This is the same pattern that shows up in the example when hovering over the "i" button
**\*.csproj;-:**\*.Tests.csproj

**Comment by lvsezhufu** [comment] 2017-07-04 03:26
For the option of Path to csproj or nuspec file(s) to pack, **the negative pattern can’t work**.

Such as the pattern` **\*.csproj` can works fine, but these patterns can’t work: `**\*.csproj;-:**\ConsoleApplication1.csproj` and ` ;-:**\ConsoleApplication1.csproj`.

**Comment by TThat17** [comment] 2017-07-04 04:14
I'm sorry, but this is a frustrating answer.  Are you saying that it doesn't work now or that it will not be supported at all?

I have issues with this because previously, I used the Nuget Packager step.  This step now shows that it is deprecated now.  Also, someone updated it and now my builds are no longer working.  I tried to update them to use the new 'Nuget' step as recommended, but this step doesn't support the pattern that the old one did. So my builds still are not working.  If I leave the negative pattern there, it finds no files.  If I remove the negative pattern it builds nuget packages for my test projects.  I know I could delete the nuget packages for the test projects after they were built and before publishing them, but it is a hassle when the minimatch pattern worked with the old step.

**Comment by bryanmacfarlane** [comment] 2017-07-04 04:22
@alexmullans from msft to advise

**Comment by lvsezhufu** [comment] 2017-07-04 05:27
@TThat17 I posted above is not an answer, but the comment to explain same issue as you met. We can wait until the nuget pack task be updated.

**Comment by ross2411** [comment] 2017-07-04 08:18
I'm having similar problems getting the negative pattern to work.  Copying the example from the markdown text doesn't work.  Any update on when this may be fixed?  Currently I have 14 Nuget Pack tasks because I can't use wildcards!  (I raised stackflow question http://bit.ly/2tcvuZH which lead me to this issue)

**Comment by alexmullans** [comment] 2017-07-05 15:35
Are you using the NuGet Packager task or the NuGet task (with the 'pack' command selected)? If the former, that task is now deprecated and a number of improvements were made to the new NuGet task. Please switch to using that task and see if that fixes your issue.

**Comment by ross2411** [comment] 2017-07-05 15:37
Using the new shiny NuGet task with the pack command.  Unless you've done a release since yesterday (with a fix for this in it) it's still broken :)

**Comment by grantwar** [comment] 2017-07-11 10:50
I'm experiencing the same issue using the NuGet task with the pack command selected.
The issue isn't just for negative patterns not working, its not even working for multiple files. In short if I use the semicolon separator the task finds no matching files.

**Comment by grantwar** [comment] 2017-07-11 10:52
If anyone requires a workaround for this, you can build all the csproj files using the **\*.csproj wildcard search, and then add a powershell task and use an inline script such as this to remove the unwanted packages before pushing them up:
`Remove-Item –path $(Build.ArtifactStagingDirectory)\*test*.nupkg –recurse`

**Comment by ross2411** [comment] 2017-07-11 10:54
@grantwar - I noticed that the ; was messing things up too.  I'll give the powershell script you've mentioned a go.  Thanks ;)

**Comment by mjcheetham** [comment] 2017-07-13 09:19
Can confirm, we're hitting this issue too. There's something wrong when you include a semi-colon.

**Comment by alexmullans** [comment] 2017-07-17 19:54
This is fixed by #4775. Will be live in the next day or so.

**Closed by alexmullans** 2017-07-17 19:54 UTC
Labels: Area: Packaging
