### ISSUE TITLE
Visual Studio Test Agent Deployment hangs with 'Interactive Process' checked

### ISSUE THREAD

**Issue by Framnk** [Microsoft/vsts-tasks#2023] opened 2016-07-05 19:59 UTC
I am trying to use the Visual Studio Test Agent Deployment task with the TFS vNext build system to deploy a test agent to a virtual machine during our build process.  This works fine if I do not have 'Interactive Process' checked for the deployment task, however our testing requires the ability to interact with the desktop.  However when I select the 'interactive process' checkbox on the deployment task, it just seems to hang the build with messages that the task is 'taking a long time' until it eventually times out.

I checked on the virtual machine for a log file and found one in DtaLogs where it seems to be repeating the following sequence:

Web method running: [http://tfs/tfs/ATI/_apis/test/Agents/10/Commands/0] (GET)0[test]
Web method response: [http://tfs/tfs/ATI/_apis/test/Agents/10/Commands/0] (GET)0[test] 15 ms
V, 2360, 11, 2016/07/05, 15:51:20.655, ATI000457-BUILD\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 2360, 11, 2016/07/05, 15:51:20.655, ATI000457-BUILD\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 2360, 11, 2016/07/05, 15:51:20.655, ATI000457-BUILD\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for some time.

**Comment by atinb** [comment] 2016-07-06 04:36
Can you ensure that you have signed off from the machine (not locked but logged off)? Thanks!

**Comment by Framnk** [comment] 2016-07-06 12:03
It doesn't seem to make a difference, in fact when I run this task while logged in it automatically logs me out and when it logs back in it shows the DTAExecutionHost window (which I would expect for the interactive process) but the task never completes in TFS and will eventually time out.

**Comment by tanvi-soni** [comment] 2016-07-08 05:30
Can you try closing the remote session of the machine and then try out the task. Is your test agent machine non-enu. Can you also share Dtalogs and TestAgentConfiguration logs with us. You will testAgentConfig logs in your temp folder on test agent machine.

**Comment by Framnk** [comment] 2016-07-11 12:24
I'm not exactly sure what you mean by the 'remote session'.  This is a VM, I'm not remoting into it.  There is no TestAgentConfiguration log on the machine, I've attached the DTAExecutionHost.log file.

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/357061/DTAExecutionHost.exe.txt)

**Comment by tanvi-soni** [comment] 2016-07-12 12:52
Can you provide us with fresh DTAExecutionHost logs. Go to C:\Dtalogs and delete the DTAExecutionHost.log file. Run a new build with interactive process checkbox as ticked and please send us DTAlogs of that fresh run. Can you also provide us with build console logs.

**Comment by Framnk** [comment] 2016-07-12 16:24
Here the DTA log for a fresh run of the Deploy Test Agent task:

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/359817/DTAExecutionHost.exe.txt)

**Comment by nigurr** [comment] 2016-07-13 09:56
@Framnk please provide build logs + full DTA execution host log

**Comment by Framnk** [comment] 2016-07-13 11:02
I've already provided the DTAExecutionHost log twice already in this thread, and a snippet in the initial post.  All of them show the same info so I'm not sure why I get asked for this log again every day.  Attached is the build log from the same run that generated the last DTAExecutionHost log.

[logs_7819.zip](https://github.com/Microsoft/vsts-tasks/files/361313/logs_7819.zip)

**Comment by nigurr** [comment] 2016-07-13 11:10
Sorry for the trouble. We would like to help you out asap.
Is there any IT policy "which do show up in your machines before you login"

When you enable "Interactive Process", we try to reboot the machine and auto-logon into Test account. If there's any IT policy/Login setting which block this, the configuration fails.

**Comment by Framnk** [comment] 2016-07-13 11:30
We do have that policy but I have disabled it on this automated testing machine.  I can witness the reboot during the Deploy Test Agent task on the VM and I can verify it successfully logs into the machine and starts the DTAExecutionHost.  It just appears that whatever condition it is waiting for to verify that the DTAExecutionHost started successfully is never satisfied and the task eventually times out.

I can also verify that it is deploying the test agent successfully as if I immediately run a build containing tests after I cancel the Deploy build config which is timing out, my tests will run so the test agent does get configured.  My problem is that I need the deploy task to pass and not time out so I can include it as part of an overall build configuration to provision the VM for automated testing.

**Comment by Framnk** [comment] 2016-07-21 14:33
Any updates?  We recently updated our TFS server to the latest update and now we are dead in the water for running Automated Tests as the 'Run Functional Tests' task type now _requires_ that the 'Visual Studio Test Agent Deployment' task complete first (previously I was able to work around this issue by running a separate build to deploy, cancelling it and then running our automated test build configuration).

**Comment by vimegh** [comment] 2016-07-22 06:37
Sorry for inconvenience caused Framnk. Such issue mostly prop up due to autologon failure or policy issues. Can you try following:

1. Uninstall Test Agent from the test machine. You can do that in Programs and Features bu Uninstalling Microsoft Agents for Visual Studio.
2. Run the Deploy Test Agent and Run Functional Test with Update Test Agent checked, with the same user on Test Agent machine with which the build agent is configured. Using same user will not require a restart to the machine.

Please let us know the outcome. Also if above doesn't work then we would need to know:
TFS version that you are using and Test agent version installed.

**Comment by Framnk** [comment] 2016-07-22 18:47
I tried the suggested steps with the same result.  Attached is an updated DTAExecutionHost logfile
[DTAExecutionHost.txt](https://github.com/Microsoft/vsts-tasks/files/378846/DTAExecutionHost.txt)

Our TFS version is 14.102.25423.0 and the agent version shown in Programs and Features is Microsoft Agents for Visual Studio 2015 with Update 3 (14.0.25420.1)

It really appears that the 'Interactive Process' checkbox seems to be the holdup not autologon as that all seems to work but when the DTAExecutionHost.exe window shows on the system, the task will never finish.  If I uncheck the 'Interactive Process' checkbox the Deploy Test Agent task will complete successfully, so it seems like it's waiting for something to happen *after* the agent has installed successfully that never happens.

**Comment by FerdinandBa** [comment] 2016-07-26 14:32
Are there any updates yet? I have the same issue too, that the Deploy Test Agent task times out when the interactive process option is checked.
I observed that it does not freeze when I have an open remote desktop connection to the VM while the test agent is being deployed. But then, the test run is aborted shortly after it started, without a reason. It only says "UnExpected error occured during test execution".

**Comment by Framnk** [comment] 2016-08-02 11:44
Really looking for some guidance here... what condition is the task looking for when determining that the Deploy succeeded?  Seems like this is not occurring and hanging the task.

**Comment by nigurr** [comment] 2016-08-02 12:49
@Framnk please feel free to see code here[open source] https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/TestAgentInstall.ps1 :)

**Comment by vimegh** [comment] 2016-08-02 12:49
@Framnk  Can you please email your skype id on vimegh@microsoft.com. We would want to get in a call with you in order to understand the problem as we are unable to reproduce it at our end.

**Comment by Framnk** [comment] 2016-08-02 16:55
@nigurr I don't believe the problem exists in TestAgentInstall.ps1 as the logs show that it completes that powershell script successfully.  This is why I've been skeptical that the problem has to do with autologon.  

The issue seems to be when it tries to run TestAgentConfiguration.ps1.   That powershell script task never finishes and I don't see any debug output from it in the build log.  You can see this in the snippet below.  If you could point me to where the source for the 'Invoke-DeployTestAgent' Powershell cmdlet exists it would make troubleshooting a bit easier.  Right now I have to just infer what's going on without that.

Clearly it can find TestAgentConfiguration.ps1 and attempts to execute it but something 'hangs' and it will never finish.  My suspicion is that DTAExecutionHost.exe isn't returning when being launched as an interactive process and that blocks the whole task.

The last few lines in the build log are:

2016-08-02T15:06:22.6742286Z ##[debug]DistributedTests: PERF: DeployTestAgent: took 202592.2356 ms
2016-08-02T15:06:22.6742286Z ##[debug]DistributedTests: PERF WARNING: DeployTestAgent: took 202592.2356 ms
2016-08-02T15:06:22.6771584Z ##[debug]DistributedTests: configuring testagent process to run with ATINET\Build1
2016-08-02T15:06:22.6771584Z ##[debug]DistributedTests: ConfigureTestAgent powershell script location : C:\vsoagent\tasks\DeployVisualStudioTestAgent\1.0.25\TestAgentConfiguration.ps1
2016-08-02T15:06:22.6849720Z ##[debug]DistributedTests: Configuring test agent on test machines.
2016-08-02T15:06:22.6849720Z ##[debug]DistributedTests: Total machines where task ConfigureTestAgent needs to be run : 1
2016-08-02T15:06:22.6859474Z DistributedTests: Task 'ConfigureTestAgent' on machine 'ati000457-build1.accuratetechnologies.com:5985' is being run
2016-08-02T15:07:22.6865940Z DistributedTests: Task 'ConfigureTestAgent' on machine 'ati000457-build1.accuratetechnologies.com:5985' is taking time. Please Wait
2016-08-02T15:08:22.6871476Z DistributedTests: Task 'ConfigureTestAgent' on machine 'ati000457-build1.accuratetechnologies.com:5985' is taking time. Please Wait

(This continues until the build times out).

**Comment by vimegh** [comment] 2016-08-03 09:32
Just an update to this thread, @Framnk got this working with a workaround: he started using same credentials for Test Agent, with which the build agent registration is done, avoiding any restarts or autologons.

@FerdinandBa You can try with same credentials for build agent and test agent, but it seems to me your problem could be different, as in your issue Run Functional Test task is atleast getting started and then failing. I would recommend you to open another issue to track that and do provide us DTAExecutionHost.exe logs from C:\\DtaLogs\ folder in Test Agent Machine in that issue.

**Comment by vimegh** [comment] 2016-08-23 08:22
@tanvi-soni Please close this thread here. The issue faced was resolved using same credentials for Test Agent and Build Agent. We have mailed Framnk to get back to us in case he wants to look into problems related with different user credentials.

**Closed** 2016-08-23 08:23 UTC
Labels: Area: Test

**Comment by adegaston** [comment] 2016-11-17 15:46
Using the same credentials for the Test Agent as the Build Agent solved the problem for me.   

In VSTS Release Management I've been having the simplest of CodedUI tests fail when running the "Run Functional Tests" task in a release. The initial "fix" was to reboot the machine that is running the tests. But then the issue would come back if I disconnected from the machine. As long as the session was attended then the CodedUI tests would get past this hurdle (and fail for other reasons but that's a different issue). But once disconnected then the failed CodedUI test would throw an error message including the text "Microsoft.VisualStudio.TestTools.UITest.Extension.UITestException: Automation engine is unable to playback the test because it is not able to interact with the desktop. This could happen if the computer running the test is locked or it’s remote session window is minimized." 

By configuring the Agent Login and Agent Password parameters of the "Visual Studio Test Agent Deployment" task of the Release Definition to be the same as used for the Build Agent which is used to execute the release the problem goes away.

**Comment by jachakrohit07** [comment] 2017-06-30 16:40
Hello. I am new to tfs but learning things quickly. Sometimes just before the release I discover that the build agent has stopped running. I have tfs 2015 on my windows machine. How can I automate the process to make the build agent run continuously or start it automatically when it stops running?

**Comment by nigurr** [comment] 2017-07-03 08:41
@jachakrohit07 any build agent related issues can be reported here: https://github.com/microsoft/vsts-agent
You can configure the agent to run in "Service" mode.

**Comment by jachakrohit07** [comment] 2017-08-01 15:56
Hello guys. I am having really an important question regarding changeset report on the tfs server as I want to link the changeset to the tasks in the report. Who can I reach out to as it is related to the TFS Datawarehouse..

**Comment by bryanmacfarlane** [comment] 2017-08-01 23:07
@jachakrohit07 - send me a mail.  That's bryanmac and it's at microsoft.  I can help route.
