### ISSUE TITLE
Namespace ignored on Azure Container Registry Secret

### ISSUE THREAD

**Issue by benbuckland** [Microsoft/vsts-tasks#6695] opened 2018-03-15 04:29 UTC
I have tried to day to deploy to a custom namespace within AKS. The deploy works as expected but the secret for the Azure Container Registry gets created in the default namespace.

Steps to reproduce:
1. On a 'Deploy to Kubernetes' task
-  Set the namespace, I choose 'Dev'
-  Under the 'Container Registry Details' enter a secret name, I choose acr-secret
2. Run the release
3. Check the log, you can see the kubectl task is run with no namespace appended to the command. Snippet of log:
```
2018-03-14T21:46:45.3935732Z [command]/tmp/kubectlTask/1521064003452/kubectl --kubeconfig /tmp/kubectlTask/1521064003452/config create secret docker-registry acr-secret --docker-server=xxx.azurecr.io --docker-username=******** --docker-password=******** --docker-email=xxxx
2018-03-14T21:46:45.4373720Z secret "acr-secret" created
```
It make no difference if 'Force update secret' is selected or not.

Thanks.

**Comment by jikuma** [comment] 2018-03-16 04:03
@benbuckland can you share your account name. e.g: **accountname**.visualstudio.com

We have identified the issue and the fix will be rolled out in a couple of weeks for all ring. Is this a blocker for you?

You can use 'create' command to create docker registry secret instead of providing container registry details. I understand that this is not an ideal solution as you will have to get the secrets from registry manually but you can try this as workaround.

**Comment by benbuckland** [comment] 2018-03-16 04:29
Hey Jitendra, account name is PagePulse.visualstudio.com.

I have created the secret manually so all good for a work around.

Thanks, for coming back to me.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jikuma** [comment] 2018-03-16 05:11
Fix for the issue is already getting deployed. So closing the issue.

**Closed by jikuma** 2018-03-16 05:11 UTC
Labels: Area: Release
