### ISSUE TITLE
Azure App Service Manage doesn't start my slot (but logs say it started)

### ISSUE THREAD

**Issue by andrecarlucci** [Microsoft/vsts-tasks#5714] opened 2017-10-26 17:00 UTC
## Environment
- Server - VSTS    
-- account name: Way2
-- Project: Way2Consumers
-- Build Name: Way2ConsumersBuild
-- Build number: Any

- Agent - Hosted or Private: 
Private: Windows Server 2012

## Issue Description
The task says it started my slot, but it doesn't (slot name = pre)
I have to manually start it every time :(

### Error logs
Logs say that the operation was successfully, but the app is still down

2017-10-26T16:44:00.9713333Z ##[section]Starting: Start Azure App Service: powerhub-web
2017-10-26T16:44:00.9713333Z ==============================================================================
2017-10-26T16:44:00.9713333Z Task         : Azure App Service Manage
2017-10-26T16:44:00.9713333Z Description  : Start, Stop, Restart, Slot swap or Install site extensions for an Azure App Service
2017-10-26T16:44:00.9713333Z Version      : 0.2.17
2017-10-26T16:44:00.9713333Z Author       : Microsoft Corporation
2017-10-26T16:44:00.9713333Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=831573)
2017-10-26T16:44:00.9713333Z ==============================================================================
2017-10-26T16:44:02.0963380Z Starting App Service : powerhub-web-pre
2017-10-26T16:44:02.8619976Z App Service 'powerhub-web-pre' started successfully
2017-10-26T16:44:07.4401674Z Successfully updated deployment History at https://powerhub-web-pre.scm.azurewebsites.net/api/deployments/2661509036244143
2017-10-26T16:44:07.4401674Z ##[section]Finishing: Start Azure App Service: powerhub-web

[Insert error from the logs here]

**Comment by vincentdass** [comment] 2017-10-27 08:12
@andrecarlucci , Can you please enable/set variable `system.debug` to `true` and rerun the build for debug logs. This will provide more logs on whether the app service is started.

**Comment by andrecarlucci** [comment] 2017-10-27 11:34
There you go:

2017-10-27T11:23:42.9251685Z ##[debug]Evaluating condition for step: 'Start Azure App Service: PowerHub'
2017-10-27T11:23:42.9251685Z ##[debug]Evaluating: succeeded()
2017-10-27T11:23:42.9251685Z ##[debug]Evaluating succeeded:
2017-10-27T11:23:42.9251685Z ##[debug]=> (Boolean) True
2017-10-27T11:23:42.9251685Z ##[debug]Expanded: True
2017-10-27T11:23:42.9251685Z ##[debug]Result: True
2017-10-27T11:23:42.9251685Z ##[section]Starting: Start Azure App Service: PowerHub
2017-10-27T11:23:42.9251685Z ==============================================================================
2017-10-27T11:23:42.9251685Z Task         : Azure App Service Manage
2017-10-27T11:23:42.9251685Z Description  : Start, Stop, Restart, Slot swap or Install site extensions for an Azure App Service
2017-10-27T11:23:42.9251685Z Version      : 0.2.17
2017-10-27T11:23:42.9251685Z Author       : Microsoft Corporation
2017-10-27T11:23:42.9251685Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=831573)
2017-10-27T11:23:42.9251685Z ==============================================================================
2017-10-27T11:23:43.3626548Z ##[debug]agent.workFolder=D:\PowerHubBuild\_work
2017-10-27T11:23:43.3626548Z ##[debug]loading inputs and endpoints
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_47b1753f-871d-4546-b297-2368a58b18ac
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_47b1753f-871d-4546-b297-2368a58b18ac_SERVICEPRINCIPALID
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_47b1753f-871d-4546-b297-2368a58b18ac_SERVICEPRINCIPALKEY
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_47b1753f-871d-4546-b297-2368a58b18ac_TENANTID
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_SCHEME_47b1753f-871d-4546-b297-2368a58b18ac
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2017-10-27T11:23:43.3626548Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_ACTION
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_CONNECTEDSERVICENAME
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_PRESERVEVNET
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_RESOURCEGROUPNAME
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_SLOT
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_SPECIFYSLOT
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_SWAPWITHPRODUCTION
2017-10-27T11:23:43.3626548Z ##[debug]loading INPUT_WEBAPPNAME
2017-10-27T11:23:43.3626548Z ##[debug]loading SECRET_WEBSITEPASSWORD
2017-10-27T11:23:43.3626548Z ##[debug]loading SECRET_WEBSITEUSERNAME
2017-10-27T11:23:43.3626548Z ##[debug]loaded 18
2017-10-27T11:23:43.5657825Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_8db5e2e9-c774-4a81-9ef7-c8deb2682f22_build_4_271
2017-10-27T11:23:43.5657825Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_8db5e2e9-c774-4a81-9ef7-c8deb2682f22_build_4_271
2017-10-27T11:23:43.5814033Z ##[debug]AZURE_HTTP_USER_AGENT=VSTS_8db5e2e9-c774-4a81-9ef7-c8deb2682f22_build_4_271
2017-10-27T11:23:43.5814033Z ##[debug]check path : D:\PowerHubBuild\_work\_tasks\AzureAppServiceManage_f045e430-8704-11e6-968f-e717e6411619\0.2.17\task.json
2017-10-27T11:23:43.5814033Z ##[debug]set resource file to: D:\PowerHubBuild\_work\_tasks\AzureAppServiceManage_f045e430-8704-11e6-968f-e717e6411619\0.2.17\task.json
2017-10-27T11:23:43.5814033Z ##[debug]system.culture=en-US
2017-10-27T11:23:43.5814033Z ##[debug]ConnectedServiceName=47b1753f-871d-4546-b297-2368a58b18ac
2017-10-27T11:23:43.5814033Z ##[debug]Action=Start Azure App Service
2017-10-27T11:23:43.5814033Z ##[debug]WebAppName=powerhub-web
2017-10-27T11:23:43.5814033Z ##[debug]ResourceGroupName=PowerHub
2017-10-27T11:23:43.5814033Z ##[debug]SpecifySlot=true
2017-10-27T11:23:43.5814033Z ##[debug]Slot=pre
2017-10-27T11:23:43.5814033Z ##[debug]SourceSlot=null
2017-10-27T11:23:43.5814033Z ##[debug]SwapWithProduction=true
2017-10-27T11:23:43.5814033Z ##[debug]TargetSlot=null
2017-10-27T11:23:43.5814033Z ##[debug]PreserveVnet=false
2017-10-27T11:23:43.5814033Z ##[debug]ExtensionsList=null
2017-10-27T11:23:43.5814033Z ##[debug]OutputVariable=null
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac data subscriptionid = 84bf2f67-067c-4a64-99bb-ee072526952e
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac auth param serviceprincipalid = ********
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac auth param serviceprincipalkey = ********
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac auth param tenantid = ********
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac data subscriptionid = 84bf2f67-067c-4a64-99bb-ee072526952e
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac data environmentAuthorityUrl = https://login.windows.net/
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac=https://management.azure.com/
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac data environment = AzureCloud
2017-10-27T11:23:43.5814033Z ##[debug]47b1753f-871d-4546-b297-2368a58b18ac data activeDirectoryServiceEndpointResourceId = https://management.core.windows.net/
2017-10-27T11:23:43.5814033Z ##[debug]Requesting for Auth Token: https://login.windows.net/********/oauth2/token/
2017-10-27T11:23:44.0189070Z ##[debug]Request to start App Service: https://management.azure.com/subscriptions/84bf2f67-067c-4a64-99bb-ee072526952e/resourceGroups/PowerHub/providers/Microsoft.Web/sites/powerhub-web/slots/pre/start?api-version=2016-08-01
2017-10-27T11:23:44.0189070Z Starting App Service : powerhub-web-pre
2017-10-27T11:23:45.4564438Z App Service 'powerhub-web-pre' started successfully
2017-10-27T11:23:45.4720268Z ##[debug]Requesting for Auth Token: https://login.windows.net/********/oauth2/token/
2017-10-27T11:23:45.9095287Z ##[debug]Request to get App State: powerhub-web-pre
2017-10-27T11:23:46.5189815Z ##[debug]App Service State : Running
2017-10-27T11:23:46.5345188Z ##[debug]App Service is in Running State
2017-10-27T11:23:46.5345188Z ##[debug]build.buildUri=vstfs:///Build/Build/271
2017-10-27T11:23:46.5345188Z ##[debug]release.releaseUri=undefined
2017-10-27T11:23:46.5345188Z ##[debug]build.buildId=271
2017-10-27T11:23:46.5345188Z ##[debug]release.releaseId=undefined
2017-10-27T11:23:46.5345188Z ##[debug]Requesting for Auth Token: https://login.windows.net/********/oauth2/token/
2017-10-27T11:23:46.9720793Z ##[debug]Requesting Azure Publish Profile: https://management.azure.com/subscriptions/84bf2f67-067c-4a64-99bb-ee072526952e/resourceGroups/PowerHub/providers/Microsoft.Web/sites/powerhub-web/slots/pre/publishxml?api-version=2016-08-01
2017-10-27T11:23:47.5657646Z ##[debug]Web App Publish Kudu URL: powerhub-web-pre.scm.azurewebsites.net:443
2017-10-27T11:23:47.5657646Z ##[debug]build.sourceVersionAuthor=andrecarlucci
2017-10-27T11:23:47.5657646Z ##[debug]build.buildUri=vstfs:///Build/Build/271
2017-10-27T11:23:47.5657646Z ##[debug]release.releaseUri=undefined
2017-10-27T11:23:47.5657646Z ##[debug]build.buildId=271
2017-10-27T11:23:47.5657646Z ##[debug]release.releaseId=undefined
2017-10-27T11:23:47.5657646Z ##[debug]build.buildNumber=20171027.1
2017-10-27T11:23:47.5657646Z ##[debug]release.releaseName=undefined
2017-10-27T11:23:47.5657646Z ##[debug]system.TeamFoundationCollectionUri=https://way2.visualstudio.com/
2017-10-27T11:23:47.5657646Z ##[debug]system.teamProjectId=27d3ae76-fb3a-43f1-9392-a9b84cd7f387
2017-10-27T11:23:47.5657646Z ##[debug]build.sourceVersion=17eff191406394da4796b5dc6ff61a3d960c100f
2017-10-27T11:23:47.5657646Z ##[debug]build.repository.name=Way2Consumers
2017-10-27T11:23:47.5657646Z ##[debug]build.repository.provider=TfsGit
2017-10-27T11:23:47.8001400Z Successfully updated deployment History at https://powerhub-web-pre.scm.azurewebsites.net/api/deployments/2711509103426518
2017-10-27T11:23:47.8157710Z ##[section]Finishing: Start Azure App Service: PowerHub

**Comment by andrecarlucci** [comment] 2017-10-27 16:38
Hi guys,

Another problem with slots, when trying to use the REST API, I always get NOT FOUND when trying to Start/Stop the slot.

This is my URL: https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{webAppName}/slots/{slotName}/stop?api-version=2016-08-01

I tried using the slot fullname "powerhub-web-pre" and just "pre". Same problem.
I also created a new slot and had the same problems too :(

**Comment by vincentdass** [comment] 2017-10-29 10:09
@andrecarlucci , Is the 'NOT FOUND' issue happening with Azure App Service Manage Task?
If not, how is the call made? (say, using postman). Are you passing authentication headers?

Coming to first issue, we can confirm that the app service is in running state once the app is started.
Can you please provide some more info on this issue?
  -  How did you confirm that the app service is in stopped state? (via Azure Portal or just a web request).
    if possible, can you please add a powershell task that makes a request to your service after Manage Task?
`Invoke-WebRequest http://<app_name_here>.azurewebsites.net -UseBasicParsing `

In this way we can be sure that the app service is not running after Manage Task.

**Comment by andrecarlucci** [comment] 2017-10-31 18:10
Hi @vincentdass ,

It starts the app correctly:

```
##[debug]GET http://pre.powerhub.io/ with 0-byte payload
2017-10-31T17:53:30.9409137Z ##[debug]received -1-byte response of content type text/html; charset=utf-8
2017-10-31T17:53:31.0658975Z 
2017-10-31T17:53:31.1283933Z 
2017-10-31T17:53:31.3783984Z StatusCode        : 200
2017-10-31T17:53:31.3783984Z StatusDescription : OK
2017-10-31T17:53:31.3783984Z Content           : 
```

Which is even weirder!!!

According to the Azure logs, the app goes down 2min AFTER the build, and I have no idea why :(

![image](https://user-images.githubusercontent.com/66689/32240808-6e24f61a-be55-11e7-993f-72f61dfa55da.png)

That's the unidentified Stop Operation log:

```json
{
    "authorization": {
        "action": "Microsoft.Web/sites/slots/stop/action",
        "scope": "/subscriptions/84bf2f67-067c-4a64-99bb-ee072526952e/resourceGroups/PowerHub/providers/Microsoft.Web/sites/powerhub-web/slots/pre"
    },
    "channels": "Operation",
    "claims": {
        "aud": "https://management.azure.com/",
        "iss": "https://sts.windows.net/4fc4fbc1-b0bf-4c8c-9aa5-fb710b99b784/",
        "iat": "1509472244",
        "nbf": "1509472244",
        "exp": "1509476144",
        "aio": "Y2NgYGBlVE3n65qavHtx3xSbyfELAQ==",
        "appid": "01dc6854-0e96-4f25-a03e-8fd58983ed8b",
        "appidacr": "1",
        "http://schemas.microsoft.com/identity/claims/identityprovider": "https://sts.windows.net/4fc4fbc1-b0bf-4c8c-9aa5-fb710b99b784/",
        "http://schemas.microsoft.com/identity/claims/objectidentifier": "abb600a7-32ff-41ba-8ad7-338933468986",
        "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": "abb600a7-32ff-41ba-8ad7-338933468986",
        "http://schemas.microsoft.com/identity/claims/tenantid": "4fc4fbc1-b0bf-4c8c-9aa5-fb710b99b784",
        "uti": "gsNn0edpk0O8IQaQ2okHAA",
        "ver": "1.0"
    },
    "correlationId": "962bbc40-ef77-4f59-84ef-7cc91aa1ff36",
    "description": "",
    "eventDataId": "a094df63-da7b-403f-99e2-f58c7a8b36a3",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2017-10-31T17:55:44.8439253Z",
    "id": "/subscriptions/84bf2f67-067c-4a64-99bb-ee072526952e/resourceGroups/PowerHub/providers/Microsoft.Web/sites/powerhub-web/slots/pre/events/a094df63-da7b-403f-99e2-f58c7a8b36a3/ticks/636450693448439253",
    "level": "Informational",
    "operationId": "962bbc40-ef77-4f59-84ef-7cc91aa1ff36",
    "operationName": {
        "value": "Microsoft.Web/sites/slots/stop/action",
        "localizedValue": "Microsoft.Web/sites/slots/stop/action"
    },
    "resourceGroupName": "PowerHub",
    "resourceProviderName": {
        "value": "Microsoft.Web",
        "localizedValue": "Azure Web Sites"
    },
    "resourceType": {
        "value": "Microsoft.Web/sites/slots",
        "localizedValue": "Microsoft.Web/sites/slots"
    },
    "resourceId": "/subscriptions/84bf2f67-067c-4a64-99bb-ee072526952e/resourceGroups/PowerHub/providers/Microsoft.Web/sites/powerhub-web/slots/pre",
    "status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
    },
    "subStatus": {
        "value": "OK",
        "localizedValue": "OK (HTTP Status Code: 200)"
    },
    "submissionTimestamp": "2017-10-31T17:56:00.7781926Z",
    "subscriptionId": "84bf2f67-067c-4a64-99bb-ee072526952e",
    "properties": {
        "statusCode": "OK",
        "serviceRequestId": "3ebcb830-91d6-42cb-9a58-2e0cf6a59573"
    },
    "relatedEvents": []
}
```

Any idea?

**Comment by vincentdass** [comment] 2017-11-01 15:15
@andrecarlucci , Can you please share the whole build/Release logs?
As you can see, the event is initiated by VSTS tasks (should be the Manage Task), can you please re-run the  build/Release and monitor it via Azure Portal activity logs once again?

**Comment by vincentdass** [comment] 2017-11-09 06:38
@andrecarlucci , is the issue resolved?

**Comment by andrecarlucci** [comment] 2017-11-09 17:33
Hi @vincentdass 

The problem is still there :(

![image](https://user-images.githubusercontent.com/66689/32619397-cfa79e8e-c561-11e7-8a5a-1b4c6bb7e518.png)

Can I send you directly the logs? They're not small :(

**Comment by vincentdass** [comment] 2017-11-10 04:34
@andrecarlucci , please share the logs to `RM_Customer_queries@Microsoft.com`.

**Comment by andrecarlucci** [comment] 2017-11-10 11:57
@vincentdass  sent :)

**Comment by vincentdass** [comment] 2017-11-14 17:00
Closing the thread, as the issue is not repro-able in new Build configuration.

**Closed by vincentdass** 2017-11-14 17:00 UTC
Labels: Area: AzureAppService, Area: Release
