### ISSUE TITLE
View YAML of NuGetCommand@2 task does not show value for exportFeedCredentials

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-tasks#7315] opened 2018-05-29 11:57 UTC
## Environment
- Server - VSTS or TFS on-premises?
    
VSTS - account: `rcss-02-willistowerswatson`

- Agent - Hosted or Private: 
    
NA

## Issue Description

The `Restore Nuget` task v2 `NuGetCommand@2` does not export the `exportFeedCredentials` field entry when clicking on `View YAML`
![image](https://user-images.githubusercontent.com/9250262/40657378-8f31c47a-633f-11e8-8a79-ef9585852514.png)

As a workaround, I have to peek into the json definition to find out it is a comma separated string of GUIDS that match to the endpoints (instead of using the human readable Name, that is displayed and can be used in the non-yaml task)

**Comment by keithrob** [comment] 2018-05-30 22:37
Duplicate of #7304

**Closed** 2018-05-30 22:37 UTC
Labels: Area: Packaging
