### ISSUE TITLE
AzureFileCopy task fails due to MaxEnvelopeSizekb WinRM setting being too low

### ISSUE THREAD

**Issue by DanielBMann9000** [Microsoft/vsts-tasks#3496] opened 2017-01-25 23:15 UTC
The AzureFileCopy task does not attempt to set the MaxEnvelopeSizeKb WinRM setting during prerequisite configuration. Every other task that configures WinRM prerequisites does this. Error message:

> 2017-01-25T22:01:27.2370791Z ##[error]Failed to initiate the download on the remote machine.Starting a command on the remote server failed with the following error message : The WinRM client sent a request to the remote WS-Management service and was notified that the request size exceeded the configured MaxEnvelopeSize quota. For more information, see the about_Remote_Troubleshooting Help topic.To fix WinRM connection related issues, select the 'Enable Copy Prerequisites' option in the task. If set already, and the target Virtual Machines are backed by a Load balancer, ensure Inbound NAT rules are configured for target port (5986). Applicable only for ARM VMs. For more info please refer to https://aka.ms/azurefilecopyreadme

It's also worth noting that this task is the only one that pulls its WinRM configuration directly from external GitHub content.
Ex:
```
    $configWinRMScriptFile="https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/ConfigureWinRM.ps1"
    $makeCertFile="https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/makecert.exe"
    $winrmConfFile="https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd"
```

That seems dangerous, as there is no guarantee that these files will
- Remain the same/correct
- Continue to exist 

Also worth noting that the need to update this value was called out in #1897, when a similar fix was put in place for the PowerShell on Remote Machine task.

**Comment by pavanadepu2** [comment] 2017-02-03 04:39
@DanielBMann9000, we have fixed the WinRM MaxEnvelopeSizeKb issue. Could you please retry your scenario and let me know if you still see any issue.

Also, the scripts present in external GitHub are maintained by our team itself. These scripts exists forever and remain correct.

**Comment by mvvsubbu** [comment] 2017-02-06 10:32
Any update?

**Comment by mvvsubbu** [comment] 2017-02-07 06:31
I am resolving as the issue is resolved. You can feel free to reopen if it doesn't work.

**Closed by mvvsubbu** 2017-02-07 06:31 UTC
Labels: Area: Release, Dev15

**Comment by DanielBMann9000** [comment] 2017-02-08 06:03
@mvvsubbu @pavanadepu2 That took care of it, thank you!
