### ISSUE TITLE
Azure App Service Deploy fail when doing a "slot" deployment to a "Virtual application" with long App Service name

### ISSUE THREAD

**Issue by mathlesp** [Microsoft/vsts-tasks#6708] opened 2018-03-15 15:23 UTC
## Environment
VSTS
Hosted Agent

## Issue Description
Azure App Service Deploy task (v3.3.42) fail when doing a "slot" deployment to a "Virtual application" with a long App Service name:

* Create an App Service with a long name (i.e. 45 chars)
* Configure a Virtual directory in "Application settings" i.e. (/api)
* Add a deployment slot (i.e. staging)
  * Note that in the full name of the slot (Url), the App Service name part will be truncated to 40 chars)
  * i.e. instead of "longNameStart[...]**longNameEnd-staging**.azurewebsites.net" we get something like "longNameStart[...]**longNa-staging**.azurewebsites.net"
* In VSTS create a release and add an Azure App Service Deploy task:
  * App type: Web App
  * App Service name: the App Service you just created
  * Tick the "Deploy to slot" checkbox
  * Select the slot (i.e. "staging")
  * Enter the name of the "Virtual application" (i.e. "api")
  * Select a package or folder to deploy, etc
* Trigger the release
* Notice the error:
 ##[error]Error: Failed to list path 'site/api' from Kudu. Error: getaddrinfo ENOTFOUND longNameStart[...]longNameEnd-staging.scm.azurewebsites.net longNameStart[...]longNameEnd-staging.scm.azurewebsites.net:443
* Notice the task is trying to connect using the non-truncated version of the slot name

If the deployment is NOT to a Virtual Application, the task will succeed but with a warning related to "UpdateDeploymentHistory":
 ##[warning]Error: FailedToUpdateDeploymentHistory getaddrinfo ENOTFOUNDlongNameStart[...]longNameEnd-staging.scm.azurewebsites.net longNameStart[...]longNameEnd-staging.scm.azurewebsites.net:443

* This only fail for slot deployment
* Version of the task is 3.3.42
* This was working in version 3.3.36

### Error logs
##[error]Error: Failed to list path 'site/api' from Kudu. Error: getaddrinfo ENOTFOUND longNameStart[...]longNameEnd-staging.scm.azurewebsites.net longNameStart[...]longNameEnd-staging.scm.azurewebsites.net:443

**Comment by vincentdass** [comment] 2018-03-16 09:19
@mathlesp , thanks for reporting the issue.
We have determined the issue in App Service API and reported the same to App Service team.
Will update you, if there is any other updates.

**Comment by vincentdass** [comment] 2018-03-18 08:41
@mathlesp , Since the issue is from Azure App Service side, I have created a bug [here](https://social.msdn.microsoft.com/Forums/en-US/bb04acdd-5951-4814-8c34-f4a2f1a17e74/azure-app-service-provides-incorrect-scm-url-in-publishing-credentials?forum=windowsazurewebsitespreview).
Please do follow-up there for more details.

Closing the issue, as there is no action item required from VSTS side.

**Closed by vincentdass** 2018-03-18 08:41 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by wolesolana** [comment] 2020-02-10 21:30
Did we get a solution to this problem? I'm experiencing the same issue and the forum link you added doesn't seem to have a solution posted @vincent1173
