### ISSUE TITLE
Xamarin license deactivation seems to be failing consistently

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-tasks#1800] opened 2016-05-26 23:40 UTC
The Xamarin license activation step succeeds, but the DEactivation step fail every time.

Even though a build step prior to the deactivation is failing, the deactivation should still be able to complete. I've double- and triple-checked the credentials in the step.

Agent console output:
https://gist.github.com/jsauvexamarin/aa399160fee2ec7ca62274ab1e67c753

Source of error message:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/XamarinLicense/xamarinlicense.ts#L290

Agent version (for OS X):
https://github.com/Microsoft/vsts-agent/releases/tag/v2.101.0

Xamarin settings on build agent: 
https://gist.github.com/jsauvexamarin/36262b236800414862aae4cf9cbfff72

**Comment by jsauvexamarin** [comment] 2016-05-27 02:24
It turns out this may have been in error. Since I'm using the OS X VSTS build agent, and since my Mac Mini already has the Xamarin licenses activated locally, I didn't need the Xamarin licensing build steps anyway. So, I just removed the activation and deactivation steps entirely from my VSTS build config.

However, I'm still not sure why the activation was working and the deactivation was not. To test, I disabled the deactivation step and queued a build. In the Xamarin store web interface, I expected to see a new activation show up in the list; but I didn't. Since the build was starting, apparently even when a license activation wan't taking pace, I realized that I didn't need the activation steps, so I removed them completely.

My final build config wound up being this simple:
![screen shot 2016-05-26 at 9 13 45 pm](https://cloud.githubusercontent.com/assets/12718942/15595854/1a0858a6-2388-11e6-9e57-085a51ea898b.png)

**Comment by yacaovsnc** [comment] 2016-05-31 13:17
If a license is detected, the activation step will simply return successful without making any changes to the system.  That's why it worked in your case, it was simply a no-op.  

I am closing this as this is working as intended.  Please let us know if you hit any other issues related with license.

**Closed by yacaovsnc** 2016-05-31 13:17 UTC
