### ISSUE TITLE
Facing issue during use of ZIP deploy and Run from zip

### ISSUE THREAD

**Issue by harsh-argusoft** [Microsoft/vsts-tasks#8313] opened 2018-09-14 06:42 UTC
Hi,

I am using zip deploy method to deploy code on WebApp. But sometimes we are facing issue file missing issue on zip deploy as result server is not working.

Same as Run from zip we are facing permission issue. sometime we are not able to edit files under wwwroot.

Someone please suggest if any solution for this?

Previously we were using WebDeploy but We are deploying nodeJs+Angular(Webpack) application so we have to deploy node_modules on server so it's taking more than one hours. It is trying to delete every individual files and trying to upload it again.

**Comment by SumiranAgg** [comment] 2018-09-17 05:50
@harsh-argusoft RunFromZip makes file structure under wwwroot ReadOnly by design. If you want to edit something after deployment you should use ZipDeploy.
As for the issue with ZipDeploy, it removes previous files with every deployment. Are you using two Release Definitions to deploy (for instance one for Core app, another for dependencies)? If yes, that might be causing file missing issue.
Can you share debug logs for the task and release logs at RM_Customer_Queries@microsoft.com for further investigation?

**Comment by harsh-argusoft** [comment] 2018-09-20 05:34
Hey @SumiranAgg ,

We are using a single pipeline and deploying directly to production slot. Faced with this issue yesterday again where index.html and web.config were missing. I have shared the debug logs on the above-mentioned email address. Thanks.

**Comment by SumiranAgg** [comment] 2018-10-15 04:34
If you see the issue again, check the manifest file for latest deployment (You can find the link in debug log) for the missing files.
If the entries are missing, share that manifest file with us. 
Closing the issue until details are shared for further investigation. Pleas re-open if required.

**Closed by SumiranAgg** 2018-10-15 04:34 UTC
Labels: Area: AzureAppService, Area: Release
