### ISSUE TITLE
Publish Test Results doesn't produce the code coverage results in summary page

### ISSUE THREAD

**Issue by dsbenghe** [Microsoft/vsts-tasks#6649] opened 2018-03-09 08:33 UTC
## Environment
- Server - TFS on-premises
15.117.26714.0

- Agent - Private: 
2.126.0

## Issue Description

We are trying to publish the tests results and code coverage via Publish Test Results task. Tests results are published correctly but not the code coverage results which are not shown in the build results  summary page. There is a zip created as attachment which contains the .trx and .coverage file but this is not what is expected.

We tried with both v1 and v2-preview Publish Test Results tasks - same outcome.

According with a recent issue - https://github.com/Microsoft/vsts-tasks/issues/6316 - this is supposed to work but it doesn't for us.

### Error logs

The logs from running v1 (1.0.36)

Preparing task execution handler.
Executing the powershell script: d:\BLD\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.36\PublishTestResults.ps1
PowerShellHandler.Execute - AddCommand(d:\BLD\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.36\PublishTestResults.ps1)
PowerShellHandler.Execute - Add inputParameters
PowerShellHandler.Execute - AddParameter(testRunner=VSTest)
PowerShellHandler.Execute - AddParameter(testResultsFiles=d:\BLD\_work\13\s\TestResults\**\*.trx)
PowerShellHandler.Execute - AddParameter(mergeTestResults=true)
PowerShellHandler.Execute - AddParameter(testRunTitle=)
PowerShellHandler.Execute - AddParameter(platform=x64)
PowerShellHandler.Execute - AddParameter(configuration=release)
PowerShellHandler.Execute - AddParameter(publishRunAttachments=true)
PowerShellHandler.Execute - Invoke
Entering script PublishTestResults.ps1
Loading module from path 'D:\BLD\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.Internal\Microsoft.TeamFoundation.DistributedTask.Task.Internal.psd1'.
Loading module from path 'D:\BLD\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.Internal\Microsoft.TeamFoundation.DistributedTask.Task.Internal.psm1'.
Loading module from path 'D:\BLD\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.LegacySDK.dll'.
...
Loading module from path 'D:\BLD\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.Common\Microsoft.TeamFoundation.DistributedTask.Task.Common.psd1'.
Loading module from path 'D:\BLD\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.Common\Microsoft.TeamFoundation.DistributedTask.Task.Common.psm1'.
...
Loading module from path 'D:\BLD\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.TestResults\Microsoft.TeamFoundation.DistributedTask.Task.TestResults.psm1'.
..
Pattern found in testResultsFiles parameter.
Find-Files -SearchPattern d:\BLD\_work\13\s\TestResults\**\*.trx
FindFiles.FindMatchingFiles(rootFolder = , matchPattern = d:\BLD\_work\13\s\TestResults\**\*.trx, includeFiles = True, includeFolders = False
FindFiles.GetMatchingItems(includePatterns.Count = 1, excludePatterns.Count = 0, includeFiles = True, includeFolders = False
FindFiles.GetMatchingItems - Found: d:\BLD\_work\13\s\TestResults\XXX_2018-03-08_09_51_10.trx
FindFiles.FindMatchingFiles - Found 1 matches
matchingTestResultsFiles = d:\BLD\_work\13\s\TestResults\XXX_2018-03-08_09_51_10.trx
Calling Publish-TestResults
Publishing Test Results...
Get - SecretService and EndpointService from TaskContext
Fetched Endpoint:SystemVssConnection
AuthorizationType : OAuth
VssConnection created
Attachment location: d:\BLD\_work\13\s\TestResults\XXX_2018-03-08_09_51_10\In
Setting run start and finish times.
Adding run level attachment: d:\BLD\_work\13\s\TestResults\XXX_2018-03-08_09_51_10\In\YYY\XXX 2018-03-08 09_51_05.coverage
Total test results: 4904
Test results remaining: 4904
Test results remaining: 3904
Test results remaining: 2904
Test results remaining: 1904
Test results remaining: 904
Published Test Run : https://ZZZ/_TestManagement/Runs#runId=390214&_a=runCharts
Leaving script PublishTestResults.ps1
Finishing: Publish Test Results

Cheers

**Comment by dsbenghe** [comment] 2018-03-15 20:39
Any news here? This should just work but somehow it doesn't. 

Or I can publish other types of coverage results but not the one generated by Microsoft's own tools?

**Comment by ShreyasRmsft** [comment] 2018-03-19 06:47
@dsbenghe, how are you running your tests and generating the code coverage and trx files? Are you using the VsTest task?

Can you send me screen shots of your definition so i can understand the setup? And maybe some info as well to quickly get me up to speed on what you are trying to do.

Also in tfs 2015 this was the behavior and it was fixed later on. In VSTS this should work fine and in latest version of tfs as well.

**Comment by dsbenghe** [comment] 2018-03-19 07:36
We are running the tests via a powershell based build script and the vstest console.

The command line we use is roughly this one  "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" /logger:trx $testAssemblies EnableCodeCoverage /Settings:XXX.runsettings

The .runsettings file is quite simple mostly to exclude some dlls from code coverage via 

<DataCollector friendlyName="Code Coverage" uri="datacollector://Microsoft/CodeCoverage/2.0" assemblyQualifiedName="Microsoft.VisualStudio.Coverage.DynamicCoverageDataCollector, Microsoft.VisualStudio.TraceCollector, Version=11.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a">
...
</DataCollector>

The build steps are just two:
- the one for the build script which generates the .trx and .coverage file
- the next one running Publish Test Results

We will prefer to do the publish test results and code coverage from the build script - but could not make it working: not sure if this is in fact doable or not. Maybe you can point me into the right direction regarding this if is doable.

Running the tests via VsTest task obviously works and we get the test results and code coverage published and nicely displayed in the summary, but this is not what we want to do.

**Comment by ShreyasRmsft** [comment] 2018-03-19 08:07
@dsbenghe I can't help you since you if you are on an older version of tfs as this was already fixed in later versions.

One solution is to upgrade to the latest Tfs.

Also since running via the vstest task works and is the recommended way can you please tell why you can't go ahead with using the vstest task? Is there some limitation? Maybe I can help you accomplish what you need with the vstest task itself.

Are there any additional step you are performing in the ps script that you would like vstest to perform?

**Comment by ShreyasRmsft** [comment] 2018-03-19 08:10
@dsbenghe the crux of the issue is that the .codecoverage file is going into the zip and code coverage summary is not generated unless the codecoverage file goes as a standalone attachment and not in a zip file.

You can take a look at the source code for the vstest task or some other task (these are open source) and  maybe attach the code coverage file separately out of the zip from you powershell script as a workaround if you can't move to a later tfs version

**Comment by dsbenghe** [comment] 2018-03-19 09:23
We are on 15.117.26714.0 - do you know in what version of TFS is this issue fixed?

We prefer not go with vstest task as a build step as this will defeat the purpose of having a build script (publish test results was a more acceptable compromise).

We tried to publish the tests & code coverage results from the powershell build script via vso commands (the only docs we could find was here - https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md ) but could not make it working (tried ##vso[task.addattachment ..). This is our preferred choice - it will be great if you can point us to the right documentation/place to publish test results & coverage from the powershell build script.

Cheers.

**Comment by ShreyasRmsft** [comment] 2018-03-19 10:27
@dsbenghe uploading the attachments that way is unsupported and we will not be able to provide support if something goes wrong. 

Call me persistent but in the long run I would still recommend using the vstest task. Whatever you are doing today via the powershell script you can do the same via vstest task. You can set output variable in your powershell script and use them as inputs to the vstest task which quite simply put invokes vstest console and publishes the result.

You can still retain your powershell script and only move the testing logic to the vstest task whose job it is to run and publish your results.

I did a bit of digging and you can not add attachments to a test run via an agent command. You have to go via the TestManagement apis to do this. And a simple script won't cut it as there a lot of inputs you need to provide. Again reiterating why you need a script to run tests when a complete solution already exists.

I tried looking at the commits to figure out when we made this fix but couldn't pinpoint which version exactly. But I do know that this works in the latest 2017 update 3 version of tfs.

**Comment by ShreyasRmsft** [comment] 2018-03-19 10:29
@dsbenghe I can assist you if you want help in moving to the vstest task but otherwise I'll be closing this issue as we have fixed it already.

**Comment by dsbenghe** [comment] 2018-03-19 11:12
Call me crazy to be that persistent :) but there are quite a bit of reasons to run tests from the build script.

Thanks for all the very valuable info - at least now we know what is working and what is not working and we can take a decision on what route we go:
- run vstest task build step as you suggested
- still do publish test results as now but without coverage and get the coverage reported via different tool.
- try to upgrade tfs to update 3

**Comment by ShreyasRmsft** [comment] 2018-03-19 12:20
@dsbenghe I'm closing this issue then. Reach out if you face any issues in case you move to the vstest task or if you upgrade and find it is not working.

**Closed by ShreyasRmsft** 2018-03-19 12:20 UTC
Labels: Area: Test

**Comment by shravanipandarmish-gep** [comment] 2019-07-30 02:19
Hi, I am facing issue with code coverage on VSTS (Azure DevOps). Pipeline throws error : "No code coverage attachments were found from the trx files". But when used command "vstest.console.exe H:\Agent8\31\s\GEP-Order-2.0\OrderService\OrderMSTest\bin\Release\OrderMSTest.dll /logger:trx /EnableCodeCoverage" on  Visual Studio Command Prompt it generates CodeCoverage. 
Can you please help on how can add this to my build pipeline to get Coverage. 
Thanks in advance.
