### ISSUE TITLE
Nuget installer task is not working behind a proxy

### ISSUE THREAD

**Issue by gereon77** [Microsoft/vsts-tasks#7564] opened 2018-06-26 09:48 UTC
## Environment
- Server - VSTS or TFS on-premises?
VSTS (Unfortunately I can't provide the URL for public)

- Agent - Hosted or Private: 
    Private: WinServer2k16, Version: vsts-agent-win-x64-2.134.2

## Issue Description
Agent was configured to use a proxy: https://docs.microsoft.com/en-us/vsts/pipelines/agents/proxy?view=vsts&tabs=windows 

It seems that the nuget install task doesn't respect the proxydetails. Other tasks like dotnet install work fine.

### Error logs
2018-06-25T09:39:44.5596486Z ##[debug]Evaluating condition for step: 'Use NuGet 4.7.0'
2018-06-25T09:39:44.5601807Z ##[debug]Evaluating: succeeded()
2018-06-25T09:39:44.5602605Z ##[debug]Evaluating succeeded:
2018-06-25T09:39:44.5603639Z ##[debug]=> True
2018-06-25T09:39:44.5604918Z ##[debug]Result: True
2018-06-25T09:39:44.5606517Z ##[section]Starting: Use NuGet 4.7.0
2018-06-25T09:39:44.6193704Z ==============================================================================
2018-06-25T09:39:44.6194331Z Task         : NuGet Tool Installer
2018-06-25T09:39:44.6195026Z Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this step to change the version of NuGet used in the NuGet steps.
2018-06-25T09:39:44.6195599Z Version      : 0.1.5
2018-06-25T09:39:44.6196001Z Author       : Microsoft Corporation
2018-06-25T09:39:44.6196455Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=852538)
2018-06-25T09:39:44.6197067Z ==============================================================================
2018-06-25T09:39:45.3505746Z ##[debug]agent.workFolder=D:\agent01\_work
2018-06-25T09:39:45.3507250Z ##[debug]loading inputs and endpoints
2018-06-25T09:39:45.3507851Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2018-06-25T09:39:45.3508506Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2018-06-25T09:39:45.3509055Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2018-06-25T09:39:45.3509564Z ##[debug]loading INPUT_CHECKLATEST
2018-06-25T09:39:45.3510041Z ##[debug]loading INPUT_VERSIONSPEC
2018-06-25T09:39:45.3510574Z ##[debug]loading SECRET_AGENT_PROXYPASSWORD
2018-06-25T09:39:45.3511064Z ##[debug]loaded 6
**2018-06-25T09:39:45.5149295Z ##[debug]Agent.ProxyUrl=hidden
2018-06-25T09:39:45.5150085Z ##[debug]Agent.ProxyUsername=hidden
2018-06-25T09:39:45.5160064Z ##[debug]Agent.ProxyPassword=undefined
2018-06-25T09:39:45.5160897Z ##[debug]Agent.ProxyBypassList=[hidden]**
2018-06-25T09:39:45.5165852Z ##[debug]check path : D:\agent01\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\0.1.5\node_modules\vsts-task-tool-lib\lib.json
2018-06-25T09:39:45.5170486Z ##[debug]set resource file to: D:\agent01\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\0.1.5\node_modules\vsts-task-tool-lib\lib.json
2018-06-25T09:39:45.5171517Z ##[debug]system.culture=en-US
2018-06-25T09:39:45.5551854Z ##[debug]check path : D:\agent01\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\0.1.5\task.json
2018-06-25T09:39:45.5554045Z ##[debug]set resource file to: D:\agent01\_work\_tasks\NuGetToolInstaller_2c65196a-54fd-4a02-9be8-d9d1837b7c5d\0.1.5\task.json
2018-06-25T09:39:45.5555959Z ##[debug]system.culture=en-US
2018-06-25T09:39:45.5689394Z ##[debug]versionSpec=4.7.0
2018-06-25T09:39:45.5694530Z ##[debug]checkLatest=false
2018-06-25T09:39:45.5718283Z ##[debug]isExplicit: 4.7.0
2018-06-25T09:39:45.5719207Z ##[debug]explicit? true
2018-06-25T09:39:45.5720257Z ##[debug]Exact match expected on version: 4.7.0
2018-06-25T09:39:45.5721173Z ##[debug]Trying to get tool from local cache
2018-06-25T09:39:45.5725318Z ##[debug]isExplicit: 4.7.0
2018-06-25T09:39:45.5726151Z ##[debug]explicit? true
2018-06-25T09:39:45.5730619Z ##[debug]Agent.Version=2.134.2
2018-06-25T09:39:45.5731875Z ##[debug]Agent.ToolsDirectory=D:\agent01\_work\_tool
2018-06-25T09:39:45.5733304Z ##[debug]checking cache: D:\agent01\_work\_tool\NuGet\4.7.0\x64
2018-06-25T09:39:45.5739281Z ##[debug]not found
2018-06-25T09:39:45.5743580Z ##[debug]Agent.Version=2.134.2
2018-06-25T09:39:45.5744322Z ##[debug]Agent.ToolsDirectory=D:\agent01\_work\_tool
2018-06-25T09:39:45.5777494Z ##[debug]isExplicit: 4.1.0
2018-06-25T09:39:45.5778564Z ##[debug]explicit? true
2018-06-25T09:39:45.5784438Z ##[debug]evaluating 1 versions
2018-06-25T09:39:45.5878739Z ##[debug]match not found
2018-06-25T09:39:45.5881258Z ##[debug]Querying versions list
**2018-06-25T09:39:46.7181451Z ERR:connect ECONNREFUSED 152.199.19.160:443**
2018-06-25T09:39:46.7185158Z ##[debug]task result: Failed
2018-06-25T09:39:46.7210032Z ##[debug]Processed: ##vso[task.complete result=Failed;]
2018-06-25T09:39:46.7363663Z ##[section]Finishing: Use NuGet 4.7.0

**Comment by iconfusepc** [comment] 2018-07-18 12:53
Having the same issue. Any updates/workarounds for this one?

**Comment by bryanmacfarlane** [comment] 2018-07-18 14:39
@iconfusepc - since the task installs nuget, the workaround is to not use the task and install it yourself on the machine?  If you're behind a proxy, I'm assuming it's on-prem private agent machine that you control?

**Comment by keithrob** [comment] 2018-07-24 19:45
Duplicate of #6252

**Closed by keithrob** 2018-07-24 19:45 UTC
Labels: Area: Packaging
