### ISSUE TITLE
vstest.console.exe failed with return code: 3221225477

### ISSUE THREAD

**Issue by rikvandenberg** [Microsoft/vsts-tasks#8072] opened 2018-08-20 12:31 UTC
## Environment: VSTS
- account name: sator
- team project name: (unable to share)
- build definition name: "PR (unable to share)"
- build id: 7481, 7482, 7487

**Private agent 1 details**

Agent.ComputerName | RIKVANDENBERG
-- | --
Agent.HomeDirectory | C:\dev\agents\DARTHREVAN
Agent.Name | DARTHREVAN
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.17134
Agent.Version | 2.136.1

**Private agent 2 details**

Agent.ComputerName | YODA
-- | --
Agent.HomeDirectory | D:\Agent
Agent.Name | YODA
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.17134
Agent.Version | 2.136.1

## Issue Description

Today we are receiving conflicting messages about the usage of VSTEST.console.exe. A lot of pull requests builds with the VSTEST task are producing the "Failed with return code 3221225477" unexpectedly.

![image](https://user-images.githubusercontent.com/397160/44339217-df10f600-a480-11e8-91d4-2c8c8e28da08.png)

Previous builds have **never** produced these errors and our stable main branch is also producing the same error code. From the 772 test, only ~690 are run before the tasks criticially errors out. 

Here are our VSTS Test Task settings.

![image](https://user-images.githubusercontent.com/397160/44339848-387a2480-a483-11e8-8596-9ce7e5b116f9.png)

**What have we attempted to solve the issue**

- Updated Visual Studio on Build agent from 15.7 to 15.8

#### VSTS Task output
```
2018-08-20T11:36:28.8980888Z ##[debug]rc:3221225477
2018-08-20T11:36:28.8981166Z ##[debug]success:false
2018-08-20T11:36:28.9001722Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-08-20T11:36:28.9002112Z ##[debug]Processed: ##vso[task.issue type=warning;]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-08-20T11:36:28.9008651Z ##[debug]Agent.Version=2.136.1
2018-08-20T11:36:28.9009075Z ##[debug]Release.ReleaseUri=undefined
2018-08-20T11:36:28.9009905Z ##[debug]Release.ReleaseId=undefined
2018-08-20T11:36:28.9010143Z ##[debug]Build.BuildUri=vstfs:///Build/Build/7482
2018-08-20T11:36:28.9010381Z ##[debug]Build.Buildid=7482
2018-08-20T11:36:28.9010933Z ##[debug]Agent.Version=2.136.1
2018-08-20T11:36:28.9012144Z ##[debug]telemetry area: TestExecution feature: TestExecutionTask data: {"builduri":"vstfs:///Build/Build/7482","buildid":"7482","areacode":"ExecuteVsTest","result":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe failed with return code: 3221225477","tracepoint":1005,"isusererror":true}
2018-08-20T11:36:28.9301162Z ##[debug]Processed: ##vso[telemetry.publish area=TestExecution;feature=TestExecutionTask;]{"builduri":"vstfs:///Build/Build/7482","buildid":"7482","areacode":"ExecuteVsTest","result":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe failed with return code: 3221225477","tracepoint":1005,"isusererror":true}
2018-08-20T11:36:28.9302214Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 3221225477
```

#### Event viewer
```
Application: vstest.console.exe Framework Version: v4.0.30319 Description: The process was terminated due to an internal error in the .NET Runtime at IP 6F4DA000 (6F440000) with exit code 80131506. 
```

**Comment by acesiddhu** [comment] 2018-08-20 16:25
@rikvandenberg does you test exercise any native code by any chance?

**Comment by rikvandenberg** [comment] 2018-08-20 20:28
@acesiddhu No it does not. 

Is there a way to find more detailed information about why the vstest.console.exe is critically failing?

**Comment by acesiddhu** [comment] 2018-08-21 04:08
you can take dump of the testhost process and see what might be wrong. here is the link on how to do this
. Note that this will work for VS 15.5 or more.
https://github.com/Microsoft/vsts-tasks/blob/users/nigurr/Docs/Tasks/VsTestV2/docs/DumpCollection.md

**Comment by acesiddhu** [comment] 2018-08-27 04:34
@rikvandenberg hope the dump helped you get to the root cause? I am closing the issue for now. Please reopen or create a new ticket if you are facing the issue still

**Closed by acesiddhu** 2018-08-27 04:34 UTC
Labels: Area: Test

**Comment by acesiddhu** [comment] 2018-08-27 10:26
Thanks for letting us know. Do open a new issue if you are facing any issues.

**Comment by jamers99** [comment] 2018-10-08 18:56
This is happening for us now... We are getting the blame logs now. @rikvandenberg did you ever attempt to resolve this?  We cannot use `dotnet test` because we target .NET Framework.
