### ISSUE TITLE
Windows agent failing on test build step when "publish test results" is enabled and the results directory has a space

### ISSUE THREAD

**Issue by ajbeaven** [Microsoft/vsts-tasks#6890] opened 2018-04-05 14:01 UTC
Running a dotnet test build step fails with the "publish test results" option checked if the path to the agent working directory has a space in it.

From the logs it looks like this happens because the --results-directory argument isn't enclosed in quotes:

```
2018-04-05T13:23:29.1389315Z ##[section]Starting: Test
2018-04-05T13:23:29.1399322Z ==============================================================================
2018-04-05T13:23:29.1399322Z Task         : .NET Core
2018-04-05T13:23:29.1399322Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2018-04-05T13:23:29.1399322Z Version      : 2.131.0
2018-04-05T13:23:29.1399322Z Author       : Microsoft Corporation
2018-04-05T13:23:29.1399322Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2018-04-05T13:23:29.1399322Z ==============================================================================
2018-04-05T13:23:30.0509234Z [command]"C:\Program Files\dotnet\dotnet.exe" test "D:\VSTS Agent\_work\9\s\MyApp.Tests\MyApp.Tests.csproj" --configuration release --logger trx --results-directory D:\VSTS Agent\_work\_temp
2018-04-05T13:23:30.2571100Z MSBUILD : error MSB1008: Only one project can be specified.
2018-04-05T13:23:30.2571100Z Switch: Agent\_work\_temp
2018-04-05T13:23:30.2571100Z 
2018-04-05T13:23:30.2571100Z For switch syntax, type "MSBuild /help"
2018-04-05T13:23:30.2821274Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
2018-04-05T13:23:30.2821274Z ##[warning]No test result files were found.
2018-04-05T13:23:30.2831285Z ##[error]Dotnet command failed with non-zero exit code on the following projects : D:\VSTS Agent\_work\9\s\MyApp.Tests\MyApp.Tests.csproj
2018-04-05T13:23:30.2881338Z ##[section]Finishing: Test
```

If you uncheck the "publish test results" checkbox there are no errors.

**Comment by abhishkk** [comment] 2018-04-11 18:25
@ajbeaven We are able to reproduce this issue. I am working on the fix for this issue.

**Comment by ikourfaln** [comment] 2018-05-04 14:38
@ajbeaven 
The issue is because of open/close quote mark, so this command:

`"C:\Program Files\dotnet\dotnet.exe" test "D:\VSTS Agent\_work\9\s\MyApp.Tests\MyApp.Tests.csproj" --configuration release --logger trx --results-directory D:\VSTS Agent\_work\_temp`

must be:

`"C:\Program Files\dotnet\dotnet.exe" test "D:\VSTS Agent\_work\9\s\MyApp.Tests\MyApp.Tests.csproj" --configuration release --logger trx --results-directory "D:\VSTS Agent\_work\_temp"`

So, waiting for the fix, in Test Task, uncheck the "Publish test results" checkbox, and append ` --logger trx --results-directory "D:\VSTS Agent\_work\_temp"` to you Arguments, just like this:

![capture](https://user-images.githubusercontent.com/9744226/39633857-19a242bc-4fb1-11e8-8f4a-5b9764de9fac.PNG)

**Comment by ajbeaven** [comment] 2018-05-05 00:42
@ikourfaln Yes, I realise you can manually hard-code the path. This issue is describing a bug with the "Publish test results" checkbox, which is presumably the option that ends up inserting `--results-directory` argument without the necessary quotes.

**Comment by nigurr** [comment] 2018-05-14 10:05
https://github.com/Microsoft/vsts-tasks/issues/6890

**Closed** 2018-05-16 08:09 UTC
Labels: Area: Test
