### ISSUE TITLE
Resource Group Deployment Task : output variables suddenly break deployment

### ISSUE THREAD

**Issue by jkewley** [Microsoft/vsts-tasks#4985] opened 2017-08-08 03:28 UTC
A few hours ago my deployment tasks built on Azure Resource Group Deployment suddenly stopped working. The error message I'm seeing appears to be new functionality which copies output variables into environmental variables. The failures looks like this:

`##[error]Unable to process command '##vso[task.setvariable isOutput=true;variable=DeploymentOutputs;]{"environment":{"type":"String","value":"d"},"....  }' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)`

`##[error]Value cannot be null.`

`Parameter name: RefName`

I found what looks to be a recent commit [related to this feature here](https://github.com/Microsoft/vsts-tasks/commit/6fe66c005b69f13fe1ff8e41fc63e7d1a7654af2#diff-88e5264e1fb79fe333c9ae8ddbc27e4d)

with a reference to documentation [explaining how it works here](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/outputvariable.md) - this appears to be preview documentation.

Did something get rolled out over the last few hours which broke my deployments?

**Comment by jkewley** [comment] 2017-08-08 04:10
It looks like version 2.1.10 was bumped to 2.2.0 while I was working.

**Comment by jkewley** [comment] 2017-08-08 04:12
sorry - 2.2.2

**Comment by ds-ms** [comment] 2017-08-08 05:13
@jkewley what's the agent version on your machine?

**Comment by jkewley** [comment] 2017-08-08 05:20
I'm using VSTS hosted build and release agents

**Comment by bryanmacfarlane** [comment] 2017-08-08 05:24
@jkewley - if you're using hosted build, at the top of your log it should output agent version.  Can you include?

**Comment by jkewley** [comment] 2017-08-08 05:41
Current agent version: '2.119.1'

**Comment by ds-ms** [comment] 2017-08-08 05:44
@jkewley Have you tried running the build again? 
I just tried to reproduce this error, but it seemed to be working fine for me. Could you also, give me some information about the type of template you were using for the deployment?

**Comment by jkewley** [comment] 2017-08-08 05:53
I kicked it off again and it failed the same way. It's a fairly vanilla implementation - Azure Resource Group Deployment template from the library with basic hooks into a build pipeline. The  only non-typical settings I can think of are using a variable for the resource group name, configuring with WinRM agent, the use of a WinRM output variable, and my ARM template having output variables,

All this had been working all day with 2.1.10. Then the task was bumped to 2.2.2 and this error message appeared. My work around is to continue on error and fetch the output variables using PS in the following step, but now my builds show partial success

**Comment by jkewley** [comment] 2017-08-08 06:04
FWIW, the RG deployment succeeds but the tasks fails because the attempt to create output variables fails after the RG deployment completes

**Comment by ds-ms** [comment] 2017-08-08 06:26
You're using 'Hosted' pool right? Could you try running it on 'Hosted VS2017' pool and see if it's producing the same error? 
The reason I ask is, when I tried reproducing this error, the agent version was greater than 2.119.1; The error says that the value is null, but from the command it doesn't look that way.

**Comment by RobertoPrevato** [comment] 2017-08-08 08:28
Hi, I am experiencing the same problem, with same Agent version (2.119.1).

@ds-ms I am using 'Hosted VS2017' pool

**Comment by RobertoPrevato** [comment] 2017-08-08 09:00
I am experiencing the same problem. Previously I wrote I was using Hosted VS2017, but I did a mistake: I was using "Hosted" agent for release.

However, I just updated to "Hosted VS2017" and I am getting the same error.

**Comment by jkewley** [comment] 2017-08-08 14:13
I tried this as well - hosted 2017 with a 2017 VS version in the solution build step. The agent still shows as 2.119.1. Same errors

**Comment by graych** [comment] 2017-08-08 16:53
Same issue here.  I opened an issue with our details, but closed it when I saw this one.  https://github.com/Microsoft/vsts-tasks/issues/4992

**Comment by TingluoHuang** [comment] 2017-08-09 13:06
@jkewley @graych are you guys hitting this during a Release or Build?

**Comment by jkewley** [comment] 2017-08-09 13:08
Mine is the first step of a release

**Comment by TingluoHuang** [comment] 2017-08-09 13:16
@jkewley have you try a build? i guess you can't repro the error in a build definition.

**Comment by jkewley** [comment] 2017-08-09 13:19
My whole release pipeline is built on the availability of those output variables. Can you repo the issue in release?

**Comment by TingluoHuang** [comment] 2017-08-09 13:29
I think so, since Release haven't enable output variable feature, so step doesn't have reference name. that is what the error complains about.

**Comment by jkewley** [comment] 2017-08-09 13:33
Sounds like something that should probably be a major version number update. Is the path forward to add output variable support in the release pipeline or roll back the task?

**Comment by TingluoHuang** [comment] 2017-08-09 13:35
task should major version when they consume output variable as I suggested in doc: https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/consumeoutputvariable.md#bump-task-major-version

**Comment by graych** [comment] 2017-08-09 13:36
I'm hitting it in a release, we only execute arm template deployments in releases

**Comment by jkewley** [comment] 2017-08-09 13:40
So @TingluoHuang - you authored the task updates, but who should be engaged from the VSTS team to get it rolled it back and properly versioned? It looks like your docs are in preview and still have a number of outstanding questions. Is this even ready for the build pipeline?

**Comment by ds-ms** [comment] 2017-08-09 13:53
I rollback this update. It should get fixed by tomorrow morning. 
We tested this feature with the feature flags enabled to execute this feature; so we didn't run into this issue before checking it in.

**Comment by strtdusty** [comment] 2017-08-09 14:03
This has broken all of our releases.  Any chance it could get fixed before tomorrow morning?

**Comment by jkewley** [comment] 2017-08-09 14:05
@strtdusty you can opt to 'continue on error' for the failing step until they get it fixed

**Comment by strtdusty** [comment] 2017-08-09 14:10
@jkewley  Are the output variables actually written to?

**Comment by jkewley** [comment] 2017-08-09 14:13
No, but they weren't being captured before this new feature was added, so it will be as it was. This will be a very useful feature once they have the supporting bits in place.

**Comment by ds-ms** [comment] 2017-08-10 08:38
The change has been reverted. This shouldn't be blocking your releases now.

The problem was with the editor you guys were using. Since you guys were using the old release definition editor, certain parameters weren't passed to the agent which are required for updating this output variable upon execution. 

The old editor is not deprecated yet, so we'll enable this feature once we fix it in the old editor and enable this feature for everyone! 
I apologize for the inconvenience caused! Closing this issue.

**Closed by ds-ms** 2017-08-10 08:38 UTC
Labels: Area: Release

**Comment by jkewley** [comment] 2017-08-10 13:07
Just for completeness - I used the new editor for everything but pre-deployment configuration. The new editor doesn't allow you to specify that pre-deployment notifications should be sent via email, so I had to use the old editor for that.

**Comment by ds-ms** [comment] 2017-08-10 13:11
Aah! As soon as you save your definition from the old editor, the required value is set to null; because it's irrelevant to it.

**Comment by jkewley** [comment] 2017-08-10 13:12
For completeness, then - If the last save was in the new editor, would this have worked?

**Comment by ds-ms** [comment] 2017-08-10 13:15
I guess so; It also depends on the Release Management service which was being served to your account. If it was the latest build of RM service, it definitely would have.

When I tested earlier this morning, it worked just fine with the new editor.

**Comment by iratherscribble** [comment] 2017-08-10 14:12
Keep in mind that some people are using Task Groups and the tasks are being edited in the editor presented in that UI (the old editor).

**Comment by degant** [comment] 2017-08-13 14:44
@ds-ms We're facing the same issue in our deployment task (Version: 2.2.3). This looks like the same issue or a similar one? I tried saving from new as well as old editor and trying but getting the same results. Is there a workaround available?

    2017-08-13T14:33:42.2096101Z ##[error]Unable to process command '##vso[task.setvariable isOutput=true;variable=DeploymentOutputs;]{}' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
    2017-08-13T14:33:42.2096101Z ##[error]Value cannot be null.
    Parameter name: RefName
    2017-08-13T14:33:42.2720935Z ##[debug]System.ArgumentNullException: Value cannot be null.
    Parameter name: RefName
       at Microsoft.VisualStudio.Services.Agent.Worker.ExecutionContext.SetVariable(String name, String value, Boolean isSecret, Boolean isOutput)
       at Microsoft.VisualStudio.Services.Agent.Worker.TaskCommandExtension.ProcessTaskSetVariableCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)
       at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)
    2017-08-13T14:33:42.2720935Z ##[debug]Processed: ##vso[task.setvariable isOutput=true;variable=DeploymentOutputs;]{}
    2017-08-13T14:33:42.2720935Z Updated output variable 'DeploymentOutputs', which contains the outputs section of the current deployment object in string format. Follow this link: https://go.microsoft.com/fwlink/?linkid=853539 to learn how to use it in your defintion
    2017-08-13T14:33:42.2720935Z Successfully deployed the template.

Task Details:

    2017-08-13T14:32:23.5001033Z Task         : Azure Resource Group Deployment
    2017-08-13T14:32:23.5001033Z Description  : Deploy, start, stop, delete Azure Resource Groups
    2017-08-13T14:32:23.5001033Z Version      : 2.2.3

**Comment by ds-ms** [comment] 2017-08-16 05:15
@degant we have hotfixed this; could you run your deployment again and see if this problem persists.

**Comment by degant** [comment] 2017-08-16 09:21
@ds-ms working fine today! Thanks!
