### ISSUE TITLE
Exception when running TFS 2015 custom build task

### ISSUE THREAD

**Issue by yigaldviri** [Microsoft/vsts-tasks#2236] opened 2016-08-07 12:54 UTC
I have developed a plugin (extension) for TFS 2015.
The plugin is actually a custom build task that can be added as a step in the build process.

The problem is that when I developed my plugin I used TFS 2015 update 2.1 but my users work with update 2.0 and they see this strange error shortly after the plugin starts running during the process of asking for the user inputs.

When this line is executed:

`var credentials = tl.getEndpointAuthorization(endpoint, false)["parameters"];`  

This error occurs:

> System.FormatException: Input string was not in a correct format.

I was able to reproduce this error and it exists only in update 2.0 and gone after I updated to 2.1 /3 . I have searched and found in the 2.1/3 [update change log](https://www.visualstudio.com/en-us/news/releasenotes/tfs2015-update3-vs) that this bug was fixed:

> Extensions with cross platform build tasks do not work

Is there any workaround for this issue? My customer can't just upgrade his platform to the latest build and I need to find a way to help him.
Can you shed some light on this issue? Something that might help?

**Comment by bryanmacfarlane** [comment] 2016-08-09 08:51
What version of the task-lib do you package with your task?

https://github.com/Microsoft/vsts-task-lib

**Comment by bryanmacfarlane** [comment] 2016-08-09 08:52
You should probably also move this issue to the repo ...

**Comment by yigaldviri** [comment] 2016-08-09 09:07
vsts-task-lib@0.5.10.
It works on agent downloaded from update 2.1 or update 3. But not on agent downloaded from update 2.0

**Comment by bryanmacfarlane** [comment] 2016-08-09 09:23
QU2.1 was a re-release of QU2.  The one critical fix in the .1 re-release was we distribute node4.x instead of node0.12.7.  That's what that release note section is referring to.

I'm aware of tasks that are written and compiled to ES6 won't work (ones that defined strict or used generators like our newer async/await).  Those need node 4+.  I'm not sure why the line you mention would make a difference between node0.12 and 4.

You can try a few things:
- ensure you actually package the lib (in node_modules).  We do an npm install as part of our build process.  You don't want to subject to whichever happens to be up the tree.  Lock to one as part of your build process.
- Try replacing node that's part of the agent download with node 4 LTS binary.
- An agent downloaded from a 2.1 server should work against a QU2 server.

Finally, if you want to email me ( my alias is bryanmac ) the task, I can have a look at it.

**Comment by yigaldviri** [comment] 2016-08-09 10:06
Hi,
First, thanks for responding.
Second,

1. My code is being compiled to ES5, so it should be able to run on node 0.12
2. The vsts-task-lib comes packed within the plugin node_modules, so no issue here.
3. Haven't tried yet to replace the node within TFS agent, but I will try that.
4. I did try to use 2.1 agent against 2.0 server and it worked but shouldn't I be worried about other compatibility issues that might happen? 
5. I will try to get the approval to share my code in a public repository (:smiley: corporate life)

**Comment by yigaldviri** [comment] 2016-08-09 15:56
Hi, I have uploaded my code. 
You can find it in [TFS2015-CA-RA-Plugin]( https://github.com/yigaldviri/TFS2015-CA-RA-Plugin)
Thanks!

**Comment by bryanmacfarlane** [comment] 2016-08-09 18:52
OK.  The issue is not the one mentioned about node (I don't believe).  The error is coming out of the .net agent (System.Format Exception).  Can you send us the _diag logs from the agent when it repros for you?  You may want to email that to me.  Secrets etc... are masked but just to be on the safe side, let's not post on the internet.

**Comment by yigaldviri** [comment] 2016-08-10 09:54
I sent you the log.

**Comment by bryanmacfarlane** [comment] 2016-08-23 02:51
@yigaldviri - can you send the mail again to get on top of my mail box?  Closing again since not an issue with one of the tasks in this repo

**Closed by bryanmacfarlane** 2016-08-23 02:51 UTC
Labels: Area: Core

**Comment by yigaldviri** [comment] 2016-08-23 06:28
Sent. Thanks for all the help.
