### ISSUE TITLE
Running the "DeployVisualStudioTestAgent" task reboots the machine; Is it by design?

### ISSUE THREAD

**Issue by BaskiGIT** [Microsoft/vsts-tasks#3788] opened 2017-03-14 20:47 UTC
We have TFS 2017.

As part of TFS build we are deploying Test Agent with this task "Deploy Visual Studio Test Agent".

When it is used for the first time in a machine, it works fine, running Test AGent as User2, while another user is logged in to the machine as User1.

On a consecutive build to the same machine when User1 is logged to the machine, the machine gets rebooted, as the build runs the task "Deploy Visual Studio Test Agent".

Upon checking the logs, I see that there is a reboot after this log

**You have chosen to run the test agent process as Domain\User2. Restart the machine for this change to take effect.**

IN the second run why is it trying to delete the service and reinstall it?

**Comment by acesiddhu** [comment] 2017-03-20 12:17
If the task is configured to run as interactive process for UI Tests it tries its best effort to make sure the test user has a active UI session . If this is Windows Client OS it tries to get user2 (test agent is configured as this user) an active session by rebooting the machine and adding a EnableAutoLogon settings.

**Comment by BaskiGIT** [comment] 2017-03-21 10:54
Hi I have below queries:

1. With Win 7 SP1 machine the user with which the Tests are run, is already logged on in the PC. But the reboot is still happening.

2. After running for the first time, the service is left installed. But the service is stopped. During the next run why does the task try to reinstall the agent?

**Comment by tanvi-soni** [comment] 2017-03-30 09:10
Can you please set build variable system.debug = true and share those build logs with us at devops_tools@microsoft.com 
In your case, the reboot might be happening if test agent did not find an active user session while trying to run UI test.

**Comment by tanvi-soni** [comment] 2017-04-06 11:37
Any update?

**Comment by BaskiGIT** [comment] 2017-04-06 11:54
Dear Tanvi,

Thank you for the follow up and apologies for the delay in getting back.

With Interactive:

1. I am running the build agent as User1 and running the tests also as User1.
2. There is an active session for User1 already in the machine.
3. User2 is also logged in.

Now when the Test Agent is configured there is not a reboot.

However I am yet to try the below option:

1. Run the agent as User1.
2. Run the tests as User2.
3. Have an active session for User1.
4. I hope there won't be a need to have an active session for User2 as well.
5. Login as User3 and try the build to see if there is a reboot done.

**Comment by tanvi-soni** [comment] 2017-04-07 09:32
@BaskiGIT If you already have active session for user 1, then reboot would not happen, as you have mentioned above.
Rebooting of test agent machine is by design and it happens only if there is no active session for the user with which you want to run tests. 
You can simply disconnect the machine or log out, and let the build run. It will reboot the machine, if required to establish active session for mentioned user, and run the test. If you log into the machine with the same user during run functional test task, you can see the tests running.

**Comment by RanjanarMS** [comment] 2017-04-11 06:34
Hope you got unblocked. Closing this thread for now. If you feel the issue is not addressed please re-open.

**Closed by RanjanarMS** 2017-04-11 06:34 UTC
Labels: Area: Test
