### ISSUE TITLE
Azure PowerShell script fails to find principal

### ISSUE THREAD

**Issue by ChrisWalford** [Microsoft/vsts-tasks#1683] opened 2016-05-10 10:38 UTC
We are using the a PowerShell script to apply a role to an Azure resource group.

Since 5th May this has stopped working.

This is the log previous to the error:

2016-05-03T14:35:14.5295457Z Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.98.1\tasks\AzurePowerShell\1.0.17\AzurePowerShell-Legacy.ps1
 
2016-05-03T14:35:14.6405465Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
 
2016-05-03T14:35:17.5375458Z AzurePSCmdletsVersion= 1.3.0
 
2016-05-03T14:35:17.5525470Z Get-ServiceEndpoint -Name cd21ede8-adc5-4b39-b322-0be09b5d35d9 -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext
 
2016-05-03T14:35:17.5595456Z Username= ********
 
2016-05-03T14:35:17.5605467Z azureSubscriptionId= 60849bdd-2a58-4036-a060-bf2528528aa5
 
2016-05-03T14:35:17.5615472Z azureSubscriptionName= Dell One Service (32)
 
2016-05-03T14:35:17.5665467Z Add-AzureAccount -Credential $psCredential
 
2016-05-03T14:35:19.7915043Z Add-AzureRMAccount -Credential $psCredential
 
2016-05-03T14:35:20.3748569Z Select-AzureSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5
 
2016-05-03T14:35:20.3858695Z Select-AzureRMSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5
 
2016-05-03T14:35:22.0839033Z ScriptArguments= -ResourceGroupName Supervisor-Test -RoleType Reader -ObjectId 8e5f6ff2-a9f8-47d6-861d-2afe76fc6228
 
2016-05-03T14:35:22.0848993Z ScriptPath= C:\a\d8080d483\Supervisor\Deploy\AssignRoleToResourceGroup.ps1
 
2016-05-03T14:35:22.0859625Z scriptCommand= & "C:\a\d8080d483\Supervisor\Deploy\AssignRoleToResourceGroup.ps1" -ResourceGroupName Supervisor-Test -RoleType Reader -ObjectId 8e5f6ff2-a9f8-47d6-861d-2afe76fc6228
 
2016-05-03T14:35:48.1425947Z ##[debug]Using Azure RM cmdlets...
 
2016-05-03T14:35:53.0705816Z ##[debug]Role already assigned.
 
Now we see the following:

2016-05-05T13:59:15.8786603Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1 -Global
 
2016-05-05T13:59:17.0786610Z ##[command]Add-AzureAccount -Credential System.Management.Automation.PSCredential
 
2016-05-05T13:59:18.9187162Z ##[command]Select-AzureSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5 
 
2016-05-05T13:59:20.4247160Z ##[debug]Using Azure RM cmdlets...
 
2016-05-05T13:59:21.0837148Z ##[error]Run Login-AzureRmAccount to login.

The above is using a "Classic" connection type, if we switch to using "Resource Manager" we see the following:

2016-05-05T13:59:22.7049025Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
 
2016-05-05T13:59:27.7746526Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
 
2016-05-05T13:59:28.8486218Z ##[command]Select-AzureRMSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5 -TenantId ********
 
2016-05-05T13:59:30.3379843Z ##[debug]Using Azure RM cmdlets...
 
2016-05-05T13:59:31.6278214Z ##[error]Cannot find principal using the specified options
 
2016-05-05T13:59:31.6358209Z ##[debug]Assigning Contributor role to Supervisor-Test...
 
2016-05-05T13:59:31.8785447Z ##[error]AuthorizationFailed: The client 'f1b0e8aa-02ba-4e86-8411-94a88faf08f6' with object id 'f1b0e8aa-02ba-4e86-8411-94a88faf08f6' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/60849bdd-2a58-4036-a060-bf2528528aa5/resourceGroups/Supervisor-Test/providers/Microsoft.Authorization/roleAssignments/53b0dbe1-87b8-4a8d-819a-c00f7e18d3ea'.

**Comment by ericsciple** [comment] 2016-05-10 15:26
Using the classic connection type, does adding "Select-AzureRMSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5" to your script workaround the issue?

**Comment by ChrisWalford** [comment] 2016-05-10 16:05
Adding that made no difference:

Classic:

2016-05-10T15:57:45.9684064Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1 -Global
 
2016-05-10T15:57:47.2814044Z ##[command]Add-AzureAccount -Credential System.Management.Automation.PSCredential
 
2016-05-10T15:57:49.4167303Z ##[command]Select-AzureSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5 
 
2016-05-10T15:57:51.1007310Z ##[debug]Using Azure RM cmdlets...
 
2016-05-10T15:57:51.4647306Z ##[error]Run Login-AzureRmAccount to login.


Resource Manager:

2016-05-10T15:57:53.2617311Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
 
2016-05-10T15:57:58.5887314Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
 
2016-05-10T15:57:59.7249598Z ##[command]Select-AzureRMSubscription -SubscriptionId 60849bdd-2a58-4036-a060-bf2528528aa5 -TenantId ********
 
2016-05-10T15:58:01.3725165Z ##[debug]Using Azure RM cmdlets...
 
2016-05-10T15:58:01.4935100Z Environment           : AzureCloud
 
2016-05-10T15:58:01.4945093Z Account               : ********
 
2016-05-10T15:58:01.4955101Z TenantId              : ********
 
2016-05-10T15:58:01.4955101Z SubscriptionId        : 60849bdd-2a58-4036-a060-bf2528528aa5
 
2016-05-10T15:58:01.4965098Z CurrentStorageAccount : 
 
2016-05-10T15:58:02.8855548Z ##[error]Cannot find principal using the specified options
 
2016-05-10T15:58:02.9015516Z ##[debug]Assigning Contributor role to AccountSupervisor-Test...
 
2016-05-10T15:58:03.2149661Z ##[error]AuthorizationFailed: The client 'f1b0e8aa-02ba-4e86-8411-94a88faf08f6' with object id 'f1b0e8aa-02ba-4e86-8411-94a88faf08f6' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/60849bdd-2a58-4036-a060-bf2528528aa5/resourceGroups/AccountSupervisor-Test/providers/Microsoft.Authorization/roleAssignments/4aa32459-b301-4c7f-a887-c20893e3c49f'.

**Comment by ChrisWalford** [comment] 2016-05-10 16:06
Inadvertently closed

**Comment by ericsciple** [comment] 2016-05-10 17:27
Can you try setting a variable `preferazpsoverps3` to `true`? That reverts to previous sprint's task handler. Another thing you can is the latest version of the AzureRM modules (`install-module azurerm` then run `Install-AzureRM`).

**Comment by ericsciple** [comment] 2016-05-10 17:30
If that unblocks you, I'd still like to understand the issue. It looks like AzureRM is complaining about a permissions issue for the service principal. How does it work when you run the script from a powershell prompt? The task script prints each commands that it runs, so I'm wondering what's missing to make it work for you.

**Comment by ericsciple** [comment] 2016-05-10 18:32
Sorry the back-compat variable is `system.preferazpsoverps3` not `preferazpsoverps3`.

**Comment by ChrisWalford** [comment] 2016-05-11 08:43
This appears to have resolved the issue at least when in "Azure Classic" mode.

**Comment by efridman** [comment] 2016-05-11 21:51
The error _"Cannot find principal using the specified options"_ is from a call to **Get-AzureRmRoleAssignment**. If we remove all parameters from the cmdlet, then the error changes to

_{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API version."}}}_

Adding the **system.preferazpsoverps3** variable does resolve the issue.

**Comment by ericsciple** [comment] 2016-05-12 02:50
@ChrisWalford when using `system.preferazpsoverps3` + Azure RM service principal connection, do you get the same error as when you used Azure RM service principal connection without the back compat variable? It looks like that error is related to a permissions issue with the way the service principal is configured.

@efridman same question. Can you clarify, are you saying setting `system.preferazpsoverps3` alone resolved the issue (and still using an Azure RM service principal connection)?

**Comment by ericsciple** [comment] 2016-05-12 05:24
@ChrisWalford @efridman  I have a PR that I think will fix your issue https://github.com/Microsoft/vsts-tasks/pull/1706

Let me know if you'd be willing to try out the fix before it rolls out every in production. The back-compat variable will still work, so even if it doesn't fix it then you're in the same place :)

**Comment by ChrisWalford** [comment] 2016-05-12 08:54
The error is still the same when using Azure RM with the back compatibility variable.

2016-05-11T08:09:44.8687853Z ##[error]Cannot find principal using the specified options
2016-05-11T08:09:44.8717832Z ##[debug]Assigning Contributor role to AccountSupervisor-Test...
2016-05-11T08:09:45.9893747Z ##[error]AuthorizationFailed: The client 'f1b0e8aa-02ba-4e86-8411-94a88faf08f6' with object id 'f1b0e8aa-02ba-4e86-8411-94a88faf08f6' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/60849bdd-2a58-4036-a060-bf2528528aa5/resourceGroups/AccountSupervisor-Test/providers/Microsoft.Authorization/roleAssignments/1f6da80e-236d-4407-8c38-ac2fc8d1c56f'.

**Comment by ericsciple** [comment] 2016-05-12 15:08
@ChrisWalford OK, it sounds like a permissions issue with the service principal. You might try following the steps from [this page](https://blogs.msdn.microsoft.com/visualstudioalm/2015/10/04/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-buildrelease-management/) to setup the service principal. The page is also linked from the Azure RM service endpoint configuration window in VSTS - in case you need it again later.

**Comment by efridman** [comment] 2016-05-15 15:10
@ericsciple For the Azure Classic issue - yes, we can try out the PR. How would we go about doing that?

WRT the Azure RM issue - I have reproduced this locally, setting up a service principal from scratch. Based on [#1896](https://github.com/Azure/azure-powershell/issues/1896), it appears that security principles can't be used with a number of Azure cmdlets including Get-AzureRmRoleAssignment. Could you confirm that, please. In that case we need to wait until that issue is resolved before we can switch away from Azure Classic.

**Comment by ericsciple** [comment] 2016-05-15 17:41
@efridman There's a few options:
1) You can build from releases/m100 and use the TFX CLI to upload the task from _build/Tasks/AzurePowerShell
2) I can build and send you the zip, you can upload using the TFX CLI
3) I can build and send you a self-contained ps1 script that will do the upload

In all cases, you will need to be pool administrator in order to upload the task. If you want to go with options 2 or 3, email ersciple and I'll send you whatever you need (microsoft com).

**Comment by ericsciple** [comment] 2016-05-15 17:45
@efridman wrt your question, I can try it out later this weekend and let you know if I can repro the issue with Get-AzureRMRoleAssignment.

**Comment by efridman** [comment] 2016-05-16 09:36
@ericsciple Can you please send me the zip.

**Comment by ericsciple** [comment] 2016-05-16 16:13
[AzurePowerShell.zip](https://github.com/Microsoft/vsts-tasks/files/266471/AzurePowerShell.zip)

**Comment by efridman** [comment] 2016-05-17 07:19
@ericsciple I've uploaded this to our VSTS instance and that solves the issue for Azure Classic. Thanks for your help.

**Comment by ericsciple** [comment] 2016-05-17 07:53
Great! Thanks helping me confirm the fix! Sorry repro'ing the Get-AzureRMRoleAssignment issue fell off my radar. It's on my paper to-do list now, just haven't gotten to it yet.

**Comment by ericsciple** [comment] 2016-05-18 01:07
@efridman fyi - I tried adding my service principal identity to the subscription owner role and I get `
{"odata.error":{"code":"Authentication_Unauthorized","message":{"lang":"en","value":"Access denied to the specified API version."}}}` when attempting to call `Get-AzureRMRoleAssignment`. I'm using AzureProfile 1.4.0 (installed from the gallery `Find-Module`/`Install-Module`).

**Comment by ericsciple** [comment] 2016-06-03 19:00
Closing now that the deployment has rolled out.

**Closed by ericsciple** 2016-06-03 19:00 UTC
Labels: deployment
