### ISSUE TITLE
JenkinsQueueJob task fails with the following Error

### ISSUE THREAD

**Issue by kumarappanc** [Microsoft/vsts-tasks#3589] opened 2017-02-10 22:41 UTC
2017-02-10T11:47:59.2528919Z ##[warning]File name doesn't indicate a full path to a executable file.
 
2017-02-10T11:47:59.2528919Z Set workingFolder to default: c:\B\SourceRootMapping\9c0304b3-b058-4e7d-84ef-4f205f292902\Job-f98d6625-a150-4098-983c-27b363bf0508
 
2017-02-10T11:47:59.3154170Z ##[error]System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
 
2017-02-10T11:47:59.3154170Z ##[error]   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
 
2017-02-10T11:47:59.3154170Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ProcessWrapper.Start()
 
2017-02-10T11:47:59.3154170Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Agent.Common.ProcessInvoker.Run(CancellationToken token)
 
2017-02-10T11:47:59.3154170Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.NodeHandler.Execute(ITaskContext context, CancellationToken cancellationToken)
 
2017-02-10T11:47:59.3154170Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.RunTask(ITaskContext context, TaskWrapper task, CancellationTokenSource tokenSource)

Could anyone please help me with this issue?

**Comment by DavidStaheli** [comment] 2017-02-11 14:18
Thanks for reporting this, @kumarappanc.  Can you please attach the full log here or email it to dastahel at microsoft.com?

**Comment by DavidStaheli** [comment] 2017-03-29 12:32
Hi @kumarappanc, thanks very much for reporting this.  Unfortunately, we've been unable to reproduce it.  I'll close this issue for now, but **please** reactivate if you have a log or it still is an issue for you.

**Closed by DavidStaheli** 2017-03-29 12:32 UTC
Labels: Area: CrossPlatform
