### ISSUE TITLE
AzureRmWebAppDeployment fails to stop WebApp and fails with ERROR_FILE_IN_USE

### ISSUE THREAD

**Issue by treierts** [Microsoft/vsts-tasks#3293] opened 2016-12-22 09:24 UTC
Our Release script uses the "Deploy AzureRM Web App" task and we have set "Take App Offline" to true.

Our WebApp no longer deploys, we get the following errors in the log:

```
2016-12-22T09:15:40.4470806Z ##[error]Failed to deploy website.
 
2016-12-22T09:15:40.4470806Z ##[error]Error Code: ERROR_FILE_IN_USE
 
2016-12-22T09:15:40.4470806Z More Information: Web Deploy cannot modify the file 'OurWebApp.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
 
2016-12-22T09:15:40.4470806Z Error count: 1.
```

This used to work a while back, I am not quite sure when this error started happening.
If we manually stop the app, the deploy works.

**Comment by iamthemovie** [comment] 2016-12-22 14:51
I have the same issue. Happening with all our ASP.NET Web Apps at the moment.

**Comment by iamthemovie** [comment] 2016-12-22 15:10
Looks like the app_offline.html has no affect on the state of the web app!?

**Comment by zeekebud** [comment] 2016-12-22 16:38
I'm also having this issue. Has it stopped it in the past and/or should it? I would think so.

**Comment by iamthemovie** [comment] 2016-12-22 16:43
Right, so, turns out that the app_offline.htm for ASP.NET Core based apps might not work the same way as old school IIS Handler. This is in the case of using ASP.NET Core, as it deploys an executable.

If your apps are set the Always On, try turning that particular setting off and deploying then turning it off. I've just talked to someone at MSFT and they've said that Always On can intermittently cause issues and lock DLLs.

My issue is the "Take App Offline" tick box no longer has any bearing on the process:

![image](https://cloud.githubusercontent.com/assets/369020/21432924/a35bbe90-c865-11e6-96ca-a3bcec6f6de2.png)

It says it uses app_offline.htm but I don't think it's working correctly behind the scenes.

**Comment by zeekebud** [comment] 2016-12-22 16:48
Thanks. My app is also ASP.NET Core. So I'd have to do what Frank recommends here? Seems like the task should be able to do this.

https://blogs.msdn.microsoft.com/azuredev/2016/05/22/visual-studio-team-services-azure-web-app-deployment-failure-error_file_in_use/comment-page-1/

**Comment by iamthemovie** [comment] 2016-12-24 12:55
I used Azure PowerShell (as that article mentioned) and stopped the slots manually. Still a bit strange that this has randomly popped up as an issue, we've had these pipelines running for months now with no issue.

**Comment by mclark1129** [comment] 2016-12-29 22:04
I am also seeing an increase in this issue recently.  I've even disabled Always On where it was being used and the issue still persists.  This makes our automated deployment process very difficult.

**Comment by iamthemovie** [comment] 2016-12-29 22:22
If you're looking to ensure this doesn't happen in your release pipelines
you will need to stop the instance (we stop a slot and then swap for zero
down time) with  azure power shell.

We have created some scripts and task groups for reuse purposes, it makes
it easier if you have lots of Web Apps in one project.

It might be worth someone creating a task and putting on the market place?

**Comment by mclark1129** [comment] 2016-12-30 16:39
@iamthemovie I realize that there is a workaround we can use, but it does seem like this is the responsibility of this task.  Also like you mentioned this has not been a problem for months, and has only started happening recently, which seems like something new might have been introduced which caused a regression.

**Comment by mclark1129** [comment] 2016-12-30 16:41
Occasionally I will also see **Error Code: ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER** which I believe means the same thing.

**Comment by vincentdass** [comment] 2017-01-01 14:23
@treierts, @mclark1129 , @iamthemovie , Currently we are investigating this issue. Can u enable `'rename locked file`' option under Additional deployment option ? 
![image](https://cloud.githubusercontent.com/assets/20121508/21581551/bd6293d8-d05b-11e6-8b76-2560e04119a5.png)

This renames the locked file. 
You can also restart the app to unlock the files as a workaround.

**Comment by vincentdass** [comment] 2017-01-03 17:39
FILE_IN_USE error occurs when DLL's are locked. App_offline brings the app down and unlocks the resource. ASPCore Module requires `app_offline.htm` but MSDeploy provides `App_Offline.htm` (case sensitive).

The fix for app_offline issue will be available [soon](https://github.com/aspnet/Home/issues/694#issuecomment-269997757).

**Comment by mvvsubbu** [comment] 2017-01-25 12:21
Closing it as there is another issue tracking the same https://github.com/Microsoft/vsts-tasks/issues/3312

**Closed by mvvsubbu** 2017-01-25 12:21 UTC
Labels: Area: Release
