### ISSUE TITLE
WebApp with WebJob deployment failing to delete jobs directory on alternate builds

### ISSUE THREAD

**Issue by TheFairey** [Microsoft/vsts-tasks#4716] opened 2017-07-04 09:34 UTC
Hi

This issue started a few months ago (possibly even tail end of last year) and I've seen others with similar issues but no posting as to why this suddenly started happening. The specific error is:

`Error: An error was encountered when processing operation 'Delete Directory' on 'D:\home\site\wwwroot\app_data\jobs'.`

I've read numerous threads and the most recent suggested stopping the webjob first so in my VSTS build I now do just that with:

```
Stop-AzureWebsiteJob -Name myname -JobName myjob
Write-Host "Stopping myjob"
Start-Sleep -s 30
```

This does what it's meant to and stops the webjob but I still get the above error every other build, if I hit queue new build the second time it works without fail.

I have Remove Additional Files at Destination enabled for the WebApp which is deployed first then don't have it enabled for the WebJob.

Any help appreciated.

Cheers

Si

**Comment by vincentdass** [comment] 2017-07-04 14:06
@TheFairey, Is Application Insight Extension  (or Webjob) present in your Azure App Service ?
If so, Can you please stop the Webjob and requeue the release ?
You can use the script provided [here](https://github.com/Microsoft/vsts-tasks/issues/4496#issuecomment-309294640) to achieve the same. 

Please feel free to ping, if you face any issue.

**Comment by TheFairey** [comment] 2017-07-05 09:28
@vincentdass I used that link you provided originally but the stop script didn't work and kept asking to run AzureLogin so I replaced it with the stop script I included in my original post. This does stop the webjob but I still get the issue even adding a 30s instead of 15s delay. The application Insights Extension is included in my App Service. I will tried adding in this step:
Stop Azure App Service - Azure App Service Manage Task
which is the one I don't have from that link and the corresponding start but I'm still getting the same error when it tries to delete the jobs directory

**Comment by vincentdass** [comment] 2017-07-05 10:10
@TheFairey , Did u use `Azure PowerShell Task` to run the scripts ?
Application Insights will be running as a Webjob, which need to be stopped before deployment.

Can you please try the scripts with Azure Powershell task to check once ?

**Comment by TheFairey** [comment] 2017-07-05 11:02
@vincentdass 
Ok so tried with Classic connection type and got the login request then tried with Azure Resource Manger connection type and that worked once I updated the scripts to use the versions that don't look for a slot so thanks for your help.

**Comment by vincentdass** [comment] 2017-07-05 11:22
@TheFairey , is the issue resolved with the provided script ?

**Comment by TheFairey** [comment] 2017-07-05 13:20
@vincentdass with a slight change because I have no slots but yes the issue is resolved.

**Comment by akuryan** [comment] 2017-12-26 09:00
@TheFairey We are experiencing the same issue - doing ARM MsDeploy via VSTS to stopped staging slot we encounter an error, when ```App_data\jobs```, despite being empty, could not be deleted.
As you can see in [related issue](https://github.com/Microsoft/vsts-tasks/issues/4496#issuecomment-353940351) - we also tried to use script to add app setting - still, not avail. Can you please, help?

**Comment by TheFairey** [comment] 2017-12-29 23:00
@akuryan Not sure how I can help, the issue for us was the hidden app insights webjob mentioned in the related threads so when I use the PowerShell script to stop all webjobs prior to performing the release everything deploys without an issue. Sorry!

**Comment by vincentdass** [comment] 2018-01-01 05:29
@akuryan , Can you share the steps how you confirmed` App_Data/Jobs` folder is empty?

**Comment by akuryan** [comment] 2018-01-01 10:26
@vincentdass After build failed I used FTP to login to staging slot and check App_data/jobs content

**Comment by vincentdass** [comment] 2018-01-02 04:58
@akuryan , Can you open the KUDU SCM portal and check if the folder is empty?
SCM URL: `https://APP_NAME_HERE.SCM.AZUREWEBSITES.NET` 
![image](https://user-images.githubusercontent.com/20121508/34474599-09cc7138-efa7-11e7-83b5-502e73945f5a.png)

Then naivgate to the Jobs folder and check the content. I assume there might be a resource that locks the app_data folder, which might prevent from opening/accessing the path.
![image](https://user-images.githubusercontent.com/20121508/34474622-67f8c810-efa7-11e7-9251-3a512b5792ac.png)

**Comment by akuryan** [comment] 2018-01-02 07:50
Yes, @vincentdass, it was empty

**Comment by vincentdass** [comment] 2018-01-03 08:39
@akuryan , From SCM portal, Can you download the logFiles folder and share the same with `RM_CUSTOMER_QUERIES@MICROSOFT.COM`?

To download the logFiles folder, click the download button next to the folder name.
![image](https://user-images.githubusercontent.com/20121508/34513721-aa3a6b32-f08f-11e7-9fd9-4cc307fd6b8d.png)

**Comment by akuryan** [comment] 2018-01-04 08:22
If I will be able to replicate this issue again - I will do it. At this point of time I resorted to remove and recreate staging before deployment

**Comment by vincentdass** [comment] 2018-01-08 04:50
Closing the thread as waiting for the response.
Fell free to re-open the issue or create a new thread if required.

**Comment by TheFairey** [comment] 2018-02-20 21:15
This issue has started happening again, after a failed deployment the next deployment works. 

I put a powershell delay in after the powershell that stops the jobs and the stop web app step. During the delay I can see there is only one w3wp process running, the scm site however if I look in the open_file_handles I can see the scm site has open filehandle into the app_data...continuous directory.

After the failed deployment if I go and look again the file handle on the continuous directory it's gone. I had hoped the 5 min delay step might give whatever it is time to remove the open file handle but I guess not.

Open to suggestions as to why the SCM site has this open file handle and how I can clear it, is there a way to force a restart of the SCM site as part of the VSTS tasks?

I found this [link](https://github.com/projectkudu/kudu/wiki/Full-stopping-a-Web-App) but not sure how I might do it during a VSTS deployment?

**Comment by vincentdass** [comment] 2018-03-18 09:22
@TheFairey , As the issue is related to Azure App Service, Can you please open a issue [here](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowsazurewebsitespreview).


Also, stopping the SCM site is not recommended from VSTS, as VSTS primarily depends on SCM for deployment.

**Closed by vincentdass** 2018-03-18 09:22 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by TheFairey** [comment] 2018-03-20 23:51
FYI - With no change my end this magically started working again, by working I mean no more double releases required so I'm guessing someone somewhere fixed something in the deployment process.
