### ISSUE TITLE
Build Solution task fails after SonarQubePre task when using Fakes

### ISSUE THREAD

**Issue by zmckinnon** [Microsoft/vsts-tasks#2275] opened 2016-08-15 19:02 UTC
I am building my solution using the Visual Studio Build task.

The task right before it is the SonarQube for MSBuild - Begin Analysis.

I am using Microsoft Fakes with my project.

Sometimes (like every other time or so), I get the following error when building:

```
Error MSB3231: Unable to remove directory "F:\Agent-03\_work\1\.sonarqube\out\\f_AnyCPU_Release_4391". The process cannot access the file 'FilesToAnalyze.txt' because it is being used by another process.
```

Here are the logs: [logs_40521.zip](https://github.com/Microsoft/vsts-tasks/files/418742/logs_40521.zip)

**Comment by zmckinnon** [comment] 2016-08-15 19:03
Looks like someone else had a similar issue here: http://stackoverflow.com/questions/38105789/sonarqube-integration-targets-process-conflicts-when-building-a-project

**Comment by zmckinnon** [comment] 2016-08-15 19:45
Also, when I clean repository, it happens either WAY more often or EVERY time.  Not sure.

**Comment by bryanmacfarlane** [comment] 2016-08-15 23:30
Are you using your own private agent or hosted build?

**Comment by bgavrilMS** [comment] 2016-08-16 09:22
@zmckinnon 

Could you provide more information please: 

- are you running on a private or on a hosted agent (I assume it's private)
- can you confirm that the SonarQube C# plugin is up to date. There was a fix a while back to ignore .fakes projects from build (https://jira.sonarsource.com/browse/SONARMSBRU-26)

A few things to try: 

- disable the antivirus from the build agent
- force msbuild to use a single worker process, by passing in the param /m:1 to the build step (https://msdn.microsoft.com/en-us/library/bb651793.aspx)

**Comment by zmckinnon** [comment] 2016-08-16 14:12
Private agent.

**Comment by zmckinnon** [comment] 2016-08-16 14:16
@bgavrilMS 

- It is a private agent.

- I have version 5.3.2 of the SonarQube C# Pluglin installed.

And

- I DID NOT disable the antivirus.   IT is in charge of that.

- I DID pass msbuild the maxcpucount param . . . I got the same error.

**Comment by bgavrilMS** [comment] 2016-08-16 14:41
@zmckinnon Thank you for your quick reply!

Could you try to build and analyse locally from the command line and see if this repros. Instructions are at http://docs.sonarqube.org/display/SCAN/From+the+Command+Line

**Comment by zmckinnon** [comment] 2016-08-16 19:45
I was NOT able to reproduce the issue running it locally (using the latest version of SonarQube Runner [2.0]).  However, I also was not able to reproduce it using an earlier version (1.1). 1.1 is the version on the server.

I have identified that there does seem to be an AV process that is accessing that file at the same time, but I did want to point something out:

It should never actually be analyzing the f.csproj file that is creating the FilesToAnalyze.txt file.

I took a look at that bug fix that you referenced (https://jira.sonarsource.com/browse/SONARMSBRU-26) and I am not sure it excludes what it SHOULD exclude.

From my understanding, .fakes files do NOT necessarily need to be excluded.  The f.csproj files that are generated from the .fakes files DO.

According to the targets file, it is excluding the wrong files.  Here is the line I am talking about:

```
    <!-- Fakes detection -->
    <PropertyGroup>
      <IsFakesProject Condition="$(AssemblyName.EndsWith('.fakes', System.StringComparison.OrdinalIgnoreCase))">true</IsFakesProject>
    </PropertyGroup>
    <PropertyGroup Condition="$(IsFakesProject) == 'true'">
      <SonarQubeTestProject>true</SonarQubeTestProject>
      <SonarQubeExclude>true</SonarQubeExclude>
    </PropertyGroup>
```

I am pretty sure that needs to check for f.csproj and not necessarily .fakes.

I can log an issue with them.  Does that sound right?

If so, then I may need a workaround (at least until they update it).

**Comment by duncanpMS** [comment] 2016-08-17 09:56
@zmckinnon I think the integration targets are doing the right thing. The snippet you've included isn't looking at the .fakes file, it's looking at the _AssemblyName_ property in the project file that is being built. Here's what is happening at build time:
* the main project (the one containing the _fakes.xml_) is built, and the SonarQube integration targets are automatically imported.
* the main project executes the _BuildFakesAssemblies_ target, which generates the _f.proj_, and then calls MSBuild to build it.
* The _f.proj_ file is built, again pulling in the SonarQube integration targets. The _SonarQubeCategoriseProject_ target is executed which looks at the _AssemblyName_ property of the project. In the case of a Fakes project is the name of the project plus ".fakes". If it is a fakes project, then the project is marked as excluded in the _ProjectInfo.xml_ file that is created under _.sonarqube\out\{project-specific-directory}_.

FYI the _f.proj_ files are created under the _out\{debug|release}\Fakes_ directory.

Before _SONARMSBRU-26_, _f.proj_ files were analysed and the results uploaded to _SonarQube_ which resulted in a whole series of components called "f" appearing on the SonarQube dashboard.

So, it looks like the integration targets are correctly detecting that the project is a fakes project. However, the targets still write out two files under _.sonarqube_, and it's one of these files that you are getting the locking issue on.

Thanks for confirming it's the AV that is holding the file lock. However, it's not clear why this is only happening on fakes projects, or why it is happening so frequently. The files are supposed to be written out under a per-project directory, where the directory name is calculated using a semi-random name that includes a timestamp.

Are you using a large number of fakes assemblies, or are the directories under _.sonarqube\out_ left from previous builds? If the folders are left over from previous builds then a potential workaround would be to add a script step to the build defintion to explicitly delete the _.sonarqube_ directory at the start of the VSO build (although this might run into the same file locking issue).

I have an alternative possible workaround that I'll try out and post details on separately.

**Comment by zmckinnon** [comment] 2016-08-17 12:15
@duncanpMS 
Thanks for clearing that up!
This particular project uses 8 fakes (not sure if that qualifies as a large number). The directories under .sonarqube/out ARE left after builds but WHEN it succeeds, the f_whatever directories are NOT there.(Not sure if that is because they never got created or because they get deleted too quickly for me to see them)
If the build fails, it leaves SOME of the f_whatever directories.

**Comment by zmckinnon** [comment] 2016-08-17 15:10
Another thing I noticed . . .

The .sonarqube directory is in the directory "above" the source directory so it doesn't get removed if you do a "clean repository".

Any particular reason NOT to put it in the sources directory?

**Comment by bgavrilMS** [comment] 2016-08-17 15:32
The .sonarqube directory is created by SonarQube MSBuild Scanner for its use. It will have, among other items - a copy of the scanner, a description of the project that get analysed in a format that SonarQube understands and many files internal to SonarQube. It has nothing to do with the sources. In general we avoid touching the sources directory - it can lead to unintended consequences. 

The .sonarqube directory gets deleted by the next analysis. We decided not clean up when the analysis finishes since it provides valuable information about the analysis itself, so occasionally we ask users to send us files from there.

**Comment by zmckinnon** [comment] 2016-08-17 15:38
@bgavrilMS, that makes sense, thanks.

I disabled the SQ tasks and kicked off the build again.  I got the same issue.

I think it's pretty doubtful that AV is still using that file.

Any ideas what else could be accessing that file?

**Comment by duncanpMS** [comment] 2016-08-17 16:31
@zmckinnon no, I'm afraid not. A tool like SysInternals _Process Monitor_ might help pin it down.

Here's a possible workaround: copy the following XML into a file (the name doesn't matter) and dump it on the agent machine. The detailed explanation is in the file: the short version is that it attempts to guarantee that the per-project folder name is unique by using a guid.

You'll be able to tell if the file is being used by looking for the text "FolderDisambiguator" in the build output.

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <!-- This target changes the suffix used to disambiguate folders names.
       It's an attempt to work round a problem encountered when generating fakes -
         the build is failing because the integration targets are attempting
         to delete a folder that contains a locked file. However, the folder names
         are supposed to be unique to the project, and include a tick/timestamp suffix.

         This tweak uses a GUID instead which should definitely be unique, at the cost of
         increasing the length of the name i.e. there is the possibility that the generated
         name will be too long.

         USAGE: drop this file in the standard MSBuild ImportBefore folder for the version
           of MSBuild you are using (create the ImportBefore folder if it does not exist)
           e.g. %ProgramFiles(x86)%\msbuild\14.0\Microsoft.Common.Targets\ImportBefore
  -->

  <PropertyGroup>
    <FolderDisambiguator Condition=" $(FolderDisambiguator)=='' ">_$(Platform)_$(Configuration)_$([System.Guid]::NewGuid().ToString())</FolderDisambiguator>
  </PropertyGroup>

  <!-- This target is not required: it simply writes out additional information to simplify debugging -->
  <Target Name="ChangeFolderDisambiguator_DEBUG" BeforeTargets="CoreCompile"
          Condition=" $(SonarQubeTempPath) != '' ">
    <Message Importance="high" Text="FolderDisambiguator = $(FolderDisambiguator)" />
  </Target>

</Project>
```

**Comment by zmckinnon** [comment] 2016-08-22 14:04
I used SysInternals Process Monitor to take a look at what processes might be locking the file.

The AV (System Center Endpoint Protection) WAS still accessing it.  I managed to ACTUALLY exclude it, but it is still getting this error:

```
F:\Agent-03\_work\1\.sonarqube\bin\targets\SonarQube.Integration.targets (240, 5)
Could not write lines to file "F:\Agent-03\_work\1\.sonarqube\out\\f_AnyCPU_Release_4953\FilesToAnalyze.txt". The process cannot access the file 'F:\Agent-03\_work\1\.sonarqube\out\f_AnyCPU_Release_4953\FilesToAnalyze.txt' because it is being used by another process. [F:\Agent-03\_work\1\s\Paragon.Web.Tests\obj\Release\Fakes\npb\f.csproj]
```

Process Monitor is NOT showing any weirdness, but the AV is definitely not accessing that file anymore.

I am running out of ideas.

@duncanpMS I will try the "FolderDisambiguator" thing today.

**Comment by bgavrilMS** [comment] 2016-08-30 09:06
Hi @zmckinnon  - did you have a chance to use the FolderDisambiguator ?

**Comment by zmckinnon** [comment] 2016-08-30 15:44
@bgavrilMS I tried it and it seemed to fix the problem.

The .sonarqube\out directories changed from having a random 4 digit ending to having a GUID ending.

Could you explain why this would have fixed it?

Thanks.

**Comment by bgavrilMS** [comment] 2016-08-31 08:35
Thank you for confirming! 

We initially used a GUID to disambiguate between the folders. The problem is that GUIDs are long and users started complaining about long path exceptions. So we now use 4 digits which are the final 4 ticks of the current datetime. It seems highly unlikely that collisions can occur, but obviously for you it happns, and consistently so.

**Comment by zmckinnon** [comment] 2016-08-31 12:19
We have multiple test projects with Fakes and they get built in parallel.

We will use this as a solution. I'll let you guys close this issue out.

Thanks everyone!

**Closed** 2016-08-31 12:20 UTC
Labels: Area: Analysis, Dev15

**Comment by iamthegD** [comment] 2016-11-25 21:54
Sorry to necro this thread but I'm having the same problem. 

If launching XAML imports/FolderDisambiguator is not a solution since we are moving away from xaml for obvious reasons. Are there any work around or updates that will fix this issue ?

Thanks

**Comment by bgavrilMS** [comment] 2016-11-28 15:44
@iamthegD - could you try the workaround proposed by Duncan?

**Comment by CodersB** [comment] 2017-10-11 17:31
Did it fix the problem ? I'm getting the error below and not able to find away to skip the projects that causes this error during Build. Appreciate your help in fixing this.

_error MSB3231: Unable to remove directory ./sonarqube/out/f_1002_

**Comment by duncanp-sonar** [comment] 2017-10-16 08:09
@CodersB reading the responses above, it looks like using the _FolderDisambiguator_ option did work for zmckinnon.
Alternatively, you can exclude specific projects from analysis - see https://stackoverflow.com/questions/32563682/how-to-exclude-ignore-referenced-projects-analysis-from-soanrqube
