### ISSUE TITLE
Run Distributed Tests on TFS 2015.3 could not load file or assembly Microsoft.TeamFoundation.TestPlatform.Client

### ISSUE THREAD

**Issue by mutee88** [Microsoft/vsts-tasks#3872] opened 2017-03-26 10:04 UTC
I am experiencing exactly the same issue as #2387. 

I have tried all the resolutions outlined including:-

1. Re-installing agents by hand
2. Repairing the installation. 

What doesn't make sense is that the DLL is nowhere to be found in any installation. 

Task version : 1.0.49

Error
DistributedTests: Test discovery started.
DistributedTests: Test Run Discovery Aborted . Test run id : 38037
DistributedTests: UnExpected error occured during test execution. Try again.
DistributedTests: Error : One or more errors occurred.--->Could not load file or assembly 'Microsoft.TeamFoundation.TestPlatform.Client, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
DistributedTests: Test run aborted. Test run id: 38037
System.Exception: The test run was aborted, failing the task.
PowerShell script completed with 1 errors.

**Comment by tanvi-soni** [comment] 2017-03-30 07:40
Which version of test agent did you install? Can you try installing from http://go.microsoft.com/fwlink/?LinkId=615472 

After installation, can you try searching for dll in C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow

**Comment by tanvi-soni** [comment] 2017-04-06 10:56
@mutee88 Any update?

**Comment by RanjanarMS** [comment] 2017-04-11 06:19
Closing this thread for now. If you feel the issue is not addressed please re-open.

**Closed by RanjanarMS** 2017-04-11 06:19 UTC
Labels: Area: Test

**Comment by mutee88** [comment] 2017-04-11 09:44
Hello-

This has not been resolved. I uninstalled whatever was installed and installed the version on the link provided. Still, no DLL named "Microsoft.TeamFoundation.TestPlatform.Client".

**Comment by mutee88** [comment] 2017-04-11 09:58
Please reopen this issues as it has not been resolved yet!

**Comment by mutee88** [comment] 2017-04-13 09:42
Fixed this by copying the specific DLL from the development machine to the build server.
