### ISSUE TITLE
AzureRM Web App Deployment - Cannot bind argument to parameter 'files' because it is an empty string

### ISSUE THREAD

**Issue by massimocode** [Microsoft/vsts-tasks#2348] opened 2016-08-27 11:04 UTC
I created an AzureRM Web App Deployment on 24th August and specified my file paths using the [...] button which allows you to view the output of the last build using the file explorer modal dialog. My json configuration looked like this:

``` json
"package": "$(System.DefaultWorkingDirectory)/MainBuildScript/drop/*.zip",
"setParametersFile": "$(System.DefaultWorkingDirectory)/MainBuildScript/drop/parameters.xml",
```

The release worked great until I tried releasing early this morning (8am 27th August GMT) when it started failing. The working release had the following in the logs:

```
2016-08-24T19:45:02.7429081Z msdeploy.exe is located at 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2016-08-24T19:45:02.7459078Z filePath = Find-Files -SearchPattern C:\a\254569071\MainBuildScript\drop\*.zip
2016-08-24T19:45:03.0719076Z filePath = C:\a\254569071\MainBuildScript\drop\29.zip
2016-08-24T19:45:03.0769077Z filePath = Find-Files -SearchPattern C:\a\254569071\MainBuildScript\drop\parameters.xml
2016-08-24T19:45:03.0879076Z filePath = C:\a\254569071\MainBuildScript\drop\parameters.xml
```

The failed release this morning had the following in the logs:

```
2016-08-27T08:41:21.9138109Z msdeploy.exe is located at 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
2016-08-27T08:41:21.9168115Z filePath = Find-Files -SearchPattern C:\a\r1\a/MainBuildScript/drop/*.zip
2016-08-27T08:41:22.2598194Z filePath = 
2016-08-27T08:41:22.4288105Z ##[error]Cannot bind argument to parameter 'files' because it is an empty string.
```

I have since manually updated the paths (not using the file picker!) and so my json configuration now looks like this:

``` json
"package": "$(System.DefaultWorkingDirectory)\\MainBuildScript\\drop\\*.zip",
"setParametersFile": "$(System.DefaultWorkingDirectory)\\MainBuildScript\\drop\\parameters.xml",
```

The deployment now works correctly again.

There are 2 potential issues here:
- Either the code which reads the path that used to correctly translate the forward slashes to back slashes is no longer working
- Or the file picker should not be generating paths that use forward slashes

I reckon the best solution would be to fix the code which translates the paths because, as you can imagine, there are probably thousands of other users like me who have forward slashes in the paths and it wouldn't be great to have to tell everyone to manually fix their paths.

**Comment by bryanmacfarlane** [comment] 2016-08-27 14:03
@massimocode - Agreed.  Not only are forward slashes common, it's what the web definition editor puts in for paths.

**Comment by kmkumaran** [comment] 2016-08-29 14:10
@bryanmacfarlane @ericsciple the task here uses find-vstsfiles from powershell lib. Are there any changes/issues in lib?

**Comment by bryanmacfarlane** [comment] 2016-08-29 14:43
@kmkumaran - no known issues.  Let us know what you find.

**Comment by kmkumaran** [comment] 2016-08-30 14:22
@massimocode - we weren't able to reproduce this issue locally. Can you help us with few additional details:
a) Can you share your build/release log with system.debug set to true
b) Can you tell us if you are using 1.x agent (Windows legacy) or the 2.x agent or hosted agent?

**Comment by boydc2014** [comment] 2016-08-30 15:47
@kmkumaran I encountered the same issue just now.  with 2.x windows agent. on maasg account.
with such logs:

2016-08-30T15:39:38.5463918Z ##[command]Import-Module -Name C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\AzureRM.Profile\AzureRM.Profile.psd1 -Global
 
2016-08-30T15:39:38.7943936Z ##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential
 
2016-08-30T15:39:40.1595016Z ##[command]Select-AzureRMSubscription -SubscriptionId 75a41c9b-66bc-42f5-9865-e6ace37523cd -TenantId ********
 
2016-08-30T15:39:48.5910027Z ##[error]Cannot bind argument to parameter 'storageKey' because it is an empty string.
 
2016-08-30T15:39:48.6150024Z ##[section]Finishing: AzureVMs File Copy

**Comment by boydc2014** [comment] 2016-08-30 16:05
@kmkumaran I'm using Azure PS2.0.1, looks like that might be the root cause.

**Comment by massimocode** [comment] 2016-08-30 20:59
@boydc2014 I am not sure that the symptoms you are experiencing are related to the issue I posted

**Comment by massimocode** [comment] 2016-08-30 21:02
@kmkumaran see answers below:

a) I would be happy to provide my full build/release log but it would be best if you could provide me your email address because it contains sensitive information like project name, azure account name, etc. My email address is massimo.hamilton@outlook.com.
b) I'm using a hosted build agent.

**Comment by Ajay-MS** [comment] 2016-08-31 06:43
@massimocode  please share logs at RM_Customer_Queries@microsoft.com

**Comment by kmkumaran** [comment] 2016-09-11 09:02
@massimocode - The issue has not been reproducible locally for us. I am marking this thread closed. If the problem is still present, feel free to re-open this issue and share logs with us in the above mentioned DL. I have also sent you a note from my Microsoft ID. You can reply to it as well.

**Comment by francescomagalini** [comment] 2016-09-18 13:52
Hi all,
same issue here.
Dropped an email to RM_Customer_Queries@microsoft.com
Thanks

**Comment by massimocode** [comment] 2016-09-19 21:55
@kmkumaran Sorry for the long delay, I have just send all the build logs to you Microsoft ID. The RM_Customer_Queries@Microsoft.com address does not work. It might be worth sharing your Microsoft ID with @francescomagalini as well as he might have some valuable logs too.

**Comment by Ajay-MS** [comment] 2016-09-23 05:19
@massimocode @francescomagalini 

I hope you are facing this issue with hosted agent -  2.105.2 only , because its failing while resolving regex for files that why filePath is empty. You will not face this issue with next deployment ( approx. 1-2 weeks ).

Work around
1.	Select complete path of file without any regex. 
2.	Download 2.106 onPrem agent and run your task with that agent.

Please update if these workarounds are working for you.

**Comment by Ajay-MS** [comment] 2016-09-26 11:30
@massimocode 

Closing this thread as you are unblocked on it, depending on offline conversation.

**Comment by stevematdavies** [comment] 2017-08-25 13:26
This issue has caused a failure of our VST to Azure deployment, so badly with no solution from MS, we have considered dropping Azure alltogether

**Comment by KrishnaAdityaB** [comment] 2017-08-28 06:57
@stevematdavies 
1. Did you face the issue with 'files' or 'storageKey"? 
2. Can you share the debug logs with RM_Customer_Queries@Microsoft.com? (Run the release with System.Debug variable set to true)
3. Can you give details about the agent?
3.1 Hosted Agent? If yes, what is the queue name?
3.2 Private Agent? If yes, what is the agent version? what is the AzurePS version? - if possible, share the capabilities of the agent

**Comment by stevematdavies** [comment] 2017-08-28 07:12
1. No, only with Files.
2. No, Im not our VSTS or Azure Admin,
3. Hosted, and I'm not sure I can even divulge the queue name, its a private company account

This issue arose many months ago. (No clear or concise solution offered, just more overly complex questions). We removed all our builds and started from scratch, which temporarily fixed the issue. We have recently done the same at considerable time loss to our development cycle and for now it has also fixed the issue. However, this is another consideration for whether we stay with Azure.

Points of note,

It happens every few months, a build constantly works then one day this error, despite nothing changing in our deployment code or cycle (Its an Azure error anyhow, not in our deployment app which is a uncomplex Node application)

There is not a single iota of help or guidance for any such issues on VSTS builds. All links to MS solutions do nothing but link back to instructions for setting up builds. (One instruction which we followed, and still received the error)

Digging through the utter mess of discussions with MS, GitHub, StackExchange etc, there is almost Zero solutions for when this happens on VSTS, 99% assume we are deploying from a local machine via Command Shell, we are not. We have a simple CI Build in VSTS which deploys to our Azure WebApp (in fact many builds, but only the Node apps break).

So, I cannot divulge such info to you at this time. However, there seems to be more than enough on this issue (going back many months and even a year) for you to look into it. For example the PS Agent in VSTS?

**Comment by Ajay-MS** [comment] 2017-08-28 09:30
@stevematdavies 

I apologize that you are still facing issue being mentioned in above thread. 

Above mentioned issue was being reported in Azure App Service task with version 1.* ( written in PowerShell).  In PS based implementation of Find-VstsFiles ( a utility method for resolving actual path with regex) was failing if the path contains regex + BackSlash. In case of regex with a back slash, it was returning an empty array of files and not able to find actual path to web app zip file.  This issue was only encountered with agent version 2.105.2. 

We had following observation at that time 
Agent 2.105.2

_Case I ( Regex + Path Selected using file picker )     -   ISSUE_
User provided Input for FilePicker: $(System.DefaultWorkingDirectory)/PublishArtifacts/test/*.zip
Input received to task : C:\coreclrAgents\11\_work\r1\a/PublishArtifacts/test/*.zip
Result  : Failed ( As not able to resolve this expression)  
 
_Case II ( Full Path is selected using file picker )_
User provided Input for FilePicker : $(System.DefaultWorkingDirectory)/PublishArtifacts/test/webapp.zip
Input received to task : C:\coreclrAgents\11\_work\r1\a\PublishArtifacts\test\webApp.zip
Result  : Succeed.

_Case III ( Changed backslash to forward one + Regex )_ 
User provided Input for FilePicker : $(System.DefaultWorkingDirectory)\PublishArtifacts\test\*.zip
Input received to task : C:\coreclrAgents\11\_work\r1\a\PublishArtifacts\test\*.zip
Result  : Succeed

Agent 2.106

_Case I ( Regex + Path Selected using file picker )_ 
User provided Input for FilePicker : $(System.DefaultWorkingDirectory)/PublishArtifacts/test/*.zip
Input received to task : C:\coreclrAgents\11\_work\r1\a\PublishArtifacts\test\*.zip
Result  : Succeed.

_Case II ( Full Path is selected using file picker )_
User provided Input for FilePicker : $(System.DefaultWorkingDirectory)/PublishArtifacts/test/webapp.zip
Input received to task : C:\coreclrAgents\11\_work\r1\a\PublishArtifacts\test\webApp.zip
Result  : Succeed.

_Case III ( Changed backslash to forward one + Regex )_ 
User provided Input for FilePicker : $(System.DefaultWorkingDirectory)\PublishArtifacts\test\*.zip
Input received to task : C:\coreclrAgents\11\_work\r1\a\PublishArtifacts\test\*.zip
Result  : Succeed

Later versions of the task have handled this issue. 

I am assuming current version of Azure App Service deploy task that you are using >= 2.* ( which is being written in node js). Unfortunately, you have faced similar kind of issue but it seems that there will different reason that is causing this issue. 

To find exact cause of this issue please share following details 
1.  Your VSTS account name?
2.  Link to your build/release definition where the task is being failed?
3.  Share the debug logs with RM_Customer_Queries@Microsoft.com? (Run the release with System.Debug variable set to true)

I assure you we will look this at priority and will resolve it soon.

**Comment by vincentdass** [comment] 2017-09-26 14:19
Azure App Service Deploy task works fine with regex in 2.* and 3.* version.
Closing the issue.

**Closed by vincentdass** 2017-09-26 14:19 UTC
Labels: Area: Release
