### ISSUE TITLE
Proxy and VSTS_HTTP_PROXY is failing for Node.js Tasks 

### ISSUE THREAD

**Issue by mmercan** [Microsoft/vsts-tasks#3441] opened 2017-01-18 06:38 UTC
I run my agent under a proxy I added .proxy file and I also added VSTS_HTTP_PROXY environment variable too, Powershell base tasks works well on
Requesting for Auth Token: https://login.windows.net/********/oauth2/token/
But Node.js tasks gives Error: connect ETIMEDOUT 23.101.222.242:443
error message

(https://github.com/Microsoft/vsts-node-api/blob/28cc72093615fbdaf274e3c4e17653e449f799ca/api/HttpClient.ts

 ```
var proxyUrl: url.Url;
        if (process.env.HTTPS_PROXY && usingSsl) {
            proxyUrl = url.parse(process.env.HTTPS_PROXY);
        } else if (process.env.HTTP_PROXY) {
            proxyUrl = url.parse(process.env.HTTP_PROXY);
        }
```

Solution: I followed and see process.env.HTTPS_PROXY is used in HttpClient and I added HTTPS_PROXY to windows  environment variable, now It works fine

**Comment by mmercan** [comment] 2017-01-18 06:45
Azure App Service Deploy (RM)  2.1.8 / Private Agent
Error: The underlying connection was closed: An unexpected error occurred on a send.
Error: Authentication failed because the remote party has closed the transport stream.
Error count: 1.

To fix this I added
RegEdit
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319 
SchUseStrongCrypto (DWORD)  =  1

**Comment by vincentdass** [comment] 2017-01-19 11:17
@bryanmacfarlane , the issue is coming for vso-node-api.
Can you please look at this issue ?

**Comment by bryanmacfarlane** [comment] 2017-01-20 15:31
I'm looking into this.

@mmercan can you clarify something?  In your issue you talked about both powershell and node.  Then you said you fixed node by using envvar (good - btw, we have work for agent proxy settings to flow and just work in node tasks).   But then you mentioned the net framework reg key.  Was that need for node task (you said it work prior).  I wouldn't expect .net framework to effect node unless it effects the OS layer.  Or was that needed for powershell?

**Comment by mmercan** [comment] 2017-01-21 04:20
Hi Bryan,
This problem is Just for Node, Powershell worked fine from the beginning and adding envvar solved the connection problem for Node too.

**Comment by mmercan** [comment] 2017-01-21 04:22
Comment I added was the second problem I encountered after proxy worked, (I Know I should open a second Issue for this)

Azure App Service Deploy (2.1.10) Runs msdeploy.exe after Azure Authentication, this is the result of msdeploy.exe command 
and It was returning 
##[error]Error Code: ERROR_CERTIFICATE_VALIDATION_FAILED
I fixed this with 
RegEdit
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
SchUseStrongCrypto (DWORD) = 1



Got connection details for Azure App Service:'mybupa-cms-bupaaunz'
[command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:IisApp='F:\agent\_work\r1\a\Sitecore_8.2_update_1\CM' -dest:iisApp='***********',ComputerName='*****************:443/msdeploy.axd?site=*************',UserName='********',Password='********',AuthType='Basic' -enableRule:DoNotDeleteRule -userAgent:VSTS_***************
Info: Using ID 'ac525a90-d351-47c8-9483-f009f8e9ef28' for connections to the remote server.
##[error]Failed to deploy App Service.
##[error]Error Code: ERROR_CERTIFICATE_VALIDATION_FAILED
More Information: Connected to the remote computer ("****************") using the specified process ("Web Management Service"), but could not verify the server’s certificate. If you trust the server, connect again and allow untrusted certificates.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CERTIFICATE_VALIDATION_FAILED.
Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
Error: The remote certificate is invalid according to the validation procedure.
Error count: 1.

**Comment by bryanmacfarlane** [comment] 2017-01-26 01:55
Yes, create another issue for that other issue.  closing this as the node proxy issue was addressed.  Thanks!

**Closed by bryanmacfarlane** 2017-01-26 01:55 UTC
