### ISSUE TITLE
Is there a logging command for informational or verbose messages?

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/vsts-tasks#6291] opened 2018-01-26 14:29 UTC
[This page](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) lists an error or warning command, but I don't see any informational message command. Is there one present?

**Comment by kmkumaran** [comment] 2018-02-02 03:12
There is no commands for information or verbose. Any output you put in console using write-output or write-verbose from your script can meet your needs here. Adding @ericsciple

**Comment by StingyJack** [comment] 2018-02-02 14:23
No, not tags. Just trying to write information to the log from a script.  Write-Verbose only does so when debug is turned on, and Write-Output seems less reliable (and less appropriate) than Write-Host in capturing the messages, but even Write-Host sometimes doesn't capture.

**Comment by mmajcica** [comment] 2018-02-20 09:54
I just tried and I do see that the following command transforms in a verbose message:
##vso[task.debug]My text

Is this what you were looking for?

**Comment by StingyJack** [comment] 2018-02-20 13:12
@mmajcica - actually I was looking for something clear, easy, and reliable like the WriteBuildMessage, WriteBuildWarning, and WriteBuildError that were available in XAML builds.  Write-Host seems the most reliable choice so far.

This [task.debug] missing from the documentation just adds more change-test cycles for everyone, making it a time consuming effort in trial and error to discover what works or doesn't. (5 minutes for a single change-test cycle with vNext build is still much shorter than the same for XAML, but its 5 minutes spent per attempt due to incomplete documentation and commands that resemble some of git's contortions. )

**Comment by bryanmacfarlane** [comment] 2018-02-20 13:23
> Just trying to write information to the log from a script.

Simply writing to stdout from a script goes to the log.  

The reason only Warning and Error exist is those go to the "Issues" section of the summary page.   They standout from the standard log lines.  If it's informational, then it should just be stdout in the log.

Closing as this is by design.  It's also not an issue with one of the tasks in this repo which is what these issues capture.

**Closed by bryanmacfarlane** 2018-02-20 13:23 UTC
Labels: Area: Core, question

**Comment by StingyJack** [comment] 2018-02-20 13:30
@bryanmacfarlane  - if the [task.debug] exists (haven't tried it yet), then there is at least a missing element in that documentation page (part of this repo).  Which is the key point I'm making in the second paragraph - instead of being able to easily find and read the doc page and get the info, I had to spend an inordinate amount of time (not a single 5 minute cycle, several of them) trying to figure out what works and doesnt.

**Comment by bryanmacfarlane** [comment] 2018-02-20 13:32
It's in the user docs:

https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

**Comment by StingyJack** [comment] 2018-02-20 13:35
Where on that page do I find these ##vso[task.*] things?

**Comment by bryanmacfarlane** [comment] 2018-02-20 13:38
Those are user facing docs.  The point of setting system.debug is to help the consumer of the tasks help figure out why what they are doing isn't working.  For example, in the copy tasks, in debug it prints out full src and dest paths per file to help the user figure out why their copy specs aren't working.

##vso commands is for task authors.  Since the task repo is a repo of reference examples (that's why we open sourced the tasks), that doc is in that repo.

**Comment by mmajcica** [comment] 2018-02-20 13:47
@StingyJack you can find an example of this command in here https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/VstsTaskSdk/LoggingCommandFunctions.ps1
I'm using it in a situation that I will describe.

@bryanmacfarlane 
In my custom build task I'm invoking some code via WinRM through Invoke-Command cmdlet. In that case, if the code that is executed remotely, needs to write verbose messages, this is the only way as far as I know.

**Comment by StingyJack** [comment] 2018-02-20 13:48
@bryanmacfarlane - I didnt ask about system.debug.  I asked about getting informational messages out to the console/log (regardless of the value in system.debug).

And I know the doc is in this repo, its why I logged the issue here. You are the one who said this issue doesnt belong, and then pointed me at a guide that doesnt have the thing I asked for either.

I'm a bit salty now, so I am going to close this browser tab and revisit when I get into the office later. Please take a minute to digest the conversation.
