### ISSUE TITLE
NuGet Installer Task fails due to being unable to access nuget.config

### ISSUE THREAD

**Issue by thorbenw** [Microsoft/vsts-tasks#2182] opened 2016-08-02 09:02 UTC
Since today, we're facing problems with the NuGet Installer task (restore).

We're using a custom nuget.config to specify a VSTS Package Management source. The task fails to remove and then reapply the source (including credentials?) to the temp nuget.config file. Later on, access to the feed fails due to lack of credentials.

Most recent log from the build:
[20160802.2.txt](https://github.com/Microsoft/vsts-tasks/files/396211/20160802.2.txt)

**Comment by LarsSkovslund** [comment] 2016-08-03 08:30
If you are hosting your own build agent, fixing the issue is easy, simply copy [nuget.exe 3.4.4 from nuget.org](https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe) into [agent folder]\agent\Worker\Tools

**Comment by thorbenw** [comment] 2016-08-03 11:36
@LarsSkovslund many thanks for your tip - I downloaded nuget 3.4.4 and explicitly specified to use it with the NuGet Installer VSTS Task in the build configuration just to see if it helps out. Unfortunately it didn't and the issue remained.

Just in case it is important for further investigations: We're leveraging the hosted build agents and don't maintain own build agents.

Log from this build:
[20160803.3.txt](https://github.com/Microsoft/vsts-tasks/files/399342/20160803.3.txt)

**Comment by thorbenw** [comment] 2016-08-05 01:52
@jmyersmsft I just tested NuGet Installer 0.2.7 - it's working without any issues.

Thanks a lot!

**Comment by zjrunner** [comment] 2016-09-05 18:22
Fixed in 0.2.7 and verified, closing.

**Closed by zjrunner** 2016-09-05 18:22 UTC
Labels: Area: Packaging, Dev15
