### ISSUE TITLE
NuGet Packager tasks failed due to old version

### ISSUE THREAD

**Issue by matttrakker** [Microsoft/vsts-tasks#3746] opened 2017-03-07 20:22 UTC
Dear all,

the nuget packager task is failing with the following error:
##[error]'System.ComponentModel.EventBasedAsync' already has a dependency defined for 'System.Runtime'.

EventBasedAsync is version 4.3.0 downgrading to 4.0.11 has not solved it.

I found a walkaround by downloading the latest nuget exe before the packaging task and then using this nuget.exe for the package task.
I think is not a good idea if the ci is building multiple times with multiple projects a day.

May you please update the nuget.exe?

Thanks and best regards,
matthias

**Comment by ekumlin** [comment] 2017-03-07 23:24
NuGet 3.3 also fails (silently -- it produces the `Unsupported0.0` framework) when attempting to pack something with a target of `netstandard1.6`. Other tasks allow us to choose between 3.5 and 3.3, and the same would be helpful here.

**Comment by KZeronimo** [comment] 2017-03-08 15:43
Agreed.  NuGet Restore and Publisher tasks allow the choice of NuGet version - NuGet Packager needs to behave the same manner.

**Comment by chrisnott** [comment] 2017-03-19 21:10
Yes, this is essential. Please add support for this.

**Comment by mikanyg** [comment] 2017-03-21 22:28
Yes all 3 nuget tasks should be aligned with regards to nuget version selection.

**Comment by alexmullans** [comment] 2017-04-13 15:07
Duplicate of #3756

**Closed by alexmullans** 2017-04-13 15:07 UTC
Labels: Area: Packaging
