### ISSUE TITLE
Xml Substitution does not work if value is empty string

### ISSUE THREAD

**Issue by neurospeech** [Microsoft/vsts-tasks#6419] opened 2018-02-13 09:14 UTC
## Environment
- Server - VSTS

## Issue Description

This used to work well in the past, but it has stopped working since last two days.

Consider `web.config`

```xml
<appSettings>
     <add name="CDNHost" value="" />
     <add name="SignalRHost" value="localhost" />
</appSettings>
```

Substitution 
CDNHost = "some-cdn.azureedge.net"
SignalRHost = "notify.some-host.com"

Expected output
```xml
<appSettings>
     <add name="CDNHost" value="cdn.azureedge.net" />
     <add name="SignalRHost" value="notify.some-host.com" />
</appSettings>
```

Actual Output
```xml
<appSettings>
     <add name="CDNHost" value="" />
     <add name="SignalRHost" value="notify.some-host.com" />
</appSettings>
```

Notice that `CDNHost` remains empty. This was working correctly two days ago.

**Comment by asranja** [comment] 2018-02-13 09:24
@neurospeech can you specify the task version that the release is picking up ?

**Comment by neurospeech** [comment] 2018-02-13 09:33
IIS Web App Deploy Version is `[0.*]`

```
[AGENT_VERSION] --> [2.126.0]
[AGENT_WORKFOLDER] --> [C:\vstsagent\A1\_work]
[AZURE_HTTP_USER_AGENT] --> [VSTS_ad14dd5b-81d8-4ee5-af36-fe96e7927997_release_2_404_640_1]
```

Since the log contains sensitive information, I will need to know what fields you need from the release log.

**Comment by asranja** [comment] 2018-02-13 09:59
Please specify the exact task version from the release logs. 

2018-02-13T09:57:02.3630259Z ==============================================================================
2018-02-13T09:57:02.3630491Z Task         : IIS Web App Deploy
2018-02-13T09:57:02.3630652Z Description  : Deploy a Website or Web Application using WebDeploy
2018-02-13T09:57:02.3630831Z Version      : 0.0.34
2018-02-13T09:57:02.3631013Z Author       : Microsoft Corporation
2018-02-13T09:57:02.3631189Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=866789)
2018-02-13T09:57:02.3631388Z ==============================================================================

**Comment by neurospeech** [comment] 2018-02-13 11:40
```
2018-02-13T08:57:28.6464653Z ##[section]Starting: IIS Web App Deploy
2018-02-13T08:57:28.6468542Z ==============================================================================
2018-02-13T08:57:28.6468643Z Task         : IIS Web App Deploy
2018-02-13T08:57:28.6468720Z Description  : Deploy a Website or Web Application using WebDeploy
2018-02-13T08:57:28.6468797Z Version      : 0.0.30
2018-02-13T08:57:28.6468880Z Author       : Microsoft Corporation
2018-02-13T08:57:28.6468957Z Help         : [More Information](https://aka.ms/iiswebappdeployreadme)
2018-02-13T08:57:28.6469039Z ==============================================================================
2018-02-13T08:57:57.0118336Z XML variable substitution applied successfully.
```

**Comment by asranja** [comment] 2018-02-13 12:45
@neurospeech we have fixed this issue in version 0.0.33 of the task which is currently being deployed. Depending on the location of your account, you will receive this fix within two weeks.

**Comment by NateB2** [comment] 2018-02-13 22:53
I can confirm this bug exists for the App Service deploy task version 3.3.36.  Is the fix for that task currently being deployed as well?

**Comment by vincentdass** [comment] 2018-02-14 04:24
@NateB2 , the issue is fixed in 3.3.40 task version. The fix will be available in 2-3 weeks.

**Comment by vincentdass** [comment] 2018-02-28 14:04
@NateB2 , The Fix is deployed. Rerun the release for the new task version.

**Closed by vincentdass** 2018-02-28 14:04 UTC
Labels: Area: AzureAppService, Area: Release

**Comment by Andreas-Lehmann** [comment] 2018-03-02 12:31
Hello @vincentdass can you tell me if the other direction of empty string substitution shall work?
I try to replace a value in my XML config with an empty string (modified initial example for clarification).

Consider `web.config`
```xml
<appSettings>
     <add name="CDNHost" value="abc" />
     <add name="SignalRHost" value="localhost" />
</appSettings>
```
**Substitution**
CDNHost = "" *empty string*
SignalRHost = "notify.some-host.com"

Expected output
```xml
<appSettings>
     <add name="CDNHost" value="" />
     <add name="SignalRHost" value="notify.some-host.com" />
</appSettings>
```

Actual Output
```xml
<appSettings>
     <add name="CDNHost" value="abc" />
     <add name="SignalRHost" value="notify.some-host.com" />
</appSettings>
```

Notice that CDNHost still has the original value.
I'm using this version of the  Task:
```
2018-03-02T10:58:28.1088669Z ==============================================================================
2018-03-02T10:58:28.1088669Z Task         : Azure App Service Deploy
2018-03-02T10:58:28.1088669Z Description  : Update Azure WebApp Services On Windows, Web App On Linux with built-in images or docker containers, ASP.NET, .NET Core, PHP, Python or Node based Web applications, Function Apps, Mobile Apps, Api applications, Web Jobs using Web Deploy / Kudu REST APIs
2018-03-02T10:58:28.1088669Z Version      : 3.3.41
2018-03-02T10:58:28.1088669Z Author       : Microsoft Corporation
2018-03-02T10:58:28.1088669Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2018-03-02T10:58:28.1088669Z ==============================================================================
```

**Comment by stajs** [comment] 2018-10-17 08:06
@Andreas-Lehmann FYI, I hit the same problem as you so I opened #8631.
