### ISSUE TITLE
RM Summary page not masking secrets

### ISSUE THREAD

**Issue by fsbuilds** [Microsoft/vsts-tasks#2720] opened 2016-09-29 23:17 UTC
The "secret" setting for properties, when logged as an error, will display and not be obfuscated on the TFS front end during a build/release process. The non-obfuscated string can appear on the Summary page under Issues - however, it is (as expected) obfuscated in the logs. I couldn't image this being the expected behavior.

Here are a couple images that may help show what I'm referencing. 

[Obfuscated in logs](http://s21.postimg.org/8e01v5riv/TFS_obfuscated_secret.png)

[Not on the summary page](http://s17.postimg.org/n4wzjlu0v/TFS_Shows_Secret_on_Summary_Errrors.png)

This example code *should* reproduce the problem.

```
var host= tl.getInput('host', true);
var pw= tl.getInput('pw', true);
var un = tl.getInput('un', true);.

var baseUri= "https://" + un + ":" + pw+ "@" + host;
var query = baseUri+ "/access/listvs?prot=tcp&Port=443";

fetch(query).then(function(res) {
        // doesn't matter what is here
}).catch(function(error) {
        console.log("Request to server failed. fyl.");
        tl.error(error);
        process.exit(1);
});
```

I am using this package:
"vsts-task-lib": "^0.9.20"

**Comment by bryanmacfarlane** [comment] 2016-10-02 13:08
This looks like an RM service bug.  Since the logs are masking the secret, the infra appears to be doing the right thing.

**Comment by GitHubSriramB** [comment] 2016-10-03 11:08
@fsbuilds We can repro this issue on 1.x version of agent when used to execute release or build on a VSTS account. This issue does not seem to repro with 2.x version of agent.  Can you confirm the version of the agent you used?

Did you execute release on TFS server or on VSTS account? If TFS server, what version of TFS server did you have?

**Comment by kmkumaran** [comment] 2016-10-12 13:54
Tagging as Core as the issue is relevant in both Build and RM per @GitHubSriramB

**Comment by ericsciple** [comment] 2016-10-12 14:22
@TingluoHuang fixed this recently in the 1.x agent. The fix will be in TFS 2016. If you are on visualstudio.com, then please use the 2.x agent (does not have the bug).

**Closed by ericsciple** 2016-10-12 14:22 UTC
Labels: Area: Core
