### ISSUE TITLE
Nuget Push Task not send api key

### ISSUE THREAD

**Issue by julioarruda** [Microsoft/vsts-tasks#5457] opened 2017-09-25 16:56 UTC
In the last week, my costumer has been reported that push task is not working. I saw the log, and i think, that token / apikey isn't send in the push command.

Using authentication information for the following URI: http://NexusURL
2017-09-25T12:17:18.5873980Z [command]E:\Bld\Agent-01\_work\_tool\NuGet\4.0.0\x64\nuget.exe push E:\Bld\Agent-01\_work\87\a\Package.1.0.1.20.nupkg -NonInteractive -Source http://NexusURL -ApiKey RequiredApiKey -ConfigFile E:\Bld\Agent-01\_work\87\Nuget\tempNuGet_6131.config -Verbosity Detailed
2017-09-25T12:17:19.0184281Z NuGet Version: 4.0.0.2283
2017-09-25T12:17:19.0994426Z Pushing Package.1.0.1.20.nupkg to 'http://NexusURL'...
2017-09-25T12:17:19.1454370Z   PUT http://NexusURL
2017-09-25T12:17:19.1994412Z Using credentials from config. UserName: ********
2017-09-25T12:17:19.6324720Z   Unauthorized http://NexusURL 487ms
2017-09-25T12:17:19.6514730Z System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
2017-09-25T12:17:19.6514730Z    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2017-09-25T12:17:19.6514730Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__19_1(HttpResponseMessage response)
2017-09-25T12:17:19.6514730Z    at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
2017-09-25T12:17:19.6514730Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6514730Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6514730Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6514730Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__19.MoveNext()
2017-09-25T12:17:19.6514730Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6514730Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6514730Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6514730Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__13.MoveNext()
2017-09-25T12:17:19.6514730Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6514730Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6514730Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6524726Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__12.MoveNext()
2017-09-25T12:17:19.6524726Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6524726Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__8.MoveNext()
2017-09-25T12:17:19.6524726Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6524726Z    at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
2017-09-25T12:17:19.6524726Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6524726Z    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()
2017-09-25T12:17:19.6524726Z    --- End of inner exception stack trace ---
2017-09-25T12:17:19.6524726Z    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
2017-09-25T12:17:19.6524726Z    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
2017-09-25T12:17:19.6524726Z    at NuGet.CommandLine.Command.Execute()
2017-09-25T12:17:19.6524726Z    at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
2017-09-25T12:17:19.6524726Z ---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
2017-09-25T12:17:19.6524726Z    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
2017-09-25T12:17:19.6524726Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<>c.<PushPackageToServer>b__19_1(HttpResponseMessage response)
2017-09-25T12:17:19.6524726Z    at NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__14`1.MoveNext()
2017-09-25T12:17:19.6524726Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6524726Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6534722Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageToServer>d__19.MoveNext()
2017-09-25T12:17:19.6534722Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6534722Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackageCore>d__13.MoveNext()
2017-09-25T12:17:19.6534722Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6534722Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<PushPackage>d__12.MoveNext()
2017-09-25T12:17:19.6534722Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6534722Z    at NuGet.Protocol.Core.Types.PackageUpdateResource.<Push>d__8.MoveNext()
2017-09-25T12:17:19.6534722Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6534722Z    at NuGet.Commands.PushRunner.<Run>d__0.MoveNext()
2017-09-25T12:17:19.6534722Z --- End of stack trace from previous location where exception was thrown ---
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-09-25T12:17:19.6534722Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-09-25T12:17:19.6534722Z    at NuGet.CommandLine.PushCommand.<ExecuteCommandAsync>d__28.MoveNext()<---
2017-09-25T12:17:19.6534722Z 
2017-09-25T12:17:19.6684740Z ##[error]Error: E:\Bld\Agent-01\_work\_tool\NuGet\4.0.0\x64\nuget.exe failed with return code: 1
2017-09-25T12:17:19.6684740Z ##[error]Packages failed to publish
2017-09-25T12:17:19.6764731Z ##[section]Finishing: NuGet push

**Comment by shimmyt** [comment] 2017-09-25 17:40
#5383 Same Issue

**Comment by alexmullans** [comment] 2017-09-25 19:09
Duplicate of #5383

**Closed by alexmullans** 2017-09-25 19:09 UTC
