### ISSUE TITLE
Deploy App Service Task Failing 

### ISSUE THREAD

**Issue by shiningdragon** [Microsoft/vsts-tasks#3437] opened 2017-01-17 15:58 UTC
Since yesterday I am seeing these failures deploying to app services. Was the task updated to version 2.1.9 recently? The failures started happening then.

2017-01-17T15:51:47.6828631Z ##[section]Starting: Deploy App Service
 
2017-01-17T15:51:47.6828631Z ==============================================================================
 
2017-01-17T15:51:47.6828631Z Task         : Azure App Service Deploy
 
2017-01-17T15:51:47.6828631Z Description  : Update Azure App Service using Web Deploy / Kudu REST APIs
 
2017-01-17T15:51:47.6828631Z Version      : 2.1.9
 
2017-01-17T15:51:47.6828631Z Author       : Microsoft Corporation
 
2017-01-17T15:51:47.6828631Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
 
2017-01-17T15:51:47.6828631Z ==============================================================================
 
2017-01-17T15:51:48.8287776Z 65d575ce-48c4-4ab3-be96-49b30f1fb650 exists true
 
2017-01-17T15:51:50.2137399Z Got connection details for Azure App Service:'lmtwebapptschedule'
 
2017-01-17T15:51:51.5816303Z ##[error]Error: Error: Unclosed root tag
 
2017-01-17T15:51:51.5816303Z Line: 8
 
2017-01-17T15:51:51.5816303Z Column: 27
 
2017-01-17T15:51:51.5816303Z Char: 
 
2017-01-17T15:51:51.5990677Z Line: 8
 
2017-01-17T15:51:51.5990677Z Column: 27
 
2017-01-17T15:51:51.5990677Z Char: 
 
2017-01-17T15:51:51.7066585Z ##[error]Unhandled: EBADF: bad file descriptor, write
 
2017-01-17T15:51:51.7066585Z ##[error]Unhandled: EBADF: bad file descriptor, close
 
2017-01-17T15:51:51.7266827Z ##[section]Finishing: Deploy App Service

**Comment by shiningdragon** [comment] 2017-01-17 16:00
These release were working fine with no issues until very recently

**Comment by vincentdass** [comment] 2017-01-17 16:54
@shiningdragon , Thanks for reporting the issue.
Can you please queue a new release with system.debug = true and share the debug logs ?

**Comment by shiningdragon** [comment] 2017-01-18 13:40
OK will do. I've enabled the setting, we are not planing any releases today but I will update the next time we do a release. Thanks

**Comment by vincentdass** [comment] 2017-01-23 06:08
@shiningdragon, just a gentle reminder. Is the issue resolved ?

**Comment by shiningdragon** [comment] 2017-01-24 08:24
I ran new builds today, it picked up version 2.1.10 of the task and no errors so far so looks good.

Thanks

**Comment by mvvsubbu** [comment] 2017-01-24 08:33
We noticed few customers are hitting it. We are working on the solution we will update as soon as the fix is deployed.

**Comment by shiningdragon** [comment] 2017-01-24 09:42
its come back again ;( heres the full debug trace...

2017-01-24T09:41:04.5985021Z ##[debug]rc:0
 
2017-01-24T09:41:04.5985021Z ##[debug]rc:0
 
2017-01-24T09:41:04.5985021Z ##[debug]success:true
 
2017-01-24T09:41:04.5985021Z ##[debug]success:true
 
2017-01-24T09:41:04.6297256Z ##[debug]task result: Failed
 
2017-01-24T09:41:04.6455318Z ##[error]Error: Error: Unclosed root tag
 
2017-01-24T09:41:04.6455318Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: Unclosed root tag
 
2017-01-24T09:41:04.6455318Z Line: 5
 
2017-01-24T09:41:04.6455318Z Column: 5
 
2017-01-24T09:41:04.6455318Z Char: 
 
2017-01-24T09:41:04.6455318Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: Unclosed root tag
 
2017-01-24T09:41:04.6455318Z Line: 5
 
2017-01-24T09:41:04.6455318Z Column: 5
 
2017-01-24T09:41:04.6455318Z Char: 
 
2017-01-24T09:41:04.7703794Z ##[debug]task result: Failed
 
2017-01-24T09:41:04.7703794Z ##[error]Unhandled: EBADF: bad file descriptor, write
 
2017-01-24T09:41:04.7703794Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: EBADF: bad file descriptor, write
 
2017-01-24T09:41:04.7703794Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: EBADF: bad file descriptor, write
 
2017-01-24T09:41:04.7703794Z ##[debug]task result: Failed
 
2017-01-24T09:41:04.7890844Z ##[error]Unhandled: EBADF: bad file descriptor, close
 
2017-01-24T09:41:04.7890844Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: EBADF: bad file descriptor, close
 
2017-01-24T09:41:04.7890844Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: EBADF: bad file descriptor, close
 
2017-01-24T09:41:04.7890844Z ##[section]Finishing: Deploy App Service

**Comment by mvvsubbu** [comment] 2017-01-25 12:05
We got the root cause of the issue, we working on fix we will update once it is rolled out.

**Comment by ErikvanMaanen** [comment] 2017-01-26 11:23
@arjgupta @mvvsubbu : Any update on this issue?

Currently we need to redeploy 4 times or more to get all (12) webapps running.
Same issue. Unclosed root tag/FileDescriptor.
Seems random what get's deployed succesfull and what not.

**Comment by mvvsubbu** [comment] 2017-01-30 12:41
Currently fix is deployed to few accounts, we will deploy to remaining SUs tomorrow.

**Comment by mvvsubbu** [comment] 2017-02-01 04:01
The fix is rolling out to all the SUs in stages, it will happen in next 24 - 48 hrs. Please try after that, I am closing the issue for now. Please feel free to re open if issue persists even after that time frame as well.

**Closed by mvvsubbu** 2017-02-01 04:01 UTC
Labels: Area: Release, bug, Dev15

**Comment by burhan** [comment] 2019-12-12 23:36
It seems this problem has resurfaced. My maven build works fine on my local machine, but gives this exact error on azure pipelines.

![image](https://user-images.githubusercontent.com/603112/70757620-4f681880-1d51-11ea-9a3f-61d80a42381b.png)
