### ISSUE TITLE
VS Test Agent Deployment Unhandled Exception...PSInvalidOperationException

### ISSUE THREAD

**Issue by Gimpan** [Microsoft/vsts-tasks#2964] opened 2016-10-27 14:27 UTC
Hi,

I suspect it might be related to our current TFS '15' RC1 with tasks from 1.0.35 and/or being offline.
Since everytime I try to let the task update the test agent for me, I run into this:

---

2016-10-27T12:57:32.3277152Z DistributedTests: Path to script that installs test agent on remote machine: C:\Agent_work_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\1.0.35\TestAgentInstall.ps1
...
...
2016-10-27T12:57:37.4339032Z DistributedTests: Starting to download testagent
2016-10-27T12:57:37.4495915Z 
2016-10-27T12:57:37.4495915Z Unhandled Exception: System.Management.Automation.PSInvalidOperationException: The WriteObject and WriteError methods cannot be called from outside the overrides of the BeginProcessing, ProcessRecord, and EndProcessing methods, and they can only be called from within the same thread. Validate that the cmdlet makes these calls correctly, or contact Microsoft Customer Support Services.
2016-10-27T12:57:37.4495915Z    at System.Management.Automation.MshCommandRuntime.ThrowIfWriteNotPermitted(Boolean needsToWriteToPipeline)
2016-10-27T12:57:37.4495915Z    at System.Management.Automation.MshCommandRuntime.WriteHelper_ShouldWrite(ActionPreference preference, ContinueStatus lastContinueStatus)
2016-10-27T12:57:37.4495915Z    at System.Management.Automation.MshCommandRuntime.WriteWarning(WarningRecord record, Boolean overrideInquire)
2016-10-27T12:57:37.4495915Z    at System.Management.Automation.Cmdlet.WriteWarning(String text)
2016-10-27T12:57:37.4495915Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.Logger.WriteWarning(String message)
2016-10-27T12:57:37.4495915Z    at Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation.TestAgentDownloader.wc_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)
2016-10-27T12:57:37.4495915Z    at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
2016-10-27T12:57:37.4495915Z    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2016-10-27T12:57:37.4495915Z    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
2016-10-27T12:57:37.4495915Z    at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
2016-10-27T12:57:37.4495915Z    at System.Threading.ThreadPoolWorkQueue.Dispatch()
2016-10-27T13:17:29.5095307Z ##[error]LegacyVSTSPowerShellHost.exe completed with return code: -532462766.
2016-10-27T13:17:29.5095307Z ##[section]Finishing: Deploy TestAgent on $(TargetTestMachines)
2016-10-27T13:17:29.5095307Z ##[section]Starting: Post Job Cleanup
2016-10-27T13:17:29.5252328Z ##[section]Finishing: Post Job Cleanup
## 2016-10-27T13:17:29.5252328Z ##[section]Finishing: Build

As a workaround I grab the test agent from [here](https://www.microsoft.com/en-us/download/details.aspx?id=48152), I have to manually install this on the computer/client that will run coded UI tests. Then I go to the task and untick the "Update Test Agent" option in the task. When I do this I don't get the error and my run functional test task runs. I ran into more problems though...

But if I want the task to do the updating for me, what am I doing wrong?
I have the build logs in case anyone wants to check on them, was thinking about e-mailing them. I can also give more specifics on my tasks. 

Thanks in advance!

**Comment by acesiddhu** [comment] 2016-11-01 07:36
I think there is a problem in downloading the test agent from internet on build machine. Because of which we try to log the problem and that fails (writing error message is a bug). But the root cause is downloading the test agent fails. is this you own build agent or hosted build agent?

**Comment by acesiddhu** [comment] 2016-11-01 07:37
Also if you can run the scenario with system.debug = true and share the logs it might help.

**Comment by Gimpan** [comment] 2016-11-02 09:12
@acesiddhu ,Ok I'll need a few days to do it with debug on. It is my own build agent.
Can I send the logs somewhere?

**Comment by acesiddhu** [comment] 2016-11-02 09:29
devops_tools AT microsoft.com

**Comment by Gimpan** [comment] 2016-11-08 09:18
I sent the logs!

**Comment by nigurr** [comment] 2016-11-08 11:58
@Gimpan Can you try with the latest Agent and see if it's still happening. In the mean time, we will investigate with your logs. thanks for help

**Comment by Gimpan** [comment] 2016-11-08 12:50
I just received a reply:

Your message couldn't be delivered to multiple recipients.
The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.

I tried to send to: devops_tools AT microsoft.com, @ ofc.

**Comment by acesiddhu** [comment] 2016-11-09 09:00
We got the logs. Checking them now

**Comment by nigurr** [comment] 2016-11-14 05:04
@Gimpan is it still happening with latest agent?

**Comment by Gimpan** [comment] 2016-11-14 08:22
I think we have found the problem but another issue arises. I did not have a chance to try with latest agents or updates.
Problem was the client was missing some updates, leading to insufficient requirements. But after that was fixed the task successfully downloaded an agent we provided through our shared network. It installed the agent and the client automatically rebooted. The task failed to continue afterwards.

**Comment by Gimpan** [comment] 2016-11-24 11:07
We've installed the latest release, TFS 2017 released a week ago. So I thought I could try this again. I downloaded the latest vstfs_testagent.exe from the link provided by the task and put it on a local share. On the deploy task I provided the path the the testagent and ran the build. It successfully copied and deployed it.

So I guess for On-Prem you have to provide the testagent yourself. This makes sense but given the error message I get it mislead me to think something else was the problem.

I got new logs from the successful deploy if you are still interested. Otherwise I think we can close this issue.

**Comment by acesiddhu** [comment] 2016-11-24 11:38
Thanks @Gimpan for confirming. Even for on prem the task will try to download the test agent iself. if for some reason there is no internet connection you need to give test agent path. I agree the error message is misleading. We will fix that. Will close the issue for now

**Closed by acesiddhu** 2016-11-24 11:38 UTC
Labels: Area: Test
