### ISSUE TITLE
Access denied when deploying the test agent 

### ISSUE THREAD

**Issue by girishgoudar** [Microsoft/vsts-tasks#3780] opened 2017-03-13 12:49 UTC
I am trying to deploy the test agent on a machine with .net 4.6.1 and remoting enabled . I get access denied for connecting to the test agent machine.

**Comment by nigurr** [comment] 2017-03-14 04:29
@girishgoudar can you attach the build logs? 

Can you please check your build definition - Deploy Test Agent task where the username and password are correct

**Comment by girishgoudar** [comment] 2017-03-14 06:30
Hi @nigurr

The username and passowrd is correct 

I have followed this link 
https://www.visualstudio.com/en-us/docs/build/apps/cd/deploy-webdeploy-iis-winrm

and ran the powershell script as below 

ConfigureWinRM.ps1 {FQDN} http

find the logs attached . I am getting access denied 
[log.txt](https://github.com/Microsoft/vsts-tasks/files/840424/log.txt)

Do we need install the certficate for HTTP?

**Comment by acesiddhu** [comment] 2017-03-14 07:56
@girishgoudar can you check if the issue is similar to http://stackoverflow.com/questions/14127050/powershell-remoting-giving-access-is-denied-error 
From logs it looks like while connecting via remote powershell we are getting access denied.

Also I suggest to check out https://blogs.msdn.microsoft.com/deployment_service/2015/09/11/windows-remote-management-winrm-troubleshooting-guide-for-remote-sessions-on-the-target-machines while configuring winrm and remote PS. Let me know if this helps

**Comment by acesiddhu** [comment] 2017-03-20 12:41
@girishgoudar did this help? Assuming it worked as I see another issue on GitHub which is a step after winrm connections. I am closing this issue for now. Please reactivate this is this is still an issue.

**Closed by acesiddhu** 2017-03-20 12:41 UTC
Labels: Area: Test
