### ISSUE TITLE
deploy test agent suddenly hangs for unknown reason

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/vsts-tasks#2911] opened 2016-10-21 10:16 UTC
```bash
I, 2336, 1, 2016/10/21, 10:07:02.995, 1386376443701, DTAExecutionHost.exe, Main.TryReadAndCacheVssCredentials Acquiring the Token Info
I, 2336, 1, 2016/10/21, 10:07:03.010, 1386376543240, DTAExecutionHost.exe, Communicating to the Token Servicehttp://OurTfsServer:8080/tfs/DefaultCollection
W, 2336, 1, 2016/10/21, 10:07:03.042, 1386376863080, DTAExecutionHost.exe, Service task failed. Retry attempt 10.
```
only 3 lines in the log file, hanging for 2 hours now. worked for like 2 weeks in a row without error.
is this already a known problem? thanks a lot

**Comment by SatishThareja** [comment] 2016-10-24 05:59
@hqer2k9 Do you suspect any change in the test environment, which could have led to this issue?

To help us debug this issue, please collect the DtaExcutionHostlogs and Event Viewer logs from the test agent machine and send it to devops_tools@microsoft.com.

**Comment by hqer2k9** [comment] 2016-10-25 08:43
Hey @SatishThareja thanks for the reply, unfortenatly the DtaExcutionHostlog only has the 3 lines as shown above, the event viewer has no events at all.
I will monitor the problem

**Comment by SatishThareja** [comment] 2016-10-28 06:47
Closing the issue for now. Will reopen if the issue is observed again.

**Closed by SatishThareja** 2016-10-28 06:47 UTC
Labels: Area: Test
