### ISSUE TITLE
Allow $web as a container name now that Azure Blob Storage can be a static web host

### ISSUE THREAD

**Issue by kenotron** [Microsoft/vsts-tasks#7649] opened 2018-07-06 22:35 UTC
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

'Azure Storage container names can only contain lowercase alpha-numeric characters or hyphens'

**Comment by brosenoff** [comment] 2018-07-08 23:29
Agreed now that Azure storage supports static websites and you must use the $web container we need to be able to deploy code to that container via VSTS release but it fails because of the use of $.

**Comment by kmkumaran** [comment] 2018-07-09 03:58
Please refer #7611 that is used for tracking this issue.

**Comment by SumiranAgg** [comment] 2018-07-10 12:18
Closing since duplicate of above mentioned issue. Feel free to reopen if required.

**Closed by SumiranAgg** 2018-07-10 12:18 UTC
Labels: Area: Release
