### ISSUE TITLE
PowerShell on Target Machines task: Non-zero exit code is marked as "pass"

### ISSUE THREAD

**Issue by shaykalyan** [Microsoft/vsts-tasks#4102] opened 2017-04-22 20:40 UTC
Invoking a PowerShell script that exits with a non-zero code does not mark the task as failed. 

E.g., simply running a .ps1 with 
```
Exit 1
```
has the following output reported in the logs
```
Deployment status for machine '<hostname>:5985' : 'Passed'
```

The regular _PowerShell_ task with an inline script marks the task as failed as expected.

**Comment by NikolayKash** [comment] 2017-04-23 13:13
I'd also like to be able to fail a task by non-zero exit code

**Comment by pavanadepu2** [comment] 2017-04-25 07:47
@shaykalyan , @NikolayKash , thanks much for reporting the issue. This behavior is by design.
We consider your feedback and will try to address it in future releases.

**Comment by psutharsan** [comment] 2017-04-28 21:03
i have the same problem, I am running some webtest using powershell on target machine. It passes the task even when the tests are failed. Is there a work around for this. Thanks.

**Comment by shaykalyan** [comment] 2017-05-02 22:51
@psutharsan: Not a very clean work around, but since the default $ErrorActionPreference is set to "Stop", writing to the Error stream in your script via `Write-Error` will be terminal and result in the task being marked as failed.

@pavanadepu2: I'm curious why the design is such?

**Comment by ansariwn** [comment] 2018-02-06 16:00
@ericsciple  @pavanadepu2  @mvvsubbu @RoopeshNair - Can you please confirm if the exit code is now returned with merge #5606?

**Comment by ericsciple** [comment] 2018-02-07 06:30
nope that pr is for the powershell task

**Comment by RoopeshNair** [comment] 2018-10-12 12:38
Thank you for your feedback. This should be fixed now. The latest version supports additional error handling options as well. 

![image](https://user-images.githubusercontent.com/1370480/46869560-dff35200-ce49-11e8-8e92-6a6e5d6fa936.png)

**Closed by RoopeshNair** 2018-10-12 12:38 UTC
Labels: Area: Release, enhancement
